backend/cms/admin.py, backend/cms/apps.py, backend/cms/models/event.py, backend/cms/models/extra_template.py, backend/cms/models/language.py, backend/cms/models/language_tree.py, backend/cms/models/page.py, backend/cms/models/poi.py, backend/cms/models/push_notification.py, backend/cms/models/site.py, backend/cms/templates/_base.html, backend/cms/templates/_raw.html, backend/cms/templates/push_notifications/push_notifications.html, backend/cms/templates/statistics/statistics_dashboard.html, backend/cms/urls.py, backend/cms/views/pages/__init__.py, backend/cms/views/pages/archive.py, backend/cms/views/pages/page.py, backend/cms/views/pages/page_form.py, backend/cms/views/registration/__init__.py, backend/cms/views/registration/forms.py, backend/cms/views/registration/registration.py, backend/cms/views/statistics/__init__.py, backend/cms/views/statistics/matomo_api_manager.py, backend/cms/views/statistics/statistics.py, backend/requirements.txt
- Provides an analytic dashboard about recent calls of the site by requesting information via the Matomo API
TO-Dos:
Closes #1
Closes #9
Closes #8 
Closes #109
=> [on hold] Feature/statistics: Implements Analytics Feature and basic Push Notification functionality

backend/cms/models/language.py, backend/cms/models/language_tree.py, backend/cms/models/page.py, backend/cms/views/general/dashboard.py
We should now be back at 10/10 pylint rating. And I added some on_delete behaviour for our ForeignKeys
=> Refactor code & Add docstrings

README.md, install-venv.sh
* Install stdeb with pip3 not from debian repositories.
* Fix setup.py path in install-venv.sh.
=> Fix Packaging in README

README.md, _docker/django/development/Dockerfile, backend/backend/settings.py, docker-compose.yml, setup.py
* Describe building package with dependencies on
Ubuntu and installing + running the CMS.
* Include static files in setup.py.
=> Add install on Ubuntu to README, fix Dockerfile

README.md
README reflects the sourced Python3 venv in the bashrc.
=> [README] Update Django commands in Docker container

backend/cms/templates/pages/page.html, backend/cms/templates/pages/sbs_page.html, backend/cms/urls.py, backend/cms/views/pages/__init__.py, backend/cms/views/pages/sbs_page.py
Translation: Side by side view #85
=> Translation: Side by side view #85

backend/cms/views/push_notifications/push_notification_sender.py, backend/cms/views/push_notifications/push_notifications.py
**Translations not added yet**
=> Added ability to send push notifications via FCM legacy http api

backend/backend/settings.py, backend/cms/models/__init__.py, backend/cms/models/configuration.py, backend/cms/views/push_notifications/push_notification_sender.py, backend/cms/views/push_notifications/push_notifications.py
This branch builds on #136 and adds db-configuration and logging
=> #136 + use config from database and logging

backend/cms/page_xliff_converter.py
if the translation page exists.
=> XLIFF export language direction

backend/api/urls.py, backend/api/v3/languages.py, backend/api/v3/sites.py
- Django #16, sites
- Django #18, languages
=> API: sites, languages

backend/cms/templates/_base.html, backend/cms/templates/analytics/translation_coverage.html, backend/cms/urls.py, backend/cms/views/analytics/__init__.py, backend/cms/views/analytics/translation_coverage.py
Translation coverage analytics #9
=> Translation coverage analytics #9

backend/cms/locale/de/LC_MESSAGES/django.po
Update of error messages in the .po file
=> [WiP]Update Language files

backend/cms/views/language_tree/language_tree_node.py
See issue description #174 for detailed information to the bug and the solution.
=> Fix IntegrityError in language tree (resolves #174)

Jenkinsfile, README.md, backend/backend/docker_settings.py, backend/backend/settings.py, backend/cms/fixtures/test_data.json, dev-tools/create_superuser.sh, dev-tools/install.sh, dev-tools/loadtestdata.sh, dev-tools/migrate.sh, dev-tools/prune_database.sh, dev-tools/run.sh, setup.py
- Small bugfix of the dev-tools
- Divide requirements into base requirements and dev requirements
- Add json file with initial test data fixtures
- Add new dev-tool to load the test data
Fixes #182
=> Provide Test Data

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/region.py, backend/cms/models/user_profile.py, backend/cms/templates/regions/region.html, backend/cms/tests.py, backend/cms/urls.py, backend/cms/views/regions/__init__.py, backend/cms/views/regions/region_form.py, backend/cms/views/regions/regions.py, backend/cms/views/utils/slug_utils.py
- Refactor region form
- Enable deletion of regions (resolves #42)
=> Refactor RegionForm, enable region deletion

backend/cms/fixtures/test_data.json, backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/language.py, backend/cms/templates/language_tree/tree_row.html, backend/cms/templates/languages/archive.html, backend/cms/templates/languages/language.html, backend/cms/templates/languages/list.html, backend/cms/templates/languages/list_row.html, backend/cms/templates/pages/page.html, backend/cms/tests.py, backend/cms/views/languages/language_form.py, backend/cms/views/languages/languages.py
See issue #168 
~PR #196 should be merged before this one.
[View the actual diff of this PR](https://github.com/Integreat/cms-django/compare/feature/extra_templates...feature/languages)~
=> Native language names

dev-tools/loadtestdata.sh, dev-tools/migrate.sh, dev-tools/run.sh
Before executing docker commands check if Docker daemon is running.
=> Fix dev-tools for local Postgresql Database

backend/api/urls.py, backend/api/v3/pages.py, backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/page.py
Add a proof of concept for the pages endpoint
=> API: Pages endpoint (Fixes #15)

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/poi.py, backend/cms/templates/pois/poi.html, backend/cms/views/pois/poi_form.py
Added short description field to model, form model, translation and html.
=> Add short description field to poi (fixes #187)

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/event.py, backend/cms/models/page.py, backend/cms/models/poi.py, backend/cms/templates/pages/tree_row.html, backend/cms/templatetags/page_filters.py, backend/cms/tests.py, backend/cms/views/pages/page.py
- Improve the translation models
- Add a few helper functions to the page translation model
- Add status icons to the page translation tree view
fixes #83
=> Translation status icons

dev-tools/loadtestdata.sh, dev-tools/migrate.sh, dev-tools/prune_database.sh, dev-tools/run.sh
- Simplify checks for docker container
- Comment all important lines for better understanding
- Reset translation file if only the date changed
- Remove default environment variable (causes error for gettext and Django doesn't need it for default settings)
=> Improve dev-tools for docker users

.gitignore, backend/backend/settings.py, backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/templates/_raw.html, backend/cms/templates/statistics/statistics_dashboard.html, dev-tools/create_superuser.sh, dev-tools/install.sh, dev-tools/loadtestdata.sh, dev-tools/migrate.sh, dev-tools/prune_database.sh, dev-tools/run.sh, dev-tools/translate.sh, package.json, setup.py
Django-Compressor together with its requirements has been added to our project. Furthermore Dev-Tools has been updated.
Open ToDos:
=> Add Django-Compressor with npm-toolkit

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/static/js/custom.js, backend/cms/templates/_raw.html, backend/cms/templates/pages/page.html, package.json
Add Code View and add localization to TinyMCE.
=> Add translations to TinyMCE

dev-tools/resolve_translation_conflicts.sh
- Replace git conflict markers
- Remove duplicates in translation file
- Run translate.sh to fix format
=> Add dev tool for resolving conflicts in translation file

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/templates/pages/page.html
Added several user interface elements to the tinymce editor
=> Adjust user interface

dev-tools/run.sh
Fix dev tools for esoterik operating systems like ubuntu which don't have a current version of npm in their repositories.
=> Fix usage of sudo command in dev tool

backend/cms/fixtures/test_data.json, backend/cms/models/page.py, backend/cms/static/js/page.js, backend/cms/templates/pages/page.html, backend/cms/templatetags/page_filters.py, backend/cms/urls.py, backend/cms/views/pages/__init__.py, backend/cms/views/pages/page.py, backend/cms/views/pages/page_form.py, package.json
Change page selection to Django forms
=> Add attach page / live content, fixes #13

backend/cms/models/page.py
=> Use objects.filter().first() instead of objects.get()

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/page.py, backend/cms/static/css/tinymce_custom.css, backend/cms/templates/pages/page.html
Implements the required changes of the editor. Furthermore there was a bug on the page template that has been fixed in this PR.
Closes #234
=> Add colour to no_translate and fix language in page templates

README.md, dev-tools/install.sh
Adds a little bit of bash magic to determine if the required version of npm is installed.
=> Check if dependencies are installed (fixes #252)

backend/cms/models/page.py
* Adopt changed reference to page translation.
=> Change Page property best_language_title

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/templates/extras/extra_list.html, backend/cms/views/extras/extra_list_view.py, backend/cms/views/pois/poi_list_view.py, package.json
As expected, I messed everything up with my previous PR.
This new PR should now fix the `TemplateDoesNotExist` errors.
=> Bugfix: template names

backend/cms/forms/extra_templates/extra_template_form.py, backend/cms/forms/pois/poi_form.py, backend/cms/forms/pois/poi_translation_form.py, backend/cms/forms/regions/region_form.py, backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/pages/page_translation.py, backend/cms/models/pois/poi.py, backend/cms/models/pois/poi_translation.py, backend/cms/static/js/custom.js, backend/cms/static/js/poi.js, backend/cms/templates/events/event_list.html, backend/cms/templates/events/event_list_archived.html, backend/cms/templates/pois/confirmation_popups/archive_poi.html, backend/cms/templates/pois/confirmation_popups/delete_poi.html, backend/cms/templates/pois/confirmation_popups/restore_poi.html, backend/cms/templates/pois/poi_form.html, backend/cms/templates/pois/poi_list.html, backend/cms/templates/pois/poi_list_archived.html, backend/cms/templates/pois/poi_list_archived_row.html, backend/cms/templates/pois/poi_list_row.html, backend/cms/urls.py, backend/cms/utils/slug_utils.py, backend/cms/views/pois/__init__.py, backend/cms/views/pois/poi_actions.py, backend/cms/views/pois/poi_list_view.py, backend/cms/views/pois/poi_view.py, package.json
- Fix page permalink when ancestor path is empty
- Fix slug utils when fallback value not valid
- Fix path of included event templates
- Upgrade postcss-cli
- Transform POI form to match other content types (fixes #263)
=> Transform POI form

backend/cms/fixtures/test_data.json, backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/static/js/page.js, backend/cms/static/js/poi.js, backend/cms/templates/_raw.html, backend/cms/templates/events/event_form.html, backend/cms/templates/pages/_page_permission_table.html, backend/cms/templates/pages/page_form.html, backend/cms/templates/pois/poi_form.html, backend/cms/templates/pois/poi_list.html, backend/cms/templates/pois/poi_list_archived.html, backend/cms/views/pages/page_actions.py
- Move tinyMCE js and css to html head
- Improve JS handling in page form
=> Improve PageForm

backend/cms/templates/organizations/organization_form.html, backend/cms/templates/regions/region_form.html
- Remove publish button for regions
- Remove publish button for organizations
Fixes #222
=> Remove publish buttons for models without status

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/static/js/page.js, backend/cms/templates/pages/page_form.html
Move the button to its separate box and add a select field to choose the source language for the side by side view.
Fixes #236
=> Move Side-by-Side view button

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/static/js/custom.js, backend/cms/templates/_base.html, backend/cms/templates/authentication/login.html, backend/cms/templates/authentication/login_mfa.html, backend/cms/templates/authentication/password_reset_confirm.html, backend/cms/templates/authentication/password_reset_form.html, backend/cms/templates/events/event_form.html, backend/cms/templates/events/event_list.html, backend/cms/templates/events/event_list_archived.html, backend/cms/templates/events/event_list_archived_row.html, backend/cms/templates/events/event_list_row.html, backend/cms/templates/extra_templates/extra_template_list.html, backend/cms/templates/extras/extra_list.html, backend/cms/templates/language_tree/language_tree.html, backend/cms/templates/languages/language_list.html, backend/cms/templates/media/media_list.html, backend/cms/templates/messages.html, backend/cms/templates/organizations/organization_list.html, backend/cms/templates/pages/_page_permission_table.html, backend/cms/templates/pages/page_tree.html, backend/cms/templates/pois/poi_form.html, backend/cms/templates/push_notifications/push_notification_list.html, backend/cms/templates/regions/region_list.html, backend/cms/templates/roles/list.html, backend/cms/templates/statistics/statistics_dashboard.html, backend/cms/templates/users/admin/list.html, backend/cms/templates/users/region/list.html, package.json
The transition to the new tailwind version and my improvements to the poi list view left a few open problems, of which I want to address some in this PR.
=> Fix styling

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/pages/page_translation.py, backend/cms/templates/analytics/translation_coverage.html, backend/cms/views/analytics/translation_coverage_view.py, package.json
Improve translation coverage
- Adapt to the changed language name attribute (fixes #296)
- Add outdated translations to the report
=>  Improve translation coverage

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/templates/pages/page_form.html, backend/cms/templates/pages/page_tree_node.html
- Replace edit icon with checkmark
- Replace plus icon with x
- Rename translation icon tooltips
Fixes #237
=> Improve translation status UI

backend/api/v3/pages.py, backend/cms/models/pages/page.py, backend/cms/models/pages/page_translation.py
Add mirrored page translation to page content.
=> Change pages API endpoint, fixes #275

backend/cms/locale/de/LC_MESSAGES/django.po, backend/cms/models/pages/page_translation.py, backend/cms/templates/analytics/translation_coverage.html, backend/cms/views/analytics/translation_coverage_view.py
=> Add currently_in_translation to translation coverage

dev-tools/resolve_translation_conflicts.sh
- Check if msguniq could resolve all conflicts automatically
- If not, show error message
Fixes #306
=> Improve resolve-translation-conflicts.sh

src/cms/forms/users/__init__.py, src/cms/forms/users/user_email_form.py, src/cms/forms/users/user_password_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/settings/user.html, src/cms/views/settings/user_settings_view.py
Add possibility to change
- email and
- password
in user settings
Fixes #313
=> Add possibility to change email and password in user settings

src/cms/templates/users/admin/list_row.html, src/cms/templates/users/region/list_row.html
=> Unify icon position in users table

src/cms/forms/users/user_profile_form.py
I found the bug which caused the user creation problem and fixed it by changing the region assignment.
Fixes #342
=> Fix TypeError in user profile form

README.md, dev-tools/install.sh, dev-tools/resolve_translation_conflicts.sh, dev-tools/translate.sh
* Add dependency to README.md
* Add check to:
* translate.sh
* resolve_translation_conflicts.sh
Fixes #362
=> Specify additional system dependencies

dev-tools/test.sh
This is mainly copied and pasted from migrate.sh.
Some day I might put all these tools in a single script and refactor code duplications in re-usable bash functions, but at the moment I don't know enough about it...
=> Add database logic to test script

Pipfile.lock, README.md, setup.py, src/backend/settings.py
Add cors-headers to enable this feature
Signed-off-by: thimmy687 <kaser23@gmx.de>
=> add cors headers settings

src/api/urls.py, src/api/v3/feedback/event_list_feedback.py, src/api/v3/feedback/offer_list_feedback.py, src/api/v3/feedback/region_feedback.py, src/cms/models/__init__.py, src/cms/models/feedback/event_list_feedback.py, src/cms/models/feedback/offer_list_feedback.py
* Feedback endpoint for event list, offer list, region list, region
* Feedback model for event list, offer list, region list
Resolves #26
Resolves #349
Resolves #350
=> Add several api feedback endpoints

dev-tools/install.sh
Sorry for the trouble, I forgot an `!`. :sweat_smile: 
Fixes #380
=> Fix check for Python3.7-dev on Ubuntu

src/cms/views/pages/page_actions.py
=> Change Live Content page sorting

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/utils/__init__.py, src/cms/utils/file_utils.py, src/cms/utils/mfa_utils.py, src/cms/utils/slug_utils.py
Just another documentation-PR :slightly_smiling_face: 
Fixes: #329
=> Add documentation of cms utils

src/cms/apps.py
Aaaaand another documentation-PR :slightly_smiling_face: 
Fixes: #330
=> Add documentation of cms app config

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/rules.py, src/cms/views/pages/page_view.py
- Fix page permissions
- Improve page permission feedback
Fixes #415
=> Page permission bugfixes

Pipfile.lock, package-lock.json, package.json, setup.py, src/api/v3/feedback/page_feedback.py, src/cms/forms/pages/page_form.py, src/cms/forms/pages/page_translation_form.py, src/cms/forms/regions/region_form.py, src/cms/forms/users/user_form.py, src/cms/forms/users/user_password_form.py, src/cms/forms/users/user_profile_form.py, src/cms/models/media/document.py
This fixes a variety of security issues in our dependencies.
=> Update pip & npm dependencies

setup.py, sphinx/conf.py, src/cms/_tests.py, src/cms/models/pages/page.py, src/cms/models/pages/page_translation.py, src/cms/page_xliff_converter.py, src/cms/templatetags/poi_filters.py, src/cms/utils/slug_utils.py, src/cms/views/pages/page_actions.py, src/cms/views/push_notifications/push_notification_sender.py, src/cms/views/statistics/matomo_api_manager.py, src/gvz_api/apps.py, src/gvz_api/utils.py
I think f-strings are more readable than the previous syntax ;)
=> Use f-strings instead of string.format()

dev-tools/install.sh, dev-tools/run.sh, dev-tools/translate.sh
- Add check for python3.7
- Fix check for python3.7-dev
- Add check for nc
- Check for msgfmt instead of gettext
Fixes #424
=> Improve dependency checks 

.circleci/config.yml, .circleci/images/bionic-setuptools/Dockerfile, .circleci/images/python-node-gettext/Dockerfile
This adds
- The Dockerfiles
- The CircleCI config to build these images automatically and push them to the Docker Hub
Fixes: #406
=> Add docker images for CircleCI build

src/gvz_api/utils.py
* Introduce a check that handles no results for the details search
of the GVZ API.
=> Change GVZApiWrapper

sphinx/conf.py, src/backend/__init__.py, src/backend/circleci_settings.py, src/backend/context_processors.py, src/backend/docker_settings.py, src/backend/settings.py, src/backend/urls.py, src/backend/wsgi.py
This adds some docstrings and explanations for the backend package.
Fixes #336
=> Improve documentation of backend package

src/cms/tests/__init__.py, src/cms/tests/pages/__init__.py, src/cms/tests/pages/models.py
=> Improve documentation of cms tests

src/cms/templatetags/__init__.py, src/cms/templatetags/content_filters.py, src/cms/templatetags/offer_filters.py, src/cms/templatetags/page_filters.py, src/cms/templatetags/poi_filters.py, src/cms/templatetags/push_notification_filters.py
- Remove unused POI template filters
- Improve documentation of templatetags
Fixes #327
=> Improve documentation of cms templatetags

src/cms/decorators.py
=> Improve documentation of cms decorators

dev-tools/create_superuser.sh, dev-tools/install.sh, dev-tools/loadtestdata.sh, dev-tools/migrate.sh, dev-tools/package.sh, dev-tools/run.sh, dev-tools/test.sh, dev-tools/translate.sh
* If pipenv is running in a venv, it produces lots of noice.
These notifications are only notices and spam the window.
=> Change verbosity for pipenv in venv

src/cms/views/pages/page_actions.py
* Fix ording of live content pages by their title
=> Change ordering live content pages, fix #464

src/backend/settings.py, src/cms/models/events/event.py, src/cms/models/pages/__init__.py, src/cms/models/pages/abstract_base_page.py, src/cms/models/pages/abstract_base_page_translation.py, src/cms/models/pages/imprint_page.py, src/cms/models/pages/imprint_page_translation.py, src/cms/models/pages/page.py, src/cms/models/pages/page_translation.py, src/cms/tests/pages/models.py, src/cms/views/events/event_list_view.py, src/cms/views/pages/page_tree_view.py
As this is my first PR in the django repo (and my first every python PR), please review very carefully.
There are several things I'm not quite sure about. I'll add comments for these things.
If I am not following your conventions somehow, please let me know.
Fixes #357
=> Add imprint model

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/static/js/autosave.js, src/cms/templates/events/event_form.html, src/cms/templates/pages/page_form.html, src/cms/templates/pages/page_sbs.html, src/cms/templates/pois/poi_form.html
Implement a basic autosave functionality using the local Storage-Event of the tinyMCE. Every 2 mins and with pending changes a new draft of the page/poi/event is created.
Further improvements could be done by adding some kind of popup or message to inform the user about the save.
Fixes #41 .
=> Add basic autosave functionality

src/cms/templates/_base.html, src/cms/templates/pois/poi_list.html, src/cms/templates/pois/poi_list_archived.html, src/cms/views/pois/poi_actions.py, src/cms/views/pois/poi_list_view.py, src/cms/views/pois/poi_view.py
=> Rename points of interest

src/sitemap/sitemaps.py, src/sitemap/utils.py
I added Offers to sitemap. 
This code
`            try:
url["alternates"] = url["item"].sitemap_alternates
except AttributeError:
logger.debug("%s has no attribute sitemap_alternates", url["item"])`
was added because of AttributeError "Offer object has no attribute sitemap_alternates". I know this may not be the best solution, just let me know and I will try to fix it in some other way.
=> Added Offers to sitemap

Pipfile.lock, package-lock.json, package.json, src/cms/constants/all_day.py, src/cms/constants/recurrence.py, src/cms/forms/events/__init__.py, src/cms/forms/events/event_filter_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/static/js/events/event_query_pois.js, src/cms/templates/events/_event_filter_form.html, src/cms/templates/events/_poi_query_result.html, src/cms/templates/events/event_form.html, src/cms/templates/events/event_list.html, src/cms/templates/events/event_list_archived.html, src/cms/views/events/event_actions.py, src/cms/views/events/event_list_view.py
This PR adds the possibility to sort the events in the event overview list.
Additionally, the event list can be filtered to not include all but a restricted selection of events.
- Adds the javascript dependency `tablesort` for event list sorting functionality
- Adds a filter form (frontend) which lets users enter information on how they want to filter the events
- Adds server-side filter functionality to process the filter requested by a user and only return the events matching the given filter
Fixes: #245
=> Add event sorting and filtering functionality, fixes #245

src/cms/models/languages/language.py
Fixes: #524
I don't know if I have done this right but I think I have?
=> Change things to SlugField

src/backend/settings.py, src/cms/admin.py, src/cms/constants/push_notifications.py, src/cms/forms/push_notifications/push_notification_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/__init__.py, src/cms/models/push_notifications/push_notification.py, src/cms/models/push_notifications/push_notification_channel.py, src/cms/models/push_notifications/push_notification_translation.py, src/cms/static/js/push_notifications.js, src/cms/templates/push_notifications/push_notification_form.html, src/cms/templates/push_notifications/push_notification_list_row.html, src/cms/views/push_notifications/push_notification_sender.py, src/cms/views/push_notifications/push_notification_view.py
* Use basic design of PageTranslations form
* Use formsets to enter all translations at once
* Add send modes: only available translations, use main language
=> Add language support for Push Notifications, fixes #311

src/api/decorators.py, src/api/urls.py, src/api/v3/feedback/event_feedback.py, src/api/v3/feedback/event_list_feedback.py, src/api/v3/feedback/imprint_page_feedback.py, src/api/v3/feedback/legacy_feedback_endpoint.py, src/api/v3/feedback/offer_feedback.py, src/api/v3/feedback/offer_list_feedback.py, src/api/v3/feedback/page_feedback.py, src/api/v3/feedback/region_feedback.py, src/api/v3/feedback/search_result_feedback.py, src/api/v3/languages.py, src/api/v3/offers.py, src/api/v3/pages.py, src/api/v3/push_notifications.py, src/api/views.py, src/cms/admin.py, src/cms/models/feedback/feedback.py, src/cms/models/feedback/imprint_page_feedback.py, src/cms/models/pages/imprint_page.py
* Split into three endpoints for pages, events, imprint pages each
* Edit page/event/disclaimer-endpoint to legacy endpoint
* Add one-to-one field for the association of regions to imprint pages
* Require slug as parameter instead of permalink
* Add API documentation
Resolves #22
Resolves #23 
Resolves #27 
Resolves #359 
Resolves #337
=> Change Feedback API

src/api/apps.py, src/api/decorators.py, src/api/v3/pages.py, src/api/v3/regions.py
This PR adds documentation for 2 files which were left out in #512
=> Change API documentation, fix #337

src/api/urls.py, src/api/v3/imprint.py, src/cms/admin.py, src/cms/models/pages/imprint_page_translation.py
* Add imprint API endpoint
* Make trailing slashes optional for all API endpoints
* Merge offer/extra and offers/extras URL patterns
=> Add imprint API endpoint, fixes #80

src/api/v3/single_page.py
Fix two bugs in the single page API endpoint
- Fix Queryset in single page API endpoint
- Remove permalink check in single page API endpoint
Fixes: #575
Fixes: #576
=> Fix single page API endpoint

sphinx/include/pipenv-path-environment-variable.rst, sphinx/installation.rst, sphinx/troubleshooting.rst
Fixes some issues in the installation documentation
- Fix typo in pipenv path environment variable
- Add pcregrep as dependency for translation features (used in `/dev-tools/check_translations.sh`)
- Mention ubuntu explicitly as debian-based
Fixes: #581
=> Fix installation documentation

sphinx/troubleshooting.rst
Add troubleshooting guide for problem described in #536.
=> Add "Not a git repository" to troubleshooting guide

src/cms/forms/regions/region_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/regions/region.py, src/cms/static/css/style.less, src/cms/static/js/region-form-icon.js, src/cms/templates/regions/region_form.html, src/cms/templates/regions/region_icon_widget.html, src/cms/templatetags/form_icon_filters.py, src/cms/views/regions/region_view.py
Added region icon to form/model
-The region icon may be set in the region form, after setting the image
it is displayed in the form.
-For region forms without user defined icon, there is a sample mockup
icon presented in region form.
Fixes: #546
=> Added region icon to form/model

Pipfile.lock, setup.py, src/backend/settings.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/static/css/style.less, src/cms/static/js/toggle-dashboard-section.js, src/cms/templates/_base.html, src/cms/templates/dashboard/dashboard.html, src/cms/templatetags/parse_struct_time.py, src/cms/views/dashboard/dashboard_view.py
Added RSS feed to dashboard
- Five latest news fetched from integreat website news feed.
- Rough outline of the remaining dashboard sections.
Fixes: #5
=> Add RSS feed to dashboard

src/cms/forms/imprint/__init__.py, src/cms/forms/imprint/imprint_form.py, src/cms/forms/imprint/imprint_translation_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/pages/abstract_base_page_translation.py, src/cms/models/pages/imprint_page_translation.py, src/cms/models/pages/page_translation.py, src/cms/templates/_base.html, src/cms/templates/imprint/imprint_form.html, src/cms/templates/imprint/imprint_revisions.html, src/cms/templates/imprint/imprint_sbs.html, src/cms/templates/pages/page_form.html, src/cms/urls.py, src/cms/views/imprint/__init__.py, src/cms/views/imprint/imprint_actions.py, src/cms/views/imprint/imprint_revision_view.py, src/cms/views/imprint/imprint_sbs_view.py, src/cms/views/imprint/imprint_view.py
Creation of Imprint form. Adjusted the code from the page form, page template and page view to suit that of the imprint.
- Inside _cms.view.imprints.imprint_view.py_, `page_id` and `new_page` variables were replaced by `imprint_id` and `new_imprint` with no noticeable effect.  
- Imprint tab can be clicked from the menu
Fixes: #39
=> Add Imprint form

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/pages/page.py, src/cms/models/pages/page_translation.py, src/cms/templates/pages/page_view.html, src/cms/views/pages/page_actions.py
Add live content to page preview
- Pages with embedded live content are previewed with their live
content.
- This does not address issue #496 (general improved preview) due to
missing links for a web-app based preview.
Fixes: #619
=> Added live content preview for pages

src/cms/templatetags/page_filters.py
See bug description of #631 for details.
- Use python list operations instead of Django QuerySet filters
Fixes: #631
=> Fix get_last_root_page template tag

.gitignore, src/cms/constants/mirrored_page_first.py, src/cms/forms/pages/page_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/static/js/pages/page_mirroring.js, src/cms/templates/pages/_mirrored_page_field.html, src/cms/templates/pages/page_form.html, src/cms/templates/pages/page_tree_archived.html, src/cms/templatetags/page_filters.py, src/cms/urls.py, src/cms/views/pages/__init__.py, src/cms/views/pages/page_actions.py
Refactor mirrored page field
- Save field only when form is submitted (fixes the submission message of the page form)
- Prevent page embedding itself
- Add warning when archived page is embedded
- Add warning when page from archived or hidden region is embedded
Fixes: #635
=> Refactor mirrored page field

src/cms/constants/translation_status.py, src/cms/forms/pages/page_filter_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/static/js/reset_filter.js, src/cms/templates/events/_event_filter_form.html, src/cms/templates/pages/_page_filter_form.html, src/cms/templates/pages/page_tree.html, src/cms/templates/pages/page_tree_node.html, src/cms/views/pages/page_tree_view.py
Add filtering to the page tree
- Adapt the filtering solution of events also for pages
Resolves #240
=> Page list filter

README.md
Minor updates to the README to improve the info about the current production setup.
=> Update production info in README

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/pages/page_form.html
Move side-by-side widget to bottom
-
-
-
Fixes: #623
=> Move side-by-side widget to bottom, fixes #623

package.json, src/cms/static/js/forms/tinymce-init.js, src/cms/templates/events/event_form.html, src/cms/templates/imprint/imprint_form.html, src/cms/templates/imprint/imprint_sbs.html, src/cms/templates/pages/page_form.html, src/cms/templates/pages/page_sbs.html, src/cms/templates/pois/poi_form.html
Adjust the source of the custom css accordingly.
Fixes: #665
=> Change source of css file

src/cms/forms/pages/page_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/static/css/style.less, src/cms/static/js/pages/collapse-subpages.js, src/cms/templates/pages/_page_order_table.html, src/cms/templates/pages/page_tree.html, src/cms/templates/pages/page_tree_node.html, src/cms/templatetags/tree_filters.py
This adds improvements to the hierarchy of the page tree.
- Clarify hierarchy in page tree
- Enable collapsing of subpages
Fixes: #503
=> Improve hierarchy in page tree

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/static/css/style.less, src/cms/templates/_base.html, src/cms/templates/settings/user.html
Moved language switcher to user settings
- Removed language switcher from top menu bar.
- Added language switcher to user settings.
Fixes: #651
=> Moved language switcher to user settings

src/cms/templates/events/event_form.html
Fix the POI field in event form
- Include `event_query_pois.js` in the event form
Fixes: #674
=> Fix POI field in event form

package-lock.json
Just adds the updated package-lock.json to the repo. Somehow this wasn't included in the last commit.
=> Add updated package-lock

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/_base.html
Only show menu item if user has permission to open it
Fixes: #676
=> Check permissions for menu items

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/pages/page_form.html
Reinserted a wrongly removed div-ending tag to page form.
This `</div>` was wrongly removed during my last PR #660 , so I reinserted it.
Fixes: #679
=> Fixed page form layout

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/static/js/custom_plugins/autolink_tel/plugin.js, src/cms/static/js/forms/tinymce-init.js, src/cms/templates/_base.html, src/cms/templates/_raw.html
This PR applies some changes to the TinyMCE which include:
- Fix Icon size to 15x15
- Remove function "Remove format"
- Add word counting for TinyMCE
- Change "No translate"-Icon to the common one
- Add a fork of the autolink plugin which supports phone numbers
- Adds `<br />` instead of `<p>`-tags if the user press enter
MISC:
- Remove Search field from base HTML
- Rename Website title to "Editorial System/Redaktionssystem"
Fixes: #587
=> Refactor TinyMCE editor

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/pages/page.py, src/cms/models/pages/page_translation.py, src/cms/views/pages/page_actions.py
Fix mirrored text in page API
- Add extra checks to determine if mirrored page exists before accessing the mirrored text
Fixes: #706
=> Fix mirrored text in page API

src/api/v3/pages.py, src/api/v3/pdf_export.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/regions/region.py, src/cms/views/pages/page_tree_view.py, src/sitemap/sitemaps.py
Fix FieldError in PDF API
- Add possibility to return unrestricted queryset of all pages of a region
- Adapt PDF API to new concept of archived pages introduced in #598
Fixes: #711
=> Fix FieldError in PDF API

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/events/_event_filter_form.html, src/cms/templates/events/event_list.html, src/cms/templates/events/event_list_row.html
Edit  Event Page
-Remove ID and version columns
-Fix icon of edit action
-Make text color of filter button always white
Fixes: #693
=> Improve event list

dev-tools/check_translations.sh
It bothered me that it was sometimes unclear why the translation check fails and it took multiple fixing loops until everything was fine. This should ideally fix this by showing the exact lines which cause the warnings.
- Print which translations exactly are missing or incorrect
- Show diff if translation file is not up to date
- Show hint how to disable the checking script
- Fix bug where translation file is considered out of date if the last change was less than a minute ago
- Lots of unnecessary bash magic to make everything beautiful
=> Improve output of check-translations.sh script

src/cms/constants/status.py, src/cms/forms/events/event_translation_form.py, src/cms/forms/offer_templates/offer_template_form.py, src/cms/forms/pages/page_translation_form.py, src/cms/forms/pois/poi_translation_form.py, src/cms/forms/regions/region_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/pages/abstract_base_page_translation.py, src/cms/models/pages/page_translation.py, src/cms/static/css/style.less, src/cms/static/js/forms/update-permalink.js, src/cms/templates/pages/page_form.html, src/cms/urls.py, src/cms/utils/slug_utils.py, src/cms/views/pages/__init__.py, src/cms/views/pages/page_actions.py, src/cms/views/pages/page_view.py
Improves page form layout and renames some labels.
"The latest changes have only been saved as a draft. Currently, version {Revision ID} of this page is displayed in the app."
"Die letzten Änderungen wurden nur als Entwurf gespeichert. Aktuell wird Version {Revision ID} dieser Seite in der App angezeigt."
Fixes: #691
=> Improve page form

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/pois/poi_list.html, src/cms/templates/pois/poi_list_archived.html, src/cms/templates/pois/poi_list_archived_row.html, src/cms/templates/pois/poi_list_row.html, src/frontend/css/tablesort.css, src/frontend/js/tablesort.ts
changing some css classes of html elements.
Apart from that, the different lists (especially for pages, events and pois) aren't rendered consistently. For example, they use different shades of grey for the table borders. It should be investigated in which points they really differ (apart from the given example) as well as those differences should be eliminated in order to have a consistent UI experience.
-
-
-
This fixes the POI part of #292 and #624
=> Improve POI list

src/cms/constants/administrative_division.py, src/cms/forms/regions/region_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/regions/region.py, src/cms/templates/pages/page_pdf.html, src/cms/templates/regions/region_form.html
Improves region form
- Renamed "Gemeindeverbande" to "Verbandsgemeinde"
- Added field "administrative division included" to include adm. div.
into region name
- Updated PDF documents according to aforementioned field
Fixes: #703
=> Improved region form

src/cms/views/authentication/authentication_actions.py, src/frontend/js/forms/update-permalink.ts, src/frontend/js/pages/page-side-by-side.ts
Fix a few small bugs in our Typescripts
- Fix "Uncaught TypeError" in JS console 
- Fix "DOM text reinterpreted as HTML"
- Fix "Information exposure through an exception"
Fixes: 
- [Code Scanning Alert 31 (DOM text reinterpreted as HTML)](https://github.com/Integreat/integreat-cms/security/code-scanning/31?query=ref%3Arefs%2Fheads%2Fdevelop)
- [Code Scanning Alert 32 (DOM text reinterpreted as HTML)](https://github.com/Integreat/integreat-cms/security/code-scanning/32?query=ref%3Arefs%2Fheads%2Fdevelop)
- [Code Scanning Alert 33 (Information exposure through an exception)](https://github.com/Integreat/integreat-cms/security/code-scanning/33?query=ref%3Arefs%2Fpull%2F763%2Fhead)
=> Small TypeScript bugfixes

src/cms/views/pages/page_view.py
Fixes  new page translation form bug
- Sets proper if condition.
Fixes: #777
=> Fixes new page translation bug

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/pages/page_translation.py, src/cms/templates/pages/page_tree.html, src/cms/templates/pages/page_tree_node.html
This pr adds labels to the pages tree, showing whether a page is empty or live content.
Fixes: #567
=> Add labels to page entries

README.md, dev-tools/generate_documentation.sh, sphinx/dev-tools.rst, sphinx/documentation.rst, sphinx/index.rst, sphinx/installation.rst, sphinx/packaging.rst, sphinx/prod-server.rst, src/backend/settings.py
Adds small improvements to the documentation
- Add deployment section to documentation
- Document `--clean` parameter of documentation-dev-tool
=> Improve documentation

README.md, dev-tools/install.sh, sphinx/installation.rst
Change the install.sh to check for NodeJS versions 12, 14 or 15.
=> Change installation nodejs version check

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/events/event_translation.py, src/cms/models/pages/abstract_base_page.py, src/cms/models/pages/abstract_base_page_translation.py, src/cms/models/pages/imprint_page.py, src/cms/models/pages/page.py, src/cms/models/pois/poi_translation.py, src/sitemap/sitemaps.py
Fix two small bugs in the sitemaps
- Fix `ProgrammingError` in sitemap (fixes #789)
- Return an unrestricted queryset for `region.get_pages()` to prevent a `Subquery has too many columns` error in the sitemap
- Fix `AttributeError` in sitemap
- Fix `'QuerySet' object has no attribute 'remove'` error in event & POI sitemap
- Convert `language` property from list to queryset in page sitemap for consistency with event & POI sitemap
Fixes: #789
=> Fix bugs in sitemap

src/cms/forms/pois/poi_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/pois/poi.py, src/cms/templates/pois/poi_form.html, src/cms/templates/pois/poi_list.html, src/cms/templates/pois/poi_list_archived.html, src/cms/templates/pois/poi_list_archived_row.html, src/cms/templates/pois/poi_list_row.html
Updated the changes for Issue 695. 
-Check box to show/not to show the location was moved to the right slidebar.
-Location form looks now similar to the page form.
-commented out lines are deleted.
Fixes: #695
=> Improve POI list and form

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/dashboard/region_selection.html, src/cms/urls.py, src/cms/views/dashboard/__init__.py, src/cms/views/dashboard/redirect_view.py, src/cms/views/dashboard/region_selection.py
This pr adds a region selection screen for users who have access to multiple regions, which is shown after login.
Fixes: #592
=> Implement regions selection for multiple region users

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/push_notifications/push_notification_translation.py, src/cms/templates/_base.html, src/cms/templates/push_notifications/push_notification_form.html, src/cms/templates/push_notifications/push_notification_list.html, src/cms/templates/push_notifications/push_notification_list_row.html, src/frontend/index.ts, src/frontend/js/charCounter.ts
Changes for the Issue #698 Improve push notification form are done.
- Renaming : Pusch nofification -> News message
- Message field is now multi line
- Letter count is added below the message field
Fixes: #698
_Note: This supersedes #791_
=> Improve push notification form

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/pages/page_tree.html
Only show export option to current language, if the current language is not the root language.
Fixes: #650
=> Change XLIFF export bulk actions

src/cms/templates/_base.html
Following up on #812, this fixes the menu item for the broken link checker
- Fix current menu item of link checker
=> Fix current menu item of link checker

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/imprint/imprint_form.html, src/cms/templates/imprint/imprint_revisions.html, src/cms/templates/pages/page_revisions.html, src/frontend/css/style.scss, src/frontend/js/revisions.ts
Changes for Issue 692 Improve revision view.
- Renamed "Revision" to "Version"
- The slider is now shorter
- "Back to Editor" button was moved up to the right upper corner
- Editor name in tool tip
Fixes: #692
=> Improve revision view

src/api/urls.py, src/api/v3/locations.py
This pr adds support for the locations api endpoint.
Fixes: #794
=> Add api endpoint for locations

src/cms/views/imprint/imprint_view.py
Fix `UnboundLocalError` in imprint form
- Set `imprint` to `imprint_instance` if imprint already exists
Fixes: #831
=> Fix `UnboundLocalError` in imprint form

src/api/urls.py, src/api/v3/events.py, src/api/v3/locations.py
This pr adds support for the events api endpoint.
Fixes: #793
=> Add api endpoint for events

src/cms/templates/events/event_list.html, src/cms/templates/events/event_list_archived.html, src/cms/templates/pages/page_tree_archived.html, src/cms/templates/pois/poi_list.html, src/cms/templates/push_notifications/push_notification_list.html
changes for the issue #837.
- copy&pasted from the pages code.
-
-
Fixes: #837
=> Fix flag icons

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/events/event_list.html, src/cms/templates/events/event_list_archived.html, src/cms/templates/generic_language_switcher.html, src/cms/templates/pages/page_tree.html, src/cms/templates/pages/page_tree_archived.html, src/cms/templates/pois/poi_list.html, src/cms/templates/pois/poi_list_archived.html, src/cms/templates/push_notifications/push_notification_list.html
This PR includes changes for the issue "Adapt new content language switcher for other views #836".
~and partially changes for #837 (modification on the changes which were submitted as "changes for issue 837 Fix flag icons" )~
- a generic sub-template for the language switcher is made.
- the language switcher is added for other views.
Fixes: #836
=>  Adapt new content language switcher

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/analytics/_broken_links_widget.html, src/cms/utils/filter_links.py, src/cms/views/analytics/analytics_overview.py, src/cms/views/dashboard/dashboard_view.py, src/cms/views/linkcheck/linkcheck.py
Adds brief summary about linkcheck to dashboard
Briefly reports the number of valid, invalid, etc. links on dashboard and analytics overview
Fixes: #824
=> Adds brief summary about linkcheck to dashboard

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/linkcheck/link_list_row.html, src/cms/templates/linkcheck/links_by_filter.html, src/cms/views/linkcheck/linkcheck.py
Adds actions to brokenlink checker
- Ignore, unignore and recheck actions added
- Link selection via checkboxes
- Only non-ignored links can be either ignored or rechecked
- Ignored links can only execute action "unignore"
Fixes: #825
=> Adds actions to brokenlink checker

src/api/urls.py, src/backend/urls.py
This PR contains the newly implemented URL patterns for WordPress API endpoint.
- New URL pattern was implemented.
-
-
Fixes: #855
=> Implement WordPress API endpoint URL patterns

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/languages/language_tree_node.py, src/cms/views/regions/region_actions.py
Fix the region deletion, the solution was similar to #862.
- Fix ordering of language tree nodes
- Remove mapping of event location to prevent `ProtectedError`
Fixes: #864
=> Fix region deletion

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/events/event.py, src/cms/models/pages/page.py, src/cms/models/pois/poi.py, src/cms/models/regions/region.py, src/cms/models/users/organization.py, src/cms/templates/organizations/organization_form.html, src/cms/templates/organizations/organization_list_row.html, src/cms/views/organizations/organization_view.py
Fixed a bug, where the organization form wasn't updated yet to work properly with the new media library. 
- updated organization_view
- changed the organization model's icon entry 
- added the logo as a thumbnail to the organization list 
Fixes: #889
=> Fix logo issue in organizations

.circleci/config.yml, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/views/events/event_view.py, src/cms/views/pois/poi_view.py
This pr adds a message that no changes were detected for event forms and poi forms if they did not change.
Fixes: #888
=> Add no change detected message to poi and event forms

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/media/media_file.py
Changes the max_size settings for the different file objects. This allows files with longer file names to be uploaded.
Fixes: #873
=> Change max size of file names

src/cms/templates/_base.html
Fix permissions in base template.
=> Fix permission names

src/frontend/js/tinymce-plugins/custom_link_input/plugin.js
This pr fixes the tinymce link popup to show the correct url when the selected element is just a child of a link.
- Make the `getAnchor` function walk the node hierarchy until it finds an anchor element
Fixes: #912
=> Show the correct url when clicking on a node that is a child of a link

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/imprint/imprint_form.html, src/cms/views/imprint/imprint_view.py
This pr fixes a bug where the media library could not be opened on the imprint page.
Fixes: #917
=> Allow the media libray to be opened on the imprint page

src/cms/views/imprint/imprint_actions.py
This pr fixes a bug which prevented the user from archiving imprints.
- Rename outdated field setters
Fixes: #916
=> Fix bug which prevented archiving imprints

src/cms/locale/de/LC_MESSAGES/django.po, src/cms/templates/dashboard/_news_widget.html, src/cms/views/dashboard/dashboard_view.py, src/frontend/js/toggle-dashboard-section.ts
Re-implementation of the rss-news-feed in ajax. 
This PR features the discussed rss-feed improvements so that it allows an asynchronous loading of news-entries. This allows an independent timeout handling and also makes it possible to load more feed-entries dynamically. 
Fixes: #801
=> Ajax RSS feed

dev-tools/prune_database.sh, src/backend/settings.py, src/cms/forms/media/upload_media_file_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/models/media/media_file.py, src/cms/utils/media_utils.py
Change path of media library, fixes #902
-
-
-
Fixes: #902
=> Change path of medialibrary, fixes #902

Pipfile.lock, package-lock.json, sphinx/patches/breadcrumbs.diff, sphinx/patches/footer.diff, src/cms/forms/offer_templates/offer_template_form.py, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/tests/views/view_test.py, src/cms/utils/pdf_utils.py, src/cms/views/authentication/mfa/mfa_assert_view.py, src/cms/views/authentication/mfa/mfa_verify_view.py, src/cms/views/pages/page_actions.py
- Update all python dependencies
- Update sphinx template patches for new rtd theme version
This is required for #940 and #939
=> Update pip dependencies

example-configs/apache2-integreat-vhost.conf
This adds the mod_wsgi process parameter to the example Apache2 config for future reference.
=> Apache2 example: add mod_wsgi processes param

Pipfile.lock, src/cms/locale/de/LC_MESSAGES/django.po, src/cms/utils/pdf_utils.py, src/cms/views/error_handler/error_handler.py
This update seems to introduce some problems, so we have to figure out how to fix the tests.
I assume it has something to do with https://github.com/django-webpack/django-webpack-loader/pull/297.
- Update django-webpack-loader from 1.3.0 to 1.4.0
=> Update django-webpack-loader from 1.3.0 to 1.4.0

src/cms/views/pages/page_actions.py, src/frontend/js/pages/page-permissions.ts, src/locale/de/LC_MESSAGES/django.po
- change the way, page forms are initialized in the page_actions.py 
Fixes: #989
=> Fix specific user permissions bug 

src/cms/templates/imprint/imprint_sbs.html, src/cms/templates/pages/page_sbs.html, src/frontend/js/pages/sbs-copy-content.ts
This pr implements two small improvements for the sbs view.
- Fix padding for the buttons in the top right corner
- Include title when clicking the "copy" button
Fixes: #990
=> Improve sbs view

src/backend/settings.py, src/cms/admin.py, src/cms/models/events/event_translation.py, src/cms/models/pages/page_translation.py, src/cms/models/pois/poi_translation.py, src/cms/templates/analytics/_broken_links_widget.html, src/cms/templates/linkcheck/link_list_row.html, src/cms/templates/linkcheck/links_by_filter.html, src/cms/templatetags/content_filters.py, src/cms/templatetags/model_tags.py, src/cms/utils/filter_links.py, src/cms/views/analytics/analytics_overview.py, src/cms/views/dashboard/dashboard_view.py, src/cms/views/linkcheck/linkcheck.py, src/locale/de/LC_MESSAGES/django.po
This pr adds the improvements specified by #991 to the link checker.
- Hide links from object translations which are outdated
- Add links to the source
- Fix some css issues
Fixes: #991
=> Improve link checker

src/cms/models/pages/page.py, src/cms/templates/events/_event_filter_form.html, src/cms/templates/events/event_list.html, src/cms/templates/events/event_list_archived.html, src/cms/templates/feedback/admin_feedback_list.html, src/cms/templates/feedback/region_feedback_list.html, src/cms/templates/pages/_page_filter_form.html, src/cms/templates/pages/page_tree.html, src/cms/templates/pages/page_tree_archived.html, src/cms/templates/pages/page_tree_node.html, src/frontend/css/style.scss, src/locale/de/LC_MESSAGES/django.po
This PR applies the some changes to the UI of the page overview. These include:
- Apply consistent styling to the filter buttons
- Changes to the order of the page table
=> Apply UI changes to the treeview

src/frontend/js/tinymce-plugins/custom_link_input/plugin.js
This PR changes the behavior that an existing link text gets overwritten by the link, if we select some text input that we want use for linking.
=> Stop overwriting link text

integreat_cms/core/settings.py
Fix a few config problems with cacheops
- Tell cacheops about redis socket if configured
- Cache cms and linkcheck database tables
=> Fix cacheops config

integreat_cms/cms/templates/events/event_list.html, integreat_cms/cms/templates/events/event_list_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po
Add recurring attribute to event table and shows icon whether or not an event is recurring or not
Fixes #1012
-
-
-
Fixes: #1012
=> Add recurring attribute to event table, fixes #1012

CHANGELOG.md, integreat_cms/cms/constants/events_time_range.py, integreat_cms/cms/forms/events/event_filter_form.py, integreat_cms/cms/models/events/event.py, integreat_cms/cms/templates/events/_event_filter_form.html, integreat_cms/cms/templates/events/event_list.html, integreat_cms/cms/templates/events/event_list_archived.html, integreat_cms/cms/templates/events/event_list_archived_row.html, integreat_cms/cms/templates/events/event_list_row.html, integreat_cms/cms/views/events/event_list_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/events/conditional-fields.ts, integreat_cms/static/src/js/filter-form.ts
This PR changes to only show upcoming events by default and adds filter options to filter upcoming and past events, fixes #992
Fixes: #992
=> Add filter options to event filter, fixes #992

integreat_cms/static/src/js/events/conditional-fields.ts
Right now, when loading a page a console error shows up. 
- Don't try to access a property of null
- Alternatively, we could maybe not load this file when it is not needed
=> Fix console error on page load

CHANGELOG.md, integreat_cms/cms/models/media/directory.py, integreat_cms/cms/models/media/media_file.py, integreat_cms/cms/templates/_search_input.html, integreat_cms/cms/urls.py, integreat_cms/cms/views/media/__init__.py, integreat_cms/cms/views/media/media_actions.py, integreat_cms/cms/views/media/media_context_mixin.py, integreat_cms/cms/views/utils/search_content_ajax.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/media-management/component/breadcrumbs.tsx, integreat_cms/static/src/js/media-management/component/directory-content.tsx, integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx, integreat_cms/static/src/js/media-management/directory-content-library.tsx, integreat_cms/static/src/js/media-management/index.tsx, integreat_cms/static/src/js/media-management/library.tsx, integreat_cms/static/src/js/media-management/search-result-library.tsx, integreat_cms/static/src/js/search-query.ts
The goal of this PR is to add  search funcionality for media library so users can look for directories and files that match key words.
So far keyword search of items is functioning, but the result is shown as Json string not properly displayed.
At the moment the chanes are applied only for admin media library but we can add the changes also to non-admin media library once everything is done.
I appreciate your help and advice!
- Search box and button
- Search suggestion by ajax call
- Search for directories and media files that much the keyword
- Display of searched items
Fixes: #931
=> Add search function for Media Library

tailwind.config.js
Fix tailwind purge config
This updates the paths which are searched for occurrences of tailwind classes to determine which classes can be purged.
Now, classes which only occur in TypeScript files or preact components are no longer excluded from the `npm run prod` build.
This fixes layout problems in the media library (a few classes only occurred in the media library and nowhere else, which broke the layout).
=> Fix tailwind purge config

.circleci/scripts/get_access_token.py
Hopefully this should fix the bump-version job on the main branch and trigger a new release.
=> Fix release

Pipfile.lock, SECURITY.md, integreat_cms/core/urls.py
Update dependencies and add security policy.
- Update all python dependencies
- Rewrite django-debug settings in urls.py (As requested in @timoludwig upstream issue :tada: )
- Add SECURITY.md for CVE reporting and project policy
=> House Keeping & Security policy

integreat_cms/cms/templates/pois/poi_list.html, integreat_cms/cms/templates/pois/poi_list_archived.html, integreat_cms/cms/templates/pois/poi_list_archived_row.html, integreat_cms/cms/templates/pois/poi_list_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po
This pr improves the performance of poi views.
Co-authored-by: philip popien <membralala@users.noreply.github.com>
- Load poi translations in one query
- Load the current language just once
=> Improve performance for poi views

Pipfile.lock, dev-tools/loadtestdata.sh, example-configs/integreat-cms.ini, integreat_cms/core/settings.py
Update python dependencies and remove obsolete setting
- Update python dependencies
- Remove obsolete `LINKCHECK_DISABLE_LISTENERS` setting
=> Update python dependencies

integreat_cms/cms/templates/content_form_language_switcher.html, integreat_cms/cms/templates/content_language_switcher.html, integreat_cms/cms/templates/events/event_form.html, integreat_cms/cms/templates/pages/page_form.html, integreat_cms/cms/templates/pois/poi_form.html, integreat_cms/cms/templatetags/content_filters.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Fixes language tabs scale issue
- puts version number into the box
- limits language tabs to a max of 5, remaining languages appear in dropdown
Fixes: #1030
=> Fixes language tabs scale issue

.circleci/config.yml, Pipfile, Pipfile.lock, README.md, dev-tools/generate_documentation.sh, dev-tools/install.sh, integreat_cms/cms/templates/settings/user.html, integreat_cms/cms/views/authentication/mfa/mfa_assert_view.py, integreat_cms/cms/views/authentication/mfa/mfa_verify_view.py, integreat_cms/cms/views/settings/mfa/get_mfa_challenge_view.py, integreat_cms/cms/views/settings/mfa/register_user_mfa_key_view.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/mfa/add-key.ts, integreat_cms/static/src/js/utils/mfa-utils.ts, setup.cfg, sphinx/documentation.rst, sphinx/installation.rst
This PR updates python to 3.9 and its corresponding packages. Webauthn also got a complete redesign and our implementation is corrected accordingly.
Co-authored-by: jonas osburg jnugh@users.noreply.github.com
- Update python
- Fix breaking changes in webauthn
- Update documentation
Fixes: #1017
=> Update python to 3.9 and fix breaking changes in webauthn 

.circleci/config.yml, dev-tools/generate_documentation.sh, integreat_cms/api/tests.py, integreat_cms/api/tests/__init__.py, integreat_cms/api/tests/api_tests.py, integreat_cms/api/tests/api_tests_utils.py, integreat_cms/api/tests/expected-outputs/augsburg_de_children.json, integreat_cms/api/tests/expected-outputs/augsburg_de_events.json, integreat_cms/api/tests/expected-outputs/augsburg_de_locations.json, integreat_cms/api/tests/expected-outputs/augsburg_de_page_1.json, integreat_cms/api/tests/expected-outputs/augsburg_de_pages.json, integreat_cms/api/tests/expected-outputs/regions.json, integreat_cms/api/tests/expected-outputs/regions_live.json, integreat_cms/cms/models/regions/region.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Adds api tests for most important endpoints 
- Compares test data with api return values
- Checks json format and status codes
Fixes: #1023
=> Simple API tests

integreat_cms/api/urls.py, integreat_cms/api/v3/pages.py
Add parents (actually ancestors) APIv3 end point.
Add a new function and URL to return all ancestors of a page.
Fixes: #19
=> APIv3: add parents/ancestors end point, fixes #19

integreat_cms/api/decorators.py, integreat_cms/api/middleware/json_debug_toolbar_middleware.py, integreat_cms/api/urls.py, integreat_cms/api/v3/events.py, integreat_cms/api/v3/imprint.py, integreat_cms/api/v3/languages.py, integreat_cms/api/v3/locations.py, integreat_cms/api/v3/offers.py, integreat_cms/api/v3/pages.py, integreat_cms/api/v3/push_notifications.py, integreat_cms/api/v3/regions.py
As we are about to release our first version, I aligned the documentation of our API functions for a better representation in our sphinx docu and removed some dummy lines of code.
=> Streamline API documentation and remove dummy function

integreat_cms/cms/forms/pages/page_form.py, integreat_cms/cms/templatetags/content_filters.py, integreat_cms/cms/views/form_views.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/pages/page-order.ts
Some further improvements for forms
- Reduce number of SQL queries in page form
- Fix resetting to default value in page order table
- Fix permission checks in generic form views
=> Improve forms

integreat_cms/cms/templates/pages/page_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po
Small UI change issues by Daniel.
=> Change position of icon in page_form

example-configs/integreat-cms.ini, integreat_cms/cms/templates/events/event_list.html, integreat_cms/cms/templates/pois/poi_list.html, integreat_cms/cms/views/events/event_actions.py, integreat_cms/cms/views/events/event_list_view.py, integreat_cms/cms/views/pois/poi_actions.py, integreat_cms/cms/views/pois/poi_list_view.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Add setting to enable/disable automatic translations
- Add settings `DEEPL_AUTH_KEY` and `DEEPL_ENABLED`
- Hide automatic translation bulk actions if DeepL is deactivated
=> Add setting to enable/disable automatic translations

CHANGELOG.md, integreat_cms/core/settings.py, integreat_cms/xliff/xliff1_serializer.py
Fix XLIFF segmentation
- Add legacy `<header>` in XLIFF 1.2
- Use legacy field ids in XLIFF 1.2
Fixes: #1134
=> Fix XLIFF segmentation

integreat_cms/cms/models/push_notifications/push_notification.py, integreat_cms/cms/templates/push_notifications/push_notification_list_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR tries to reduce SQL-queries for push notification page.
Related to #943 
-  collect all languages for which a translation exists before showing a push notification message in the list to avoid same/similar database calls at language flags (to choose edit icon or plus icon)
-
-
=> Improve performance for push notification

CHANGELOG.md, dev-tools/generate_documentation.sh, sphinx/changelog.rst
Link to related issues in the changelog
- Add markdown links to CHANGELOG.md
- Convert links to restructured text in documentation build
Fixes: #1061
=> Link to related issues in the changelog

CHANGELOG.md, integreat_cms/cms/templates/events/_event_filter_form.html, integreat_cms/cms/templates/events/_poi_query_result.html, integreat_cms/cms/templates/events/event_form.html, integreat_cms/cms/views/events/event_form_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/events/event-query-pois.ts
This fixes a few problems with POIs in the event form and list
- Fix filtering for locations in event list
- Redesign POI selection in event form
- Do not preselect unused location for new event
Fixes: #1166
Fixes: #1172
Fixes: #1173
=> Fix POI integration in event form and list

CHANGELOG.md, integreat_cms/cms/fixtures/test_data.json, integreat_cms/cms/templates/linkcheck/link_list_row.html, integreat_cms/cms/templatetags/text_filters.py, integreat_cms/locale/de/LC_MESSAGES/django.po, tests/api/expected-outputs/api_augsburg_de_children_depth_2.json, tests/api/expected-outputs/augsburg_de_children.json, tests/api/expected-outputs/augsburg_de_pages.json
Fix `AttributeError` in link list
- Add fallback status if unchecked
- Improve appearance of linkchecker table
- Add links to test data to catch such errors in the future
Fixes: #1188
=> Fix `AttributeError` in link list

integreat_cms/cms/views/pages/page_xliff_import_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/xliff/utils.py
This fixes the error:
`TypeError: join() argument must be str, bytes, or os.PathLike object, not 'UUID'`
=> Fix `TypeError` in XLIFF import view

integreat_cms/cms/forms/pages/page_form.py, integreat_cms/cms/forms/pages/parent_field_widget.py, integreat_cms/cms/urls/protected.py, integreat_cms/cms/views/pages/__init__.py, integreat_cms/cms/views/pages/page_actions.py, tests/cms/views/view_config.py
Fix parent page select input
- Make it possible again to select no parent page for root pages
- Optimize url patterns for page order table
=> Fix parent page select input

.circleci/config.yml
Create non-beta release
- Remove beta tag from next bump version update
- Create non-pre-release on GitHub
=> Prepare non-beta release

integreat_cms/core/settings.py, integreat_cms/linkcheck/apps.py, sphinx/conf.py
Use AutoField for primary keys of linkcheck app
Fixes: #1205
=> Use `AutoField` for primary keys of linkcheck app

CHANGELOG.md, integreat_cms/api/v3/events.py, integreat_cms/api/v3/locations.py, tests/api/expected-outputs/augsburg_de_events.json
Fix API return format of event location
=> Fix API return format of event location

integreat_cms/cms/templates/pages/page_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po
Fix layout in new page form on large screens (when you don't have a large screen you can see the broken behaviour when you zoom out)
- Show high dpi grid only when page already exists
This is a low prio PR, does not need to be reviewed today.
=> Fix layout in new page form on large screens

CHANGELOG.md, integreat_cms/api/v3/events.py, integreat_cms/api/v3/locations.py, integreat_cms/cms/constants/position.py, integreat_cms/cms/forms/custom_tree_node_form.py, integreat_cms/cms/forms/language_tree/language_tree_node_form.py, integreat_cms/cms/forms/pages/page_form.py, integreat_cms/cms/models/abstract_tree_node.py, integreat_cms/cms/templates/pages/page_form.html, integreat_cms/cms/views/language_tree/language_tree_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/forms/tinymce-init.ts, tests/api/expected-outputs/augsburg_de_events.json
New release with the latest fixes
* [ [#1214](https://github.com/digitalfabrik/integreat-cms/issues/1214) ] Fix API return format of event location
* [ [#1218](https://github.com/digitalfabrik/integreat-cms/issues/1218) ] Fix saving of first root node
* [ [#1215](https://github.com/digitalfabrik/integreat-cms/issues/1215) ] Use canonical Enter / Shift+Enter behavior in TinyMCE
=> Fixup release

CHANGELOG.md, integreat_cms/api/v3/pdf_export.py
Fix PDF export API
- Fix `MultipleObjectsReturned` error
- Fix `TypeError` - list.count() takes exactly one argument (0 given)
Fixes: #
=> Fix PDF export API

CHANGELOG.md, integreat_cms/api/v3/imprint.py, integreat_cms/api/v3/pdf_export.py
Hopefully, that's the final release for today :see_no_evil: 
* [ [#1223](https://github.com/digitalfabrik/integreat-cms/issues/1223) ] Remove icon from imprint API
* [ [#1224](https://github.com/digitalfabrik/integreat-cms/issues/1224) ] Fix PDF export API
=> Final fix release

CHANGELOG.md, integreat_cms/api/v3/imprint.py
This PR is correcting the path and url field in the api response for the imprint
Fixes: #1227
=> Add path field to imprint response

.circleci/config.yml
Fix bumping of alpha versions
- Do not iterate in a loop but query the latest version and do the bumping job twice
Fixes: #1228
=> Fix bumping of alpha versions

.circleci/config.yml
Fix bumping of alpha versions
Fixes: #1228
=> Fix bumping of alpha versions (this time for real)

integreat_cms/api/v3/pages.py
Improve error message when duplicate slugs exist
- Improve error message
- Log additional information
This is related to #1232
=> Improve error message when duplicate slugs exist

CHANGELOG.md, integreat_cms/cms/forms/custom_tree_node_form.py
Fix page form change detection
Coerce initial and data value to integers
Fixes: #1251
=> Fix page form change detection

CHANGELOG.md, integreat_cms/api/v3/regions.py, tests/api/expected-outputs/regions.json, tests/api/expected-outputs/regions_live.json
Fix the `push_notifications` attribute in the region/sites endpoint.
=> Deploy fixed region/sites endpoint

CHANGELOG.md, integreat_cms/api/v3/feedback/event_feedback.py, integreat_cms/api/v3/feedback/page_feedback.py, integreat_cms/api/v3/feedback/poi_feedback.py, integreat_cms/cms/fixtures/test_data.json, tests/api/expected-outputs/api_augsburg_de_children_depth_2.json, tests/api/expected-outputs/augsburg_de_children.json, tests/api/expected-outputs/augsburg_de_events.json, tests/api/expected-outputs/augsburg_de_locations.json, tests/api/expected-outputs/augsburg_de_page_1.json, tests/api/expected-outputs/augsburg_de_pages.json
This fixes the bug in the feedback endpoint
- Add second version for content translations to test data (this reproduces the bug)
- Fix `MultipleObjectsReturned` in feedback endpoint
Fixes: #1271
=> Fix feedback endpoint

CHANGELOG.md, integreat_cms/cms/models/pages/abstract_base_page_translation.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/xliff/utils.py, tests/xliff/__init__.py, tests/xliff/dummy_django_app/__init__.py, tests/xliff/dummy_django_app/static_urls.py, tests/xliff/files/export/augsburg_de_en_1_2_willkommen.xliff, tests/xliff/files/export/augsburg_de_en_2_1_willkommen-in-augsburg.xliff, tests/xliff/files/import/augsburg_de_en_1_2_willkommen.xliff, tests/xliff/files/import/augsburg_de_en_2_1_willkommen-in-augsburg.xliff, tests/xliff/xliff_test.py
This fixes the XLIFF import
- Add tests for xliff import/export
- Fix change detection for XLIFF import
- Allow importing unchanged XLIFF files
Fixes: #1276
Fixes: #1277
=> Fix XLIFF import

README.md, integreat_cms/README.md
Let's test whether the PR comment works
- Add code coverage badge to README
Fixes: #1193
=> Add code coverage badge to README

CHANGELOG.md, dev-tools/_functions.sh, integreat_cms/cms/models/push_notifications/push_notification_translation.py, integreat_cms/cms/templates/_base.html, integreat_cms/cms/templates/push_notifications/push_notification_form.html, integreat_cms/cms/templates/push_notifications/push_notification_list.html, integreat_cms/cms/templates/push_notifications/push_notification_list_row.html, integreat_cms/cms/templatetags/push_notification_filters.py, integreat_cms/cms/views/push_notifications/push_notification_form_view.py, integreat_cms/cms/views/push_notifications/push_notification_list_view.py, integreat_cms/cms/views/push_notifications/push_notification_sender.py, integreat_cms/core/circleci_settings.py, integreat_cms/core/context_processors.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, tests/cms/views/view_config.py
- Improve the feedback a user gets when something goes wrong with push notifications
- Enable linking of push notifications to local news in native apps
Fixes #760
=> Improve push notifications handling

integreat_cms/cms/templates/events/event_list.html, integreat_cms/cms/templates/pages/page_tree.html, integreat_cms/cms/templates/pois/poi_list.html, integreat_cms/cms/views/pois/poi_list_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Improve translation of disabled creation button
- Improve translation of disabled creation button
=> Improve translation of disabled creation button

CHANGELOG.md, integreat_cms/static/src/js/media-management/component/edit-directory-sidebar.tsx, integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx, integreat_cms/static/src/js/media-management/library.tsx
Fix layout of media library on small screens
=> Fix layout of media library on small screens

CHANGELOG.md, integreat_cms/static/src/js/media-management/component/edit-directory-sidebar.tsx, integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx, integreat_cms/static/src/js/media-management/library.tsx
Deploy the fix for the media library
* [ [#1314](https://github.com/digitalfabrik/integreat-cms/issues/1314) ] Fix layout of media library on small screens
=> Release 2022.3.6

CHANGELOG.md, Pipfile.lock, integreat_cms/cms/urls/protected.py, integreat_cms/cms/views/bulk_action_views.py, integreat_cms/core/settings.py, integreat_cms/deepl_api/utils.py, integreat_cms/locale/de/LC_MESSAGES/django.po, setup.cfg
This is my first draft for the DeepL API. This is for my final exam.
So far I only implemented the first step. However this already raised a few questions for me, so Giuliano proposed to me to upload what I had as a draft, so you can have a look at it already.
The API is so far only implemented for the pois. At a later point this will be implemented for the events in milestone 1.1.
I want to "finish" the API around the 11th of february, so I still have enough time to write the required documentation for the IHK. 
First, let's get to the general questions:
- Do you think the functions I outlined make sense, or do you think there is a redundant function or one that's missing?
- With the structure of the file I tried to stay close to the gvz_api, however I'm not sure if the structure of the …
=> Add automatic translations via DeepL API

CHANGELOG.md, integreat_cms/cms/forms/linkcheck/edit_url_form.py, integreat_cms/cms/templates/linkcheck/link_list_row.html, integreat_cms/cms/templates/linkcheck/links_by_filter.html, integreat_cms/cms/urls/protected.py, integreat_cms/cms/views/linkcheck/linkcheck.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR provides a basic search and replace solution for URLs. It therefore enhances the linkchecker's list view
- Add an URL edit form to the linkchecker's list view
- Replace the URL in pages contents 
Fixes: #1024
=> Implement URL search-replace for linkchecker

Pipfile.lock, package-lock.json
Updates our Python and JS libraries to the newest stable versions. This also comes with a small performance update for the JS compilation :tada: 
Fixes: https://github.com/digitalfabrik/integreat-cms/security/dependabot/6
=> Update dependencies to mitigate minimist vulnerability

CHANGELOG.md, Pipfile.lock, integreat_cms/cms/linklists.py
Filters page translations to only recent version for same page and language
- Updates django-linkcheck app
- Filters page translation to check only recent translation versions for broken links e.g. after a migration
Fixes: #1255
=> Add linkcheck filter

CHANGELOG.md, integreat_cms/cms/templates/events/event_list.html, integreat_cms/cms/templates/pois/poi_list.html, integreat_cms/cms/views/events/event_list_view.py, integreat_cms/cms/views/pois/poi_list_view.py, integreat_cms/core/settings.py, integreat_cms/deepl_api/apps.py, integreat_cms/deepl_api/utils.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR changes the bulk actions for the DeepL API. Bulk action shows option for automatic translations only if the selected language is supported by DeepL.
Fixes: #1198
=> Change bulk action for supported languages by DeepL

CHANGELOG.md, integreat_cms/api/v3/feedback/imprint_page_feedback.py, integreat_cms/cms/fixtures/test_data.json, integreat_cms/cms/views/imprint/imprint_actions.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR fixes two issues with a non existing imprint.
Fixes: #1289 
Fixes: #1359
=> Fix behaviour of imprint feedback

CHANGELOG.md, webpack.config.js
This PR should fix the misbehavior of the cache dealing with CSS files. However, I am not completely sure if this affects all relevant CSS files. @timoludwig Can you verify this? :)
- Add contenthash to MiniCSSPlugin
Fixes: #1369
=> Use contenthash for css files

integreat_cms/cms/templates/pages/page_tree.html, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR renames the XLIFF option to the requested naming from the Service team.
=> Rename xliff export option

.github/workflows/codeql-analysis.yml, .github/workflows/dependency-review.yml, .github/workflows/ossar-analysis.yml
Since we faced a few problems with the OSSAR action in PRs #1393 and #1389, I played around with the github actions a bit, but couldn't find the issue...
Does anybody have an idea how to fix it? If not, I'd just disable it temporarily, until they fix their upstream problem...
Nonetheless, I think we could merge this changes to use the newest versions of the actions and add a new dependency check...
- Update CodeQL and OSSAR
- Add Dependency review
=> Update GitHub actions

CHANGELOG.md, integreat_cms/static/src/js/bulk-actions.ts
Restructure handling of updating the counter. This leads to some massive increases in performance.
Fixes: #1404
=> Fix performance issues for "select all"

integreat_cms/cms/templates/pages/page_tree_archived_node.html, integreat_cms/cms/templates/pages/page_tree_node.html, integreat_cms/locale/de/LC_MESSAGES/django.po
I noticed a small bug with the preview button in the page tree
- Add missing button closing tag
=> Add missing button closing tag

CHANGELOG.md, integreat_cms/cms/templates/regions/region_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po
Add statistic settings to region form again
Fixes: #1471
=> Add statistic settings to region form again

sphinx/conf.py
The certificate is broken again
- Temporarily ignore requests intersphinx mapping
=> Temporarily ignore requests intersphinx mapping

CHANGELOG.md, integreat_cms/api/v3/regions.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, tests/api/expected-outputs/regions.json, tests/api/expected-outputs/regions_live.json
Add default bounding box to region API
Part of: #742
=> Add default bounding box to region API

CHANGELOG.md, integreat_cms/cms/forms/pages/page_form.py, integreat_cms/cms/templates/pages/_page_permission_table.html, integreat_cms/cms/views/pages/page_actions.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Only allow users of the same region for page-specific-permissions
- Remove staff users from selection for page-specific permissions
- Remove users of other regions from selection
- Improve texts and translations
Fixes: #1452
=> Only allow users of the same region for page-specific-permissions

CHANGELOG.md, integreat_cms/cms/models/languages/language.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Invalidate cache of language tree when languages are changed
Fixes: #1487
=> Invalidate cache of related objects when languages are changed

CHANGELOG.md, integreat_cms/cms/forms/__init__.py, integreat_cms/cms/forms/users/user_filter_form.py, integreat_cms/cms/models/regions/region.py, integreat_cms/cms/templates/users/_user_filter_form.html, integreat_cms/cms/templates/users/user_list.html, integreat_cms/cms/utils/user_utils.py, integreat_cms/cms/views/users/region_user_actions.py, integreat_cms/cms/views/users/region_user_form_view.py, integreat_cms/cms/views/users/region_user_list_view.py, integreat_cms/cms/views/users/user_list_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Improve user list
- Hide staff users from region user list
- Add filters to admin user list
Fixes: #1416
=> Improve user list

CHANGELOG.md, integreat_cms/cms/linklists.py, integreat_cms/cms/views/events/event_actions.py, integreat_cms/cms/views/pages/page_actions.py, integreat_cms/cms/views/pois/poi_actions.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Do not check links in archived pages
- Delete link objects when pages/event/locations are archived
- Create link objects when pages/event/locations are restored
Fixes: #1502
=> Do not check links in archived pages

CHANGELOG.md, integreat_cms/cms/views/imprint/imprint_revision_view.py, integreat_cms/cms/views/pages/page_revision_view.py
Fix status change when restoring revisions
Fixes: #1550
=> Fix status change when restoring revisions

CHANGELOG.md, integreat_cms/cms/forms/regions/region_form.py, integreat_cms/locale/de/LC_MESSAGES/django.po, tests/cms/test_duplicate_regions.py
Set all pages to draft when duplicating regions
Fixes: #1517
=> Set all pages to draft when duplicating regions

CHANGELOG.md, integreat_cms/cms/templates/pois/poi_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po
Rename location contact labels
Fixes: #1561
=> Rename location contact labels

CHANGELOG.md, integreat_cms/cms/templates/users/region_user_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po
Hide organization field in user form when no organizations exist
Fixes: #1567
=> Hide organization field in user form

CHANGELOG.md, integreat_cms/cms/templates/imprint/imprint_revisions.html, integreat_cms/cms/templates/imprint/imprint_sbs.html, integreat_cms/cms/templates/pages/page_form.html, integreat_cms/cms/templates/pages/page_revisions.html, integreat_cms/cms/templates/pages/page_sbs.html, integreat_cms/cms/templates/pois/poi_form.html, integreat_cms/cms/templates/users/region_user_form.html, integreat_cms/cms/views/imprint/imprint_revision_view.py, integreat_cms/cms/views/pages/page_form_view.py, integreat_cms/cms/views/pages/page_sbs_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
A few quick fixes for our forms
* [ [#1561](https://github.com/digitalfabrik/integreat-cms/issues/1561) ] Rename location contact labels
* [ [#1567](https://github.com/digitalfabrik/integreat-cms/issues/1567) ] Hide organization field in user form
* [ [#1563](https://github.com/digitalfabrik/integreat-cms/issues/1563) ] Fix permission checks in side-by-side view
=> Release `2022.6.3`

CHANGELOG.md, integreat_cms/cms/templates/events/event_list.html, integreat_cms/cms/templates/events/event_list_archived.html, integreat_cms/cms/templates/events/event_list_archived_row.html, integreat_cms/cms/templates/events/event_list_row.html, integreat_cms/cms/templates/pois/poi_list.html, integreat_cms/cms/templates/pois/poi_list_archived.html, integreat_cms/cms/templates/pois/poi_list_archived_row.html, integreat_cms/cms/templates/pois/poi_list_row.html, integreat_cms/cms/templates/push_notifications/push_notification_list_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/css/style.scss
This PR should fix some misalignments in the list view for long titles / small screens.
- Enable horizontal scrolling for the ```table-listing```  css class
- Truncate titles to 35 chars 
Fixes: #1528
=> Fix list view layout for long titles

CHANGELOG.md, integreat_cms/cms/utils/matomo_api_manager.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR adds the hits from the mobile applications to our statistic and export functions.
- Add specific async call to our matomo requests
Fixes: #1571
=> Add visualization of offline downloads to the statistics

CHANGELOG.md, integreat_cms/cms/templates/imprint/imprint_form.html, integreat_cms/cms/views/imprint/imprint_form_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Fix text of imprint publish/update button
=> Fix text of imprint publish/update button

CHANGELOG.md
Fixes the Changlog, which had an entry at the wrong section
=> Fix corrupted changelog

.circleci/config.yml, .gitignore, CHANGELOG.md, MANIFEST.in, integreat_cms/cms/views/dashboard/dashboard_view.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/locale/nl/LC_MESSAGES/django.po, sphinx/internationalization.rst
This PR adds a dutch translation file
- Add dutch translation file
Fixes: #1628
=> Add dutch translation file

CHANGELOG.md, example-configs/integreat-cms.ini, integreat_cms/core/settings.py
- [ [#1649](https://github.com/digitalfabrik/integreat-cms/issues/1649) ] Make UI languages configurable
=> Release `2022.8.2`

CHANGELOG.md, integreat_cms/cms/templates/pages/page_sbs.html, integreat_cms/cms/views/pages/page_sbs_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This pr fixes the media library and the content edit lock in the page sbs view.
Fixes: #1664
=> Fix page sbs view

integreat_cms/cms/templates/_base.html, integreat_cms/locale/de/LC_MESSAGES/django.po
This is a small PR that adds the last requested changes from #1615 that needed some further feedback.
=> Change position of feedback and change content label

CHANGELOG.md, integreat_cms/cms/templates/analytics/translation_coverage.html, integreat_cms/cms/views/analytics/translation_coverage_view.py, integreat_cms/cms/views/pages/page_form_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/analytics/translation_coverage.ts
This PR updates the UI of our translation report and adds the word calculation for missing translations.
- Change axis of chart to scale vertically with additional languages
- Add word column for missing translations
- Downgrade postcss/autoprefixer to get rid of deprecation warning
Fixes: #1440
Fixes: #1596
=> Refactor translation coverage and add missing translations to word count

CHANGELOG.md, integreat_cms/cms/views/pages/page_form_view.py, tests/cms/views/view_config.py
Fix `AttributeError` when creating new page translations
- Check whether the page translation exists before accessing its status
Fixes: #1678
=> Fix `AttributeError` when creating new page translations

integreat_cms/static/src/js/pages/sbs-copy-content.ts
Fix small JS error in page form
- Fix `Uncaught TypeError: toggleButton is null`
=> Fix JS error in page form

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a new section to the PR template with a section about side effects.
As usual, this section can just be deleted when a PR does not have side effects (similar to deleting the "resolved issues" section when there are no issues resolved, like in this PR), but it raises awareness for the topic.
=> Add side effects section to PR template

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, sphinx/index.rst, sphinx/pull-request-review-guide.rst
I tried to merge the PR reviewing standards we have established into our developer documentation.
=> Add pull request reviewing guide to documentation

.github/PULL_REQUEST_TEMPLATE.md
In our Mattermost notifications, the `<hr>` line is not rendered correctly.
Let's see whether this Markdown-variant of the horizontal rule works as expected...
=> Use markdown `<hr>` in pull request template

CHANGELOG.md, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/summ_ai_api/utils.py
Fix translation of empty tags with SUMM.AI API for Easy German
- Filter out all empty texts and don't translate them
Fixes: #1720
=> Fix translation of empty tags with SUMM.AI API for Easy German

CHANGELOG.md, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/summ_ai_api/utils.py
Release hotfix for SUMM.AI
-  [ [#1720](https://github.com/digitalfabrik/integreat-cms/issues/1720) ] Fix translation of empty tags with SUMM.AI API for Easy German
=> Release `2022.9.5`

CHANGELOG.md, Pipfile.lock, dev-tools/fix_dependencies.sh, integreat_cms/cms/forms/regions/region_form.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/summ_ai_api/summ_ai_api_client.py
A few improvements for the SUMM.AI API client
* [ [#1734](https://github.com/digitalfabrik/integreat-cms/issues/1734) ] Increase timeout for SUMM.AI API client
=> Release `2022.10.0`

CHANGELOG.md, integreat_cms/cms/forms/media/replace_media_file_form.py, integreat_cms/cms/forms/media/upload_media_file_form.py, integreat_cms/cms/models/media/media_file.py, integreat_cms/cms/views/media/media_context_mixin.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx, integreat_cms/static/src/js/media-management/index.tsx
Added last modified date to media sidebar
Added translation
=> Added last modified date to media sidebar

CHANGELOG.md, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/summ_ai_api/utils.py
Fix `IndexError` when SUMM.AI API returns empty result
- Do not replace text if paragraph contains only special characters
Fixes: #1770
=> Fix `IndexError` when SUMM.AI API returns empty result

.github/ISSUE_TEMPLATE/feature-request.md
This PR updates our feature template with a UI/UX section to reference detailed requirements for the design process.
=> Extend feature template with UI/UX recommendations

integreat_cms/cms/templates/statistics/_statistics_widget.html, integreat_cms/cms/templates/statistics/statistics_overview.html, integreat_cms/cms/views/statistics/statistics_actions.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/analytics/statistics-charts.ts
Adjusted the error message. 
Fixes: #1700 
=> Add adjusted error message for statistics page

tests/summ_ai_api/summ_ai_test.py
I hope this fixes the failing tests of #1781, #1775 and #1785
- No longer change `last_updated` field of region object when executing async SUMM.AI test
=> Fix race condition in async tests

example-configs/integreat-cms.ini, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Make textlab API configurable
- Change default textlab url
- Add new setting to config file
Fixes: #1774
=> Make textlab API configurable

CHANGELOG.md, integreat_cms/cms/templates/pois/poi_form.html, integreat_cms/cms/views/pois/poi_actions.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/css/style.scss, integreat_cms/static/src/index.ts, integreat_cms/static/src/js/pois/poi-actions.ts, integreat_cms/static/src/js/pois/poi-map.ts, integreat_cms/static/src/map.ts, package-lock.json, package.json, webpack.config.js
This PR adds a map preview function on the POI form.
- Add a button "Preview on Map".
- The location will be shown on the map as a pin, if coordinates are given (or auto-filled). Otherwise an error message* (will be decorated later).
- Uses https://github.com/maplibre/maplibre-gl-js
- Preview in popup as hidden overlay
*I'm not sure what kind of error message is good for the case that no coordinates are given. Should the button apper first after the coordinates are given/auto-calculated?
- The POI form page might be slow now, having an ajax, many events and live map popup.
Fixes: #1170 
=> Add map preview on POI form

CHANGELOG.md, integreat_cms/nominatim_api/nominatim_api_client.py, integreat_cms/static/src/js/pois/poi-actions.ts
This is a follow-up on #1633
- If a street number range is given, only take the first street number
- There might be street names which contain number ranges which do not belong to the street number. 
Fixes: #1579
=> Fix auto-filling of coordinates for multiple street numbers

CHANGELOG.md, integreat_cms/cms/utils/matomo_api_manager.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Include offline downloads in per language download numbers.
Change Matomo API request to count all downloads per language.
Invalidates numbers from last months, but is compatible with statistics over last years.
Fixes: #1767
=> Change statistics calculcation, fixes #1767

.circleci/config.yml, .gitattributes, dev-tools/check_changelog.sh
This hopefully improves our workflow regarding the changelog file.
- Add CircleCI check for changelog format
- Use union as default merge strategy for the CHANGELOG.md
- How can we test that the format is still valid after merging?
- How can we test that the entries are not placed in the sections of already released versions, e.g. if the branch is outdated and a release was triggered in the meantime?
- Also, I'm not quite sure how the `.gitattribute` works, whether it enabled merges despite conflicts or whether it just makes resolving conflicts a bit easier...
- Does this make #1763 obsolete?
Fixes: #1161
Fixes: #1689
=> Improve Changelog tooling

.pre-commit-config.yaml, Pipfile.lock, integreat_cms/cms/templates/feedback/admin_feedback_list.html, integreat_cms/cms/templates/feedback/region_feedback_list.html, integreat_cms/cms/templates/imprint/imprint_revisions.html, integreat_cms/cms/templates/pages/page_revisions.html
Update pip dependencies to fix vulnerability in cryptography dependency
Fixes: https://github.com/digitalfabrik/integreat-cms/security/dependabot/13
=> Update pip dependecies

CHANGELOG.md, integreat_cms/cms/views/statistics/statistics_actions.py
Fix statistics widget on dashboard
- Remove incorrect call to `method_decorator` (this is only required for class-based views) 
Fixes: #1840
=> Fix statistics widget on dashboard

CHANGELOG.md, integreat_cms/cms/views/statistics/statistics_actions.py
Release hotfix for statistics dashboard
* [ [#1840](https://github.com/digitalfabrik/integreat-cms/issues/1840) ] Fix statistics widget on dashboard
=> Release `2022.11.1`

CHANGELOG.md, integreat_cms/cms/templates/dashboard/region_selection.html
Release hotfix for region selection
* [ [#1843](https://github.com/digitalfabrik/integreat-cms/issues/1843) ] Fix region selection after login
=> Release `2022.11.2`

CHANGELOG.md, integreat_cms/cms/views/events/event_form_view.py, integreat_cms/cms/views/pages/page_form_view.py, integreat_cms/cms/views/pois/poi_form_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This applies to pages, events and pois.
- Show warning when the user provided slug automatically got changed
- For pages, link to a version that uses the slug
- for pois and events, link to the latest translation of the object and note that the slug might have been used by a previous version of this object
/
Fixes: #1521
=> Show a warning when a user entered slug got changed

CHANGELOG.md, integreat_cms/api/v3/feedback/event_feedback.py
Enable submitting feedback about fallback translations of recurring events
- Use the event slug without the recurring date appendix also for fallback translations
- Fix the incorrect error message
Fixes: #1858
=> Fix feedback for fallback translations of recurring events

integreat_cms/cms/views/users/region_user_actions.py, integreat_cms/cms/views/users/region_user_form_view.py, integreat_cms/cms/views/users/user_actions.py, integreat_cms/cms/views/users/user_form_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Fix up a few remnants of #1670
- Use consistent success messages for user/account creation/update/deletion
=> Clean up success messages for users/accounts

integreat_cms/cms/forms/regions/region_form.py, integreat_cms/cms/models/regions/region.py, integreat_cms/cms/views/statistics/statistics_actions.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/locale/nl/LC_MESSAGES/django.po, integreat_cms/matomo_api/apps.py, integreat_cms/matomo_api/matomo_api_client.py
Move MatomoApiManager to separate app, like we did before with deepl_api, gvz and summ_ai
- Created matomo_api app and registered it
- Created apps.py file for MatomoApiManager
- MatomoApi
Fixes: #1737 
=> Move Matomo API client to separate app

.pre-commit-config.yaml
The checking script should only run when there actually something to check.
- Only run translation hook if python or HTML files were modified
- Faster execution times of the pre commit hooks if no Python and HTML files are modified
=> Only run translation hook if python or HTML files were modified

CHANGELOG.md, integreat_cms/static/src/js/charCounter.ts
Fix the character counting that was broken as a side effect from #1713 
- update the query responsible for finding textareas with a character counter
- none 
Fixes: #1886 
=> Fix push notification character counter not working

integreat_cms/deepl_api/apps.py
The change introduced in #1748 broke the DeepL functionality during local development.
Not sure if this solution is ideal tbh, maybe we should rather store the supported languages in the cache rather than the app config? :thinking: 
-  Fix availability check of DeepL API during development
- Slightly longer restarting times when the server reloads after a file has been edited
=> Fix availability check of DeepL API during development

integreat_cms/cms/models/abstract_base_model.py
Reduce logging verbosity if related object does not exist
- Skip the logging call in this case
- Add a notice that logged errors might be false positives and should be excluded when they occur
Fixes: #1908
=> Reduce logging verbosity if related object does not exist

CHANGELOG.md, integreat_cms/cms/models/abstract_content_model.py, integreat_cms/cms/templates/imprint/imprint_sbs.html, integreat_cms/cms/views/imprint/imprint_sbs_view.py, integreat_cms/cms/views/pages/partial_page_tree_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po, sphinx/pull-request-review-guide.rst
Release hotfix for page tree loading times
* [ [#1756](https://github.com/digitalfabrik/integreat-cms/issues/1756) ] Add media library, content-edit-lock and diff-view to imprint sbs-view
* [ [#1870](https://github.com/digitalfabrik/integreat-cms/issues/1870) ] Fix copy source content in imprint sbs-view
* [ [#1950](https://github.com/digitalfabrik/integreat-cms/issues/1950) ] Fix long loading time of page tree
=> Release `2022.12.1`

CHANGELOG.md, integreat_cms/cms/forms/pages/page_filter_form.py, integreat_cms/cms/templates/pages/_page_filter_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR is supposed to improve the page filters by adding a field to filter for latest revision and to filter pages by date. 
- Add filter for latest revision 
- Add filter to filter pages by date
Hopefully none
Fixes: Parts of #686 
=> Add latest revision and date filter to page filters

dev-tools/_functions.sh, dev-tools/prune_database.sh
I hope this makes it possible to use our dev tools even if docker is running in rootless mode.
@membralala could you check whether this works for you? 
- Instead of requiring root permissions for all docker operations, check whether `docker ps` already succeeds without sudo
=> Enable dev tools for rootless docker

integreat_cms/deepl_api/apps.py
I thought it might be a good idea to keep track of our credit usage
- Check DeepL credit usage on server start and add it to logging message 
- Slightly increased loading time of dev server when enabling DeepL in develop mode
=> Log DeepL character usage on server start

CHANGELOG.md, dev-tools/check_changelog.sh, package-lock.json, package.json
Hotfix to fix the broken HIX widget :fire_engine: 
* [ [#2003](https://github.com/digitalfabrik/integreat-cms/issues/2003) ] Fix HIX widget
=> Release `2023.1.1`

example-configs/integreat-cms.ini, integreat_cms/core/settings.py, integreat_cms/summ_ai_api/summ_ai_api_client.py
This PR sets the flag "is_inital" of SUMM.AI to True.
- Add a constant SUMM_AI_INITIAL_FLAG with value of True in settings
- Use this in API request.
- I hope none.
- Let me know if this change must be in Changelog.
Fixes: #1995 
=> Set SUMM.AI's "is_inital" flag to True

integreat_cms/cms/templates/translations/translations_management.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/index.ts, integreat_cms/static/src/js/translations/budget-graph.ts
Add translation budget graph to MT management section
- add translation budget graph to MT management section
- kept it as doughnut graph for now (similar to HIX chart) for more uniform design, but can easily be changed to pie chart (as in the design)
- none
Fixes: #1926 
=> Add translation budget graph to MT management section

integreat_cms/cms/templates/events/event_form.html, integreat_cms/cms/templates/pages/page_form.html, integreat_cms/cms/templates/pois/poi_form.html
This PR improves spacings in the page form, poi form and event.
- Add 0.75rem margin top to the first box
- Remove the gap-2 so everywhere is the same margin (0.75rem)
There might be some once #2039 is pushed
Fixes: #2040 
=> Improve spacing in page form, poi form and event form for mobile view

integreat_cms/cms/templates/pois/poi_form_sidebar/opening_hours_box.html, integreat_cms/locale/de/LC_MESSAGES/django.po
The opening hours are now shown in the apps:
https://github.com/digitalfabrik/integreat-app/releases/tag/2023.1.7-android
~~I just noticed this is just a beta release, so we should probably wait another week until we merge this.~~
- Indicate that opening hours are now shown in the apps
=> Indicate that opening hours are now shown in the apps

CHANGELOG.md, integreat_cms/api/v3/events.py, integreat_cms/cms/forms/regions/region_form.py, tests/api/api_config.py, tests/api/expected-outputs/augsburg_ar_events.json, tests/api/expected-outputs/augsburg_de_events.json, tests/api/expected-outputs/augsburg_en_events.json, tests/api/expected-outputs/nurnberg_de_events.json, tests/api/expected-outputs/nurnberg_en_events.json, tests/api/test_api_feedback.py, tests/cms/test_duplicate_regions.py
Release the hotfix for the recurring events API
* [ [#2012](https://github.com/digitalfabrik/integreat-cms/issues/2012) ] Exclude archived pages when cloning a region
* [ [#2093](https://github.com/digitalfabrik/integreat-cms/issues/2093) ] Fix recurring events endpoint
=> Release `2023.2.2`

dev-tools/generate_documentation.sh
During #2027, I forgot to make the documentation script version agnostic.
- Make documentation script compatible with different python versions
=> Make documentation script compatible with different python versions

CHANGELOG.md, integreat_cms/api/v3/pages.py, integreat_cms/cms/fixtures/test_data.json, tests/api/expected-outputs/api_augsburg_de_children_depth_2.json, tests/api/expected-outputs/augsburg_ar_pages.json, tests/api/expected-outputs/augsburg_de_children.json, tests/api/expected-outputs/augsburg_de_children_archived_descendants.json, tests/api/expected-outputs/augsburg_de_page_1.json, tests/api/expected-outputs/augsburg_de_pages.json
This PR adds the organization name & logo to the page API response. It is the first time I'm really working with the API so feel free to give detailed tips/background information on how we handle things with our API.
- Add organization name & logo to page API response
- I think none
Fixes:  #1322
=> Add organization name & logo to the page API response

CHANGELOG.md, docs/src/conf.py, integreat_cms/cms/templates/_base.html, integreat_cms/cms/templates/translations/translations_management.html, integreat_cms/cms/templatetags/base_filters.py, integreat_cms/core/context_processors.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR moves and renames the machine translation management section.
- Move the section to the settings area of menu bar.
- Rename it to Machine Translations.
- Remove the debug mode constraint.
- I hope none.
Fixes: #2118 
=> Move and rename MT management

CHANGELOG.md, integreat_cms/cms/views/analytics/translation_coverage_view.py
Improve performance of translation coverage
- Prefetch the major translations instead of the major public translations
Fixes: #2139
=> Improve performance of translation coverage

integreat_cms/cms/forms/translations/machine_translation_form.py, integreat_cms/cms/models/languages/language_tree_node.py, integreat_cms/cms/views/bulk_action_views.py, integreat_cms/cms/views/events/event_form_view.py, integreat_cms/cms/views/pages/page_form_view.py, integreat_cms/cms/views/pois/poi_form_view.py, integreat_cms/deepl_api/utils.py
This should fix all the remnants we missed in #2124.
- Fix usage of new DeepL availability check
Fixes: #2134
=> Fix usage of new DeepL availability check

.circleci/config.yml
This time for real (hopefully :laughing:)
- [ [#1005](https://github.com/digitalfabrik/integreat-cms/issues/1005) ] Add possibility to filter for unused media files
- [ [#1831](https://github.com/digitalfabrik/integreat-cms/issues/1831) ] Add management section for machine translation
- [ [#1875](https://github.com/digitalfabrik/integreat-cms/issues/1875) ] Add possibility to create machine translations in the form when updating pages, events and locations
- [ [#2048](https://github.com/digitalfabrik/integreat-cms/issues/2048) ] Add possibility to show media file usages in sidebar
- [ [#2055](https://github.com/digitalfabrik/integreat-cms/issues/2055) ] List the regions that use a language in the language form
- [ [#2124](https://github.com/digitalfabrik/integreat-cms/issues/2124) ] Fix …
=> Release `2023.3.1`

.circleci/config.yml
This was a regression of 7f82f66cf8296cbacbdfb2c17bf2bfb1d99bf0c1
- Fix incorrect quote in Mattermost release notification job
=> Fix incorrect quote in Mattermost release notification job

integreat_cms/cms/forms/translations/machine_translation_form.py, integreat_cms/release_notes/current/unreleased/2178.yml
Inactive languages should be hidden in the MT form.
- hide it.
- none 
=> Hide inactive languages in MT form

integreat_cms/api/v3/pages.py, integreat_cms/release_notes/current/unreleased/2169.yml, tests/api/api_config.py
Improve page API children endpoint load times
- Swap iteration to make sure the pages with prefetched translations are passed to the `transform_page` method.
Fixes: #2169
=> Improve page API children endpoint load times

integreat_cms/cms/models/abstract_content_translation.py, integreat_cms/cms/views/pois/poi_form_ajax_view.py, pyproject.toml, tools/pylint.sh
Fix pylint useless suppression warnings
- remove the useless suppressions
- none
Fixes: n/a
=> Fix pylint useless suppression warnings

integreat_cms/cms/models/abstract_content_translation.py, integreat_cms/cms/templates/pages/page_form.html, integreat_cms/cms/views/pages/page_actions.py, integreat_cms/release_notes/current/unreleased/2191.yml, integreat_cms/xliff/base_serializer.py, integreat_cms/xliff/utils.py, tests/xliff/utils.py, tests/xliff/xliff_test.py
Show translation status correctly if the latest version is a minor edit and is currently being translated
- Set the `currently_in_translation` flag for all versions, not only the latest version
Fixes: #2191
=> Fix translation state for minor edit currently in translation

integreat_cms/cms/migrations/0069_feedback_archived.py
This is another reason why we need #2060 :sweat_smile: 
=> Fix conflicting migrations

integreat_cms/cms/templates/pages/page_revisions.html, integreat_cms/core/signals/hix_signals.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2225.yml, integreat_cms/static/src/js/revisions.ts
This PR shows HIX value in page revision view.
- Show Hix score in the slide bar box and between Publication status and Author.
- Apply this only when HIX is globally and in the region activated and not deactivated for the page. If no HIX value is stored, leave the space empty (just like empty content).
Fixes: #2225 
=> Show Hix value in page revision view

integreat_cms/cms/templates/linkcheck/link_list_row.html, integreat_cms/cms/templates/linkcheck/links_by_filter.html, integreat_cms/cms/utils/linkcheck_utils.py, integreat_cms/cms/views/linkcheck/linkcheck_list_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
The author chat revealed that users do not understand the new columns "SSL" and "Code".
In my opinion, the difference between a secure and an insecure link as well as between a "404 No Found" and "403 Forbidden" should still be useful to uneducated users, thus I suggest to add a few help text, rather than just hide them from non-expert users...
- Fix differing link text in link replacement form
- Improve explanation of link checker columns
Fixes: #2237
=> Improve UI of link checker

integreat_cms/cms/templates/linkcheck/link_list_row.html, integreat_cms/cms/templates/linkcheck/links_by_filter.html, integreat_cms/cms/templatetags/pdf_filters.py, integreat_cms/cms/utils/linkcheck_utils.py, integreat_cms/cms/views/linkcheck/linkcheck_list_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2246.yml
Release the fix for PDF creation
- [ [#2246](https://github.com/digitalfabrik/integreat-cms/issues/2246) ] Fix error in PDF export
=> Release `2023.4.3`

.circleci/config.yml
Fix dev version bump when latest release is newer
- Only bump the dev version to the current alpha version if this version is newer than the current production version
Fixes: #2190
=> Fix dev version bump when latest release is newer

.pre-commit-config.yaml, docs/src/templates/layout.html
I noticed the djlint pre-commit hook only executed the `--lint` task and did not reformat anything...
- Use `--reformat` option for djlint pre-commit hook
=> Use `--reformat` option for djlint pre-commit hook

integreat_cms/cms/views/dashboard/region_selection.py, integreat_cms/cms/views/pages/page_actions.py, integreat_cms/release_notes/current/unreleased/2284.yml, tests/cms/views/utils.py, tests/cms/views/view_config.py
Fix error when granting additional page permissions
- Replace `user.regions` by `user.regions.all()`
- Add tests for page permissions
Fixes: #2284
=> Fix error when granting additional page permissions

docs/src/api-docs.rst, docs/src/index.rst, integreat_cms/release_notes/current/unreleased/1690.yml
This pr adds an api documentation.
- Add documentation to api/init.py
/
Fixes: #1690 
=> Add API documentation

docs/src/management-commands.rst, integreat_cms/cms/linklists.py, integreat_cms/cms/urls/protected.py, integreat_cms/cms/views/language_tree/__init__.py, integreat_cms/cms/views/language_tree/language_tree_bulk_actions.py, integreat_cms/cms/views/language_tree/language_tree_node_form_view.py, integreat_cms/core/settings.py, integreat_cms/release_notes/current/unreleased/2054.yml
This PR modifies link check so it will not check links in translations of inactive languages.
- Delete all links in the language which is changed to inactive. 
- Trigger link check when a language gets set to active.
- Add object filters to exclude translations in inactive languages.
- Restration/deleting of links sometimes takes a while (doesn't finish in a second).
Fixes: #2054 
=> Do not check links in inactive languages

docs/src/api-docs.rst, integreat_cms/api/v3/location_categories.py, integreat_cms/release_notes/current/unreleased/2332.yml, tests/api/expected-outputs/augsburg_ar_location_categories.json, tests/api/expected-outputs/augsburg_ar_locations.json, tests/api/expected-outputs/augsburg_de_location_categories.json, tests/api/expected-outputs/augsburg_de_locations.json, tests/api/expected-outputs/augsburg_en_location_categories.json, tests/api/expected-outputs/augsburg_en_locations.json
This PR adds a new field `icon_url` to API response of POI.
- Add `icon_url` to API response
- Adjust API documentation
- Adjust test
- I'm not sure with the path: is `STATIC_URL` enough in development?
Fixes: #2332
=> Add icon url to POI API response

example-configs/integreat-cms.ini, integreat_cms/cms/templates/_base.html, integreat_cms/core/context_processors.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/1547.yml, integreat_cms/static/src/css/style.scss
With the increasing number of test & production systems of our different whitelabel solutions, I think this banner helps to keep the overview.
- Show test banner in test systems
Fixes: #1547
=> Show test banner in test systems

integreat_cms/cms/forms/push_notifications/push_notification_form.py, integreat_cms/cms/models/push_notifications/push_notification.py, integreat_cms/cms/templates/push_notifications/push_notification_form.html, integreat_cms/cms/views/push_notifications/push_notification_form_view.py, integreat_cms/core/management/commands/send_push_notifications.py, integreat_cms/core/middleware/region_middleware.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Fix discovered bugs in the recently merged push notification features for testing
- Timezone information is not a property of PushNotifications anymore, scheduled date is now always rendered in the timezone of the currently active region
- Languages are sorted according to the language tree of the currently active region
- If the user has access to only one region, the form won't show the regions checkboxes and POST won't contain that data. Add it back so the form data can be validated and saved properly.
unknown
=> Fix Push Notification Problems

integreat_cms/cms/templates/_base.html, integreat_cms/core/middleware/region_middleware.py, integreat_cms/core/settings.py
Improve region middleware
- Refactor if conditions
- Make number of regions in the selection dropdown configurable
- Use empty queryset instead of empty list
=> Improve region middleware

integreat_cms/cms/migrations/0077_adjust_region_deepl_addon_booked.py
This is a follow up PR for the broken migrations due to the merge of #2376 
- Fix the sequence of migration files
- /
=> Fix migration

integreat_cms/cms/templates/_base.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2386.yml
Change the text of the test banner to the correct integration process.
- Change text in test banner
- None 
Fixes: #2386 
=> Change of banner text for test system

integreat_cms/core/management/commands/fix_internal_links.py
This PR fixes an error in the command `fix_internal_links`
- add a check whether the `public_translation` is not `None`
- None?
- There might be similar potential error causes. If you notice any, let me know.
Fixes: #2393
=> Fix error in fix_internal_link command

integreat_cms/cms/templates/events/event_list.html, integreat_cms/cms/templates/pages/page_tree.html, integreat_cms/cms/templates/pois/poi_list.html, integreat_cms/cms/urls/protected.py, integreat_cms/cms/views/bulk_action_views.py, integreat_cms/cms/views/utils/translation_status.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2337.yml
This PR adds the option to change pages, events and pois to draft or public in a bulk action
- Add function to change the translation status
- Add bulk action call to events, pois and pages
None I'm aware of
Fixes: #2337
=> Add drafting and publishing bulk action

integreat_cms/api/decorators.py, integreat_cms/api/v3/locations.py, integreat_cms/core/settings.py, integreat_cms/core/utils/strtobool.py
I was kinda annoyed by the `distutils` deprecation warning and solved them for our project by following the PEP 632 recommendations (see [https://peps.python.org/pep-0632/](https://peps.python.org/pep-0632/)).
- Add a general utils file to the top level of our project if our modules are needing more shared methods.
Fixes: #2122 
=> Fix pylint deprecation warnings

integreat_cms/cms/views/utils/translation_status.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR fixes an error which occurs when a selected content doesn not have any translation in the selected language.
This needs to be merged before the next release.
- Check if any translation exists in the selected language
- If not, show a message
- No?
Fixes: #2411 
=> Fix error in bulk draft/publish action

tests/deepl_api/deepl_api_test.py
Add additional tests to check automatic translation via DeepL
- Add tests to check DeepL translation when the 'automatic translation' checkbox is set on the content edit form
- Small refactoring
No?
Fixes: #2136
=> Add tests for DeepL feature

integreat_cms/cms/forms/translations/translations_management_form.py, integreat_cms/cms/views/translations/translations_management_view.py
Probably there are more radical possibilities to reduce the loading times, but this should already be a big improvement with minimal changes.
- Select the related `Language` objects of the language tree
- Prefetch the related translations of the content objects
Fixes: #2423
=> Reduce loading times of machine translation management section

integreat_cms/cms/templates/_base.html, integreat_cms/locale/de/LC_MESSAGES/django.po
The part "This is a test system." was shown twice.
=> Fix message on test banner

integreat_cms/core/management/commands/send_push_notifications.py
Since the push notification sending command is used as cronjob and not as manual command (and because the [output of the crobjob is redirected to the logfile](https://git.tuerantuer.org/DF/salt/src/commit/c0ebd23bcffb5c8ce61fb4e2e3e2d88d65dcffeb/states/integreat-cms/files/cms-worker.service#L12)), the previous solution caused a few messages in the log that were very hard to identify, e.g.:
```
Done!
```
Instead of print statements (which are great for manual commands because they're better readable than log entries), I suggest to convert the output to regular logging calls.
- Change print to logging in push notification sender
=> Change print to logging in push notification sender

integreat_cms/cms/fixtures/test_data.json, integreat_cms/cms/forms/users/password_reset_form.py, integreat_cms/cms/templates/_raw.html, integreat_cms/cms/templates/analytics/_website_size_widget.html, integreat_cms/cms/templates/authentication/login_totp.html, integreat_cms/cms/templates/emails/_base_email.html, integreat_cms/cms/templates/emails/password_reset_email.html, integreat_cms/cms/templates/emails/password_reset_email.txt, integreat_cms/cms/templates/emails/welcome_email.html, integreat_cms/cms/templates/emails/welcome_email.txt, integreat_cms/cms/templates/pages/page_pdf.html, integreat_cms/cms/templates/settings/register_totp.html, integreat_cms/cms/urls/public.py, integreat_cms/cms/utils/email_utils.py, integreat_cms/cms/utils/pdf_utils.py, integreat_cms/cms/utils/totp_utils.py, integreat_cms/cms/utils/welcome_mail_utils.py, integreat_cms/cms/views/error_handler/error_handler.py, integreat_cms/core/context_processors.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, tests/api/api_config.py, tests/api/expected-outputs/regions.json, tests/api/expected-outputs/regions_nurnberg.json, tests/sitemap/sitemap_config.py
This adds a few improvements to our whitelabel/branding functionality.
- ~Add possibility to set region-specific brandings~ (rejected, aschaffenburg is getting its own cms)
- Make radable branding title configurable
- Add more regions to the test data
=> Improve handling of brandings

integreat_cms/cms/models/regions/region.py
Fix the bug introduced in #2419
Fixes: #2449
=> Fix `TypeError` in region list

.circleci/config.yml, integreat_cms/release_notes/2023/2023.1.0/1969.yml, integreat_cms/release_notes/2023/2023.9.0/2404.yml, integreat_cms/release_notes/current/unreleased/1836.yml
I hope this prevents #1161 from happening again.
- Replace double quotes in release notes before sending to Mattermost
=> Replace double quotes in release notes before sending to Mattermost

integreat_cms/cms/models/regions/region.py, integreat_cms/release_notes/current/unreleased/2449.yml
~Hot~fix for the bug in the region list
Fixes: #2449
=> Fix internal server error in region list

integreat_cms/cms/views/authentication/password_reset_confirm_view.py, integreat_cms/release_notes/current/unreleased/2484.yml
Fix error during password reset
- Use the custom translation joining function instead of `join()`
Fixes: #2484
=> Fix error during password reset

.circleci/config.yml, integreat_cms/cms/forms/custom_content_model_form.py, integreat_cms/cms/utils/internal_link_utils.py, integreat_cms/cms/views/authentication/password_reset_confirm_view.py, integreat_cms/release_notes/current/unreleased/2484.yml, integreat_cms/release_notes/current/unreleased/2485.yml
- [ [#2484](https://github.com/digitalfabrik/integreat-cms/issues/2484) ] Fix error during password reset
- [ [#2485](https://github.com/digitalfabrik/integreat-cms/issues/2485) ] Fix error when translating links with HTML tags in the link text
=> Release `2023.10.2`

integreat_cms/cms/views/authentication/account_activation_view.py, integreat_cms/cms/views/settings/webauthn/delete_user_fido_key_view.py, integreat_cms/release_notes/current/unreleased/2496.yml
Fix error when activating a new account
- Replace `"".join()` by the translation joiner
Fixes: #2496
=> Fix error when activating a new account

integreat_cms/cms/templates/dashboard/_todo_dashboard_widget.html, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR attempts to fix (at least some of the) typos on the new dashboard
- Fix typos
- I'm not entirely sure if I really checked all files introduced with the dashboard and if I caught everything, especially in the English translation
Fixes: #2503 , Fixes: #2502, Fixes #2508 
=> Fix typos on the new dashboard

integreat_cms/cms/views/dashboard/dashboard_view.py
This PR fixes the calculation of "in total" in the new dashboard.
The cause was that the query was returning the latest ones among the versions saved with low HIX value or as in-review, not the versions with low HIX or in-review among the latest.
- Adjust the query to the same style with `get_automatically_saved_pages`, which was already working fine.
- None? (I hope)
Fixes: #2501
Fixes: #2507
=> Fix "in total" in dashboard

integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_unread_feedback_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR changes the label of the feedback button on the new dashboard
- Change label to feedback
None
Fixes: #2527 
=> Change label of feedback button in dashboard

integreat_cms/cms/models/regions/region.py
Disable caching of page ancestor subquery
Fixes: #2510
Fixes: #2525
=> Fix caching error in pages subquery

integreat_cms/cms/templates/translations/translations_management.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2504.yml
This PR adds some explanation to the language selection box of the maschine translation settings instread of leaving the box empty.
- Check the number of active languages of the region and show a message when there is none or only one (the default language)
- None (I hope)
Fixes: #2504 
=> Add explanation to language section

integreat_cms/cms/views/bulk_action_views.py, integreat_cms/cms/views/utils/__init__.py, integreat_cms/cms/views/utils/stringify_list.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2478.yml
When attempting to restore an implicitly archived page by bulk action you get a success message, although this behavior is rightfully denied. This PR fixes the feedback message in order to match the behavior we want and we already have implemented.
- This PR changes that not one bulk message is given to the user, but instead the user receives feedback for every single page they are trying to restore. At first this gave me a bit of a stomach ache because to me it looked as the user is being spammed with messages, but @MizukiTemma pointed out that we already have this behavior for MT and therefore to the user this is the expected behavior. 
- Show an error message instead of a success message when attempting to restore an implicitly archived page.
- In order to not spam the logger …
=> Fix page archive message

integreat_cms/release_notes/current/unreleased/2565.yml, integreat_cms/static/src/js/events/event-query-pois.ts
This pr fixes the poi filter in the event list not working.
- Don't assume that the html element `poi-form-widget` exists, which is only used on the event form
/
Fixes: #2565 
=> Fix poi filter in event list

integreat_cms/cms/forms/events/event_filter_form.py, integreat_cms/release_notes/current/unreleased/2524.yml, tests/cms/views/test_public_view_status_code.py, tests/cms/views/test_view_redirect.py, tests/cms/views/utils.py, tests/cms/views/view_config.py
This PR changes the search query for events and therefore fixes the bug which occurs when filtering events only by end date
- Change search query for events- 
- I think none
Fixes: #2524 
=> Fix event search

integreat_cms/cms/fixtures/test_data.json, integreat_cms/cms/forms/media/replace_media_file_form.py, tests/api/expected-outputs/augsburg_ar_locations.json, tests/api/expected-outputs/augsburg_ar_pages.json, tests/api/expected-outputs/augsburg_de_children_depth_2.json, tests/api/expected-outputs/augsburg_de_locations.json, tests/api/expected-outputs/augsburg_de_pages.json, tests/api/expected-outputs/augsburg_en_locations.json, tests/cms/test_media_library.py, tools/loadtestdata.sh
This PR adds test for media library (integreat_cms/cms/views/media/media_actions.py).
Expand the test for the following actions.
1. Add some new test data
2. Existing test media file objects are changed to .png, because thumbnail generation during replacing fails with .svg and replacement cannot be testet.
3. Expected API responses are adjusted due to 2.
Fixes: #1997 (#2582)
=> Add test for media library

integreat_cms/cms/templates/feedback/admin_feedback_list.html, integreat_cms/cms/templates/feedback/admin_feedback_list_archived.html, integreat_cms/cms/templates/feedback/admin_feedback_list_row.html, integreat_cms/cms/templates/feedback/region_feedback_list.html, integreat_cms/cms/templates/feedback/region_feedback_list_archived.html, integreat_cms/cms/templates/feedback/region_feedback_list_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2609.yml, integreat_cms/static/src/css/style.scss
Fix white space to the right of feedback form at certain screen resolution/window size:
- rework of html templates for feedback forms
- add additional templates for table rows to remove duplication between archived / non-archived feedback
No?
Fixes: #2609
=> Fix feedback list layout

integreat_cms/cms/forms/translations/translations_management_form.py, integreat_cms/cms/models/languages/language_tree_node.py, integreat_cms/cms/views/media/media_actions.py, integreat_cms/cms/views/push_notifications/push_notification_form_view.py, integreat_cms/core/management/commands/hix_bulk.py, integreat_cms/xliff/xliff2_serializer.py, tests/firebase_api/test_firebase_api_client.py, tests/summ_ai_api/summ_ai_test.py
Use comprehensions
- Use list comprehensions, set comprehensions, and generators to streamline and accelerate the code.
=> Use comprehensions

.github/workflows/codeql-analysis.yml, .github/workflows/dependency-review.yml, .github/workflows/ossar-analysis.yml, integreat_cms/cms/templates/feedback/region_feedback_list.html, integreat_cms/cms/templates/push_notifications/push_notification_form.html, integreat_cms/cms/urls/protected.py, integreat_cms/cms/views/feedback/region_feedback_actions.py, integreat_cms/release_notes/current/unreleased/2694.yml, tests/cms/views/feedback/test_region_feedback_actions.py
- [ [#2694](https://github.com/digitalfabrik/integreat-cms/issues/2694) ] Fix error when selecting multiple regions in the push notification form
=> Release `2024.3.1`

integreat_cms/cms/utils/internal_link_utils.py, integreat_cms/cms/utils/linkcheck_utils.py, integreat_cms/core/management/commands/fix_internal_links.py
This pr tries to improve the performance of the `fix_internal_links` management command.
I could not test it on production data, but I am hopeful that this can speed up the command a lot.
- Don't use the `replace_links` function and instead work directly on the already known translation (Also skips having to wait for linkcheck listeners + 0.1 seconds after each update)
- If a region is given, only include links of that region
- Make sure that not more than one new version per translation is created in the process
Also some minor improvements from reducing the number of database calls
Ideally none
Fixes: #2578
=> Improve performance of the `fix_internal_links` management command

integreat_cms/deepl_api/deepl_api_client.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2280.yml, tests/deepl_api/deepl_api_test.py
This PR adds user friendly error messages for DeepL errors.
- add `try` and `except` with new messages
- I'll wait for #2606 to make it sure that new error messages won't spam users.
Fixes: #2280 
=> Add user friendly message for failed Deepl API requests

integreat_cms/deepl_api/deepl_api_client.py, integreat_cms/google_translate_api/google_translate_api_client.py, integreat_cms/release_notes/current/unreleased/2549.yml
Make machine translations always adopt the status of the source translation
- Remove code to use status of an existing translation in that language
- 
Fixes: #2549
=> Make machine translations always adopt the status of the source translation

integreat_cms/core/circleci_settings.py, integreat_cms/core/settings.py, tests/textlab_api/textlab_api_test.py, tools/test.sh
This PR for HIX score representation on page edit
Tests for:
- HIX score is requested and saved when the page translation is updated
- HIX score is not updated when hix is disabled on region level
- HIX score is not updated when hix is enabled on page level but hix_ignore flag is set to "on"
- HIX score is not updated when hix is enabled on page level and page content is empty
- HIX score is not updated when hix is enabled on page level and page content is not updated
- HIX score is requested but response 400 received. Hix score is not updated
Relates to: #2582
=> Add tests for HIX signals

integreat_cms/cms/templates/imprint/imprint_sbs.html, integreat_cms/cms/templates/pages/page_sbs.html, integreat_cms/cms/templatetags/content_filters.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/locale/nl/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2690.yml
Remove the unnecessary word "another" from the title of the automatic translation text of **minor edit** box so that it was cleaner
- Adjust the German title of the block to "Auswirkungen auf Übersetzungen"
Fixes: #2690 
=> Adjust translation box title of content form

tests/cms/views/poi_categories/test_poi_category_form_view.py
This PR adds tests for the poi categories in order to increase our test coverage further and secondly to make sure we catch bugs such as [#2708](https://github.com/digitalfabrik/integreat-cms/issues/2708) in the future.
- Add tests both for creating new poi categories and for the poi category list
- I think none?
Fixes: Partly #2582
=> Add tests for poicategory

integreat_cms/cms/templates/pois/poi_form.html, integreat_cms/release_notes/current/unreleased/2769.yml, tests/cms/views/poi/test_poi_form.py
The organization and barrier-free box in our POI sidebar were removed in #2043.
- Include the template for organization and barrier-free to our poi form
- Write tests to make sure they also appear in the sidebar
- The poi_form probably needs some more testing, but I'm not sure if this should be done in this PR
Fixes: #2769
=> Re-add barrier-free and organization box to POI

docs/src/management-commands.rst
Add docs for CSV import of POIs
Fixes: #2771
=> Add docs for CSV import of POIs

integreat_cms/core/settings.py
Get FCM URL from env. Required for malte.
=> Get FCM_URL from env

integreat_cms/cms/fixtures/test_data.json, integreat_cms/core/signals/feedback_signals.py, integreat_cms/core/signals/hix_signals.py, integreat_cms/core/signals/organization_signals.py, integreat_cms/core/utils/decorators.py
This pr attempts to fix the problem that the test data cannot be loaded anymore after a new model gets added.
I apologize for the huge diff :see_no_evil: 
is there maybe a way to reduce the diff, other than doing it manually?
- Regenerate the test data with `./tools/integreat-cms-cli dumpdata --natural-primary --natural-foreign --o test_data.json`
- Handle an exception that occurs when loading feedback and the base object is not available yet
Fixes: #2763
=> Fix loadtestdata not working after adding a new model

.github/CODEOWNERS
Disable automatic review requests
Remove CODEOWNERS file as discussed in the Retro
=> Remove `CODEOWNERS` file

integreat_cms/gvz_api/utils.py
Move suggestions from https://github.com/digitalfabrik/integreat-cms/pull/2785 into their own PR (thanks @cclauss!)
=> Improve code conciseness in GVZ API

integreat_cms/release_notes/current/unreleased/246.yml, integreat_cms/static/src/js/events/conditional-fields.ts
Enable client to validate the verification of required fields inside the event form.
-  Fixed missing removal of "required" attribute when selecting "all day" while a previous value is set for start_time or end_time input fields.
- Changed behaviour when input fields are un-hidden to display their previous values instead of empty fields.
- Added support for client side validation of conditionally required field recurrence_end_date.  
- None 
Fixes: #246
=> Client side validation in event form

README.md, flake.lock, flake.nix, tools/_functions.sh, tools/prune_database.sh
(Since this has nothing to do with any issue or any plans we've discussed as a team, I feel that I need to preface this with: everything related to this was done on my own time, not during working hours.)
This PR adds a [nix flake](https://wiki.nixos.org/wiki/Flakes). It allows developers to utilize a standardized and completely reproducible development environment.
You might find this useful if you currently manage multiple python and/or node projects (possibly requiring conflicting versions), are a nix user already, or frequently re-setup the project; but more importantly I strongly believe this makes setting our project up significantly easier for new developers (speaking from experience from my own onboarding two years ago 😉):
Regardless of the system a person is on - any kind of …
=> Add a nix flake providing a development shell

integreat_cms/matomo_api/matomo_api_client.py, integreat_cms/release_notes/current/unreleased/2869.yml
Fix Matomo URL Pattern filter
- Change URL Filters
- Small changes in overall statistics could be possible
Fixes: #2868 
=> Change statistics URL pattern, fix #2868

vitest.config.ts
Vitest comes with some defaults for excluded files. This PR adds some additional ones, since I've notices some false failures when running vitest.
- add files to exclude
- alternatively, we could also include the defaults first, then extend them? 
- none
Fixes: n/a
=> Explicitly specify vitest excludes

docs/src/api-docs.rst, integreat_cms/api/v3/events.py, integreat_cms/release_notes/current/unreleased/2852.yml, tests/api/expected-outputs/augsburg_ar_events.json, tests/api/expected-outputs/augsburg_de_events.json, tests/api/expected-outputs/augsburg_de_events_combine_recurring.json, tests/api/expected-outputs/augsburg_en_events.json, tests/api/expected-outputs/nurnberg_de_events.json, tests/api/expected-outputs/nurnberg_en_events.json
This PR adds a new endpoint `location_path` for events.
- Add `location_path` which delivers not the full URL but the path (slugs)
- Remove `location_url` 
- None?
Fixes: #2852 
=> Add `location_path` API

integreat_cms/cms/templates/_form_language_tabs.html, integreat_cms/release_notes/current/unreleased/1815.yml, integreat_cms/static/src/index.ts, integreat_cms/static/src/js/language-tabs.ts
This PR attempts to refactor the language tabs in JS. 
- Delete the hard coded limit of shown language tabs
- Show as many language tabs as there is space
- There is still one weird side effect I couldn't get rid of. When resizing to a bigger screen there is still a strange transition happening. JS wizard @charludo do you maybe have a solution / an idea for this? :thinking: 
- Eventhough I attempted one refactoring myself, I ended up with some spaghetti code again. If you have any suggestions how to resolve it, I highly appreciate it :blush: 
Fixes: #1815 
=> Refactor language tabs

integreat_cms/cms/utils/linkcheck_utils.py, integreat_cms/cms/views/linkcheck/linkcheck_list_view.py, integreat_cms/release_notes/current/unreleased/2539.yml
This pr reduces the loading time when opening the link list view. More performance optimizations are possible, but would required bigger changes.
This pr also fixes a bug that the list view basically did not load at all when the django debug toolbar was activated.
- Filter urls in sql instead of in python
- Don't use the prefetch optimization, which does not appear to be worth it
- Due to not using the prefetch optimization the total number of database queries for the link list has increased 
Fixes: #2539 (Maybe? I could never reproduce the issue where loading takes 20 seconds. Even before this pr I 'only' had to wait for 10 seconds at most)
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review- …
=> Improve the performance of the linkcheck list

integreat_cms/textlab_api/utils.py, pyproject.toml
This pr remove the dependency on jmespath
- Remove dependency
- Rewrite code without it
Fixes: #2910
=> Remove jmespath dependency

integreat_cms/cms/linklists.py, integreat_cms/cms/templatetags/content_filters.py, integreat_cms/release_notes/current/unreleased/1627.yml
This PR enbales linkcheck for imprint.
This issue was not ranked highly but just implemented because it is (probably) not so complicated and #2530 is kind of affected by this (and anyway I was on the way due to the centralized link checker).
- Add it, in the same way with page translation, event translation and POI translation.
- None?
Fixes: #1627 
=> Enable linkcheck for imprint

integreat_cms/cms/fixtures/test_data.json, tests/api/api_config.py, tests/api/expected-outputs/regions.json, tests/api/expected-outputs/regions_berlin.json, tests/cms/views/push_notifications/test_push_notification_form_view.py, tests/sitemap/sitemap_config.py
Test behaviour for the required title field for the default language should be added.
- Add test
- None
Fixes: #2751 
=> Test title field required for default language on push notification

integreat_cms/release_notes/current/unreleased/2907.yml, integreat_cms/static/src/js/forms/tinymce-init.ts
Remove the notranslate when text is unmarked as do-not-translate.
- Remove class from selected text.
- None
Fixes: #2907
=> Remove notranslate class on toggle off

integreat_cms/cms/models/pages/page.py
I find it a bit hard sometimes to analyze the debug log, because we have a lot of spam in it. This pr tries to reduce the log spam a bit by shortening logger.debug calls which produce a lot of output but are not very important.
I would like to get rid of the machine translation log spam too, but I am not sure what the best way to achieve that would be. Does somebody have an opinion on whether it would be fine to remove those log statements?
<details>
Jul 31 14:21:16 DEBUG integreat_cms.core.utils.machine_translation_provider - Machine translations via DeepL are disabled globally.
Jul 31 14:21:16 DEBUG integreat_cms.core.utils.machine_translation_provider - Machine translations via Google Translate are disabled globally.
Jul 31 14:21:16 DEBUG …
=> Reduce debug output

integreat_cms/cms/models/users/organization.py, integreat_cms/cms/templates/_related_contents_table.html, integreat_cms/cms/templates/organizations/organization_form.html, integreat_cms/cms/templates/organizations/organization_list.html, integreat_cms/cms/templates/organizations/organization_list_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2929.yml, tests/cms/views/organizations/test_organization_form.py
This PR fixes the problem that locations which belong to an organitation are not shown in its form.
- Apply the same procedure with the pages belonging to organizations
- Add test to check both pages and locations of an organization are shown in the form
- None?
Fixes: #2929 
=> Show organization locations

integreat_cms/cms/templates/content_versions.html, integreat_cms/release_notes/current/unreleased/2962.yml, integreat_cms/static/src/js/revisions.ts
This PR fixes restoration of old versions in the version view.
- Revive the input field
- Pass the version number of the selected version to the input field value
- None...?
Fixes: #2962 
=> Fix error at restoring old version

integreat_cms/locale/de/LC_MESSAGES/django.po
This pull request replaces all occurences of event or events in the german translations with veranstaltung or veranstaltungen.
Fixes: #2922 
=> Ensure consistency of german translation for event

integreat_cms/cms/templates/_base.html, integreat_cms/locale/de/LC_MESSAGES/django.po
The PR adds the menu item "contacts" to the navigation bar for the new feature "contacts information"
- Add menu item "contact" 
- As suggested in the meta issue #2955 I used manage_translations for the permissions
- Unblock other issues of the meta issue 
Fixes: #2951
=> Add menu item "contact" to navigation bar

integreat_cms/cms/models/abstract_tree_node.py, integreat_cms/cms/models/events/event.py, integreat_cms/cms/models/pages/page.py, integreat_cms/cms/models/pages/page_translation.py, integreat_cms/cms/models/regions/region.py
Fix some typos and type hints in a few model files
/
/ 
Fixes: /
=> Fix some typos and type hints

integreat_cms/release_notes/current/unreleased/2977.yml, integreat_cms/static/src/js/analytics/translation_coverage.ts
This pull request updates the Chart.js configuration to ensure that all labels are consistently displayed. This enhancement is particularly beneficial for users who may have difficulty using a mouse, as it improves the overall accessibility and usability of the chart.
- Disable auto-skip on y-axis ticks to ensure all labels are displayed
In order to test the feature you can replace the `JsonData` in `integreat_cms/static/src/js/analytics/translation_coverage.ts `with the following mock.
```
const JsonData: ChartData = {
labels: [
"German (easy)",
"English",
"Arabic",
"Farsi",
"Hidden language",
"Amharic",
"Ukrainian",
"Greek",
"French",
"Spanish",
"Italian",
"Russian",
"Chinese",
"Japanese",
"Korean",
"Portuguese",
"Hindi",
"Bengali",
"Punjabi",
"Turkish",
],
datasets: [
{
label: …
```
=> Disable auto-skip on y-axis ticks to ensure all translation report labels are displayed

integreat_cms/release_notes/current/unreleased/2998.yml, integreat_cms/static/src/js/tinymce-plugins/autolink_tel/plugin.js
Ignore soft hyphens when auto detecting links in TinyMCE
- Ignore soft hyphens in detection only, but don't strip them out of the text content.
- Nonsensically placed soft hyphens will not be removed from the page. But on the flip side, sensibly placed ones will also stay.
Fixes: #2998
=> Ignore soft hyphens when detecting links

integreat_cms/matomo_api/matomo_api_client.py
Replace the API token value in exception messages to prevent exposure of sensitive information.
- Mask the API token in exception messages to ensure that sensitive information is not exposed.
- Modify the exception handling to drop the traceback, further safeguarding against accidental exposure of the API token in logs.
- The removal of the traceback from exception messages may make debugging more challenging, as it eliminates detailed error context that would normally be provided.
1. Use the [Docker setup for Matomo](https://github.com/matomo-org/docker/tree/master/.examples/apache) to run Matomo in your local environment.
2. Set the following environment variables to configure your application to work with the Matomo instance: `INTEGREAT_CMS_MATOMO_URL=http://localhost:8080;INTEGREAT_CMS …
=> Mask api token in MatomoException

integreat_cms/static/src/js/revisions.ts
This PR fixes `Uncaught TypeError` occuring outside of the revision view.
- Check before adding an event listner if the target exists
- None? 🙈 
Fixes: #3009 
=> Fix `Uncaught TypeError`

integreat_cms/cms/templates/events/event_list_archived.html, integreat_cms/cms/templates/pages/page_tree_archived.html, integreat_cms/cms/templates/pois/poi_list_archived.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3005.yml
Add links for the archived POI list and archived event list to navigate back to POI and event list.
- Add the two buttons
None
Fixes: #3005 
=> Add back to POI and events list link

integreat_cms/release_notes/current/unreleased/2793.yml
#2923 has introduced a release note about an internal feature. Including this in the next release would probably confuse users & testers, so it should be removed
- remove the relase note
=> Remove release note about internal feature

integreat_cms/locale/de/LC_MESSAGES/django.po
=> Fix typo in organization form

integreat_cms/cms/migrations/0104_userchat_language_userchat_region_and_more.py
Rebase user chat migration on previously merged migration 0103 from https://github.com/digitalfabrik/integreat-cms/pull/3052
- Update dependency for migration
- Working CI?!
Fixes: https://github.com/digitalfabrik/integreat-cms/runs/30626364701
=> Fix user chat migration

integreat_cms/api/v3/chat/chat_bot.py
Fix handling of empty automatic responses.
- Ignore empty automatic chat responses messages
- No multiple retries of Zammad webhooks
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/51
=> Chat: fix empty answers

integreat_cms/api/v3/chat/chat_bot.py
Allow automatic answers without sources & use page title in link.
- Render automatic messages when they do not contain a sources attribute.
- Fetch the page translation title from the page path and render it as the source link text.
- None
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/52 & https://github.com/digitalfabrik/integreat-chat/issues/40
=> Chat: improve source links & allow messages w/o sources

integreat_cms/cms/templates/contacts/contact_list.html, integreat_cms/cms/urls/protected.py, integreat_cms/cms/views/bulk_action_views.py, integreat_cms/cms/views/contacts/__init__.py, integreat_cms/cms/views/contacts/contact_bulk_actions.py, integreat_cms/locale/de/LC_MESSAGES/django.po
Adds archive/restore/delete bulk actions to contact list
- Adds archive/restore/delete bulk actions `contact_bulk_action.py`
- Overwrites `get_queryset()` to filter for selected contacts with poi region
- None
Fixes: #2954 
=> [2024-11-07] Add contact list bulk actions

integreat_cms/cms/templates/statistics/_statistics_widget.html, integreat_cms/cms/templates/statistics/statistics_overview.html, integreat_cms/locale/de/LC_MESSAGES/django.po
Change the title of statistics from online to total accesses, which is more accurate.
- Change wording on the dashboard
- Change wording on the statistics box
I hope none
Fixes: #3138
=> Adjust wording of statistics

integreat_cms/cms/fixtures/test_data.json, integreat_cms/cms/forms/contacts/contact_form.py, integreat_cms/cms/migrations/0108_rename_contact_title_to_point_of_contact_for.py, integreat_cms/cms/models/contact/contact.py, integreat_cms/cms/templates/ajax_poi_form/poi_box.html, integreat_cms/cms/templates/contacts/contact_form.html, integreat_cms/cms/templates/contacts/contact_list.html, integreat_cms/cms/templates/contacts/contact_list_row.html, integreat_cms/cms/templates/pois/poi_form_sidebar/action_box.html, integreat_cms/cms/views/contacts/contact_form_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR fixes a few issues we had with contact
- Put location of contact in contact list view in the first column
- Adjust translation for location
- Fix typo "ihr" to "Ihr" in contact form
- Fix help text shouldn't be bold
- Fix help text disappears when saving contact
- Make a few changes to str function for it to be a bit more speaking
- Rename title to point_of_contact_for
These changes should fix all issues we noticed during our first round of testing 
These were quite a few changes, it's possible that we overlooked something
Fixes: #3141
=> Fixes for contact

integreat_cms/cms/templates/_poi_query_result.html, integreat_cms/cms/templates/ajax_poi_form/_poi_address_container.html, integreat_cms/cms/templates/ajax_poi_form/poi_box.html, integreat_cms/cms/templatetags/poi_filters.py, integreat_cms/cms/views/pois/poi_form_ajax_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3150.yml, integreat_cms/static/src/js/poi_box.ts
This PR attempts to fix the spacing issues in poi box.
- remove class `whitespace-pre-line`
- add `<br>` instead
- Avoid constructing the poi box client side. Instead, always render it on the server so that we don't have to maintain two versions of the same thing
I don't know
Fixes: #3150 
=> Fix spacing in poi box

integreat_cms/cms/models/events/event.py, integreat_cms/cms/templates/events/event_list_row.html, integreat_cms/cms/views/events/event_actions.py, integreat_cms/cms/views/events/event_context_mixin.py, integreat_cms/locale/de/LC_MESSAGES/django.po, tests/cms/views/events/events.py
In the events list disallow copying by disabling the action and greying it out
- Grey out and disable copying action for events that have been imported 
None
Fixes: #3105
=> [2024-11-07] Disable copying for imported events

integreat_cms/cms/templates/events/event_form_sidebar/minor_edit_box.html, integreat_cms/cms/templates/pois/poi_form_sidebar/minor_edit_box.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3185.yml
This PR extends the "select all" checkbox for translations to events and pois
- Add checkbox to events and pois
None?
Fixes: #3185
=> Extend select all checkbox to events and pois

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
This pr adds a new heading to our issue templates so that issue creators get incentivized to link related issues, as requested at https://chat.tuerantuer.org/digitalfabrik/pl/gp87g8gk67bezr1wxqfgktyg7h 
- Add new header
None
Fixes: /
=> Add related issues header for issue templates

integreat_cms/cms/templates/_tinymce_config.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/2023/unreleased/3225.yml, integreat_cms/static/src/js/forms/tinymce-init.ts, integreat_cms/static/src/svg/fax.svg
This PR adds the functionality to insert an icon for fax numbers to the editor.
- Add fax icon SVG.
- Update editor functions.
Fixes: #3225 
=> Add fax icon svg

integreat_cms/release_notes/current/unreleased/1274.yml, integreat_cms/static/src/js/forms/tinymce-init.ts, integreat_cms/static/src/js/pages/sbs-copy-content.ts, integreat_cms/static/src/js/tinymce-plugins/custom_link_input/plugin.js, package-lock.json, package.json, webpack.config.js
While working on #3082 I also attempted to update tinymce to v7. Since that turned out to be a lot of effort, I decided to open another pr for that.
- Update tinymce to v7
- Potentially a lot, I did not do much testing yet. Here are the migration guides: https://www.tiny.cloud/docs/tinymce/latest/migration-from-6x/ and https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/
- ~~The license of tinymce changed to GPL, could that potentially be a problem for us?~~ GPL is no problem for us
Fixes: #1274
=> Update tinymce to v7

integreat_cms/cms/templates/linkcheck/links_by_filter.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/2588.yml
This PR updates some wording on the broken link list to make the GUI more intuitive for users.
- Link category "Invalid (Ungültig)" is now labelled as "Verification needed (Überprüfung notwendig)"
- Link category "Ignored (Ignoriert)" is now labelled as "Link verified (Link überprüft)"
- Icons are added to the labellings (In the issue only ⚠️ for "Verification needed" and ✅ for "Link verified" are specified but other categories have received an icon for consistent view) 
- Bulk action "Ignore" is now called "Mark as verified", "Unignore" is "Bring back to check"
- Renaming is done only on the front end: in backend they are still "ignore", "unignore", "ignored" (I guess this is intuitiver for developers because the related boolean field of the link model is named "ignore")
- The new name …
=> Improve link checker GUI

integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3181.yml
This PR corrects the translate for "archive contact"
- Adjust translation
Done in collaboration with @KateGithub12 
Fixes: #3181 
=> Correct translation for archive contact

integreat_cms/cms/templates/contacts/contact_list_row.html, integreat_cms/cms/templates/events/event_list_row.html, integreat_cms/cms/templates/pages/page_tree_node.html, integreat_cms/cms/templates/pois/poi_list_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3187.yml
This PR adds the edit icon to contact, event and poi, and change the existing edit icon for page
- Add edit icon for contact, event and poi
- Change existing icon for page
Done in collaboration with @KateGithub12
Fixes: #3187
=> Add edit icon to contact, page, event and poi

integreat_cms/cms/templates/_tinymce_config.html, integreat_cms/release_notes/current/unreleased/3237.yml
Add alt attribute for fax icon
- Add alt attribute for fax icon
None
In contribution with @KateGithub12 
Fixes: #3237 
=> Add alt attribute for fax icon

integreat_cms/api/v3/chat/utils/chat_bot.py, integreat_cms/core/settings.py
Add a setting to configure the Integreat Chat back end timeout and URL.
- None
=> Add timeout setting for Integreat chat

integreat_cms/cms/constants/linkcheck.py, integreat_cms/cms/templates/analytics/_broken_links_widget.html, integreat_cms/cms/templates/linkcheck/links_by_filter.html, integreat_cms/cms/views/linkcheck/linkcheck_list_view.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR fixes wording of link type names which were not covered by #3191 
- Search & replace
- I'm not sure whether all targets are covered, would appreciate if reviewers too search for potential missed targets to replace actively.
- No release note is provided, as #3191 is not delivered to users and this is something additional to it.
Fixes: #3254 
=> Adjust link type wording (follow up for #3191)

integreat_cms/cms/templates/_search_input.html, integreat_cms/static/src/js/revisions.ts, integreat_cms/static/src/js/search-query.ts
Currently input fields for search are not navigatable via arrow keys. They should be navigatable with arrow keys + accessible with keyboard (like Tab and enter keys)
Fixes: #3037
=> Fix input field arrow key navigation and make search query function accessible

integreat_cms/release_notes/current/unreleased/3037.yml
This is the release note for this already merged PR #3269 
- add release note 
- none
Fixes: #
=> Add release note for fix input navigation arrow keys

integreat_cms/cms/utils/external_calendar_utils.py
This PR saves calendars again. This was accidentally removed in [3307](https://github.com/digitalfabrik/integreat-cms/pull/3307).
- Save calendars
- None?
Fixes: -
=> Fix calendars not saving

integreat_cms/release_notes/current/unreleased/3078.yml
=> release note 3078: Sensible error message when adding inactive users to pages

integreat_cms/api/v3/chat/utils/zammad_api.py, integreat_cms/cms/fixtures/test_data.json
Add the Zammad Ticket URL to the chat API response.
- add a `ticket_url` attribute to the chat API response
- N/A
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/123
=> Add ticket URL attribute to chat API

integreat_cms/locale/de/LC_MESSAGES/django.po
Fix translation of iCal filter
- Add "nicht" to translation
None?
Fixes: #3351
=> Change translation of ical filter

integreat_cms/api/v3/chat/utils/chat_bot.py
The same Zammad ticket IDs can occur multiple times across different Zammad servers. We need to filter by region as well.
- Filter UserChat objects by zammad ticket ID and region (one Zammad per region)
- N/A
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/178
=> Fix UserChat object filter

integreat_cms/cms/templates/contacts/contact_form.html, integreat_cms/cms/templates/contacts/contact_list_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/css/style.scss
Indicate vidually when contact actions are not available
- disable the small buttons in the list view (sorry, I missed that previously)
- change order of styles in `style.scss` so that disabled button styling overwrites "red" button styling, instead of the other way round 
- the style changes affect all buttons, not just the contact ones. However, I think that is probably a wanted change?  
Fixes: #3371
=> Indicate when contact actions are not available

integreat_cms/release_notes/current/unreleased/4.yml
Add release note for translation coverage on dashboard. I forgot to do so during the initial PR.
- Add release note for translation coverage
None
Fixes: -
=> Add release note for translation coverage on dashboard

integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/matomo_api/matomo_api_client.py
As part of the feature to add page based statistics it was decided to use the term phone/mobile app instead of offline app.  
- Change offline app to phone app
- Adjust webapp from different variations to Web-App, as recommended by Duden
- Is mobile app better than phone app for the English version? I'm torn...  
Fixes: -
=> Rename offline app to phone/mobile app

docs/src/tools.rst
Our docs do not mention that running `tools/*.sh` with the virtual environment already activated might lead to minor problems.
- Add hint that the virtual environment is not intended to be activated
=> docs: update tools.rst

integreat_cms/cms/templates/region_condition/region_condition.html, integreat_cms/cms/templates/region_condition/region_condition_row.html, integreat_cms/cms/views/region_condition/region_condition_actions.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR adds a few fixes for region condition
- Make region name clickable
- Adds administrative division to both, table and CSV
- Adds the paginator
I think none?
Fixes: More parts of #3012 
=> Fixes pagination and adds administrative division to region condition

integreat_cms/static/src/css/contact_card.css
Before:
After:
- apply fix suggested by @PeterNerlich 
- made the icon slightly smaller and moved it down a fraction to make it look better on the very small cards. Debatable if necessary, I guess 😄 
- none
Fixes: #3342
=> Fix black bar on contact bar background icon

integreat_cms/locale/de/LC_MESSAGES/django.po
When inserting a contact card to pages we have a small typo. This PR fixes it
- Fix typo when inserting contact card
None?
Fixes: #3416
=> Fix typo when inserting contact card

integreat_cms/locale/de/LC_MESSAGES/django.po, tests/cms/views/regions/delete_region.py
This PR fixes a minor translation error
- Change region to plural form in German translation
None?
Fixes: #3302 
=> Fix minor translation error

integreat_cms/static/src/js/event-duration.ts
This PR fixes an error in the browser console which shows up so long you're not in the event form.
- Check first, if element exists
Should be none?
Fixes: -
=> Fix console error for long term events

integreat_cms/cms/templates/imprint/imprint_form.html
This PR fixes a tiny typo in the imprint form
- Fix typo
None I'm aware of
Fixes: -
=> Fix typo in imprint form

integreat_cms/cms/constants/roles.py, integreat_cms/release_notes/current/unreleased/2955.yml, tests/cms/views/contacts/test_contact_actions.py, tests/cms/views/contacts/test_contact_form.py, tests/cms/views/poi/test_poi_form.py
This PR changes the permissions for the contact feature for the release
- Adjust permissions
I think none?
Fixes: #2958
=> Finalize contact permissions

tests/cms/views/contacts/test_contact_utils.py
Fix the failing tests for contact insertion, because I forgot to do so in #3446 
- Adjust the permissions
- Hopefully only positive ones
Fixes: -
=> Fix tests for contact insertion

integreat_cms/cms/templates/contacts/contact_from_email_and_phone_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR fixes the German translation of a header in the contact suggestion.
- Change the German translation
- Change "in the page" to "in the content" as it can be a POI or event.
- None
Fixes: #3450 
=> Fix german translation in contact suggestion

integreat_cms/cms/models/contact/contact.py, integreat_cms/cms/models/pois/poi_translation.py
=> Invert condition to link app-map instead of google maps for contacts

integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html, integreat_cms/cms/templates/contacts/contact_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po
=> Show warning about contacts with an area of responsibility

integreat_cms/release_notes/current/unreleased/3467.yml, integreat_cms/static/src/js/analytics/hix-widget.ts
This PR adjust the threshold for HIX in our HIX widget as it's planned to keep the threshold of 14 long-term.
- Adjust threshold
- None?
Fixes: #3467
=> Fix hix color code

integreat_cms/release_notes/current/unreleased/3424.yml
This PR adds the release note for the already merged PR that fixes the spacing for start and end date in events.
- Needs a quick merge (before the next release)
Fixes: -
=> Release note for space in events

integreat_cms/cms/constants/roles.py, integreat_cms/cms/fixtures/test_roles.json, integreat_cms/cms/migrations/0117_add_beta_permission.py, integreat_cms/cms/models/users/user.py
Adds beta permissions to enable the service team to test new features while they are still hidden for other users
- Add permission
- Migrate database to update permissions
- None that I'm aware of
Fixes: #3470 
=> Add beta permission

integreat_cms/cms/forms/events/event_filter_form.py
Currently we have the issue on the CMS test that the search term is being cleared after a search either in the search bar or in the location bar. This is because of my refactoring in #3410. I forgot to pass the query and the poi through and therefore their search term disappeared
- Re-add the query and poi
- Would be super cool to merge this until Sunday (better: Friday), so we don't release a bug on Monday :)
Fixes: #3480
=> Fix search term being cleared after search in event filter

integreat_cms/cms/migrations/0117_rename_weekdays_in_events.py, integreat_cms/cms/models/events/event.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3436.yml, integreat_cms/release_notes/current/unreleased/3437.yml
This PR fixes the German translation of "recurring" and changes the wording of "weekdays" to "Mondays to Fridays" (including the German translation).
- fixes German translation of "recurring"
- changes wording of "weekdays" to "Mondays to Fridays"
- None?
- I added two release notes, as I'm fixing two issues in one PR
Fixes: #3437
Fixes: #3436
=> Fix wording of weekdays and translation of recurring

integreat_cms/cms/migrations/0118_rename_weekdays_in_events.py
This PR fixes the migration order: there are currently two migration files after 0116
- Fix the order
- 
- 
- 
Fixes: #
=> Fix the migration order

integreat_cms/cms/templates/contacts/contact_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3490.yml
This PR adds a text "At least one field must be filled." to the contact form.
- Add the hint text
- 
- 
- 
Fixes: #3490 
=> Add hint about mandatory fields in contact form

integreat_cms/cms/templates/users/_pages_with_observer_access.html, integreat_cms/cms/templates/users/region_user_form.html, integreat_cms/cms/templates/users/user_form.html, integreat_cms/cms/views/users/region_user_form_view.py, integreat_cms/cms/views/users/user_form_view.py, integreat_cms/cms/views/utils/__init__.py, integreat_cms/cms/views/utils/user.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3121.yml
This PR adds a table to the user form to show all pages to which an observer has access to - either as an author or as an editor.
- Add table of pages an observer has access to
- I think none?
Fixes: #3121
=> Show which pages an observer has access to

integreat_cms/cms/views/utils/user.py
This is a first idea to improve the the loading time for creating a new user. Let's merge this fast so we can find out on CMS test if it actually works :)
- return if user is None
Fixes: Best case scenario #3526
=> Improve loading time for creating new user

pyproject.toml
Bump `packaging` version to fix package publishing to PyPi.
=> Update license expression in pyproject.toml

integreat_cms/cms/utils/zammad.py
While refactoring I did not correctly obey the internal flag and also missed this in testing.
Filter messages by internal flag.
Shorter messages list :grimacing: 
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/272
=> Chat: keep internal messages internal

integreat_cms/cms/templates/ajax_poi_form/poi_box.html, integreat_cms/cms/templates/contacts/contact_form.html, integreat_cms/cms/templates/events/event_form.html, integreat_cms/release_notes/current/unreleased/3525.yml
This PR hides the ajax POI form if the opened contact/POI is archived
- Show the title of POI as plain text and hide the ajax form 
- 
- 
Fixes: #3525 
=> Hide the ajax POI form if the contact/event is archived

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
This PR adds some new sections to the issue and PR templates that were wished/suggested during our worfklow discussion.
- Add a section to insert screenshots
- Add a section to summarise discussion and updates if a long conversation was done
- Add a section to note difference from the issue description and design
- More efficient communication and happy team 😸 
Fixes: #
=> Update issue and PR templates

integreat_cms/cms/templates/pois/poi_list_archived.html, integreat_cms/cms/templates/pois/poi_list_archived_row.html, integreat_cms/locale/de/LC_MESSAGES/django.po
Fixed the translation status for the archvied PIO list.
- Fixed the translation status for the archvied PIO list.
Fixes: #3071 
=> Fix translation status for archived POI

integreat_cms/release_notes/current/unreleased/3071.yml
This PR adds a release note for #3071 
- None, should be included in next release
Fixes: -
=> Add release note for #3071

integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3591.yml
Fix a tiny typo in contact
- Fix typo
None?
No issue
Fixes: -
=> Fix typo in contact

integreat_cms/release_notes/current/unreleased/3066.yml
Issue #3066 is fixed by #3325, so we need to add a release note that this was fixed
- None
Fixes: #3066 
=> Add release note for #3066

docs/src/api-docs.rst, integreat_cms/api/v3/locations.py, integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3591.yml
This PR removes the obsolete fields from the API and adds the mobile number to the API.
- Remove obsolete fields from API
- Add mobile number to API
- Adjust API docs
- Remove warning from contact
- There should be none
- If I saw it correctly the app team already implemented the transition to the new contact field.
Fixes: #3497
=> Add mobile number to API

integreat_cms/cms/models/languages/language.py, integreat_cms/cms/templates/languages/language_list.html, integreat_cms/cms/urls/protected.py, integreat_cms/cms/views/languages/__init__.py, integreat_cms/cms/views/languages/language_list_view.py, integreat_cms/cms/views/utils/search_content_ajax.py, integreat_cms/locale/de/LC_MESSAGES/django.po
This PR adds a search function/window to the language list.
- Add a search window like other lists
- Add a search function
- 
Fixes: #1152 
=> Add search function to the language list

integreat_cms/cms/templates/pages/pages_page_tree_node.html
This PR fixes the bugs with archive/restore icons in the page tree
- Fix the conditions in the template
- 
- The edit icon will be hidden for the archived page tree by #3601 
- 
Fixes: #3597 
Fixes: #3596 
=> Fix archive/restore icons in page tree

integreat_cms/cms/migrations/0126_region_summ_ai_budget_used_and_more.py
Sorry, I messed up not rebasing on develop before merging #3586 😬
- 
- 
- 
- 
Fixes: #
=> fix: migration history, move 124->126

integreat_cms/cms/templates/statistics/statistics_viewed_pages.html
This PR fixes the alignment and height of the information icon.
- Fix height and alignment of information icon to center
I think none?
Fixes: #3611
=> Fix alignment and height of information icon

integreat_cms/release_notes/current/unreleased/3132.yml
This PR revers the release note for the statistics popup, as this feature will not yet be available in the next release for users
- Delete it
- 
Fixes: #/
=> Delete release note for statistics popup

integreat_cms/cms/templates/pages/pages_page_tree.html
This PR hides the page tree tutorial for archived pages
- Import page tree tutorial only for archived pages
I think none
Fixes: #3616
=> Hide page tree tutorial for archived pages

integreat_cms/release_notes/current/unreleased/2808.yml, integreat_cms/static/src/js/rss-feed.ts
This PR fixes the display of blog posts. Currently all blog posts are displayed in our CMS even those who haven't been selected for the editorial system. 
- Fixes that blogs that have not been selected for the CMS are still displayed
- The cleaner version would have been to fix this via website, but since it was said that not a lot of time should be spend on this, I thought this would be the best way to it. If you disagree I can still fix it on the website.
Fixes: #2808 
=> Fix display of blog posts

integreat_cms/cms/templates/region_condition/region_condition.html, integreat_cms/cms/views/region_condition/region_condition_view.py, integreat_cms/cms/views/utils/search_content_ajax.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3593.yml
This PR adds the same region search feature to the region condition table.
- Add an input window
- Use the same suggest/search function with the feature for region list
- Adjust but the suggest function to exclude archived regions if it is in the region condition table.
- 
Fixes: #3593 
=> Add search function to region conditions

integreat_cms/cms/models/contact/contact.py, integreat_cms/cms/templates/contacts/contact_list.html, integreat_cms/cms/views/contacts/contact_list_view.py, integreat_cms/cms/views/utils/search_content_ajax.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3484.yml
This PR adds a search function to the contact list
- Add the search window
- Let users search for contact name or location name
- To re-use the `search` function of `POITranslation`, `language_slug=LANGUAGE_CODE` is handed over. I hope it is safe enough to assume all the system languages (currently English and German) will be always covered by the content languages.
- 
Fixes: #3484 
Fixes: #3537 
=> Add search function to contact list

integreat_cms/api/v3/chat/user_chat.py, integreat_cms/api/v3/chat/utils/chat_bot.py, integreat_cms/cms/models/chat/user_chat.py, integreat_cms/cms/utils/zammad.py, tests/api/test_api_chat.py
Clean up and refactor the chat_bot.py.
- Refactor messages and filtering functions
- Add missing parameter documentation
None
N/A
- Fix https://github.com/digitalfabrik/integreat-chat/issues/331
- Fix https://github.com/digitalfabrik/integreat-chat/issues/337
=> Refactor chat_bot.py

integreat_cms/cms/utils/linkcheck_utils.py
After merging #3654 and testing it on the test server, it was discovered that the central linkchecker times out. Probably because the introduced query to filter for active regions can get too big together with query to filter for the urls (it basicly filters more or less the same objects twice)
- Filter for active regions directly in `get_link_query` without an additional query that gets evaluated
Fixes: # n.a.
=> Fix timeout during loading central linkchecker

integreat_cms/cms/migrations/0131_add_automatical_feedback_to_searchresultfeedback.py
This PR fixes the migration order on develop which I had messed up by #3171 
- Rename migration file to 131 and change order
None
Fixes: None
=> Fix migration file #130

integreat_cms/cms/views/regions/region_actions.py, integreat_cms/core/settings.py, integreat_cms/locale/de/LC_MESSAGES/django.po, tests/cms/views/regions/delete_region.py, tests/conftest.py
This PR implements region deletion as Celery task in the same way with #3579 
- Exctract deletion part into another function (Celery task)
- Adjust the message that appears after clicking the delete button
- Add a new info message that the deletion can take several minutes
- Adjust the affected test
- Should be none: no change in the logic and conditions
Fixes: #3049 
=> Delete region with Celery

docs/src/api-docs.rst, integreat_cms/api/v3/locations.py, integreat_cms/cms/fixtures/test_data.json, integreat_cms/cms/forms/contacts/contact_form.py, integreat_cms/cms/migrations/0135_add_opening_hours_for_contacts.py, integreat_cms/cms/models/contact/contact.py, integreat_cms/cms/models/pois/poi.py, integreat_cms/cms/models/utils.py, integreat_cms/cms/templates/contacts/contact_form.html, integreat_cms/cms/views/contacts/contact_context_mixin.py, integreat_cms/cms/views/pois/poi_context_mixin.py, integreat_cms/cms/views/utils/opening_hour.py, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/static/src/js/pois/opening-hours/index.tsx, tests/cms/views/contacts/test_contact_form.py
This PR adds opening hours to contact
- Add opening hours to contact
- Compare opening hours of contact to opening hours of linked pois and show either one of them (if contact opening hours are null we use the opening hours of the linked poi)
- Fix tests
- Code quality is not good -> refactoring ticket (#3603)
- Not totally because on contact creation it's currently not possible to add opening hours (I will have a meeting about this with @nikolahoff, @laravoelk and @hauf-toni about this)
Fixes: #3291 
=> Add opening hours to contact

integreat_cms/cms/templates/tutorials/page_access_statistics.html
Changed the font style from bold to normal.
- Fix font style 
- Normal font style
Fixes: #3672 
=> fixed-font-weight

integreat_cms/cms/forms/media/upload_media_file_form.py, integreat_cms/release_notes/current/unreleased/3743.yml
Fix upload of PDFs
- Revert part of the refactoring that wasn't thought through: Always clean `file_size` and `last_modified` fields
- 
Fixes: #3743
=> Bugfix Release: Fix upload of PDFs

tests/core/management/commands/test_update_link_text.py
This PR skips the failing test `test_command_succeeds` until we figured out why it's failing. Should I open up an issue for it or is it present enough in our minds? 
We should also vote whether we really want to do this in the next team meeting
- Skip test
- Management command not being tested at the moment
Fixes: /
=> Skip test `test_command_succeeds`

integreat_cms/release_notes/current/unreleased/3626.yml
As #3704 did not solve the problem successfully, we have to revert the release note for #3626 
- Delete it
- 
- None
- 
Fixes: #/
=> Remove the release note for #3626

integreat_cms/cms/models/contact/contact.py
Return newly created record from contact.copy() to allow more flexible use. 
- return newly created contact in the copy method of Contact
- None, hopefully
Fixes: #
=> return new Contact record from copy method

integreat_cms/cms/models/abstract_base_model.py, integreat_cms/cms/models/contact/contact.py, integreat_cms/cms/models/events/event_translation.py, integreat_cms/cms/models/feedback/feedback.py, integreat_cms/cms/models/languages/language.py, integreat_cms/cms/models/media/media_file.py, integreat_cms/cms/models/pages/page.py, integreat_cms/cms/models/pois/poi_translation.py, integreat_cms/cms/models/push_notifications/push_notification_translation.py, integreat_cms/cms/models/regions/region.py, integreat_cms/cms/models/users/organization.py, integreat_cms/cms/models/users/user.py, integreat_cms/cms/models/utils.py, integreat_cms/cms/templates/events/event_list.html, integreat_cms/cms/templates/push_notifications/push_notification_list.html, integreat_cms/cms/views/utils/search_content_ajax.py, integreat_cms/static/src/js/media-management/library.tsx, tests/cms/views/view_config.py
This PR refactors the function `search_content_ajax` a bit
- Generalize the similar/duplicating lines
- This PR is the first step. Further deep-going refactoring will be provided later as a separate PR.
- 
Fixes: #3558 (partially)
=> Refactoring for search_content_ajax

integreat_cms/core/settings.py
list.remove() does not return the list.
=> Fix debug user logging

integreat_cms/cms/models/contact/contact.py
#3832 introduced trigram similarity for searching contacts, but only for the name field. This PR extends this to all other relevant fields of the contact and its location, as originally intended.
- Define the `similarity` score as the max trigram similarity between the search query and each of the relevant fields
I decided to just use the expressions in the search vector itself *(it seems `TrigramSimilarity()` can take any expression, not just a string describing a field)* so we only define the fields we want once and don't run the risk of getting another hard to discover desync like this when we only change one of the definitions in the future
- This only affects the contact search and should be limited to showing more results, never less than without this change.
- Maybe the ideal …
=> Extend contact trigram similarity search to all search fields

integreat_cms/cms/constants/status.py, integreat_cms/cms/forms/events/event_filter_form.py, integreat_cms/cms/templates/events/_event_filter_form.html, integreat_cms/locale/de/LC_MESSAGES/django.po, integreat_cms/release_notes/current/unreleased/3719.yml
Filter for draft function in events
Added a filter events 
None are expected 
Fixes: #3719 
=> add filter for events
