backend/backend/settings.py
backend/backend/urls.py
backend/cms/templates/_base.html
backend/cms/templates/csrf_failure.html
backend/cms/templates/dashboard.html
backend/cms/templates/http_error.html
backend/cms/templates/messages.html
backend/cms/templates/registration/login.html
backend/cms/templates/registration/password_reset_confirm.html
backend/cms/templates/registration/password_reset_form.html
backend/cms/views/general.py

[Django messages](https://docs.djangoproject.com/en/1.11/ref/contrib/messages/) can now be used on all pages that extend the _base template. The normal error pages for HTTP status codes and csrf errors are replaced.

Add global alerts and custom error pages

---

backend/api/urls.py
backend/api/v3/feedback.py
backend/cms/models/feedback.py

There is some discrepancy between the API documentation and the current Feedback model. In the documentation, the field "Rating" is used, but in the database model, the field "Emotion" is used. Since the documentation is probably easier to change, I have used "Emotion" in the implementation here instead.
This code may be extended in future so that the api implementation for feedback for extras/events can also be built upon the same functions/class.

Implement API for feedback about a single page

---

backend/cms/locale/de/LC_MESSAGES/django.po
backend/cms/templates/pages/confirmation_popups/archive_page.html
backend/cms/templates/pages/confirmation_popups/delete_page.html
backend/cms/templates/pages/page.html
backend/cms/templates/pages/tree_row.html
backend/cms/urls.py
backend/cms/views/pages/__init__.py
backend/cms/views/pages/page.py
backend/cms/views/pages/page_form.py

- Enables the deletion of pages for superusers and staff members for debugging and administrative tasks (region admins can only archive a page)
- Repairs the broken archive page functionality

Enable deletion of pages (Resolves #11)

---

backend/cms/templates/pages/tree.html
backend/cms/templates/pages/tree_row.html

I realized that the table for pages in UI is having edit buttons overlap with title

Change pages tree view class to table-auto

---

backend/cms/locale/de/LC_MESSAGES/django.po
backend/cms/models/region.py
backend/cms/templates/pages/_page_permission_table.html
backend/cms/templates/pages/page.html

I redesigned the page form to point out which attributes belong to a translation and which ones belong to the entire page. I used a tab view for every language.
This is a completely new design approach which differs from the other pages, so if you have ideas how to implement the requirement more similar to the other forms or have other suggestions regarding the positioning or color choices, feel free to reach out to me.

Separate page and translation attributes in page form (fixes #154)

---

backend/cms/locale/de/LC_MESSAGES/django.po

Apparently, the merge of the last PR didn't work as expected and resulted in double entries in the translation .po file.
This PR fixes all conflicts in that file.

Remove double entries from translation file

---

backend/cms/locale/de/LC_MESSAGES/django.po
backend/cms/templates/pages/page.html
backend/cms/templates/pages/tree.html
backend/cms/templates/pages/tree_row.html
backend/cms/templatetags/page_filters.py
backend/cms/views/pages/page.py
backend/cms/views/pages/page_form.py
backend/cms/views/pages/pages.py
dev-tools/loadtestdata.sh
dev-tools/migrate.sh
dev-tools/prune_database.sh
dev-tools/run.sh

- If content and backend language differ, I show two columns in the page view. In the first column there is the page translation title in the content language, in the second column in the backend language. This makes it easier for content creators to manage translations in unknown languages. (Fixes #82)
- If a user has the permissions to view all pages, but not to edit them, the page form gets disabled and a small notification is shown. Thus, it is clear whether or not someone can edit a page and why. (Fixes #157)
- Additionally, I fixed a small bug where the template for new pages could not be rendered. This was due to the tab view and the links to different translation of a not yet existing page. I solved it by showing only one tab when creating a page, and all additional tabs when …

Enhance page view and form

---

backend/cms/templates/pages/page.html

I finally found the cause of the weird positioning of the "settings for all translations"-tab in the page form. This does not solve the problem when the tabs are shown in two lines though.

Fix positioning of right column in page form

---

backend/backend/settings.py
backend/cms/decorators.py
backend/cms/locale/de/LC_MESSAGES/django.po
backend/cms/models/__init__.py
backend/cms/models/user_mfa.py
backend/cms/static/js/mfa-utils.js
backend/cms/templates/_base.html
backend/cms/templates/_raw.html
backend/cms/templates/registration/login_mfa.html
backend/cms/templates/settings/mfa/add_key.html
backend/cms/templates/settings/mfa/authenticate.html
backend/cms/templates/settings/mfa/delete.html
backend/cms/templates/settings/user.html
backend/cms/urls.py
backend/cms/views/registration/__init__.py
backend/cms/views/registration/registration.py
backend/cms/views/settings/__init__.py
backend/cms/views/settings/mfa/__init__.py
backend/cms/views/settings/mfa/mfa.py
backend/cms/views/settings/settings.py
backend/cms/views/utils/mfa_utils.py
package.json
setup.py

Add a settings view, allowing a user to register multiple keys and remove those.
Changing MFA settings is only possible if the user (re-)verified his identity (using a password) within the last 5 minutes.
Question is: Should 2FA be checked before changes are allowed to be made?
I don't see a thread model where this would help. The user already proved his identity by logging in in the first place and the password check is only there if someone gains access to the already logged in session. Asking for the password again makes sure that the attacker could not gain persistent access. If the password was leaked he would need the key to log in in the first place.
Asking for 2FA to edit 2FA settings would only help against an attacker that has the valid password and got access to a valid session …

Implement 2FA auth using webauthn

---

backend/cms/locale/de/LC_MESSAGES/django.po
backend/cms/models/event.py
backend/cms/models/page.py
backend/cms/models/poi.py
backend/cms/templates/pois/poi.html
backend/cms/views/events/event_view.py
backend/cms/views/events/forms/event_translation_form.py
backend/cms/views/pois/poi.py
backend/cms/views/utils/slug_utils.py
package.json

I refactored the clean slug method because it was buggy for new objects.
The main changes include:
- the region and language parameter for checking for existing slugs come from the form object now instead of the form object instance
- the new property `translation.foreign_object` allows us to get the meta object for different content types, e.g. `page_translation.page` or `event_translation.event`
This changes also fixed the issue that POIs could not be created.
Fixes #262
Fixes #260

Refactor generate_unique_slug

---

backend/cms/templates/events/event_form.html
backend/cms/templates/pages/page_form.html
backend/cms/views/pages/page_view.py

- Make TinyMCE textarea readonly when form is disabled (fixes #277)
- Disable submitting forms of archived pages/events (fixes #278)

Improve readonly forms

---

backend/cms/templates/pois/poi_list.html
backend/cms/templates/pois/poi_list_archived.html
backend/cms/templates/pois/poi_list_archived_row.html
backend/cms/templates/pois/poi_list_row.html

In the page or event list, we show an additional column with the title of an instance in the backend language if the backend language differs from the default language of the selected region.
This behavior was missing in the poi list and is implemented in this PR.
Fixes #283.

Fix POI title display

---

backend/cms/apps.py

We don't want the secret key from the repository to be present in any production environment. This change verifies that the key was changed if DEBUG == False.

Add check for changed SECRET_KEY, fixes #176

---

backend/cms/locale/de/LC_MESSAGES/django.po
backend/cms/models/events/event.py
backend/cms/models/events/event_translation.py
backend/cms/models/pois/poi.py
backend/cms/models/pois/poi_translation.py
backend/cms/templates/events/event_form.html
backend/cms/templates/events/event_list_archived_row.html
backend/cms/templates/events/event_list_row.html
backend/cms/templates/pages/page_form.html
backend/cms/templates/pages/page_tree_archived_node.html
backend/cms/templates/pois/poi_form.html
backend/cms/templates/pois/poi_list.html
backend/cms/templates/pois/poi_list_row.html

Adapt the new translation icons for:
- Events
- POIs
- Archived Pages
This also copies the translation helper functions from pages to events and pois.
Fixes #305

Add new translation icons

---

package.json
src/cms/forms/events/event_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/events/event.py
src/cms/static/js/event.js
src/cms/templates/events/_poi_query_result.html
src/cms/templates/events/event_form.html
src/cms/templates/events/event_list_archived_row.html
src/cms/templates/events/event_list_row.html
src/cms/templatetags/content_filters.py
src/cms/urls.py
src/cms/views/events/__init__.py
src/cms/views/events/event_actions.py
src/cms/views/events/event_view.py

With this PR:
* The location of an event is shown in the event list (non-archived as well as archived).
* If an event has a location, the location is also shown in the event form.
* Inside an event form, a location for an event can be searched (implemented with AJAX calls).
* From the search results, either an existing POI can be selected or a new POI can be created.
Fixes #247

Add POI selection to event form

---

.circleci/config.yml
.pylintrc
dev-tools/pylint.sh
setup.py

- Move `.pylintrc` from `src`-directory to top level
- Ignore `.venv` and `node_modules` in `.pylintrc`
- Fix indendation error in `setup.py`

Configure pylint for whole project

---

src/cms/forms/users/region_user_form.py
src/cms/forms/users/region_user_profile_form.py
src/cms/forms/users/user_form.py
src/cms/forms/users/user_profile_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/views/users/user_view.py

- Add some extended logging for user forms
- Add check to make sure a user is either staff/superuser or is assigned to at least one region
Fixes: #393

Prevent the creation of region users without an assigned region

---

README.md
dev-tools/install.sh

On some distros (like e.g. Ubuntu 20.04), there is no recent version of pipenv available. Instead of installing an old packaged version, it is better to install the most recent version via pip directly. As it is generally considered bad practice to install packages with pip globally, and it seems a bit esoteric to create a virtualenv in which we install pipenv which creates another virtualenv, I think it's best to install it into `~/.local/bin` with the `--user`-flag.

Add pipenv installation hints

---

.circleci/config.yml

Sometimes, the CircleCI build takes nearly 10 minutes instead of ~3mins.
I think this is due to the jobs "tests" and "build-static-files" which install the cms again after all dependencies have been installed in "pipenv-install" already. This install command does not use the already installed package versions of Pipfile.lock, but updates them which additionally creates the problem that our builds no not reproduce our local environments.
This PR removes the separate install command and passes `src/integreat_cms.egg-info` instead, which fixes the problem that the command `integreat-cms-cli` was not found.
Fixes: #401

Fix CircleCI build times

---

.circleci/config.yml
dev-tools/check_translations.sh
src/cms/locale/de/LC_MESSAGES/django.po

This adds a new job in our CircleCI workflow, which checks, whether the translation file has 
- missing entries (e.g. because `integreat-cms-cli makemessages` was forgotten)
- empty entries (e.g. because new added strings were not translated)
Depends on: #400
Fixes: #404

Check translations in CircleCI

---

.circleci/config.yml
dev-tools/generate_documentation.sh
sphinx/conf.py

This PR adds improvements to our automatic sphinx documentation build:
- Add support for multiple sections of parameters (this makes model docstring more readable by e.g. separating normal fields from related fields and reverse relations)
- Improve appearance of related fields in model docstrings
- Remove temporary build files to reduce noise in the automatic updates on gh-pages
- Run sphinx-build in multiple threads
- Skip CircleCI build for automated documentation commits on gh-pages

Improve sphinx documentation config

---

dev-tools/check_translations.sh

This adds an additional check whether the translation file contains fuzzy entries.
Fixes: #411

Check for fuzzy translations

---

.circleci/config.yml
dev-tools/run.sh
src/backend/circleci_settings.py
src/backend/settings.py

- Add CircleCI settings for Django
- Compress JS & CSS only in production mode
Fixes: #419 
Fixes: #420

Compress JS & CSS only in production mode

---

sphinx/installation.rst

This adds a simple note to the Windows Subsystem for Linux (WSL) to the installation guide in our documentation.

Note for installation on Windows in documentation

---

src/cms/models/languages/language_tree_node.py

This adds the missing return statements I forgot :neutral_face: 
The functions are explicitly defined so they inherit the docstring of the parent model and are shown in the documentation.
Fixes #436

Add missing return statements in language tree 

---

.circleci/config.yml

This adds a filter to the `docker-images` job to ignore branches of the dependabot.
This should be no problem because the dependabot does not modify the docker images and the dependency versions have no influence on the docker images build.
You can verify that this works if the `docker-images` job for this PR is not run, since I used the same naming scheme as the dependabot.
Fixes #440

Fix CircleCI build for dependabot

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/events/event_list.html
src/cms/templates/events/event_list_archived.html
src/cms/templates/events/event_list_archived_row.html
src/cms/templates/events/event_list_row.html
src/cms/templates/pages/page_tree.html
src/cms/templates/pages/page_tree_archived.html
src/cms/templates/pages/page_tree_archived_node.html
src/cms/templates/pages/page_tree_node.html
src/cms/templates/pois/poi_list.html
src/cms/templates/pois/poi_list_archived.html
src/cms/templates/pois/poi_list_archived_row.html
src/cms/templates/pois/poi_list_row.html
src/cms/templatetags/content_filters.py

- This allows backend languages which are not contained in the content languages or have a different language code
- The table column of translation titles in the current backend languages is now hidden when the backend language does not exist in the content languages
Fixes #434

Fix non-existing language bug

---

src/api/urls.py

We don't have explicit links to the api endpoints anyway, so we don't need explicit names (especially if they clash with the names of cms urls).
Fixes  #448

Remove url names of api endpoints

---

src/cms/urls.py

I think this is enough, the [standard Django docu](https://docs.djangoproject.com/en/2.2/topics/http/urls/) referenced here has covered this topic very well.
Fixes #334

Improve documentation of cms urls

---

sphinx/conf.py
sphinx/templates/layout.html
src/api/v3/feedback/page_feedback.py
src/api/v3/single_page.py
src/backend/context_processors.py
src/cms/models/events/event.py
src/cms/models/events/event_translation.py
src/cms/models/media/document.py
src/cms/models/offers/offer_template.py
src/cms/models/pages/page.py
src/cms/models/pages/page_translation.py
src/cms/models/pois/poi.py
src/cms/models/pois/poi_translation.py
src/cms/models/regions/region.py
src/cms/utils/file_utils.py
src/cms/utils/slug_utils.py
src/gvz_api/utils.py

This is a collection of small documentation improvements where I didn't open an issue for every tiny detail.
Parts of these changes are very opinionated, so they are not necessary required changes.
- Use js instead of sphinx patch to open links in new tab
This makes is easier to keep up with upstream changes of sphinx and the rtd theme.
Additionally, it fixes some ugly borders around parameter lists.
- Fix parameter type of administrative division
`cms.constants.administrative_division` is a module of string constants and not a valid parameter type.
- Hide module path of return types
This makes the type hints more readable in my opinion.
- Minor improvements
- Add missing offer template parameters
- Move `Page.mirrored_page` to relationship fields
- Add default values of optional …

Documentation improvements

---

.circleci/config.yml
Pipfile
Pipfile.lock
dev-tools/install.sh
dev-tools/update_dependencies.sh
setup.cfg
setup.py
sphinx/installation.rst
sphinx/virtualenv.rst

This makes it easier to manage our dev dependencies. To test, whether this works for you:
```
pipenv --rm
rm ./src/integreat_cms.egg-info -r
./dev-tools/install.sh
```
Fixes #428

Move dev dependencies from setup.py to Pipfile

---

src/backend/settings.py
src/cms/apps.py

Add handler for authentication syslog and add messages for log in (attempts) and log out of users.
Creates messages like
```
Jul 29 16:28:36 INTEGREAT CMS - WARNING: login failed user=asdf, ip=127.0.0.1
Jul 29 16:29:08 INTEGREAT CMS - INFO: login user=root, ip=127.0.0.1
Jul 29 16:29:10 INTEGREAT CMS - INFO: logout user=root, ip=127.0.0.1
```
Missing:
* Verify that it actually logs to syslog

Add logging for log in/out to syslog, fixes #321

---

src/backend/settings.py
src/gvz_api/apps.py

- Add logging for `backend` and `gvz_api` apps
- Change GVZ API to https
- Only check availability on "runserver" command
- Add timeout of 3 seconds to request
Fixes #472

Add timeout to GVZ API test

---

src/backend/settings.py
src/gvz_api/apps.py

- Remove the trailing slash from the api, because the slash is also appended whenever the api url is used
- Check if response from `expect_empty_json` is actually empty
Fixes #478

Fix GVZ API URL

---

Pipfile
Pipfile.lock
sphinx/conf.py

The new dependency [sphinx-last-updated-by-git](https://pypi.org/project/sphinx-last-updated-by-git/) determines the last updated date in the documentation by the last change of the source file in git.
This package has only 1 contributor and is not used very often, but since it's just a dev dependency and won't run on our production server, I don't see a problem here.
Fixes #467

Add sphinx-last-updated-by-git

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/static/js/page.js
src/cms/static/js/pages/sbs_copy_content.js
src/cms/templates/pages/page_form.html
src/cms/templates/pages/page_sbs.html
src/cms/views/pages/page_sbs_view.py
src/cms/views/pages/page_view.py

Improvements in page form:
- Dropdown for translation direction
- Derive source language automatically from language tree
- Automatically preselect currently selected language as target language
Improvements in side-by-side view:
- Include only target language in url
- Derive source language automatically from language tree
- Adapt layout to normal page form
- Add permalink input field
- Add minor_edit checkbox
- Add draft/publish buttons
- TinyMCE editor for textarea fields
- "Copy content from source to target language"-button
Fixes #235

Improve Side by Side translation view

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/pages/page_tree_archived_node.html
src/cms/templates/pages/page_tree_node.html
src/cms/templates/regions/region_list_row.html

This fixes code scanning alerts of CodeQL.
See https://help.semmle.com/wiki/display/JS/Potentially+unsafe+external+link for more information on this issue.

Add rel="noreferrer" to external links

---

src/backend/context_processors.py
src/cms/admin.py
src/cms/fixtures/test_data.json
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/_base.html
src/cms/templates/regions/region_list.html
src/cms/templates/regions/region_list_row.html

-  Quick access to regions for staff
- This adds a list of up to 10 regions (ordered by last_updated) in the quick access list next to the language selection.
- This requires every user to have a user profile, so I added one to the test_data.json
-  Improve dashboard link in region list
- Remove CMS-URL
- Remove Webapp-URL
- Add button to open dashboard

Region selection improvements

---

src/cms/forms/pages/page_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/pages/page.py
src/cms/static/css/style.less
src/cms/static/js/pages/page_order.js
src/cms/templates/pages/_page_order_table.html
src/cms/templates/pages/page_form.html
src/cms/urls.py
src/cms/views/pages/__init__.py
src/cms/views/pages/page_actions.py
src/cms/views/pages/page_view.py

Control arrangement of pages within the page form:
1. Select parent page via dropdown
2. Change order between siblings via drag & drop
Fixes #50

Page order in page form

---

src/cms/forms/language_tree/language_tree_node_form.py

I think the usage of the [difference()](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#difference)-method is correct, but a bug in the mptt library might require this workaround here...
At least, [exclude()](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet.exclude) seems to work even with TreeQuerySets.
Fixes #514

Fix language tree node form

---

src/cms/urls.py

Most browsers will request the `favicon.ico` file per default, even if it's not used in the templates.
This results in misleading log entries, e.g.:
```
Oct 02 14:16:40 INTEGREAT CMS - WARNING: Not Found: /favicon.ico
Oct 02 14:16:40 INTEGREAT CMS - WARNING: "GET /favicon.ico HTTP/1.1" 404 6960
```
- Add `/favicon.ico` route and redirect to `/static/images/favicon.ico`

Add favicon.ico route

---

src/cms/forms/events/event_translation_form.py
src/cms/forms/pages/page_translation_form.py
src/cms/forms/pois/poi_translation_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/events/event_form.html
src/cms/templates/pages/page_form.html
src/cms/templates/pages/page_sbs.html
src/cms/templates/pois/poi_form.html

This PR disables the possibility of using the Heading 1 style in TinyMCE fields for text and descriptions, throwing a validation error if the `<h1>` tags are (manually) inserted into the field's content.
First, the PR removes the possibility of selecting "Heading 1" as a style in certain TinyMCE fields by manually overriding which styles are visible in the TinyMCE styles list. The affected tinyMCE instances are in the following templates:
- `cms/templates/events/event_form.html`
- `cms/templates/pages/page_form.html`
- `cms/templates/pages/page_sbs.html`
- `cms/templates/pois/poi_form.html`
Second, the PR adds a specific `clean_<field>` method to the Django Forms being used in the aforementioned templates, that checks for the presence of `<h1>` tags in their fields and, if found, raises a …

Disable Heading 1 style in certain TinyMCE fields

---

src/cms/locale/de/LC_MESSAGES/django.po

It seems that the GNU gettext tools behave slightly different on the CircleCI server compared to my local machine...
Even though I double-checked the translations locally before merging #510 via the command line into develop, the build is now failing.
- Fix the failing circleci build by fixing the translation file

Fix translation file

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/views/events/event_actions.py
src/cms/views/events/event_view.py
src/cms/views/language_tree/language_tree_node_view.py
src/cms/views/languages/language_view.py
src/cms/views/offer_templates/offer_template_view.py
src/cms/views/offers/offer_actions.py
src/cms/views/organizations/organization_view.py
src/cms/views/pages/page_actions.py
src/cms/views/pages/page_revision_view.py
src/cms/views/pages/page_sbs_view.py
src/cms/views/pages/page_view.py
src/cms/views/pois/poi_actions.py
src/cms/views/pois/poi_view.py
src/cms/views/push_notifications/push_notification_view.py
src/cms/views/regions/region_actions.py
src/cms/views/regions/region_view.py
src/cms/views/roles/role_view.py
src/cms/views/settings/user_settings_view.py
src/cms/views/users/region_user_view.py
src/cms/views/users/user_actions.py
src/cms/views/users/user_view.py

* Order of words was changed for many messages to be consistent.
* Stops at the end of messages was removed, as they're not really sentences and the stop just makes them unnecessarily longer.
Fixes #282
Co-authored-by: Amin Al-Ait <aminalait@outlook>

Change messages for consistency, fixes #282

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/static/css/style.less
src/cms/templates/pages/page_revisions.html

This adds steps and labels to the revision slider:
However, in my current Chromium version (85.0.4183.121), the `calc()`-statement doesn't work and the steps do not have the correct margins:
Does anybody have an idea how to resolve this (or do we just decide to not support this version of Chromium)?
Fixes #487

Improve page revision slider

---

.pre-commit-config.yaml
dev-tools/black.sh
dev-tools/check_translations.sh

This adds a few enhancements for our current code style tooling.
Since black also has side-effects on line-numbers in the translation file, we should update the translations after black formatting.
- Pin black pre-commit hook to same version as in Pipfile
- Add translation check pre-commit hook
- Execute translate.sh in black.sh
Fixes: #530

Improve code style tooling

---

src/api/v3/pages.py

* Only show page if parent is visible.
The solution is pretty straight forward: start with the main level of pages (the ones without parents). If they have visible content, start a recursive function that fetches the children.
Fixes #386

Page API: visibility of children, fixes #386

---

src/cms/constants/text_directions.py
src/cms/fixtures/test_data.json
src/cms/models/languages/language.py
src/cms/views/pages/page_actions.py

This makes the text direction values consistent.
- used the more verbose constants `LEFT_TO_RIGHT` and `RIGHT_TO_LEFT`
- changed the values in the test data
Fixes: #559

Make text direction values consistent

---

src/cms/fixtures/test_data.json
src/cms/forms/languages/language_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/languages/language.py
src/cms/templates/languages/language_form.html
src/cms/templates/pages/page_pdf.html

added table_of_contents field for language model/form
To print a uniform "Table of contents" header for each available
language, a new field is inserted for the language model/form and
applied to the PDF export feature.
Fixes: #550

added table_of_contents field to language model

---

src/cms/static/js/tree_drag_and_drop.js

fixed drag & drop bug in page tree
- the bug was caused by dom manipulation during the dragstart event
- dom manipulation must be delayed in this case by timeout
- this problem only occurs when using chrome browser
Fixes: #494

fixed drag & drop bug in page tree

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/pages/page_form.html
src/cms/views/pages/page_view.py

Fixed saving icons in page editor
- When a django form contains file/image input, the HTML form tag has to
set the attribute enctype in order to upload the content.
- Secondly, file data is handled separately to normal form data, they can
be retrieved from request.FILES, rather than request.POST.
Fixes: #545

Fixed page editor to save icons

---

src/api/decorators.py
src/api/urls.py
src/api/v3/feedback/event_feedback.py
src/api/v3/feedback/event_list_feedback.py
src/api/v3/feedback/imprint_page_feedback.py
src/api/v3/feedback/legacy_feedback_endpoint.py
src/api/v3/feedback/offer_feedback.py
src/api/v3/feedback/offer_list_feedback.py
src/api/v3/feedback/page_feedback.py
src/api/v3/feedback/region_feedback.py
src/api/v3/feedback/search_result_feedback.py
src/api/v3/imprint.py
src/api/v3/languages.py
src/api/v3/offers.py
src/api/v3/pages.py
src/api/v3/pdf_export.py
src/api/v3/push_notifications.py
src/api/v3/regions.py
src/api/v3/single_page.py
src/cms/models/regions/region.py

This adds a custom decorator which makes sure the API always returns a JSON response, even if the error `Http404` is raised.
- Make use of shortcut functions in API
- Add json_response decorator
Fixes: #578

Always return JSON in API

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/pages/abstract_base_page_translation.py
src/cms/static/js/copy-clipboard.js
src/cms/templates/pages/page_form.html
src/cms/templates/pages/page_tree_node.html
src/cms/urls.py
src/cms/views/pages/__init__.py
src/cms/views/pages/page_actions.py

Remove random short URL
`s/p/<ID>` we use the objects numeric ID in conjunction with a second part in the `URL /p/` to point towards pages. Events then get another URL, i.e.` s/e/<ID>`. ID in this case is the instance ID (integer) of a model in the database.
##Task Breakdown:
> 1.Remove URL to view pages.expand_short_url in [urls.py](url)
> 2. Remove the view `expand_short_url` in [page_actions.py](url)
> 3.Remove field `short_url_id` from [`abstract_base_page_translation.py`](url)
> 4.Re-implement the property function `short_ur`l in `abstract_base_page_translation.py` so it returns the short URL of pattern from above. You can use e.g. reverse("`expand_page_translation_id`", `short_url_id=self.id`) to get the url.
> 5.Fix the function `short_url_to_clipboard` in c[opy-clipboard.js](url) …

Remove random short URL

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/static/css/tinymce_custom.css
src/cms/templates/pages/page_form.html

The current "Do not translate" button functionality is very basic: it wraps the selected text in span tags with the `translate="no"` property. It does not concern itself with the HTML structure of the page. This is a recipe for carnage.
This PR selects the actual DOM elements and toggles the `translate="no"` attribute for it.
Fixes: #596 
There are still some limitations: If the selection starts with a nested element, the selected siblings of ancestors will not receive the translate attribute. But this is IMHO acceptable. In such cases, other parts of the page need to be selected individually.

Change TinyMCE notranslate, fixes #596

---

src/cms/forms/pages/page_form.py

Fixes change detection in page form
- Problem was that the mirror_page_first field (which was a ChoiceField) normalizes their values
to strings (see https://docs.djangoproject.com/en/2.2/ref/forms/fields/#choicefield).
- So when comparing the initial value of the select widget True with the
current value of the form field 'True',
it always evaluated True != 'True'.
Fixes: #466

Fixed detecting no changes for page form

---

Pipfile.lock

Sometimes, pipenv does strange things, like e.g. marking dependencies as local editable packages... 
I didn't yet find the reason for this, so we have to look out for this in the future. For now, this fixes the Pipfile.lock by reverting the changes introduced in 7a61ce9f9eb333f1c3386e8bc62578a01a6f88ce.
- Fix xhtml2pdf dependency in Pipfile.lock
This should fix the failing build in #616

Fix xhtml2pdf entry in Pipfile.lock

---

src/backend/wsgi.py

If I try to start the development server while no environment variables are set, I get the following error:
```
Traceback (most recent call last):
File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
self.result = application(self.environ, self.start_response)
File "/home/timo/integreat/integreat-cms/.venv/lib/python3.7/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
return self.application(environ, start_response)
File "/home/timo/integreat/integreat-cms/src/backend/wsgi.py", line 16, in application
os.environ["DJANGO_SECRET_KEY"] = environ["DJANGO_SECRET_KEY"]
KeyError: 'DJANGO_SECRET_KEY'
Jan 09 12:29:40 INTEGREAT CMS - ERROR: "GET / HTTP/1.1" 500 59
```
- Only pass the environment variables if they are set

Pass environment variables only if they are set

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/page_xliff_converter.py
src/cms/templates/pages/page_xliff_confirm.html

When importing a XLIFF file, the attempt to import a translation for a not existing pages or language produces an error in the diff list.
This PR hands the information about failed imports to the template, where an alternative to the diff is rendered.
Fixes: #622

XLIFF: import error for missing page, fixes #622

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/pages/abstract_base_page_translation.py
src/cms/page_xliff_converter.py
src/cms/static/js/pages/page_bulk_actions.js
src/cms/static/js/pages/unset_translation_state.js
src/cms/templates/pages/page_form.html
src/cms/templates/pages/page_tree.html
src/cms/templates/pages/page_tree_node.html
src/cms/urls.py
src/cms/views/pages/__init__.py
src/cms/views/pages/page_actions.py

Update the translation state when XLIFF is imported or exported
- When XLIFF is exported, ajax request is send to update database entry of the translation and display clock icon to signal the successful update. 
- When XLIFF is imported, translation is created with currently_in_translation set to false.
- Warning in page form, when page is in translation process + ability to undo process
Fixes: #618
<del>### Open issue
I experienced behavior, that maybe you might not expect:</del>
<del>1. go to page tree of augsburg
2. export english XLIFF, which has 'up-to-date' arabic  pages (e.g. page "Stadtplan" from Augsburg)
3. refresh the website
4. see that initially 'up-to-date' arabic is no outdated</del>
<del>I guess that's due to the translation changes affecting the last_updated value, up for …

Update currently in translation state on import/export XLIFF

---

src/api/v3/pages.py
src/cms/models/pages/page.py
src/cms/models/pages/page_translation.py

If a page is mirrored, the modified date in the API should be the one of the mirrored page, if the page translation itself has no content.
This adds a property `combined_last_updated` to the `PageTranslation` model that works in a similar way as the combined text property.
Fixes: #628

Combined last updated date for page with live content

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/dashboard/admin_dashboard.html
src/cms/views/dashboard/admin_dashboard_view.py
src/cms/views/dashboard/dashboard_view.py

This should be a list of the last ~5 messages.
Show admins the latest feedback from app users in dashboard. This should be a list of the last ~5 messages. In some cases, the feedback only contains a thumbs up or down, in other cases it can contain a message. The title of the page or event concerned should be displayed as well and linked to the editing page.
Additional option: Add link that sends the message string to translate.google.com or deepl.com for translation. This can be useful if the feedback is given in a language the back end user does not understand. It is perfectly fine, if the link opens the translation website in a new tab. No need to fetch a translation via the API.
Fixes: #2

Show latest feedback in dashboard

---

sphinx/troubleshooting.rst

I had some issues while getting the application running on an M1 Macbook but was eventually able to solve the issues.
I explain:
* how to use a different python version
* how to compile postgres to get psycopg2 installed
It seems, like both issues will eventually go await once everyone adopts their software for the arm platform, but maybe it makes sense to have those steps in here for the meantime 😄 .

Add troubleshooting for developing on arm macs

---

src/api/v3/imprint.py

If no imprint translation is available in the selected language, the imprint is returned in the default region language.
Co-authored-by: Sandro Wiedemann <sandro.wiedemann@gmail.com>
Fixes: #621

API imprint: return default language, fixes #621

---

src/cms/fixtures/test_data.json
src/cms/forms/users/region_user_profile_form.py
src/cms/forms/users/user_profile_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/users/user_profile.py
src/cms/templates/events/event_form.html
src/cms/templates/pages/page_form.html
src/cms/templates/pages/page_tree.html
src/cms/templates/users/admin/user.html
src/cms/templates/users/region/user.html

Added expert mode for displaying additional features.
Enabling expert mode includes the following features:
- Page mirroring
- Recurring events
- Do-Not-Translate-Tag in page editor
- Page-based permissions
- XLIFF import/export
- Page filtering
Expert mode setting is saved per user account, additional expert-mode-checkbox for (region-)user supplied.
Expert mode does not add an additional role to database, because expert mode does not deal with any additional permissions when enabled. Disabling expert mode just simplifies the GUI by hiding the aforementioned features.
Fixes: #499

Added expert mode

---

src/backend/settings.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/static/css/style.less
src/cms/templates/events/event_list.html
src/cms/templates/events/event_list_archived.html
src/cms/templates/languages/language_list.html
src/cms/templates/offer_templates/offer_template_list.html
src/cms/templates/offers/offer_list.html
src/cms/templates/organizations/organization_list.html
src/cms/templates/pages/page_form.html
src/cms/templates/pagination.html
src/cms/templates/pois/poi_list.html
src/cms/templates/pois/poi_list_archived.html
src/cms/templates/push_notifications/push_notification_list.html
src/cms/templates/regions/region_list.html
src/cms/templates/roles/list.html
src/cms/templates/users/admin/list.html
src/cms/templates/users/region/list.html
src/cms/templatetags/arithmetic.py
src/cms/views/events/event_list_view.py
src/cms/views/languages/language_list_view.py
src/cms/views/offer_templates/offer_template_list_view.py
src/cms/views/offers/offer_list_view.py
src/cms/views/organizations/organization_list_view.py
src/cms/views/pois/poi_list_view.py
src/cms/views/push_notifications/push_notification_list_view.py
src/cms/views/regions/region_list_view.py
src/cms/views/roles/role_list_view.py
src/cms/views/users/region_user_list_view.py
src/cms/views/users/user_list_view.py

Adds pagination for all objects lists
Generally shows pagination links only if there is more than one page to display, else hides all pagination links.
There is always a link to the first and the last page.
Additionally there are links for 2 previous and next pages.
To limit the number of links all other pages are displayed as `...`
Adds pagination to the following lists:
Admin:
Region:
Trees and pagination should not be combined, therefore pagination is not applied to:
- Page tree
- Language tree
At the moment feedback is split into multiple querysets, which must first be combined to a single queryset, before pagination can be applied. So for now feedback pagination is skipped until the feedback refactoring is merged.
Fixes: #620, #666

Adds pagination to lists

---

src/cms/templates/pages/page_form.html
src/cms/views/pages/page_actions.py

Fixes page mirroring bug, which is caused by trying to set a mirrored page, when a completely new page is created.
- When a region for page mirroring is selected, an ajax request is
triggered, which tries to retrieve the current page from database.
- So when there is a completely new page created, which has no entry in the
database yet, this ajax request fails.
- That means the page mirroring field in the page form should be hidden
for newly created pages.
The proposed solution is the easiest, but if you wish, there would also be an ability to adjust the `render_mirrored_page_field` view, so that it can handle pages without a database entry:
https://github.com/Integreat/integreat-cms/blob/420ecee0f727fa4097d5f241f65d75a96a759dae/src/cms/views/pages/page_actions.py#L850
Fixes: #673

Fixes page mirroring bug

---

src/backend/settings.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/middleware/timezone_middleware.py

Adds a setting for `current time zone` that is used for rendering.
Add a setting `CURRENT_TIME_ZONE`
Add a middleware-function that sets the current time zone according to this setting
Fixes: #652
For further timezone handling, #662 and #663 have been created.

Add current time zone

---

src/api/urls.py
src/cms/tests/__init__.py
src/cms/tests/views/api_view_test.py

Since we break things from time to time, it's good to have at least some basic testing functionality to leave less room for errors.
This should in theory prevent bugs like #706 and #711 in the future.
This adds a few simple API view tests which check whether the API views return status code 200.
Missing API views (implementation a bit more complicated):
- Feedback API
- Push content API
- Offer API
- Single page API
Note: Since this test detects bugs which are not yet solved on the develop branch, I expect the tests to fail. Once the bugs are fixed, I can rebase this branch and check whether they succeed.
This PR depends on

Add simple API view tests

---

src/cms/static/js/pages/page_order.js
src/cms/static/js/tree_drag_and_drop.js

Fix drag & drop in page form. The cause of the bug was identical to #494:
In Chromium, manipulating the DOM during dragstart event fires a dragend event immediately
- Add delay to dragstart in order table of page form
Fixes: #713

Fix drag & drop in page form

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/regions/region.py

In da858ad7199e27e49116bfc49ff722462f32ce2e (#715), I made a stupid mistake which resulted in `region.get_pages(archived=True)` returning all non-archived pages.
- Do not overwrite the `pages` variable with the non archived pages

Fix get_pages() for archived pages

---

src/cms/static/css/style.less
src/cms/static/js/forms/file-field.js
src/cms/static/js/pages/page_mirroring.js
src/cms/static/js/revisions.js

So far, we are accessing and changing elements by using the un-sanitized innerhtml()- and html()-method. According to ESLint this is bad behavior. I managed to use the correct methods for the innerhtml-parts, but we should do this for the html()-Methods as well.
See page_mirroring.js

Access and set HTML content according to ESLint

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/feedback/feedback.py
src/cms/templates/dashboard/admin_dashboard.html
src/cms/templates/feedback/admin_feedback_list.html
src/cms/templates/feedback/region_feedback_list.html

Support multi-line feedback
- Change `CharField` to `TextField`
- Use the css class `whitespace-pre-line` when rendering multi-line-feedback
- Collapse feedback which has multiple lines
Fixes: #719

Support multi-line feedback

---

Pipfile.lock
setup.py
sphinx/conf.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/offers/offer_template.py

The only problem I faced was that the documentation build failed with Django 3.1.
Therefore, I implemented a fix in [sphinxcontrib-django2](https://github.com/timoludwig/sphinxcontrib-django2) (see https://github.com/timoludwig/sphinxcontrib-django2/commit/2bbbcf20cb5eb9e7931caad04391048ba0c7266b and https://github.com/timoludwig/sphinxcontrib-django2/commit/b1a596da474f35447552a0f7b760494362430e9e).
I couldn't find any further problems in the running system with version 3.1 and I don't think we're using anything which is listed in the deprecated features of [3.0](https://docs.djangoproject.com/en/3.1/releases/3.0/#features-deprecated-in-3-0) and [3.1](https://docs.djangoproject.com/en/3.1/releases/3.1/#features-deprecated-in-3-1).
This should make it trivial to upgrade to Django 3.2 LTS …

Upgrade Django to version 3

---

src/backend/settings.py
src/cms/_tests.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/events/_event_filter_form.html
src/cms/templates/events/_poi_query_result.html
src/cms/templates/events/event_form.html
src/cms/templates/events/event_list.html
src/cms/templates/events/event_list_archived.html
src/cms/templates/events/event_list_archived_row.html
src/cms/templates/events/event_list_row.html
src/cms/templates/feedback/_admin_feedback_filter_form.html
src/cms/templates/feedback/_region_feedback_filter_form.html
src/cms/templates/pages/_page_filter_form.html
src/cms/templates/pages/_page_order_table.html
src/cms/templates/pages/page_form.html
src/cms/templates/pages/page_tree.html
src/cms/templates/pages/page_tree_archived.html
src/cms/templates/pages/page_tree_archived_node.html
src/cms/templates/pages/page_tree_node.html
src/cms/templates/pois/poi_form.html
src/cms/templates/pois/poi_list.html
src/cms/templates/pois/poi_list_archived.html
src/cms/templates/pois/poi_list_archived_row.html
src/cms/templates/pois/poi_list_row.html
src/cms/templatetags/content_filters.py

I noticed that PR #738 (Improve logging) got a little bit out of control, so I will split it into separate PRs.
This one is about the backend language codes. Recently, we changed our language models and used two-letter slugs for identifying languages. Since we need a mapping from backend to content languages, I propose to use "de" and "en" instead of "de-de" and "en-us" as backend languages as well.
- Adapt the backend languages to the changed content language model
- Remove unused `unify_language_slug` template tag ("en-us" and "en-gb" are both just "en" now)
- Fix language slugs in tests

Adjust backend languages codes

---

src/backend/logging_formatter.py
src/backend/settings.py

I have no idea why I missed this opportunity in #738 (Improve logging) - I mean who doesn't want colors, right? 
- Add `ColorFormatter` which inherits from the default Python logging Formatter
- Colorize logging output based on logging level
- This only affects the console output which is used if `DEBUG` is `True`.
Fixes the problem that our console log looks boring

Enable colored logging

---

example-configs/apache2-integreat-vhost.conf

Add Apache2 config entry to return a 204 for the `/ping` URL. This enables the app to check its online status.

Apache2: Add app online ping rule

---

src/cms/forms/pages/page_translation_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/_base.html
src/cms/templates/pages/page_form.html
src/cms/views/pages/page_view.py
src/frontend/css/style.scss
src/frontend/js/copy-clipboard.ts
src/frontend/js/forms/update-permalink.ts

Improve page link field 
- Per default page link field is read-only.
- Deactivating read-only displays a form field, where user can edit manually.
- After editing user can click the save button to confirm the changes (saves to the input field, changes only get persistent on form       submission)
- When clicking the abort button, the previous slug value is restored
Fixes: #735

Improve page link field

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/pages/page_pdf.html
src/cms/utils/pdf_utils.py
src/frontend/css/pdf_page_export.css

Fixes bold/italic font styles in PDF export
- The current font for PDF generation is DejaVu, which is a static
font-family. That means different font wheights and styles are shiped
in different files (see folder `cms.frontend.fonts.dejavu-sans`).
- xhtml2pdf + DejaVu accept arabic letters, but not in combination with
italic style, so italic styles are excluded from arabic documents.
Fixes: #751

Fix PDF font style bug

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/pages/page_tree.html
src/cms/views/pages/page_actions.py
src/frontend/js/bulk-actions.ts

Fixes KeyError exception when only non-existing page translations are selected for PDF export
- Adds a function to check, whether at least one translation exists for
the selected pages.
- If this is the case, PDF export for the selection is allowed else
denied.
Fixes: #753
This new function should enable both proposed approaches: User dialog or disabled bulk-action-button.

Fixes non-existing translation PDF export

---

src/api/v3/regions.py
src/cms/fixtures/test_data.json
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/regions/region.py
src/cms/templates/pages/page_pdf.html
src/cms/templates/regions/region_list.html
src/cms/templates/regions/region_list_row.html

In issue #703, I forgot to mention that the new field `administrative_division_included` should also determine the name of the regions in API responses. This PR now fixes this addendum.
- Show administrative division in API only when included in the name
- Add `prefix` and `full_name` properties to `Region` model
- Return translation of administrative division always in the region's default language

Improve handling of administrative division

---

dev-tools/install.sh
sphinx/dev-tools.rst
sphinx/troubleshooting.rst

If `./node_modules` or `./src/cms/static/*` contain legacy JS files, this may result in Webpack compilation errors.
The `install.sh` removes the `./node_modules` and `./src/cms/static/*` directories.

Add clean parameter to install.sh 

---

README.md
dev-tools/install.sh
sphinx/installation.rst

Since our new webpack bundling process has new constraints to our node-js version, I added the requirements check to the install.sh script.
- Check if nodejs version 12 or version 14 or higher is installed

Add node-js requirements to install script

---

src/cms/forms/users/user_form.py

Fix `RelatedObjectDoesNotExist` error in user form
- Only use `user.profile` in logging if user already has a profile
Fixes: #768

Fix user creation

---

src/backend/settings.py

This enables the possibility to start the server in production mode, even if no writable logfile location is given.
- Check write permissions before falling back to the default logfile location

Check write permissions of logfile

---

src/backend/settings.py
src/backend/urls.py
src/cms/admin.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/_base.html
src/cms/urls.py

This PR introduces a global setting for the wiki-URL and deactivates the django.contrib.admin app, if the system is run on production mode.
- Introduce WIKI_URL in settings.py
- Create a redirect to the Wiki
- Only add django.contrib.admin to INSTALLED_APPS, if `DEBUG=True`
- Only add `/admin` endpoint to `urls.py` if `DEBUG=True`
- Only show Django-Administration Link in base.html, if debug is true.
Fixes: #746
Fixes: #689

Add functionality to the help button & Deactivate Django.Admin in production

---

src/frontend/js/pages/page-order.ts

Initializes the event listener on window load, not on window change
Fixes: #775

Fix event handler of page order table

---

src/cms/templates/language_tree/language_tree.html
src/cms/templates/pages/_page_order_table.html
src/cms/templates/pages/page_tree.html
src/frontend/js/pages/page-order.ts
src/frontend/js/tree-drag-and-drop.ts

Both drag & drop scripts were working concurrently, because both set event listeners to the same class names.
- Only activate tree drag & drop on page & language tree
- Only activate page order drag & drop on page form
- For tree drag & drop: Move function definitions from inside the event listener to the global scope of the script
Fixes: #784

Fix page drag & drop

---

dev-tools/install.sh

Fixes the install script python3.7-dev checker
Referencing @timoludwig 
"`grep -q` exits immediately after it found the first match, but dpkg -l is not done writing its output, so it sends the error 141 SIGPIPE because it can no longer pipe its output to grep because the process is dead"
Fixes: #805

Fixes the install script python3.7-dev check

---

src/cms/templates/pages/page_tree_node.html

This collapses all pages per default, so only root pages are visible when opening the page tree.
- Collapse pages per default
Fixes: #671

Collapse pages per default

---

src/backend/settings.py
src/cms/forms/regions/region_form.py
src/gvz_api/apps.py
src/gvz_api/utils.py

This PR adopts the GVZ API v2.
To accommodate the API changes, the handling of requests is also changed. First, the children need to be searched recursively. Second, all details are directly provided in the answers. Therefore the coordinates dictionary for children can directly be created.
Fixes #796

Change GVZ API wrapper

---

src/backend/settings.py

Since our change to WebPack, we luckily don't need to serve the `node_modules` under the `static` path anymore.
Interestingly, we had an issue for this (#484 "Do not serve `node_modules` under `/static`"), but closed it even though the `node_modules` were still served.
- Remove `node_modules` from static files
Fixes #484

Remove `node_modules` from static files

---

src/cms/views/events/event_list_view.py
src/cms/views/feedback/admin_feedback_list_view.py
src/cms/views/feedback/region_feedback_list_view.py
src/cms/views/languages/language_list_view.py
src/cms/views/offer_templates/offer_template_list_view.py
src/cms/views/organizations/organization_list_view.py
src/cms/views/pois/poi_list_view.py
src/cms/views/push_notifications/push_notification_list_view.py
src/cms/views/regions/region_list_view.py
src/cms/views/roles/role_list_view.py
src/cms/views/users/region_user_list_view.py
src/cms/views/users/user_list_view.py

Fixes the links for all pagination links after the first page
Rename the paginators query string in the list views
Fixes: #833

Rename query string for pagination in views

---

src/cms/fixtures/test_data.json
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/events/event_translation.py
src/cms/models/pages/abstract_base_page.py
src/cms/models/pages/abstract_base_page_translation.py
src/cms/models/pois/poi_translation.py
src/cms/models/push_notifications/push_notification.py
src/cms/models/push_notifications/push_notification_translation.py

This pr removes the `created_date` and `last_updated` fields from some models as specified in #846.
Additionally, this pr removes the `created_date` field from `ImprintPageTranslation` and the `last_updated` field from `ImprintPage`.
Fixes: #846

Remove unused created_date and last_updated fields

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/views/pages/page_view.py

It is now possible to update a page without any change to refresh the last update date.
- By clicking the update/aktualisieren button the last update date of the page will be refreshed to the current time, even if there is no change made in the page contents.
- After refreshing a message is shown ("no changes detected but date refreshed") .
- The button name does not change (stays always "Update/Aktualisieren") in the current commit, because I think changing the button name is probably confusing (Please see the conversation on the issue page). If the changing name is even though wished, I will add it.
Fixes: #629

Add possibility to refresh last_updated date

---

src/cms/templates/_base.html
src/cms/urls.py
src/cms/views/settings/mfa/register_user_mfa_key_view.py

This PR modifies the link of the user setting so that the network setting/admin dashboard is not visible to the non-staff users. 
- added region slug in the link to the user settings.
-
-
Fixes: #786

Admin menu visible in user settings #786

---

src/api/v3/events.py
src/backend/settings.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/events/recurrence_rule.py

This pr allows recurrent events to be returned by the events api.
Add a method `iter_after` to  the`RecurrenceRule` model to generate all valid dates covered by this rule after a start date.
Use this method in the events api endpoint to additionally return these events, up to a maximum time span.
These events and their translations will have an id of `null`. Additionally, a unique path will be created for each event translation.
Fixes: #842

Return recurrent events in the events api

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/events/event_form.html
src/cms/templates/pages/page_form.html
src/cms/templates/pois/poi_form.html
src/cms/urls.py
src/cms/views/events/event_view.py
src/cms/views/pages/__init__.py
src/cms/views/pages/page_actions.py
src/cms/views/utils/__init__.py
src/cms/views/utils/slugify_ajax.py

This pr makes the design of the slug input field of page form, event form and poi form more inline with each other.
Additionally, the methods `slugify_ajax` can now work for pois and events too, while it previously just worked for pages.
- Update the slug input field of events
- Make the design of the slug input field uniform across pages, events and pois
- Make the `slugify_ajax` function more generic in order to allow it to also function with events and pois
Fixes: #804

generalize slugify_ajax

---

src/cms/views/events/event_actions.py

Fix broken poi field in event form
According to the docs:
```
Keep in mind that order_by() uses any default related model ordering that has been defined. 
You might have to explicitly order by the relation _id or referenced field to make sure 
the DISTINCT ON expressions match those at the beginning of the ORDER BY clause. 
``` 
Since the language model is ordered by bcp47_tag, docs suggest to explicitly order by the relations id. 
Fixes: #861

Fix broken poi field in event form

---

src/cms/forms/regions/region_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/regions/region.py
src/cms/templates/imprint/imprint_form.html
src/cms/templates/imprint/imprint_sbs.html
src/cms/templates/pages/page_form.html
src/cms/templates/pages/page_tree_node.html
src/cms/templates/regions/region_form.html

This PR contains changes for the issue "Add region setting for short urls".
-A new field "short_url" is added to the model and form of page.
-Short url is shown only when the expert mode is enabled for the user and the short url is activated for the region.
-the icon of short url copy is removed in the page list.
Fixes: #685

Add region setting for short urls

---

src/frontend/js/media-management/component/breadcrumbs.tsx
src/frontend/js/media-management/component/directory-content.tsx
src/frontend/js/media-management/index.tsx

Use preact router only for specific links
Instead of going opt-out on preact routing links by adding the attribute `native` to all non-preact-links, I made preact routing opt-in by adding the attribute `media-library-link`.
All links without the `media-library-link` attribute now get the `native` attribute by default.
This means that only directory links are opened in preact, and all other links work as expected.
Fixes: #877

Use preact router only for specific links

---

package-lock.json
package.json
src/frontend/css/style.scss

Since I got no reaction on my PR https://github.com/jackiboy/flagpack/pull/16, I published my own fork of flagpack:
https://github.com/timoludwig/flagpack-dart-sass
https://www.npmjs.com/package/flagpack-dart-sass
This should get rid of the warning in our webpack build:
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
```
- Use fork of flagpack with support for `dart-sass` instead of `node-sass`
Fixes: #

Use fork of flagpack with support for `dart-sass`

---

src/cms/forms/custom_content_model_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/utils/slug_utils.py
src/cms/views/events/event_view.py
src/cms/views/pages/page_view.py
src/cms/views/pois/poi_view.py
src/frontend/js/forms/tinymce-init.ts

Fixes Attribute Error at event translation form and change detection at page translation form
cfcb7a6:
Initializes forms with `additional_instance_attributes` , necessary to generating unique slugs for distinct region/language
The forms instance (and its related object, e.g. PageTranslation - Page) is not used for calling the region object, because the instance might not exist yet.
9a0c192:
- Converts tiny mce content to html (default is xhtml), necessary because [content_clean_method](https://github.com/Integreat/integreat-cms/blob/82eec7f98bdc62c0d14406ed189211911cc0c862/src/cms/forms/custom_content_model_form.py#L63) outputs html format, which causes change detection (`<br>` compared to `<br />`)
- Removes pretty print, because options appends additional line breaks to html tag, which …

Fixes Attribute Error and change detection

---

src/cms/models/events/event_translation.py
src/cms/models/pages/imprint_page_translation.py
src/cms/models/pages/page_translation.py
src/cms/models/pois/poi_translation.py

As UTF-8 characters can take up to 4 bytes, a limit of 250 bytes is very limiting for some languages. Migrating existing titles requires about 1024 bytes in length.

Change translation title length

---

src/cms/models/regions/region.py
src/cms/views/regions/region_list_view.py

This PR contains a change to show regions alphabetically sorted by dafault.
- Regions are now sorted by default when they are shown.
- Userlist was already sorted in region user list and network management.
-
Fixes: #893

Provide default order for region model

---

src/cms/forms/custom_content_model_form.py
src/cms/locale/de/LC_MESSAGES/django.po

This pr fixes the crash that occurs when creating a page/event/poi that has an empty description or a description that is for any other reason no valid html.
- Handle exceptions thrown by the function that parses html strings and return the string unmodified in case of an error
Fixes: #895

Fix crash when creating a new page/event/poi with an empty description

---

src/cms/constants/status.py
src/cms/forms/events/event_translation_form.py
src/cms/forms/imprint/imprint_translation_form.py
src/cms/forms/pages/page_translation_form.py
src/cms/forms/pois/poi_translation_form.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/events/event_translation.py
src/cms/models/pages/abstract_base_page_translation.py
src/cms/models/pois/poi_translation.py
src/cms/views/events/event_view.py
src/cms/views/imprint/imprint_view.py
src/cms/views/pages/page_view.py
src/cms/views/pois/poi_view.py
src/frontend/js/forms/autosave.ts

This PR proposes a solution to the problem that the status of page becomes Draft when some changes are made but then deleted before the autosave,
- when a POST request, which changes the status of a page to Draft, is sent by an auto save but the changes are deleted and therefore the contents have not changed, the status will be overwritten to Public.
-
-
Fixes: #714

Fix autosave changing previous version to draft

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/events/event_translation.py
src/cms/models/pages/page_translation.py
src/cms/models/pois/poi_translation.py
src/cms/templates/_tinymce_config.html
src/cms/templatetags/settings_tags.py
src/cms/urls.py
src/cms/views/utils/__init__.py
src/cms/views/utils/search_content_ajax.py
src/frontend/editor_content.ts
src/frontend/js/forms/tinymce-init.ts
src/frontend/js/tinymce-plugins/custom_link_input/plugin.js

This pr adds support for searching internal links for pois, events and pages in the tinymce editor.
- Replace the link plugin with a custom implementation of similar functionality
- Add an ajax endpoint for querying pois, events and pages for the current region that match a query string
Fixes: #590

Add internal link suggestions for tinymce editor

---

src/cms/templates/imprint/imprint_sbs.html
src/cms/templates/pages/page_sbs.html

This pr fixes the error that shows up when trying to open the page translation view.
Additionally, this pr fixes a problem where the page translation loads as readonly, even if the user has all required permissions.
- Provide the target language to `_tinymce_config.html` in the sbs view
- Fix the variable `can_change_page_object` not getting set at all
Fixes: #907

Fix translator view

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/views/events/event_view.py

This PR fixes a `TypeError` occurring when trying to save a newly created event. The error is due to missing arguments to the `has_changed` method invoked on a field of the form.
Steps to fix the error:
- Provide the necessary arguments to the method
- Check the arguments for validity (i.e., not invoking `NoneType` objects) before
Even though the `elif` clause looks a little bit messy and overloaded now, I chose to stick with the method call instead of another workaround because the method invoked on the field does checks that we'd have to account for in our workaround otherwise.
Fixes: #887

Fix `TypeError` in `EventView` caused by missing method arguments

---

src/frontend/js/forms/autosave.ts

This PR solves the problem that the auto save creates multiple of new versions instead of update the first one.
- When there is a change made, the latest version of the translation will be checked.
- If it has status Autosave, this one will be deleted and replaced with the new version by not increasing the version number.
In the second commit changed
- autosave.ts is changed as in the comment suggested.
- Line 101 of forms.pages.page_translation_form.py, which was already commented out, is deleted.
- Now only one page is created also for a content which has no published version. The problem that auto save changes unversioned page (page without published version) will be solved in the issue #899.
Fixes: #672

Autosave on new page form creates multiple new pages

---

src/api/v3/pages.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/pages/page.py

Fixes API error when no query string is supplied
When neither id nor url is supplied by API children request, use all root pages + their children (with specified depth)
Fixes: #925

Children API: use root pages as ancestors per default

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/views/pages/page_view.py

This PR contains a suggestion to solve the problem that autosave changes unversioned page models.
- Before saving page and pagetranslation objects, it will be checked in page_view.py, whether the save is triggered by an auto save, a page objects already exisits, and there is a public version backup.-
Fixes: #899

Autosave changes unversioned Page model

---

src/backend/settings.py
src/cms/views/push_notifications/push_notification_sender.py

This should fix the server crash when trying to send a push notification.
- The parsing of the fcm-authentification-token was deprecated. Now it will handle the token as a string and not as a database entry.
Fixes: #927

Fix push notifications API token

---

src/api/v3/pages.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/models/pages/abstract_base_page_translation.py
src/cms/models/pages/page_translation.py

Fix API page response format for url and path
- Prepends domain of backend to url translation path, reads domain from settings value `BASE_URL` (or is `WEBAPP_URL` expected here?)
- Sets path to permalink surrounded by slashes
Also updates url and path for these objects (included in page/children response):
1. parent
2. available_languages (path was not present before)
Fixes: #928

Fix API page response format for url and path

---

.circleci/config.yml
.gitignore
Pipfile.lock
dev-tools/run.sh
package-lock.json
package.json
setup.py
src/backend/settings.py
src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/_raw.html
src/cms/templates/_tinymce_config.html
src/cms/templates/events/event_form.html
src/cms/templates/imprint/imprint_form.html
src/cms/templates/imprint/imprint_sbs.html
src/cms/templates/pages/page_form.html
src/cms/templates/pages/page_pdf.html
src/cms/templates/pages/page_sbs.html
src/cms/templates/pois/poi_form.html
webpack.config.js

Invalidates the browser cache by adding content hashes to output file names of webpack
- Sets webpack output file name to [name].[contenthash].js
- To keep only the latest file hash, the webpack output.clean option is used 
- To use output.clean it is necessary to switch from `webpack serve` to `webpack watch` (see [861](https://github.com/webpack/webpack-dev-middleware/issues/861))
- To include the renamed webpack output into djangos templates `django-webpack-loader` is used
Instead of `django-webpack-loader` we could also use [HTMLwebpackPlugin](https://webpack.js.org/guides/output-management/#setting-up-htmlwebpackpluginl) to include the webpack output files. but this approach seemed to have problems with djangos templates format (maybe I just used the wrong template loader, I'm not …

Adds contents hash to support browsers cache invalidation

---

dev-tools/run.sh

`compgen` does not exit with code 1 when no matches are found on all distros, therefore we should inspect the standard output rather than the exit code.
- Check whether output is empty instead of whether exit code is 1

Fix `compgen` usage in `run.sh`

---

src/cms/locale/de/LC_MESSAGES/django.po
src/cms/templates/pages/page_tree.html
src/cms/templates/pages/page_tree_node.html
src/cms/templatetags/page_filters.py
src/cms/templatetags/tree_filters.py
src/cms/views/pages/page_tree_view.py

This PR is to fix the problem that subpages are not shown when the filter is applied.
- Subpages are now shown too
- Pages are shown even when their root page and/or parent page is filterd out.
- 
Fixes: #934

Include subpages in filtered page results

---

.circleci/config.yml
src/backend/circleci_settings.py

Don't use the logfile or colored output on circleci
This might fix some problems with logging on CircleCI:
```
.....--- Logging error ---
Traceback (most recent call last):
File "/usr/local/lib/python3.7/logging/handlers.py", line 934, in emit
self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/logging/handlers.py", line 937, in emit
self._connect_unixsocket(self.address)
File …
```

Use simple logging in CircleCI

---

src/api/decorators.py

This pr fixes a bug where documentation for some functions of the feedback api was not generated.
- Fix the decorator `feedback_handler` to correctly wrap the decorated functions
Fixes: #595

Show missing api feedback documentation

---

src/cms/templates/events/event_list_row.html
src/cms/templates/pages/page_tree_node.html
src/cms/templates/pois/poi_list_row.html
src/cms/views/events/event_list_view.py
src/cms/views/pages/page_tree_view.py
src/cms/views/pois/poi_list_view.py
src/locale/de/LC_MESSAGES/django.po

This PR implements an external-link option for the page tree as well as the event and POI lists. 
- Implemented the link option as an addition to the Preview mode (pages only).
- Changed link icons in all cases from "eye" to "external link" to prevent ambiguity with the page tree view.
- Link icons are disabled, if the the page/event/POI is not published.
Fixes: #965

Implement links to webapp for page, event and POI lists

---

dev-tools/_functions.sh

This increases the portability and makes the coloured output work on more devices
- Use `\x1b` instead of `\e` as escape sequence in bash scripts
Fixes the color problems e.g. on mac os

Fix colored output in bash scripts

---

src/cms/views/settings/user_settings_view.py
src/locale/de/LC_MESSAGES/django.po

This fixes the redirect after a region user changed his email or password to make sure the menu sidebar shows the region menu instead of the network management area.
- Redirect to region user settings after form submission
Fixes: #997

Fix redirect to region user settings

---

src/cms/views/pages/page_actions.py
src/frontend/js/auto-file-download.ts

On some browsers, I noticed that the automatic download doesn't work - instead, the xliff file is directly opened as XML file in the browser.
- Use `download` link attribute
- Trigger click of link instead of setting `window.location.href`

Improve browser compatibility of automatic file download

---

src/cms/views/linkcheck/linkcheck.py
src/locale/de/LC_MESSAGES/django.po

At the moment, there is no access control for the broken link checker.
Since the links itself are publicly available via the API, the worst that can happen is that unauthorized users trigger a re-check of links or ignore/unignore broken links. Nonetheless, we should fix this asap.
- Only allow link checker page for logged in users
- Only allow link checker page for users of that region

Add missing access control to link checker

---

src/cms/urls.py
src/frontend/js/tree-drag-and-drop.ts

This PR solved the problem that drag and drop did was not working in the language tree.
- the related URL and variable name in TypeScript were fixed
Fixes: #996

Fix Drap&Drop in Language Tree

---

src/cms/fixtures/test_users.json
src/cms/templates/feedback/admin_feedback_list.html
src/cms/templates/feedback/region_feedback_list.html
src/cms/templates/pagination.html
src/cms/views/events/event_list_view.py
src/cms/views/feedback/admin_feedback_list_view.py
src/cms/views/feedback/region_feedback_list_view.py
src/cms/views/languages/language_list_view.py
src/cms/views/offer_templates/offer_template_list_view.py
src/cms/views/organizations/organization_list_view.py
src/cms/views/pois/poi_list_view.py
src/cms/views/push_notifications/push_notification_list_view.py
src/cms/views/regions/region_list_view.py
src/cms/views/roles/role_list_view.py
src/cms/views/users/region_user_list_view.py
src/cms/views/users/user_list_view.py
src/frontend/css/style.scss
src/frontend/index.ts
src/frontend/js/pagination/pagination.ts
src/locale/de/LC_MESSAGES/django.po

Make pagination chunk size configurable
- Pagination chunk size is send via query string like chunk index
- Switching between the chunk sizes via selected option dropdown
- I chose to place the html select tag on the same height like rest of the the pagination tags, because this pagination html document is already included on all necessary list views. If wished we can move the position, but this will need an additional template + include statements (to prevent to much duplication).
Fixes: #994

Make pagination chunk size configurable

---

CHANGELOG.md
Pipfile.lock
integreat_cms/cms/models/regions/region.py
integreat_cms/cms/views/regions/region_list_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
sphinx/conf.py
sphinx/documentation.rst

This pr removes some database queries related to regions.
Related issue: #943 
- For region list view: pass a list of regions to the paginator, not a query. This prevents an unnecessary `SELECT Count(*) ...` query. Is it worth doing this for every model list view?
- Use `select_related` on the `Region.default_language` property. this reduces the number of queries on every view by one for every region which has `Include administrative division into name` checked. It would be possible to go even further and include the prefix as part of the name so that no additional queries are required at all, but the situation where the root language of a region gets changed would have to be handled correctly.

Improve region performance

---

integreat_cms/core/settings.py

This pr fixes a bug where non-admin users were not granted permission to edit pages, even if they were allowed to.
It looks like the bug might not actually be related to a django-rules issue. Instead, our [rules.py](https://github.com/Integreat/integreat-cms/blob/develop/integreat_cms/cms/rules.py) did not get loaded, which lead to the custom permission rules never being registered. This might be caused by the recent refactoring of the project structure.
- Tell the rules app to autodiscover rules config files
Fixes: #1028

Fix page permissions

---

integreat_cms/static/src/js/events/event-query-pois.ts
integreat_cms/static/src/js/search-query.ts

After the update of our JS dependencies, we can no longer use false for checking the existence of the timeout function.
`[webpack]       TS2322: Type 'Timeout' is not assignable to type 'number | false'.
[webpack]   Type 'Timeout' is not assignable to type 'false'.
[webpack] 
[webpack] webpack compiled with 1 error
`
- Change the Timeout type to null and change check accordingly.
- Use window.setTimeout() to distinguish from further Timeout functions.

Fix timeout bug by using the specific window method

---

integreat_cms/cms/fixtures/roles.json
integreat_cms/cms/models/events/event_translation.py
integreat_cms/cms/models/pages/imprint_page_translation.py
integreat_cms/cms/models/pages/page_translation.py
integreat_cms/cms/models/pois/poi_translation.py
integreat_cms/cms/templates/imprint/imprint_revisions.html
integreat_cms/cms/templates/pages/_page_xliff_import_diff.html
integreat_cms/cms/templates/pages/page_revisions.html
integreat_cms/locale/de/LC_MESSAGES/django.po

Handle empty creator fields correctly 
- Fix typo in roles fixture
- Handle empty `creator` fields correctly 
- Show 'deleted user' instead of empty string in revision view
- Allow duplication of translations with empty `creator` fields
Fixes: #1031

Handle empty `creator` fields correctly 

---

.circleci/config.yml

The version is now contained in setup.cfg instead of setup.py, so we have to persist a different file after the version has been bumped. This should have been included in 36618d5fac30e0803c3da91d7d3cf4221c531517, but unfortunately I missed it.
- Persist `setup.cfg` to workspace after CircleCI version bump

Persist setup.cfg to workspace after CircleCI version bump

---

CHANGELOG.md
integreat_cms/cms/templates/chat/_chat_messages.html
integreat_cms/cms/templates/dashboard/admin_dashboard.html
integreat_cms/cms/templates/dashboard/dashboard.html
integreat_cms/cms/templates/generic_confirmation_dialog.html
integreat_cms/cms/templates/media/media_list.html
integreat_cms/cms/templates/media/media_list_admin.html
integreat_cms/static/src/css/style.scss
integreat_cms/static/src/js/chat/delete-chat-message.ts
integreat_cms/static/src/js/chat/send-chat-message.ts
integreat_cms/static/src/js/confirmation-popups.ts
integreat_cms/static/src/js/media-management/component/directory-content.tsx
integreat_cms/static/src/js/media-management/component/directory-entry.tsx
integreat_cms/static/src/js/media-management/component/edit-directory-sidebar.tsx
integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx
integreat_cms/static/src/js/media-management/component/file-entry.tsx
integreat_cms/static/src/js/media-management/library.tsx

This pr allows users to make changes to the content of the media library in selection mode.
- Get rid of global confirmation popup mode (ajax / forms) and set the mode per button
- Change ajax confirmation popups so that independent different ajax popups can be shown on the same page
- Enable full media library functionality by removing most `selectionMode` checks
Fixes: #968

Enable full media library functionality in selection mode

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/events/event_list_archived.html
integreat_cms/cms/templates/events/event_list_archived_row.html
integreat_cms/cms/templates/events/event_list_row.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pages/page_tree_archived.html
integreat_cms/cms/templates/pages/page_tree_archived_node.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/templates/pois/poi_list_row.html
integreat_cms/cms/templates/push_notifications/push_notification_list.html
integreat_cms/cms/templates/push_notifications/push_notification_list_row.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/css/style.scss

Sync language grid width for table header and body
The problem is that despite both Element nodes (a-html-tags) in the header and in body of the the table have the same width of 18.67px, as inline-block elements they are followed whitespace Text nodes with different widths (4,08331px and 3,36664px)
So I updated the Elements node width so that both header and body have in total the exact same width of 22,0333px
Fixes: #1029

Sync language grid width for table header and body

---

CHANGELOG.md
integreat_cms/cms/forms/media/replace_media_file_form.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This pr fixes a crash when a user attempts to replace a file in the media library that has no thumbnail.
- Check if the file has a valid thumbnail before accessing its path
Fixes: #1062

Fix crash when replacing a file without thumbnail

---

.circleci/config.yml
MANIFEST.in
dev-tools/fix_dependencies.sh
example-configs/integreat-cms.ini
integreat_cms/core/settings.py
integreat_cms/core/wsgi.py
integreat_cms/integreat-cms-cli
package.json

During my tests with the integreat cms pypi package, I noticed a few small problems:
- If the config file contains a `%`, configparser tries to do a string interpolation
- Some tailwind classes don't seem to be correctly included in the webpack build. This seems to be an issue of NodeJS v17.
- The version in the `__init__.py` was not contained in the final python package because a source path was incorrect
- The file based cache resides inside the virtual environment
- Do not interpolate variables with configparser
- Use NodeJS v16 in CircleCI again
- Fix source directory in CircleCI config
- Add option to configure file cache location

Improve production setup

---

.circleci/scripts/get_access_token.py

The id changed due to the migration of the repository from Integreat to digitalfabrik organization.
- Fix deliverino installation id
This should resolve the failing bump-version job on the main branch

Fix deliverino installation id

---

example-configs/integreat-cms.ini
integreat_cms/core/settings.py

On the dev system, I noticed that sending emails doesn't work because of an `SMTPNotSupportedError`.
Apparently, `EMAIL_USE_TLS` has to be explicitly activated when trying to send emails via port `587`.
- Use TLS for SMTP connection per default
- Allow secure connection type configuration via environment & config file
- Add new settings to example config

Use TLS for SMTP connection per default

---

.circleci/config.yml

In our [latest GitHub release](https://github.com/digitalfabrik/integreat-cms/releases/tag/2021.12.0-beta), the comparison with the previous tag didn't work as expected. Instead of 
> Compare changes: 2021.11.0-beta → 2021.12.0-beta
it initially showed:
> Compare changes: 2021.11.0-betanexport → 2021.12.0-beta
So presumably, passing the environment variables in CircleCI didn't work correctly.
- Write two separate export statements instead of one

Fix tag in comparison with previous release

---

CHANGELOG.md
integreat_cms/api/v3/pages.py

Fix filtering of pages in the APIv3 single page endpoint with the `url` parameter.
Get distinct page(s) for a language and translation slug. Raise a `Http404` if the result is not exactly (less or more than) one page.
Fixes: #1065

API: change single page filtering

---

dev-tools/install.sh

If the directories `.venv`, `node_modules` and `integreat_cms/static/dist` do not exist and a clean installation is executed, the script aborts because grep returns a non-zero exit code when no match is found.
- Allow the grep command after the `--clean` install to fail

Fix install script when clean install cannot remove anything

---

CHANGELOG.md
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templates/pois/poi_list_archived_row.html
integreat_cms/cms/templates/pois/poi_list_row.html
integreat_cms/locale/de/LC_MESSAGES/django.po

Before this pr, the server crashed when trying to delete a poi that is referenced by an event. 
This pr disables deleting pois that are still used by at least one event
Co-authored-by: philip popien <membralala@users.noreply.github.com>
Co-authored-by: MizukiTemma <MizukiTemma@users.noreply.github.com>

Fix a crash when trying to delete a poi

---

setup.cfg

We don't have any reason to think python3.8 wouldn't work, only python3.7 and below are guaranteed to fail due to the requirement of webauthn
- Allow pip package to be installed with python3.8

Allow pip package to be installed with python3.8

---

integreat_cms/cms/templates/users/region/user.html

This error appeared when a region user had more than one region and their user form was opened. The rendering of the deletion-confirmation-popup failed because in commit b4ca14ee3f3b335f7a7f40b0c5fb357016ca8279 I forgot to replace this occurrence of 'region'.
- Fix `VariableDoesNotExist` error in region user form
I did not open an issue for it

Fix `VariableDoesNotExist` error in region user form

---

integreat_cms/cms/views/offer_templates/offer_template_view.py

This PR fixes a tiny bug, where a wrong type was passed, when creating a new offer template as admin
- Change cleaned_post_data from ```dict``` to ```str```

Fix bug when creating a new offer template

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/events/event_list_row.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/templates/pois/poi_list_row.html
integreat_cms/cms/urls.py
integreat_cms/cms/views/events/__init__.py
integreat_cms/cms/views/events/event_actions.py
integreat_cms/cms/views/pois/__init__.py
integreat_cms/cms/views/pois/poi_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/bulk-actions.ts

Add checkboxes to pois and events, add option to auto translate
Add the dropdown from posts to events and pois using the existing bulk action template. 
Fixes: #1103
This is part of the project for Johannes' final exam.

Add bulk actions to POIs and events 

---

integreat_cms/cms/templates/_base.html
integreat_cms/core/context_processors.py
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po

When we have different instances of CMS servers deployed (production, cms-test, cms-dev), it's probably handy to see the installed version of the cms at a glance, especially for bug reports etc.
I hope the placement at the bottom of the navigation bar is not too obtrusive from a UI/UX perspective...
- Show version at bottom navigation sidebar

Show package version at bottom navigation sidebar

---

integreat_cms/cms/utils/matomo_api_manager.py
integreat_cms/locale/de/LC_MESSAGES/django.po

When access to Matomo is denied, a mail with the error message is dispatched. But due to missing region name/id it is not possible to fix the prohblem.
Add the region name to the error message.

Add region name to MatomoException token message

---

integreat_cms/core/settings.py

Since we received a lot of error messages lately, I suggest to turn off this alert channel...
In the short term, we can have a look at our server log files, in the long term we can think about how we want to monitor for errors on Grafana etc...

Do not send error emails to admins

---

integreat_cms/cms/views/utils/search_content_ajax.py

Just a small permission check problem which was caused by the change from the default Django user model to our own...

Fix permission check in user search

---

integreat_cms/cms/utils/matomo_api_manager.py
integreat_cms/locale/de/LC_MESSAGES/django.po

For legacy reasons, our API tokens don't have consistent permissions levels.
Thus, we can just check for 'at least view access' to determine the correct matomo id.
- Use `getSitesIdWithAtLeastViewAccess` instead of `getSitesIdWithAdminAccess` for Matomo id check

Fix matomo API token check

---

integreat_cms/cms/templates/users/user_form.html
integreat_cms/cms/views/users/user_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR should fix an issue, where a user without superuser permissions was able to change his/her superuser state. 
- Change the user form template, so that the superuser option is hidden, when the user isn't a superuser him/herself
- Change the user form view, so that a server-side error message is rendered in the same case
- Change 'superuser' translations from 'Superadmin' to 'Admin'
Fixes:  #1123

Fix superuser permissions mechanic

---

integreat_cms/cms/models/pages/page.py
integreat_cms/static/src/js/search-query.ts

This pr fixes a few problems I noticed with the search input bar.
- Fix the `page.implicitly_archived` method returning a list instead of a boolean, causing the search to return no results
- ~When filtering for pages in `page_tree_view` create a query instead of a list so that the later call to `pages.cache_tree()` works~ I just noticed that this is fixed by Timo's previous pr #1136
- Don't treat a click on the scrollbar of the search suggestions as simultaneously clicking all suggestions

Fix search bar

---

CHANGELOG.md
integreat_cms/cms/constants/translation_status.py
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/models/regions/region.py
integreat_cms/cms/views/analytics/translation_coverage_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This pr reduces the amount of database queries required to load the translation coverage view to a constant number.
Related issue: #943 
- Use the new page query api
- Don't show languages in the outdated translation word count table if no translation for that language is outdated

Reduce queries for translation coverage to a constant amount

---

integreat_cms/api/v3/pages.py
integreat_cms/cms/forms/pages/page_form.py
integreat_cms/cms/models/abstract_tree_node.py
integreat_cms/cms/models/pages/page.py
integreat_cms/cms/templates/_search_input.html
integreat_cms/cms/templates/language_tree/language_tree_node.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pages/page_tree_archived.html
integreat_cms/cms/templates/pages/page_tree_archived_node.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/views/analytics/translation_coverage_view.py
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/css/style.scss
integreat_cms/static/src/js/pages/collapse-subpages.ts
integreat_cms/static/src/js/search-query.ts

Fixes the handling of page filters (by search query and by status filter)
- Make the page filters work with the cached tree structure
Caveats:
I'm still not sure how the hierarchy should be handled when filtering the tree. At the moment, I just disabled expanding/collapsing subpages, because it would require quite some computation to get all subpages that are in the same filtered set...
Do you think it would make more sense to completely hide the "hierarchy" column when filters are applied? Since it's not a real tree structure in this case anyway...
Fixes: #1128

Fix page filters

---

CHANGELOG.md
integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/views/utils/search_content_ajax.py

This pr improves the performance when performing a content search.
In general, the search was fairly optimized and the biggest changes could be made to pages.
Related issue: #943
- Prefetch some attributes for pages, events and pois
- Make use of cached data when searching pages

Improve performance of content searches

---

CHANGELOG.md
integreat_cms/cms/templates/pages/_page_tree_children.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pages/page_tree_archived.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/urls.py
integreat_cms/cms/views/pages/__init__.py
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/cms/views/pages/partial_page_tree_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/confirmation-popups.ts
integreat_cms/static/src/js/pages/collapse-subpages.ts
integreat_cms/static/src/js/tree-drag-and-drop.ts

Fetch page tree children by ajax request
- Page tree starts with root nodes only
- On expanding new page children get queried and added to the DOM
Fixes: #1101

Page tree ajax request to fetch children

---

CHANGELOG.md
integreat_cms/static/src/js/bulk-actions.ts
integreat_cms/static/src/js/pages/collapse-subpages.ts

Activate bulk action button on selecting sub pages
- After selecting a sub page the bulk action button is enabled
- Clicking on "Select all checkboxes" also toggles sub page checkboxes
Fixes: #1165

Add sub page event listeners for bulk action button

---

integreat_cms/cms/forms/pages/page_form.py

This PR should enable the option to embed live content from a site which belongs to the currently selected region. 
- Remove an initial query, that filters the current region from the 'mirrored_page_region' 
Fixes: #1176

Allow user to embed live content from current region

---

CHANGELOG.md
integreat_cms/cms/models/pages/page_translation.py
integreat_cms/static/src/js/tree-drag-and-drop.ts

This pr hides the empty for a page if the page has no subpages.
Generally, this tag should be hidden if the page has no publicly visible subpages, however this is not implemented as part of this pr.
This work should be done together with #1158.
Additionally, this pr fixes a crash due to an invalid url when moving a page.
Partially solves: #1175 
- Check if the page is a leaf before adding the empty tag

Don't show empty tag if the page has no subpages

---

integreat_cms/api/decorators.py
integreat_cms/api/v3/pages.py

Track single page and pages API endpoint requests with Matomo.
Add a decorator to allow tracking API endpoints. The decorator spawns a thread which executes the HTTP request to Matomo. This improves the performance of the CMS API, as the request does not have to wait for the response from Matomo.
Fixes: #1196 
This mostly works, however the `cip` parameter (https://developer.matomo.org/api-reference/tracking-api) breaks the request.

Track API requests with Matomo

---

integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/locale/de/LC_MESSAGES/django.po

Only show xliff export option for expert users

Only show xliff export option for expert users

---

integreat_cms/api/urls.py

Route the PDF creation endpoint to the Integreat APIv3 PDF creation URL.
Add a URL pattern that routes the view `pdf_export` to `/REGION/LAN/wp-json/ig-mpdf/v1/pdf`
Fixes: #1209

Support legacy PDF API, fixes #1209

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/templates/imprint/imprint_sbs.html
integreat_cms/cms/templates/language_tree/language_tree_node_form.html
integreat_cms/cms/templates/languages/language_form.html
integreat_cms/cms/templates/offertemplates/offertemplate_form.html
integreat_cms/cms/templates/organizations/organization_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pages/page_sbs.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templates/push_notifications/push_notification_form.html
integreat_cms/cms/templates/regions/region_form.html
integreat_cms/cms/templates/roles/role_form.html
integreat_cms/cms/templates/users/region_user_form.html
integreat_cms/cms/templates/users/user_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/unsaved-warning.ts

Browser warning is added so users will be warned when they are leaving a content editing page wihout saving or publishing.
- Input and click on the form section will be detected.
- If the user leaves the edit page clicking on "save as Draft", "Save as review" or "Publish"/"Update", nothing new happens. A warning will be shown before leaving otherwise. 
Fixes: #988

Add browser warning

---

CHANGELOG.md
integreat_cms/static/src/js/forms/tinymce-init.ts

Use the canonical behavior for Enter and Shift+Enter in TinyMCE.
Set `forced_root_block` to `true`.
Fixes: #1215

Use canonical Shift+Enter behavior, fixes #1215

---

CHANGELOG.md
integreat_cms/cms/views/language_tree/language_tree_view.py

Disable pagination on language tree
- Set `paginate_by` to `None`

Disable pagination on language tree

---

CHANGELOG.md
integreat_cms/api/v3/imprint.py

This PR removes the icon field from the api response as our imprint model doesn't have it anymore.

Remove icon from imprint api response

---

CHANGELOG.md
integreat_cms/api/v3/pages.py

Do not use cached properties.
Fixes #1226

API: do not use cached properties, fixes #1226

---

CHANGELOG.md
integreat_cms/cms/forms/language_tree/language_tree_node_form.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Flush the Cacheops Cache when modifying the language tree of a region.
I'm not really sure if this actually fixes the issue at hand. This probably needs some thorough testing. If nobody sees a reason why this should not help, then I suggest to deploy to the test server and invest some time into clicking around.
When moving a language tree node, flush all related objects in the region from the cache.
Fixes: #1131
Fixes: #1236

Flush Cacheops when modifying laguage tree nodes

---

CHANGELOG.md
example-configs/integreat-cms.ini
integreat_cms/api/decorators.py
integreat_cms/core/settings.py

Add an option to disable tracking of API requests. This is necessary when we want to connect to a Matomo instance in general but do not want to track API requests.
Add a `MATOMO_TRACKING` setting.
Fixes: #1242

Add option to activate Matomo tracking, fixes #1242

---

CHANGELOG.md
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pages/page_revisions.html
integreat_cms/cms/templatetags/content_filters.py
integreat_cms/cms/views/analytics/translation_coverage_view.py
integreat_cms/cms/views/imprint/imprint_actions.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/cms/views/pages/partial_page_tree_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/xliff/utils.py

Ignore minor edits in target language translations
- Add helper methods to prefetch the most recent public versions that are not minor edits
- Refactor calculation of translation status
- Update minor edit help text in forms
Fixes: #1197

Ignore minor edits in target language translations

---

integreat_cms/api/v3/events.py
integreat_cms/api/v3/pages.py
integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/forms/custom_tree_node_form.py
integreat_cms/cms/forms/language_tree/language_tree_node_form.py
integreat_cms/cms/forms/pages/page_form.py
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/models/abstract_tree_node.py
integreat_cms/cms/models/pages/page.py
integreat_cms/cms/models/pages/page_translation.py
integreat_cms/cms/models/push_notifications/push_notification.py
integreat_cms/cms/templates/language_tree/language_tree_node_form.html
integreat_cms/cms/views/analytics/translation_coverage_view.py
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/cms/views/pages/partial_page_tree_view.py
integreat_cms/cms/views/pois/poi_list_view.py
integreat_cms/cms/views/push_notifications/push_notification_list_view.py
integreat_cms/cms/views/utils/search_content_ajax.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/views/view_config.py

The fix in bbe3e55e2a57179ce6c31de5efa44ecdb7b5e68a did not work correctly, so a few more substantial changes were required.
- Add test for creating language tree nodes
- Fix creating language tree nodes
- coerce ref_node field to int was not possible because the reference to no node cannot be expressed by an integer
- Use strings for values of ref_node fields where possible
- Fix parent field after `move()` and not before `save()` because it caused problems for language tree nodes
- Provide fallback translation if default translation doesn't exist
- Under normal circumstances, this should not happen. But when the default language is changed into a language that does not have a translation for each page, this might lead to problems.
- Show content list views only for active languages
- Do …

Fix creating language tree nodes

---

CHANGELOG.md
integreat_cms/api/v3/regions.py
tests/api/expected-outputs/regions.json
tests/api/expected-outputs/regions_live.json

The attribute that indicates activated push notifications in the regions/sites endpoint should be `push_notifications`.
Change the attribute name `push-notifications` to `push_notifications` in the regions API endpoint.

Fix push notifications attribute name in API

---

CHANGELOG.md
integreat_cms/api/v3/push_notifications.py
tests/api/expected-outputs/nurnberg_de_fcm.json
tests/api/expected-outputs/nurnberg_en_fcm.json

The JSON format of the fcm API endpoint is not in the format the app expects it to be.
Each message needs to have the following attributes: `id`, `message`, `timestamp`, `title`.

Fix fcm endpoint JSON format

---

CHANGELOG.md
integreat_cms/api/v3/push_notifications.py
tests/api/expected-outputs/nurnberg_de_fcm.json
tests/api/expected-outputs/nurnberg_en_fcm.json

* [ [#1269](https://github.com/digitalfabrik/integreat-cms/issues/1269) ] Fix fcm endpoint JSON format

Deploy fixed fcm API endpoint

---

.github/ISSUE_TEMPLATE/bug-report.md

I find myself typing a lot of spoilers for bug tracebacks, so I'd benefit if it was included in the template.
- Add GitHub spoiler markdown to issue template

Add traceback spoiler to bug report template

---

integreat_cms/cms/templates/push_notifications/push_notification_form.html
integreat_cms/cms/views/push_notifications/push_notification_form_view.py

Prevent sending push notifications (again) that have a `sent_date`.
- Hide the Send button if a sent_date exists
- When submitting the form do not send the news if a sent_date exists
Fixes: #1281

Do not send a push notification twice, fixes #1281

---

CHANGELOG.md
Pipfile.lock

Since the bug in our dependency https://github.com/mbarkhau/bumpver has been resolved, this update should fix our develop CI workflow and allow our dev packages to be bumped beyond [2022.3.10a0](https://test.pypi.org/project/integreat-cms/2022.3.10a0/).
Additionally, this updates https://github.com/xhtml2pdf/xhtml2pdf which should resolve #1108.

Update bumpver, xhtml2pdf & other pip dependencies

---

CHANGELOG.md
integreat_cms/cms/forms/pages/page_filter_form.py
integreat_cms/cms/templates/pages/_page_filter_form.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pages/page_tree_archived.html
integreat_cms/cms/templates/pages/page_tree_archived_node.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/test_page_filters.py

Fix page tree after resetting filters
- Refactor page filter form
- Add page filter tests
Fixes: #1296

Fix page filter form

---

CHANGELOG.md
integreat_cms/cms/apps.py
integreat_cms/cms/signals/feedback_signals.py
integreat_cms/cms/views/feedback/admin_feedback_actions.py
integreat_cms/cms/views/feedback/region_feedback_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Fix feedback cache invalidation
django-cacheops does not support multi-table inheritance (https://github.com/Suor/django-cacheops/issues/31)
The suggested workaround is to use signal handlers to invalidate the cache manually (https://github.com/Suor/django-cacheops/issues/31#issuecomment-673564324), so signal handlers are used to invalidate the cache on feedback creation and deletion.
But marking feedback as read/unread uses the query set update method and does not trigger a save signal, so in case of feedback updates cache invalidation is performed in the view instead.
Fixes: #1282

Fix feedback cache invalidation

---

CHANGELOG.md
integreat_cms/cms/models/abstract_base_model.py
integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/events/event_list_archived.html
integreat_cms/cms/templates/events/event_list_archived_row.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pages/page_tree_archived.html
integreat_cms/cms/templates/pages/page_tree_archived_node.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/templates/pois/poi_list_archived.html
integreat_cms/cms/templates/pois/poi_list_archived_row.html
integreat_cms/cms/templates/pois/poi_list_row.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/bulk_action_views.py
integreat_cms/cms/views/events/__init__.py
integreat_cms/cms/views/events/event_actions.py
integreat_cms/cms/views/pages/__init__.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pages/page_bulk_actions.py
integreat_cms/cms/views/pois/__init__.py
integreat_cms/cms/views/pois/poi_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/views/view_config.py

Add bulk actions for archiving/restoring pages, events and locations
- Generalize bulk action views
- Provide `BulkActionView` as base for all bulk action views
- Add `BulkAutoTranslateView` as model-agnostic translation bulk action
- Convert PDF and XLIFF export of pages to the new class based view
- Add bulk actions for archiving/restoring
- Add `BulkArchiveView` and `BulkRestoreView` as model-agnostic bulk action views to archive/restore
multiple objects
- Add bulk action form to all archived lists
- Add tests for bulk archive/restore
I also updated the pip dependencies because I got a [weird CircleCI error](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/4017/workflows/ea6b2832-b502-4a8e-aaff-05b21e355487) and I assume an outdated cache is responsible.
Fixes: …

Add bulk actions for archiving/restoring pages, events and locations

---

CHANGELOG.md
integreat_cms/api/v3/imprint.py

Even though our region model has no `impint` attribute, the hasattr() method return true. Therefore, I replaced it with a None check.
Fixes: #1319

Use None-Check instead of hasattr() in imprint api

---

integreat_cms/cms/models/feedback/feedback.py
integreat_cms/cms/views/feedback/admin_feedback_actions.py
integreat_cms/cms/views/feedback/region_feedback_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
sphinx/conf.py

This pr implements a fix for deleting multiple feedback items of different types, which does not work because of a bug in django-polymorphic ([229](https://github.com/django-polymorphic/django-polymorphic/issues/229)).
The fix implements the recommended workaround for this bug, which is to only retrieve the base class before deletion.
Fixes: #1290

Fix deleting polymorphic feedback

---

CHANGELOG.md
integreat_cms/cms/forms/custom_content_model_form.py
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/models/pages/imprint_page.py
integreat_cms/cms/templates/_content_edit_lock.html
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/generic_confirmation_dialog.html
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templatetags/text_filters.py
integreat_cms/cms/urls/protected.py
integreat_cms/cms/utils/content_edit_lock.py
integreat_cms/cms/views/events/event_form_view.py
integreat_cms/cms/views/imprint/imprint_form_view.py
integreat_cms/cms/views/mixins.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/cms/views/utils/__init__.py
integreat_cms/cms/views/utils/content_edit_lock.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/confirmation-popups.ts
integreat_cms/static/src/js/content-edit-lock.ts
integreat_cms/static/src/js/forms/autosave.ts
integreat_cms/static/src/js/forms/tinymce-init.ts
integreat_cms/static/src/js/unsaved-warning.ts

This pr implements support for locking a content object so it can be edited by only a single user.
When a user tries to edit some content that is already being edited by another user, a popup will show up and ask the user to go back or to take over.
- Track which objects are locked using django's caching system
- Don't allow edits for content forms if the editor does not have the exlusive lock on the content
- Send a "heartbeat" every few seconds to extend the lock and check if the page is still locked for the user
- Create an auto-save if editing permission is lost (version history is not implemented right now for pois and events though)
- Show a popup notification if the user does not have editing permission
Fixes: #1177

Implement lock for content editing

---

integreat_cms/cms/views/language_tree/language_tree_actions.py
integreat_cms/cms/views/language_tree/language_tree_node_form_view.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Apply changes to MPTT tree structures in SQL tables with transactions to prevent race conditions with other requests.
Use the `@transaction.atomic` decorator for all views that update MPTT trees.
Fixes: #1320 (maybe)

Use transactions for tree manipulations

---

CHANGELOG.md
Pipfile.lock
integreat_cms/cms/templates/pages/page_pdf.html
integreat_cms/cms/utils/pdf_utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po

After the PDF lib released their new version, we can now fix the remaining problems at PDF export.
- Fix resolving path to media files https://xhtml2pdf.readthedocs.io/en/latest/usage.html#using-xhtml2pdf-in-django
- Fix region icon and region full name rendering
- Fix loading fonts from static folder `assets`. This is important, because Arabic letters need a specific font. 
Fixes: #1327

Fix page PDF export

---

integreat_cms/static/src/editor.ts
integreat_cms/static/src/index.ts

This pr fixes a bug where the tinymce editor was not working correctly.
Basically, the bug was introduced by 11f5d9a8e824d6397b9d9b0759a96be3fe7334d6. The problem was that we have multiple entry points in the `webpack.config.ts` file, such that the tinymce editor only gets imported when needed. Since this commit the `content-edit-lock.ts` file gets loaded in main, which in turn imports `tinymce-init.ts`, which causes the tinymce editor to be loaded twice: once via `main` and once via `editor`. 
The fix is quite simple, just defer loading `content-edit-lock.ts` to the editor entry point
Fixes #1329, Fixes #1335

Fix editor content not getting submitted

---

CHANGELOG.md
integreat_cms/cms/models/pages/page.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Fix cache invalidation in children endpoint
When a complete page tree is moved, it's tree_id is changed, so it is necessary to clear the cache for the page translation - page relation.
Fixes: #1226

Fix cache invalidation after page tree move

---

CHANGELOG.md
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pages/page_tree_archived_node.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Fix error when deleting page which was embedded as live content
- Disable possibility to delete a page which was referenced in another page as live content
Fixes: #1325

Fix error when deleting page which was embedded as live content

---

integreat_cms/api/v3/pages.py

The cache in the parents endpoint was disabled in #1230, but since it seems we solved our caching problems, we can enable it again.
- Use `get_cached_ancestors()` instead of `get_ancestors()` in the parents API endpoint
Fixes: #1234

Enable cache in parents endpoint again

---

CHANGELOG.md
integreat_cms/cms/utils/filter_links.py

This PR is to make the broken link checker list not only links in the default language of the region but also links in the other languages.
- as suggested, `.distinct("page")` is replaced with `.distinct("page", "language")`.
- the same change is applied for POI and event.
Fixes: #1328

Modify broken link checker to list links in not-default languages

---

Pipfile.lock
integreat_cms/integreat-cms-cli
package-lock.json

This PR updates our JS and python packages to their newest version. 
We should keep in mind that our setup.cfg will be deprecated by some point and we should consider switching to a pyproject.toml setup (see Issue #1362 ).

Update packages and fix pylint issues in the ini file

---

CHANGELOG.md
integreat_cms/cms/forms/events/recurrence_rule_form.py

Allow events to be monthly recurring on mondays
- Check for `None` instead of implicitly casting the value into a boolean (which doesn't work because monday is defined as the integer `0` which evaluates to `False`...
Fixes: #1366

Allow events to be monthly recurring on mondays

---

.circleci/config.yml

Our release channel on Mattermost will be renamed to also host the release notifications for Lunes.
- Use `~releases` instead of `~integreat-releases` channel
- Use Integreat logo as profile picture instead of emoji in title
- Only send notification if publish-package job succeeded

Rename Mattermost channel of release notifications

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/events/event_list_row.html
integreat_cms/cms/templates/feedback/admin_feedback_list.html
integreat_cms/cms/templates/feedback/region_feedback_list.html
integreat_cms/cms/templates/linkcheck/link_list_row.html
integreat_cms/cms/templates/linkcheck/links_by_filter.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/templates/pois/poi_list_row.html
integreat_cms/cms/templates/push_notifications/push_notification_list.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/bulk-actions.ts
integreat_cms/static/src/js/checkbox-count.ts
integreat_cms/static/src/js/pages/fetch-subpages.ts

This adds a counter of the selected items to all lists and trees with checkboxes.
- Add defining data attributes to all checkboxes
- Add selection counter beneath the lists and trees
- Add a custom change event to the page tree for correct handling of AJAX fetching of the subpages.
- Apply formatting to the django templates
- Fix some spelling issues
Fixes: #1046

Add selection counter to trees and lists

---

CHANGELOG.md
integreat_cms/cms/urls/protected.py
integreat_cms/cms/utils/slug_utils.py

The slug path converter only matches strings consisting of ASCII letters or numbers, plus the hyphen and underscore characters.
The default str path converter matches any non-empty string, excluding the path separator, '/'.
- Use str path converter for unicode slugs
Fixes: #1380

Use str path converter for unicode slugs

---

CHANGELOG.md
integreat_cms/cms/utils/pdf_utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po

(Hopefully) fix legacy media urls in PDF export.
Since the directory structure of the media export is still in progress, we might need to adapt this slightly in the future, but I hope this already fixes most problems.
- Convert image urls to absolute paths on allowed hosts
- Convert the legacy url pattern `/region-slug/wp-content/uploads/` to the new path `/media/`
Fixes (partially): #1350

Fix legacy media urls in PDF export

---

.github/workflows/dependency-review.yml

Dependency review apparently does not support the push event and just works on pull requests...

Do not run dependency review on push event

---

integreat_cms/cms/migrations/0022_rename_media_directories.py

I noticed that with my latest migration, local tests do not work anymore if the global media directory already exists and is not empty.
I forgot that the migrations are executed every time for the tests, even when the data migration on the hard drive is already completed.
So I fixed it by not explicitly raising the exception in this case - if problems on the production migration arise, there will still be an exception, just not as pretty anymore.
- Do not raise exception in migration if global media directory exists and is not empty

Do not raise exception in migration if global media directory is not empty

---

CHANGELOG.md
integreat_cms/cms/views/language_tree/language_tree_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This change flushes all content models after removing a LanguageTreeNode. It seems the problem described in #1403 only exists for page translations and no other content models, but I added them to be safe in the future.
One caveat though: Initially I tried to flush the PageTranslation objects which seemed to make more sense to me but that did not help. I'm not 100% sure why this fixes the issue. https://github.com/Suor/django-cacheops/blob/master/README.rst does not really explain how related objects are handled.
Fixes #1403

Invalidate translations when removing LanguageTreeNode, fixes #1403

---

integreat_cms/static/src/js/media-management/component/file-entry.tsx

I noticed that selected media library items no longer have the blue border and fixed that by setting the white border only for inactive elements.
- Fix border of selected media library items

Fix border of selected media library item

---

CHANGELOG.md
integreat_cms/api/v3/pages.py

Apply the slugify function on all API page endpoint slugs. This should make all calls to children endpoints compatible with old WordPress slugs. This should do no harm (except of some compute time), as we only have slugs in our database that were cleaned by the slugify function.
Use the [slugify](https://docs.djangoproject.com/en/4.0/ref/utils/#django.utils.text.slugify) function to clean page translation slugs in API requests.
Fixes: #1401

API: slugify page slugs, fixes #1401

---

CHANGELOG.md
integreat_cms/cms/views/media/media_context_mixin.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/media-management/component/upload-file.tsx
integreat_cms/static/src/js/media-management/library.tsx
package-lock.json
package.json

This pr substitutes our current file upload form with a drag and drop area. This also enables to upload multiple files due through an internal queue.
- Add Dropzone library
- Use it in the media library
Fixes: #1292

Add drag and drop for media file upload and enable multiple files

---

integreat_cms/cms/models/feedback/map_feedback.py
integreat_cms/cms/templates/_base.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/locale/de/LC_MESSAGES/django.po

This pr renames the 'locations on map' view to 'locations', to avoid confusion.
Fixes: #1457

Rename 'locations on map' to 'locations'

---

CHANGELOG.md
integreat_cms/static/src/js/forms/autosave.ts
integreat_cms/static/src/js/forms/tinymce-init.ts
integreat_cms/static/src/js/unsaved-warning.ts

This pr fixes a bug where no autosave warning was shown after editing the body of a page.
The bug is caused by tinymce not (anymore?) bubbling up the input event, which is used by the autosave mechanism to determine when to show the warning.
Additionally this pr fixes a related bug that caused `unsaved-warnings.ts` to be loaded twice.
- Manually create an input event when the editor state changes to 'dirty'
- Use a custom event to notify the unsaved-changes script that an autosave occrured
Fixes: #1461

show unsaved warning when only changing tinymce editor

---

CHANGELOG.md
integreat_cms/cms/forms/pages/page_form.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This pr hides archived pages in the page form in the parent page selection, the page order selection, and the mirrored page selection.
Additionally, the page order selection should update correctly now when selecting '----------' as parent page after selecting something else as parent page.
- Add filters to exclude archived pages
Fixes: #1283

Hide archived pages in various selections

---

CHANGELOG.md
integreat_cms/api/v3/offers.py
tests/api/api_config.py
tests/api/expected-outputs/augsburg-offers.json

The web app expects a null value instead of an empty dict in the offers API for the `post` attribute.
Convert the empty dict to null when delivering the information via API.

Adapt offers API to web app

---

CHANGELOG.md
integreat_cms/xliff/xliff1_serializer.py

Fix error when importing legacy XLIFF files from WordPress
Fixes: #1476

Fix error when importing legacy XLIFF files from WordPress

---

CHANGELOG.md
integreat_cms/cms/forms/pages/page_form.py
tests/cms/views/view_config.py

Fix bug where page with archived sibling cannot be saved.
This should only make the page form a bit slower, but as a quick fix I think it's sufficient.
- Allow archived pages as ref nodes
Fixes: #1478

Fix bug where page with archived sibling cannot be saved

---

CHANGELOG.md
integreat_cms/static/src/js/forms/tinymce-init.ts

This pr removes all formatting that gets applied when pasting into the tinymce editor.
Pasting links should still work, since the editor automatically converts text that looks like a link into a link.
Fixes: #1501

Instruct tinymce to paste as text

---

CHANGELOG.md
integreat_cms/cms/templates/imprint/imprint_sbs.html
integreat_cms/cms/templates/pages/page_sbs.html
integreat_cms/cms/views/imprint/imprint_sbs_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR fixes the text on the button in side-by-side view so that it says "Publish" when the shown translation is not yet published but "Update" when already published.
- The change has been applied for side-by-side view for page.
- I cannot find any side-by-side view for event and location. Could anybody show me where the feature is?
- but for Imprint side-by-side view is available. Should the change be also here applied?
Fixes: #1520

Fix button name in side-by-side view

---

CHANGELOG.md
integreat_cms/static/src/js/forms/update-permalink.ts

This pr changes the copy to clipboard button in the content forms to encode links, so they can be used on platforms which don't have unicode support.
- Apply the builtin `encodeURI` function to the copied text 
Fixes: #1539

Urlencode links when copied to clipboard

---

CHANGELOG.md
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po

This pr fixes the position of the copy short url button in the page form and imprint form to make it consistent with the normal page url.
Fixes: #1542

Fix short url copy button position

---

CHANGELOG.md
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pages/page_revisions.html
integreat_cms/cms/templates/pages/page_sbs.html
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/cms/views/pages/page_revision_view.py
integreat_cms/cms/views/pages/page_sbs_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/views/view_config.py

This PR tries to solve the problem that users who are not allowed to publish a page can unpublish the page by storing it as draft.
- "Save/Restore as Draft" Button will not be shown to users anymore, who do not have publishing right.
- This change is applied to Edit Page (where users edit page content) and Versions (where users manage past versions).
Fixes: #1445

Allow only users with publish permission to unpublish page

---

integreat_cms/sitemap/urls.py

This pr adds legacy sitemap url patterns:
* https://cms.integreat-app.de/wp-json/ig-sitemap/v1/sitemap-index.xml
* https://cms.integreat-app.de/region-slug/language-slug/wp-json/ig-sitemap/v1/sitemap.xml
Fixes: #1509

Add legacy sitemap url patterns

---

CHANGELOG.md
integreat_cms/cms/forms/events/event_form.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR limits the maximal duration of an event to 7 days.
- It is no longer allowed to create an one-time event with duration longer than 7 days or to change the duration of an one-time event to over 7 days.
- A small explanation for this limitation is added on the event editor page above the date inputs fields.
Fixes: #1510

Limit event duration to 7 days

---

CHANGELOG.md
integreat_cms/api/v3/events.py
integreat_cms/api/v3/locations.py
integreat_cms/cms/forms/pois/poi_translation_form.py
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/api/expected-outputs/augsburg_en_locations.json
tests/api/expected-outputs/nurnberg_en_events.json
tests/api/expected-outputs/nurnberg_en_locations.json

This pr changes the poi api so that only the default language titles of pois are delivered, in order to prevent rendering problems of the titles on the map.
- deliver default language poi name in api
- Show note in poi form that the translated title will not be shown to users
- Prefill the title of new poi translations
Fixes: #1512

Deliver only the default language title in poi api

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templatetags/content_filters.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Improve wording of minor edit label
Before, the label always was "implications on other translations", but for translations that are not the default translation, this is not correct. For languages that are further down the language tree (either leaf nodes or somewhere between the default language and a leaf node), the minor edit field not only impacts the other translations, but the current translation as well.
This change of the wording reflects the actual implications of the minor edit field.

Improve wording of minor edit label

---

CHANGELOG.md
integreat_cms/api/v3/push_notifications.py
integreat_cms/cms/models/push_notifications/push_notification.py
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/api/expected-outputs/nurnberg_de_fcm.json
tests/api/expected-outputs/nurnberg_en_fcm.json

Hide news after 28 days
- Add new setting `FCM_HISTORY_DAYS`
- Filter news in api endpoint that are older than the configured value
Fixes: #1585

Hide news after 28 days

---

CHANGELOG.md
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/views/pages/page_bulk_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Change the pages bulk action drop down menu to reduce the risk of accidentally selecting the wrong XLIFF option.
- Change the order of bulk actions
- Change caption
Fixes: #1600

Change XLIFF bulk action description, fixes #1600

---

CHANGELOG.md
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR removes the warning from the contact details in the POI form.
Fixes: #1606

Remove warning from poi contact details

---

CHANGELOG.md
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR is to solve the problem that the status of translations with only single public version is broken when the public version is minor edit.
This is a successor of PR https://github.com/digitalfabrik/integreat-cms/pull/1588 .
- If the translation is the first version, save it as major version.
- Otherwise, change the past versions to public. 
- No change in status calculation.
Fixes: #1464

Fix status of minor edit translation with only one public version

---

CHANGELOG.md
integreat_cms/cms/views/language_tree/language_tree_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR invalidates the cache of all lanuage-related objects after a language node is moved.
- Export the manual invalidation into a separate function
- Use the function after moving and deleting language nodes
However, our cache behavior is still pretty strange and I opened issue #1618 for a deeper investigation to get rid of this workarounds.
Fixes: #1534

Invalidate cache after moving nodes

---

integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This would be my suggestion to fix the translation state calculation
- Don't allow the first version to be a minor edit (identical to before)
- When a page is published and a minor edit, also publish the past versions to make sure the status is calculated correctly (and the minor change is actually a minor change and not a transition from a draft page to a public page)
Fixes: #1464
Fixes: #1622

Fix translation state when pubishing minor edit

---

CHANGELOG.md
integreat_cms/api/v3/events.py
integreat_cms/api/v3/imprint.py
integreat_cms/api/v3/locations.py
integreat_cms/api/v3/pages.py
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/models/abstract_content_translation.py
tests/api/expected-outputs/augsburg_ar_events.json
tests/api/expected-outputs/augsburg_de_events.json
tests/api/expected-outputs/augsburg_en_events.json
tests/api/expected-outputs/nurnberg_de_events.json
tests/api/expected-outputs/nurnberg_en_events.json

This pr fixes the performance problem regarding the events api.
- Don't create new events for recurrences
- Create unique slugs using the `$`-character, which is not allowed in 'normal' slugs
Fixes: #1535

Fix slow recurring event api

---

CHANGELOG.md
integreat_cms/cms/views/pages/page_revision_view.py

This PR solves the problem that links in old versions are shown in the link checker.
-<s> Links in draft versions are not shown in the link check.</s>
-<s>Only links in public versions are detected.</s>
- This bug happens when an old version is restored, because deletion of the old links will not be called during restoration, unlike case of creating a new version.
- The old links will be now deleted at restoration too.
Fixes: #1604

Show no broken links from old versions

---

CHANGELOG.md
integreat_cms/cms/templates/pages/_page_xliff_export_overlay.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/pages/__init__.py
integreat_cms/cms/views/pages/page_bulk_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/bulk-actions.ts
integreat_cms/static/src/js/pages/xliff-export-overlay.ts
integreat_cms/xliff/utils.py

This PR adds a bulk action and a pop-up window for XLIFF export in multiple languages. 
- Add bulk action option
- Add a language selection and confirmation pop-up 
Fixes: #1549

Add bulk action for multilingual XLIFF export

---

CHANGELOG.md
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/xliff/utils.py

Improve XLIFF export error messages
- Show warning instead of error when a page cannot be exported to XLIFF because of a missing source translation (see https://issues.tuerantuer.org/browse/KOMMUNE-385 for reference)
- Indicate whether only no public or no source translation at all exists

Improve XLIFF export error messages

---

CHANGELOG.md
example-configs/integreat-cms.ini
integreat_cms/core/settings.py

Make UI languages configurable
- Add new settings `LANGUAGES` and `LANGUAGE_CODE` to the config file
- make `de` and `en` the default languages and `nl` optional
Fixes: #1649

Make UI languages configurable

---

CHANGELOG.md
integreat_cms/cms/utils/matomo_api_manager.py

When retrieving the number of Integreat CMS API requests from Matomo, use the getActions instead of getVisitors API method. This should avoid the problem that Matomo sometimes attributes multiple actions to the same visitor by chance.
Fixes: #1635

Change statistics Matomo API requests, fixes #1635

---

CHANGELOG.md
integreat_cms/cms/templates/_tinymce_config.html
integreat_cms/cms/templates/pages/page_sbs.html
integreat_cms/cms/views/pages/page_sbs_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/pages/sbs-copy-content.ts

This pr adds functionality to render the diff of the source translation since the last update of the target translation in the side-by-side page editor.
- Render the diff of the source translation in sbs-view
- Add a button to toggle between the normal view and the diff view
- Remove disabled tinymce editor instance in source translation for better consistency
Fixes: #1449,  Fixes: #1573

Add diff-view for source translation in sbs-editor

---

CHANGELOG.md
integreat_cms/cms/forms/events/event_form.py
integreat_cms/locale/de/LC_MESSAGES/django.po

If one of the dates are missing or invalid, the previous solution caused a `KeyError`
- Only validate the event duration if the dates itself are valid

Only validate event duration if dates are valid

---

CHANGELOG.md
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

The page order table in the page form did not work correctly for root pages.
- Fix page order table for root pages
Fixes: #1660

Fix page order table for root pages

---

integreat_cms/core/logging_formatter.py
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Log GET parameters of failed HTTP requests
- Add logging formatter to modify the log records of the `django.request` module
If we receive any kind of secrets/keys via GET-parameters, this would expose them to the log.
However, I don't think that we do this anywhere...
Fixes: #1714

Log GET parameters of failed HTTP requests

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Prevent a locked form if SUMM.AI is globally disabled but locally enabled
Only disable region form if SUMM.AI disabled
Now, the warning is no longer shown when the "invalid" form is opened (the error only appears when the invalid form is submitted)
Fixes: #1725

Only disable region form if SUMM.AI disabled

---

CHANGELOG.md
integreat_cms/core/settings.py
integreat_cms/summ_ai_api/summ_ai_api_client.py

Increase timeout for SUMM.AI to 10 minutes (the default timeout of aiohttp was 5 minutes).

Increase timeout for SUMM.AI to 10 minutes

---

integreat_cms/cms/views/push_notifications/push_notification_sender.py

Sometimes, the Firebase API seems to not provide a `message_id` for submitted push notifications, while it is still received on subscribed devices. As it still sent HTTP status code 200, we assumed `message_id` was there and tried logging it, causing an exception. This lead to resend attempts and thus multiplied push notifications.
- Log API full response if no `message_id` is received on submitting a push notification, to gather further information
- Deliberately don't raise an exception since PNs seem to be sent correctly, (but avoid previous exception from failing to log non-existent dict field)
- Scenarios where a push notification might fail with an error in the API response, but HTTP code 200, will not be retried. Instances of this will only be visible from the logs.
Fixes: #1630 …

Fix Spontaneous Multiplication of Push Notifications

---

CHANGELOG.md
integreat_cms/cms/views/users/region_user_form_view.py
integreat_cms/cms/views/users/user_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Bug summary: when creating a user whose name already exists, the system displays the message "Pending account activation", which is incorrect.
Removed excessive message print 
Didn't find any.
Fixes: #1703

Removed excessive message print

---

integreat_cms/cms/apps.py
integreat_cms/deepl_api/apps.py
integreat_cms/gvz_api/apps.py
integreat_cms/nominatim_api/apps.py
integreat_cms/nominatim_api/nominatim_api_client.py
integreat_cms/summ_ai_api/apps.py

I was bothered by the verbosity of each server reload after a change to a Python file, so I removed the API availability checks in those cases. Especially when working on the road, this is a bit annoying.
I think it is enough to check the availability once after the first start of the server.
- Disable the re-check on every autoreload of the dev server
- Decrease verbosity of availability check exceptions

Only check availability of external APIs once

---

CHANGELOG.md
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/pois/__init__.py
integreat_cms/cms/views/pois/poi_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/nominatim_api/nominatim_api_client.py
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/pois/poi-actions.ts

Currently coordinates of a POI appears (if left blank) first after the POI is saved.
This PR auto fills coordinates live while editing when the address of POI is completed.
- Add event listeners in the address fields.
- Coordinates will be searched live while an user is filling the address fields.
- So far not known
Part of: #1000

Auto-complete address and coordinates of locations

---

integreat_cms/cms/utils/pdf_utils.py

Media files containing special chars were falsely reported as not found
- Use `urllib.parse.unquote` to decode the path
- none I am aware of 
Fixes: #1499

Fix false positive error message for urlencoded filenames in PDF export

---

CHANGELOG.md
integreat_cms/cms/utils/pdf_utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Fix broken inline icons in PDF exports by removing the css rule causing the issue.
- `default_css` for PDF exports is no longer provided by `xhtml2pdf`, but by a local copy with the fix applied
- I'll open a PR with `xhtml2pdf` to fix this upstream, so we can remove the local copy again
- none that I know of
Fixes: #1537

Fix broken inline icons in PDF exports

---

CHANGELOG.md
integreat_cms/cms/templates/_base.html
integreat_cms/static/src/css/style.scss

I added spacing to the sidebar to improve the view on small screens. At the moment the last menu point ("Language Tree")  disappears behind the version number on small screens.
- I added 3rem padding-bottom to the sidebar hard coded in the scss file
- Initially I wanted to use the tailwind class "pb-12" since this equals to 3rem, but for me it didn't work. Neither Chrome nor Firefox registered this class. However p-12 worked, which is strange since if p-12 is working, also pb-12 should be working. [See more about this here](https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale).
- Optionally I could also add a custom class for "pb-12" equaling to 3rem to the tailwind config file, but I'm not sure if we're going to use that class ever again
- Couldn't find any in Chrome or …

Add spacing to sidebar to improve view on small screens

---

CHANGELOG.md
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/pois/poi_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

At the moment, the auto completion feature introduced in https://github.com/digitalfabrik/integreat-cms/pull/1744 does only work for staff users.
Pass region_slug parameter into the view.
(Because our [access control](https://github.com/digitalfabrik/integreat-cms/blob/15ce171cc8041bac2d24823e271632db56eaebf1/integreat_cms/core/middleware/access_control_middleware.py#L59-L69) treats all views without the region_slug parameter as "staff area" and denies region users to access them.)
Fixes: #1777

Fix autocompleting POI address for non-staff users

---

CHANGELOG.md
integreat_cms/cms/views/regions/region_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

When region has nested directory structure with media elements in subfolders, attempt to delete such region produces an error:
```
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Region' because they are referenced through protected foreign keys: 'Director
y.region'.", {<MediaFile (id: 66048, name: arriving.png, path: /var/www/integreat-cms/media/regions/252/2022/06/arriving.png, Landeshauptstadt Saarbrücken (alt)
(&#9888; Versteckt))>})
```
Protected relationship is removed by setting parent = None on all directories and parent_directory = None on all media files before deleting the region
Fixes: #1749
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-req …

Fix region deletion error if media library has nested structure

---

.circleci/config.yml

Our credit usage has nearly doubled in the current month:
So maybe it's time to reduce CircleCI resource classed to save credits
Reducing the `resource_class` of the `build-documentation` did not work:
```
Exception occurred:
File "/home/circleci/.pyenv/versions/3.9.14/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
raise EOFError
```
... so somehow the job needs the cores?
Increased workflow duration, not sure how much, maybe 1-2 mins?

Reduce CircleCI resource classes to save credits

---

.circleci/config.yml

The [upload-test-coverage](https://github.com/digitalfabrik/integreat-cms/blob/8c1b48ffb325560ceff1bd77edf1dbf071b35f19/.circleci/config.yml#L191-L205) job on CircleCI doesn't work for external PRs since we don't pass our secrets to builds in other forks of this repository, see e.g. [this workflow run](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/5700/workflows/9aa77ab3-2c58-4d5b-802f-17cf49eab20b).
Add job filter by branch name: match branches where CircleCI doesn’t include pull/ at the beginning.
(CircleCI automatically names external branches as pull/XXX)
Tested on external PR:
https://github.com/digitalfabrik/integreat-cms/pull/1789
We shouldn't name our branches as pull/XXX, otherwise upload-test-coverage job won't run.
Fixes: #1762 …

Disable upload-test-coverage CircleCI job for PRs of forks

---

.circleci/config.yml
Pipfile.lock

Ok, this was another crazy rabbit hole I got myself into :laughing: 
Because of another error caused by an updated CircleCI docker image (see https://github.com/CircleCI-Public/cimg-python/issues/161) I noticed that the CircleCI cache is broken exactly at the same time a new docker image version is released:
- version `3.9.15` released today caused [failing build](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/5923/workflows/aa940c9a-0eba-47c1-ad2f-41ba3eecd3e4) for 3b8744ff25bef11e0f38599aae6e96513d736b1a
- version `3.9.14` released on Oct 4 caused [failing build](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/5501/workflows/08ba3c5b-eb04-4c32-97ee-1a0b19e31435) for d23ed936708102bb56dc2fa58df76a377379207b
- version `3.9.13` released on May …

Fix CircleCI cache invalidation

---

CHANGELOG.md
integreat_cms/cms/templates/pages/page_pdf.html
integreat_cms/cms/templatetags/pdf_filters.py
integreat_cms/cms/utils/pdf_utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/pdf/files/2861aa8c8d/Integreat - Deutsch - Augsburg.pdf
tests/pdf/files/3b02f5ea5b/Integreat - Arabisch - معلومات الوصول.pdf
tests/pdf/files/6262976c99/Integreat - Deutsch - Willkommen.pdf
tests/pdf/files/cdff964723/Integreat - German - Willkommen.pdf
tests/pdf/files/e155c5e38b/Integreat - Englisch - Welcome.pdf

Reenable table of contents and page numbers in PDFs.
The `sanitize_for_pdf` function introduced in https://github.com/digitalfabrik/integreat-cms/commit/5e8ecf83dd548b868797686fc57565da44366b19 used `lxml.html.fromstring` and `lxml.html.tostring`, which "corrected" the `xhtml2pdf` specific tag `<pdf:toc/>` to `<toc></toc>`, which `xhtml2pdf` then no longer recognized (analogously for page numbers).
- turn the `sanitize_for_pdf` function into a template filter 
- this way it can be applied on a per-page-level, skipping the `xhtml2pdf` tags which are incompatible with `lxml.html`  
- none that I found 
Fixes: #1802 

Reenable table of contents and page numbers in PDFs

---

CHANGELOG.md
integreat_cms/textlab_api/textlab_api_client.py

Unescape text sent to Textlab API
- Call `unescape()` on the text before sending it to the textlab api
- Make trailing slash of API setting optional

Unescape text sent to Textlab API

---

.circleci/config.yml

I'm not sure why I added this option in the first place, I think it makes sense to output the diff in the circleci job to see at the first glance which files and lines should be reformatted.
Just failing with:
```
100% 119/119 [00:00<?, ?it/s]
Exited with code exit status 1
```
like e.g. [here](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/6005/workflows/9cbc491f-a327-4689-8039-1089f68171cd/jobs/53914/parallel-runs/0/steps/0-103) isn't that helpful I guess.
- Remove `--quiet` option for djlint CircleCI check

Remove `--quiet` option for djlint CircleCI check

---

integreat_cms/cms/templates/chat/_chat_messages.html
integreat_cms/cms/templates/generic_confirmation_dialog.html
integreat_cms/locale/de/LC_MESSAGES/django.po

In the confirmation of deleting a chat message, a new line was not working and it was showing br tag.
Added style to p tag for accepting new line
Instead of <br> tag used space unicode character 
Not found any yet
Fixes: #1694

Fix newline in chat deletion confirmation box

---

CHANGELOG.md
integreat_cms/api/v3/feedback/event_feedback.py
integreat_cms/api/v3/feedback/poi_feedback.py

This pr fixes submitting feedback about a fallback page- or poi-translation. With this pr, the default language translation gets used if required.
The actual language of the feedback should not get lost, though.
- Handle fallback translation in the poi and event endpoints 
Fixes: #1718

Fix fallback feedback for events and pois

---

CHANGELOG.md
integreat_cms/api/v3/feedback/event_feedback.py

Slugs for recurring events contain date (in format: base-slug$yyyy-mm-dd).
As a result, when we receive a feedback for recurring event, event can't found by slug in DB and response 404 is returned.
Remove the date from the slug during feedback processing
- If someone manually creates event with the slug ending with the date in format $yyyy-mm-dd, feedback for such event won't be processed (upd: actually not possible, symbol $ is not allowed in the slug)
- There is no validation of the date in slug. If we receive feedback for an existing event but with an nonexistent date, it will be processed successfully.
- We lose information about which date the feedback belongs to.
Fixes: #1793 …

Fix sending feedback for recurring events

---

CHANGELOG.md
integreat_cms/api/v3/feedback/imprint_page_feedback.py
integreat_cms/cms/models/feedback/imprint_page_feedback.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR should fix the feedback view error, that was shown, when imprint feedback was submitted in a language, that does not exist for this regions feedback.
- Use fallback translation for the title of an imprint feedback, if the language exists in this region
- Use default backend language, otherwise
Fixes:  #1717
There was a previous PR, where I used a different solution which did not work out. When I dropped the changes, the PR was closed automatically. However, for full discussion also see #1730.

Provide fallback translations for imprint feedbacks

---

.circleci/config.yml
.circleci/scripts/create_release.py
.circleci/scripts/get_contributors.py

This mentions all contributors of a given release in the release body which automatically adds a contribution footer similar to e.g.:
- Add new script to fetch contributors between two given git references
- Add new contributors section in GitHub release body
- We cannot really test the new workflow until the next release, so it's not unlikely that I screwed something up and the notification won't work next time :see_no_evil:  (this shouldn't affect the PyPI release however, just the GitHub release and the Mattermost notification)

Add contributor list to GitHub releases

---

.circleci/config.yml

I noticed that the indentation of out git [tag](https://github.com/digitalfabrik/integreat-cms/tags) messages is a bit broken:
I assume this is because it somehow treats the first line special and expects it to be the heading or something...
- Add the heading "Changelog" to the git tag message 

Fix indentation in git tag message

---

CHANGELOG.md
integreat_cms/cms/forms/regions/region_form.py

Fix link scanning when cloning regions
- Disable the link listeners during the normal page cloning
- After cloning is finished, only query the latest versions of all translations and save them again to trigger the scan
Fixes: #1513

Fix link scanning when cloning regions

---

CHANGELOG.md
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po

As the app is not using our POI categories right now, we should inform our users about it.
Add text 'currently not publicly visible' into Category section of POI form
Fixes: #1806

Mark POI category as not visible in app

---

CHANGELOG.md
integreat_cms/cms/templates/dashboard/region_selection.html

Fix region selection template
- Fix the heading name of the endblock tag which was incorrectly set to `content` in dbbdf443059f6dc4486ff8d882c86ecd98b2025e
Fixes: #1843

Fix region selection template

---

CHANGELOG.md
integreat_cms/cms/templates/pages/_page_xliff_export_overlay.html

Make multi language popup scrollable so that even on smaller screens the end doesn't get cut off
- Add view height to popups, set to 80vh
- Add overflow scroll
- Change only for this popup. Couldn't find a popup that has the same issue. All other popups I considered had less height and therefore didn't have this issue
- Add custom height class for 80vh
There are some screens which would have just a minimal scroll which can be a bit ugly and/or annoying, but I hope that's okay
Fixes: #1827

Make Multi-language-XLIFF export popup scrollable

---

CHANGELOG.md
integreat_cms/cms/templates/hix_widget.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/utils/hix.py

Fix TextLab HIX widget for non-staff users
- Make the ajax view available in the region scope instead of network area which automatically denies access to non staff users
Fixes: #1865

Fix TextLab HIX widget for non-staff users

---

CHANGELOG.md
integreat_cms/cms/models/events/event.py
integreat_cms/cms/models/pages/page.py
integreat_cms/cms/models/pois/poi.py
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/bulk_action_views.py
integreat_cms/cms/views/events/event_actions.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pois/poi_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This pr updates the bulk archive/restore actions to mimic the exact behavior of the per-object archive/restore actions.
That should fix archived pages showing up in the linkchecker.
This pr also fixes a related issue where links of an archived page, that is not a root-page, would not show up in the linkchecker after restoring the page.
- Add archive/restore methods to the page, event and poi models
- Use these methods from both bulk-actions and per-object actions
- When restoring pages, manually restore links if the page is not a root page
/
Fixes partially: #1502

Fix bulk archive/restore

---

CHANGELOG.md
integreat_cms/cms/models/pages/page_translation.py
integreat_cms/cms/templates/pages/page_pdf.html

This pr fixes a bug that live content does not get rendered in pdfs
- Include the live content when rendering the pdf
- If no matching translation of the live content exists, render the default error message which lists alternative languages which work
/ 
Fixes: #1791

Render live content in pdfs

---

CHANGELOG.md
integreat_cms/cms/templates/imprint/imprint_sbs.html
integreat_cms/cms/views/imprint/imprint_sbs_view.py
tests/cms/views/view_config.py

I noticed I messed up the imprint side by side view template in dbbdf443059f6dc4486ff8d882c86ecd98b2025e, so this commit should fix it again and add a test case that prevents similar issues in the future.
- Fix name of `endblock` template tag
- Correctly redirect after successful form submission
- Add tests for imprint side by side view

Fix internal server error in imprint side by side view

---

integreat_cms/cms/templates/messages.html
integreat_cms/cms/utils/translation_utils.py
integreat_cms/cms/views/events/event_form_view.py
integreat_cms/cms/views/pages/page_bulk_actions.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/utils/__init__.py
tests/cms/utils/test_translation_utils.py
tests/summ_ai_api/summ_ai_test.py
tests/xliff/xliff_test.py

The assumption that our messages were `safe` was incorrect, since they also contain user input (e.g. when the title/name of an object is contained in the message).
- Escape the message per default by removing the [safe](https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#std-templatefilter-safe) template filter
- Provide a util function `translate_link()` which can be used to render links in messages correct (even if they are escaped)
- Not sure if I forgot any messages which used HTML syntax... if so, the messages would now contain the escaped tags and the HTML code would be literally printed out.

Correctly escape success/error messages

---

CHANGELOG.md
integreat_cms/cms/views/events/event_form_view.py
integreat_cms/cms/views/pois/poi_form_view.py

Fixes the issue with the broken translation status if only minor public versions exists for POI and event
- Add extra if-condition to ensure the correct translation status is set
I don't think there are any.  
Fixes: #1788

Fix broken translation status if only minor public versions exists

---

CHANGELOG.md
integreat_cms/cms/views/regions/region_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

It's not possible to delete a region of which pages are mirrored in other regions. However, up until now there was only a Django default error and there wasn't an informative output to the user
- Give warning to user why deleting the region didn't work 
- Output which pages are causing the issue
- I thought maybe it would also be interesting to know in which region the page is mirrored to. But since this wasn't in the issue I didn't do that yet. What do you think? Do I need to implement this? 
- I mean there has to be a simpler way to do this than what I did. I don't know why but I really struggled to make this more simple. I would be very interested to hear your ideas on how to refactor this
Fixes: #1688 …

Specify protected pages when trying to delete regions

---

.pre-commit-config.yaml

I noticed a small problem with the pre-commit hook failing due to eslint not being installed.
According to [this](https://github.com/pre-commit/mirrors-eslint/issues/10#issuecomment-344977736) comment, as a fix eslint should be listed as an additional dependency of itself...
/
/

Fix eslint pre-commit-hook

---

dev-tools/_functions.sh
dev-tools/test.sh
sphinx/dev-tools.rst

To make it easier to maintain/develop new tests, I suggest adding the ability to pass test_path as an argument to test.sh script.
So that only particular tests can be run like this:
./test.sh tests/api/test_api_feedback.py
* Pass TEST_PATH argument to "pipenv run pytest" command
* Generate code coverage report only when all tests are run. Not sure, if it makes sense otherwise.
N/A

Process test_path argument in test.sh

---

README.md
sphinx/index.rst

This PR aims to allow new-hires like myself and new volunteers to quickly get a sufficient understanding of the project architecture.
- The *Reference* section in the documentation index is moved up to be after *First Steps* and before *Basic Concepts* and the following sections, which describe the technical requirements of the project.
- The *Reference* section is being renamed to *Project Architecture / Reference* to better signal it as the starting point for understanding the project.
- The descriptions of each django app have been rewritten to have more concise wording and provide sufficient explanation to get a good first idea about what each app does.
- The [wiki for the municipalities](https://wiki.integreat-app.de/) is linked to allow the reader to further familiarise themselves …

Improve Documentation of Project Architecture

---

.gitignore

`.testmondata-journal` should be in gitignore
- change `.gitignore` to include all files starting with `.testmondata` 
- none

Fix: .testmondata-journal should be in gitignore

---

CHANGELOG.md
integreat_cms/cms/forms/custom_content_model_form.py
integreat_cms/xliff/base_serializer.py

Make sure translations are never a minor version after XLIFF import
- When deserializing XLIFF files, always reset the minor edit field to `False`, independently of whether the existing database object is a minor or major edit.
Fixes: #1934

Make sure translations are never a minor version after XLIFF import

---

CHANGELOG.md
integreat_cms/cms/forms/custom_content_model_form.py
integreat_cms/cms/forms/custom_model_form.py
integreat_cms/cms/forms/events/event_form.py
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/views/events/event_form_view.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/cms/views/pois/poi_form_view.py

Fix possibility to mark page as up-to-date without performing changes
- Fix possibility to mark page as up-to-date without performing changes
- Fix change detection in event form
- Fix change detection in location form
Fixes: #1864

Fix possibility to mark page as up-to-date without performing changes

---

CHANGELOG.md
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/xliff/utils.py

This pr fixes a bug where an ongoing translation was not cancellable if the latest version is a minor edit.
It also fixes two related bugs I noticed, where the status was always set to `up-to-date` after cancelling an ongoing translation, and a bug where the the translation status would not update after an xliff import/export if the latest version is a minor edit.
- Store the translation status in the latest version (as opposed to the latest major version previously)
- Don't update the objects timestamp after changing the translation state
/
Fixes: #1885

Fix ongoing page translation not cancellable

---

CHANGELOG.md
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/views/pages/partial_page_tree_view.py

Improve loading time of page tree
- Add `prefetch_major_translations` method to be able to prefetch all major versions of a queryset at once
- Prefetch major translations when building page tree
Fixes: #1950

Improve loading time of page tree

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/views/events/event_form_view.py
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/cms/views/pois/poi_list_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

There are some inconsistencies regarding the poi/event/page forms and list views for observer users.
This pr tries to fix that.
- Add no editing permission message to the location list view
- Disable the location form for users without editing permission
- Hide the create new poi/event buttons for users without the create object permission
- Don't show invalid warning in the event form for users without publishing and editing permissions
/
Fixes: #1945 

Make events, pois and pages uniform for observer users

---

CHANGELOG.md
integreat_cms/static/src/js/forms/tinymce-init.ts

Add shortcuts for Adding icons in the editor.
-  Pressing `Alt+|+<number>` would insert the corresponding icons
- The sequence corresponds to the sequence in menu. eg. 1 for `pin`, 2 for `www`, etc.
- None
Fixes: #1957

Add keyboard shortcuts for icons in the editor

---

CHANGELOG.md
integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/forms/pages/page_form.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/test_duplicate_regions.py
tests/cms/views/view_config.py

This PR excludes users wihout the page view permission from the candidates list for page-specific permission grant and prevent such cases that pege-specific permissions are given to users who do not have the page view permission and therefore cannot access the pages. 
- Show in the candidates list only the users who have the permission to view pages.
- Check if the selected user has the permission to view pages before granting them a page specific edit permission. If not, show a message.
- Test for page-specific permission: the observer in the test data is added to the editor and publisher list respectively for the pages with id=5, 6, and view test for "edit_page" will be run for those pages to check whether the observer can change the pages. The page with id=4 is used to check false …

Exclde users without page view permission from page specific permission

---

CHANGELOG.md
integreat_cms/cms/views/imprint/imprint_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Link is displayed as HTML tags in imprint form:
https://user-images.githubusercontent.com/82345046/204389202-d3e95ff6-7d71-4c38-8a36-a386df4a2089.png
Also link itself is incorrect, when there is no public version for the translation (it routes to Revision 1, but this revision is in draft state)
- Use format_html function to display link as a link
- Don't show the message, when there is no public version of the translation in the requested language.
I added condition by 'public_translation.id' for that. When it is 'None', it means that fallback translation is used.
Fixes: #1906

Fix link escape in message in imprint form

---

CHANGELOG.md
integreat_cms/static/src/js/pages/page-order.ts

Fix #1983 where an unexpected parameter type was passed to the `escapeMeta` function.
Allow the escapeMeta function to handle any parameter type and always return a valid (String) result.
I thought about splitting the nested function calls in https://github.com/digitalfabrik/integreat-cms/pull/1984/files#diff-12d9bde41ce20ae100fac96355585b5bd8415aeb05cc981c8bbb3b9f1e30f8e6R146 and only pass it to escapeMeta if there is a element. However, this made `getPageOrderTable()` even longer and the result seems to be mostly the same - except for the "unclean" parameter type.
Fixes: #1983 

Fix wrong parameter type in page order, fix #1983

---

CHANGELOG.md
integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/templates/pages/page_pdf.html
tests/pdf/files/ba6f45d0ab/Integreat - Griechisch - Καλώς ήλθατε στο Augsburg.pdf
tests/pdf/test_pdf_export.py

This PR fixes PDF export in Greek. 
- Add Greek language, its language node and some greek page translations to the default data.
- Specify Open Sans, a font set which is already used in our system and supports Greek letters, for Greek in PDF.
- Add test for PDF export in Greek
- I hope none.
Fixes: #1978 

Fix PDF export in Greek

---

.circleci/config.yml

The SSH key of the Digitalfabrikmember GitHub user was changed due to the recent incident at CircleCI
-  Update fingerprint of SSH key used in documentation deployment job
I hope this fixes our docs deployment:
https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/7014/workflows/9a241d5c-af1b-4328-afb2-4f700ee45420/jobs/68201
```
Cloning into '.gh-pages'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository
```

Update SSH key used for deployment of the documentation

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pois/poi_form.html

This PR hides the link edit icon in page/event/location form for observer users, except for pages they are allowed to publish or edit (per page-specific permission, for example).
- Check the permission of the user and decide to show or hide the icon.
- Though only page form is mentioned in the issue description, the requested change is applied also in event and location form, since observer users have no permission to change anything there too.
- I hope none.
Fixes: #1969 

Hide link edit icon for observers

---

dev-tools/check_changelog.sh

This should fix the bug in the changelog checking script which caused workflow [fd5acc40-470a-414b-bf36-25867e456954](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/7071/workflows/fd5acc40-470a-414b-bf36-25867e456954/jobs/69024) to despite the changelog looks good.
- Derive number of `-` in the headline from the actual version number

Fix changelog checking script

---

CHANGELOG.md
integreat_cms/cms/constants/roles.py
integreat_cms/cms/migrations/0056_update_observer_permissions.py
integreat_cms/cms/views/media/media_context_mixin.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/media-management/component/edit-directory-sidebar.tsx
integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx
integreat_cms/static/src/js/media-management/index.tsx
integreat_cms/static/src/js/media-management/library.tsx
integreat_cms/static/src/js/media-management/select-media.tsx

This PR adjusts the permission of observer role so observers can neither delete nor replace media files.
- remove the permission replace_mediafile from observer role (delete_media_file was not listed).
- save whether the user is allowed to replace/delete media files <s>in the attribute "value" in the template media_list(_admin)</s> as canReplaceFile and canDeleteFile in MediaContextMixin.
- hide the replace and delete buttons depend on <s>the "value" attribute</s> canReplaceFile and canDeleteFile.
- check permission before replacing/deleting the file and show an warning message if an observer user manages to send a delete/replace request.
- I hope none.
- There is probably a better way to check the permission to hide the buttons......
Fixes: #1968 …

Fix observer permissions in media library

---

integreat_cms/core/middleware/access_control_middleware.py
integreat_cms/static/src/js/menu.ts
integreat_cms/static/src/js/regions/conditional-fields.ts

I spotted a few annoying errors/exceptions that can be avoided
1. TypeError in TS on login page:
2. TypeError in conditional-fields.ts:
3. Continious PermissionDenied exceptions in debug mode under region users - added Django Debug Toolbar in the white list. 
N/A

Get rid of some TS errors and PermissionDenied exception

---

CHANGELOG.md
integreat_cms/cms/migrations/0055_track_region_deepl_api_usage.py
integreat_cms/cms/migrations/0056_update_observer_permissions.py
integreat_cms/cms/migrations/0057_add_machine_translated_flag.py

Two problems occurred during conflict resolution of #1941:
- The changelog entry was inserted at the wrong position
- The previous migrations were renamed and re-ordered, which does not work on production systems which already have them applied. Migrations depend on each other in a specific order to produce a deterministic state.
- Move changelog entry
- Reorder migrations to their previous position

Fix changelog and migrations

---

integreat_cms/api/v3/pages.py
integreat_cms/matomo_api/matomo_api_client.py

Make our statistics filters compatible to the old WP URL pattern (w/o slashes behind endpoints). This should not interfere with the Django pattern.
- Filter URLs without the ending slash.
- Disable tracking for the single page endpoint. This should have no consequences at all as the end point is not being used (and I did not find any relevant results for it in the Matomo database).
- None.
Fixes: None

Make Matomo filters compatible to WP URLs

---

CHANGELOG.md
integreat_cms/cms/templates/hix_widget.html
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR changes the strings inside the text understandabiliy-box to match the requirements from the service team.  
@osmers can you please also double-check if the strings are correct? (s. screenshot)
- Change title from HIX value to text understandability 
- Change paragraph below the "refresh"-button
I think none
Fixes: #2023 

Rephrase texts in text understandability-box

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/pois/poi_form.html

This PR extends the function to evenly distribute the sidebar boxes for POIs and events
- Add the required ids (left-sidebar-column and right-sidebar-column), so that the boxes are evenly distributed between the sidebars 
I think none
Fixes: Rest of  #1769

Distribute sidebar boxes evenly also for pois and events

---

CHANGELOG.md
integreat_cms/static/src/css/style.scss

Make slugfield usable, even if URI prefix is very long.
- make slugfield scrollable by setting `overflow: auto` on the container
- ensure `input` is never at 0 width
- reduce label opacity to $\frac{2}{3}$ for better distinction from input
- Other places using `.slug-field` will be affected. We estimate this to be fine.
Fixes: #1552 (Slug field layout broken when permalink is too long)

Make slugfield scrollable

---

CHANGELOG.md
integreat_cms/cms/templates/linkcheck/link_list_row.html
integreat_cms/cms/templates/linkcheck/links_by_filter.html
integreat_cms/locale/de/LC_MESSAGES/django.po

* For the time being the HTTP status codes for broken links should be shown to all users.
* Revert cf6d5d9d7ea63caaac3456e149817b4ffab33f97
- Remove the condition that shows the code only to expert users.
- None a.t.m.
Fixes: https://chat.tuerantuer.org/digitalfabrik/threads/n31dzqkz4bnguecz8kw4ed9ndy

Show Link Checker status codes to all users

---

integreat_cms/locale/de/LC_MESSAGES/django.po

This fixes a small bug when submitting a form with a duplicate slug which is already used in another object:
```
ValueError at /augsburg/pois/de/61/edit/
not enough values to unpack (expected 3, got 1)
```
- Fix formatting error in slug error message translation

Fix formatting error in slug error message

---

CHANGELOG.md
integreat_cms/cms/forms/events/event_form.py
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR changes the maximal event duration to 28 days, which is currently 7 days.
- Change the condition of duration check to 28 days.
- I think none.
Fixes: #2056 

Change max. event duration to 28 Days

---

CHANGELOG.md
integreat_cms/cms/templates/_collapsible_box.html
integreat_cms/cms/templates/pois/poi_form.html

With introducing the collapsible boxes to the page, event and POI form we created a gap between the boxes when certain boxes are collapsed. This is mainly due to two factors: a. using grid instead of flex, b. the two sidebars for medium and 4xl screens aren't wrapped inside one parent div. These changes are going to be relevant for all post types, however in this PR (at least up until now) I focused on POIs only. If we fixed everything for POI I will extend these changes to events and pages one by one.
For a graphical summary on what I tried to fix see the screenshots here: 
Before: 
After: 
- Using grid only for 3xl screens
- Add parent div for two sidebars (for medium and 4xl screens)
- Remove flex-auto for the editor so it doesn't create blank space
- Adjust spacing between the boxes …

Remove gap between sidebar boxes (for POIs)

---

CHANGELOG.md
integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/models/pages/page.py
integreat_cms/cms/models/pages/page_translation.py
integreat_cms/cms/views/utils/search_content_ajax.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/tinymce-plugins/custom_link_input/plugin.js

This pr changes the internal link suggestions to show the full path to an object translation instead of just its title.
As a sideeffect, the title will be shown in the backend language instead of the object translation's language.
I did not change the general search input feature, because there it is not ambiguous which object is which after performing the search.
- Add  a `path` to the JSON objects returned by `search_content_ajax`
- Display the path instead of the title in the internal link suggestions
/
Fixes: #1752

Show chapter for internal link suggestions

---

integreat_cms/static/src/js/forms/tinymce-init.ts

Our users aren't aware of our shortcuts for the icons as no shortcuts information are displayed. Furthermore, "alt+|+2" seems to be used by some other function and our shortcut for "www" wasn't working. I changed all shortcuts starting at 3 till 9 to skip it.
Fixes:  On-the-fly

Add shortcut texts to editor gui

---

dev-tools/_functions.sh
dev-tools/have_i_reviewed_enough.sh
sphinx/dev-tools.rst

Add a small dev-tool which might help us to keep track of our own reviewing workflow.
Requires [`github-cli`](https://cli.github.com/).
- `./dev-tools/have_i_reviewed_enough.sh`
- `./dev-tools/have_i_reviewed_enough.sh --since "2023-01-01"`
- `./dev-tools/have_i_reviewed_enough.sh --since "-2 months"`
- `./dev-tools/have_i_reviewed_enough.sh --since "last week"`

Add dev tool to check current review count

---

CHANGELOG.md
integreat_cms/api/v3/events.py
integreat_cms/cms/models/events/event.py
integreat_cms/cms/models/events/recurrence_rule.py
sphinx/conf.py
tests/api/api_config.py
tests/api/expected-outputs/augsburg_ar_events.json
tests/api/expected-outputs/augsburg_de_events.json
tests/api/expected-outputs/augsburg_de_events_combine_recurring.json
tests/api/expected-outputs/augsburg_en_events.json
tests/api/expected-outputs/nurnberg_de_events.json
tests/api/expected-outputs/nurnberg_en_events.json
tests/api/test_api_result.py
tests/cms/models/events/test_recurrence_rule.py

For the new endpoint /events/?combine_recurring=True only one event object is returned. This object contains an rrule, which defines how the element is repeated.
Added this new endpoint, we need to keep the old one for backwards compatibility.
If we want to remove the old endpoint in the future (we should wait at least 6 months), i can open a ticket, i think this would be nice to remove the legacy code.
Fixes: #1965 

Combine recurring events and add rrule

---

CHANGELOG.md
Pipfile.lock
integreat_cms/cms/models/abstract_tree_node.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po
setup.cfg
sphinx/conf.py

Prevent race conditions in page tree. This is no replacement for database transactions. This would not catch problems where the process dies in the middle of changing a tree structure.
* Use django-db-mutex module to implement a per class mutex that allows only one page tree move operation at a time.
* This can be replaced with basically the same functionality within tree beard if it works.
* As we have multiple processes in production, the database back end is used for communication. We could also use Redis, which would actually be a little faster. However, the app implements it this way and it should be good enough for testing if we continue to have 500 errors in our logs.
* Saving of other data should continue even when the move action fails. The user receives a notification about the …

Add mutex to tree move function, fix #1518

---

CHANGELOG.md
integreat_cms/api/v3/events.py
tests/api/expected-outputs/augsburg_ar_events.json
tests/api/expected-outputs/augsburg_de_events.json
tests/api/expected-outputs/augsburg_en_events.json
tests/api/expected-outputs/nurnberg_de_events.json
tests/api/expected-outputs/nurnberg_en_events.json

For every recurring event the first event was appended, even if it is in the past. Fixed this.
The first event of a recurring event is only appended if recurring events are delivered as one event with rrule.
Fixes: #

Fix events endpoint for recurring events

---

tests/api/api_config.py
tests/api/test_api_feedback.py

In feedback API tests we currently only check the API response.
We don't validate that feedback was actually processed correctly.
- Check feedback in database
- Add more cases to increase test coverage
No side effects, but only cms_feedback table is checked.
Also need to cover tables for different feedback types, like cms_pagefeedback, cms_poifeedback etc.
I will implement it separately.
Partially fixes: #1880

Add database checks into feedback API tests

---

dev-tools/test.sh
pyproject.toml
sphinx/dev-tools.rst

This PR makes the output of failed API tests legible, by producing deep diffs of the JSON responses. It is possible to quickly see which values differ from the expected output.
- Add pytest-diff as dependency (no additional setup seems to be required)
- Tests are now producing different output. I hope this is not being parsed after the fact somewhere? (since pytest-diff is a plugin for pytest, pytest itself should not have issues)
Fixes: #1953 

Readable test diffs with pytest-icdiff

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/pages/page_form.html

This PR removes the gap between the sidebar boxes for pages and events. The PR is similar to [the one where I remove the gap for POIs](https://github.com/digitalfabrik/integreat-cms/pull/2043).
- Switch from gap to flex for pages and events
- Adjust the spacing to be 16px / 1rem for all boxes to all sides
I think none
Fixes: #2032

Remove gap between sidebar boxes (for pages and events)

---

integreat_cms/static/src/css/style.scss

At the moment it's not very clear which checkboxes are enabled and which ones are disabled. Therefore we want to introduce some visual indicators to see a difference
- Add tailwind classes "bg-gray-100 border-gray-300" for disabled checkboxes and radio buttons  
None I'm aware of
Fixes: #2051 

Visually indicate when a checkbox is disabled

---

integreat_cms/cms/templates/emails/_base_email.html
integreat_cms/cms/templates/pages/page_pdf.html
pyproject.toml
sphinx/conf.py
sphinx/documentation.rst

The changes from my fork [timoludwig/sphinxcontrib-django2](https://github.com/timoludwig/sphinxcontrib-django2) were now merged into [edoburu/sphinxcontrib-django](https://github.com/edoburu/sphinxcontrib-django) and I took over maintenance for the upstream package, so I suggest to use that one instead.
- Switch back from `sphinxcontrib-django2` to `sphinxcontrib-django` (partially reverts changes from f4ab3c13ff1e92f4b82f8a87f31badabb6c8ed15)
- Adapt HTML code to new djLint version

Switch back to upstream doc library `sphinxcontrib-django`

---

CHANGELOG.md
integreat_cms/cms/templates/pois/poi_form_sidebar/category_box.html
integreat_cms/locale/de/LC_MESSAGES/django.po

Categories are shown in the apps now. Therefore we should remove the warning in our POI form
- Remove the warning in our POI form
- Renew the translation
- Add an entry to the changelog. Again I'm not super sure if this is wanted. Please feel free to give feedback on this.
None
Fixes: #2105 

Indicate that categories are shown in the apps now

---

CHANGELOG.md
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/views/bulk_action_views.py
tests/summ_ai_api/summ_ai_test.py

This PR restricts the usage of the SUMM AI bulk action to staff members only
- Add a check in the template if the user is staff member or not
- Add an entry to the changelog to let others teams know that we have improved this (please correct me, if we should remove the entry in case it's not meant to be seen by everyone) 
I think none. I tested it for a few roles and didn't notice any side effects. 
One thing we should keep in mind. As for now the SUMM AI function was disabled globally. So once this PR is merged, we could turn it on again
Fixes: #2065 

Only allow staff members to use the SUMM AI bulk action

---

CHANGELOG.md
integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/events/event_list_archived.html
integreat_cms/cms/templates/icon_widget.html
integreat_cms/cms/templates/pages/_page_order_table.html
integreat_cms/cms/templates/pages/page_sbs.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pages/page_tree_archived.html
integreat_cms/cms/templates/pages/page_tree_archived_node.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/templates/pois/poi_form_sidebar/position_box.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/templates/pois/poi_list_archived.html
integreat_cms/cms/templates/pois/poi_list_archived_row.html
integreat_cms/cms/templates/pois/poi_list_row.html
integreat_cms/cms/views/pois/poi_context_mixin.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/pois/opening-hours/component/opening-hours-display.tsx
integreat_cms/static/src/js/pois/opening-hours/index.tsx
integreat_cms/static/src/js/pois/poi-map.ts

This PR deactivates page order change by drag&drop in the page form if user does not have permission to change the page.
While working on this issue, I found a similar problem with icon setting of page/poi/event. Icon choise is now deactivated too when user does not have change permission.
- Set the page node in the page order section undraggable if user has no change permission.
- Deactivate all the event listners of the page order section.
- Hide icon set/change buttons in page/poi/event form if user has no change permission.
- None (I hope)
Fixes: #1970 

Deactivate page order drag and drop for observers

---

integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/utils/translation_utils.py
integreat_cms/cms/views/events/event_list_view.py
integreat_cms/cms/views/mixins.py
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/cms/views/pois/poi_list_view.py
integreat_cms/deepl_api/utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/summ_ai_api/summ_ai_api_client.py

In #1831 / #1994 and #1927 / #2036 settings were added to control who is allowed to machine translate which content, and into which languages MTs are allowed. This PR implements the necessary backend logic to ensure only permitted requests are being passed on to SUMM.AI/DeepL.
- add a utility function responsible for determining whether or not a request should be permitted
- call this function in (page/event/poi)_list_views to be able to disable the bulk action option
- also call it within the DeepL and SUMM.AI translation functions to prevent malicious circumvention of those rules
- none that I could find
Fixes: #2031 

Respect settings of machine translation management section

---

CHANGELOG.md
integreat_cms/cms/forms/__init__.py
integreat_cms/cms/forms/translations/machine_translation_form.py
integreat_cms/cms/templates/events/event_form_sidebar/minor_edit_box.html
integreat_cms/cms/templates/pages/page_form_sidebar/minor_edit_box.html
integreat_cms/cms/templates/pois/poi_form_sidebar/minor_edit_box.html
integreat_cms/cms/utils/translation_utils.py
integreat_cms/cms/views/events/event_form_view.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/deepl_api/utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/editor.ts
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/conditional-fields.ts
integreat_cms/static/src/js/mutually_exclusive_checkboxes.ts
integreat_cms/static/src/js/regions/conditional-fields.ts
tests/core/management/commands/test_summ_ai_bulk.py

Adds a checkbox "automatic translation" to Page/Event/POI form views that is exclusive to "minor edit". If checked, the respective content is translated into all languages that are descendants of the source language (if they are supported by DeepL, that is).
- added a form field `automatic_translation` to the (new) `MachineTranslationForm`
- when checked, allow selection of translations to update/create
- if checked and minor edit is not checked, pass to DeepL for translation 
- hide this checkbox if DeepL is not enabled or the language has no descendants
- none that I could find, however I'd be glad if whoever reviews this keeps an eye on the translation statuses. AFAIK everything is working as intended though. 
- moved the TS logic for hiding/showing conditional fields into its own, …

Add automatic translation checkbox to Pages, Events, POIs

---

CHANGELOG.md
integreat_cms/cms/templates/languages/language_form.html
integreat_cms/cms/views/events/event_list_view.py
integreat_cms/cms/views/pois/poi_list_view.py
integreat_cms/deepl_api/apps.py
integreat_cms/deepl_api/utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR fixes an error that occurred while using the MT for English or Portuguese. With this PR now it gets checked if a. the BCP47 code is in the correct format as expected, and either returns an error message or for the edge case that the BCP47 tag for English or Portuguese were incorrect sets en-GB respectively pt-PT as default.
- Add check if BCP47 code is correct
- Set pt-PT and en-GB as default values if the BCP47 code wasn't correct
- Return an error message for all other cases in which the BCP47 code wasn't correct
- Remove the check from the main function and put it in a separate function in order to pass pylint (too many if-branches in one function 15 out of 12). However I had to add the check "if target_language_key is None" to the main function, which is quite ugly. If someone …

Fixes MT for languages with faulty BCP code

---

pyproject.toml

When deploying the current develop state to the test system, I noticed an error with the new version of our caching library (https://github.com/Suor/django-cacheops/issues/449) which was implicitly updated in https://github.com/digitalfabrik/integreat-cms/commit/64aa4472298a7b83b5c6a172461d8a0a51af3178#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711.
- Downgrade `django-cacheops` to version `6.2`

Downgrade `django-cacheops` to version `6.2`

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/release_notes/current/unreleased/2153.yml

Fix error when cloning a region without imprint
- Only duplicate imprint when it exists
Fixes: #2153

Fix error when cloning a region without imprint

---

integreat_cms/cms/views/events/event_list_view.py
integreat_cms/cms/views/imprint/imprint_form_view.py
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/cms/views/pois/poi_list_view.py
integreat_cms/cms/views/push_notifications/push_notification_list_view.py
integreat_cms/release_notes/current/unreleased/2151.yml

Fix `django.urls.exceptions.NoReverseMatch` when listing content as long as no language nodes exist
- Fix `NoReverseMatch` error in lists without language tree
Fixes: #2151

Fix `NoReverseMatch` error in lists without language tree

---

tools/make_release_notes.sh

I noticed that the sorting is broken in some environments when there are no unreleased release notes.
E.g. on the current develop branch, the tools outputs the following on my machine (and version 2023.2.2 is clearly older than version 2023.3.1):
```
$ ./tools/make_release_notes.sh
- [ [#2012](https://github.com/digitalfabrik/integreat-cms/issues/2012) ] Exclude archived pages when cloning a region
- [ [#2093](https://github.com/digitalfabrik/integreat-cms/issues/2093) ] Fix recurring events API endpoint
```
- Fix sorting in release notes tool

Fix sorting in release notes tool

---

integreat_cms/cms/views/utils/hix.py
integreat_cms/core/signals/hix_signals.py
integreat_cms/textlab_api/textlab_api_client.py

Small improvements for HIX API client
- Allow long text for post save signals (the limitation only applies to the ajax view)
- Catch the urllib error in the API client and not in the view utility (The previous solution did not log the HTTPError)
- Do not execute post save signal when the content is empty

Small improvements for HIX API client

---

integreat_cms/cms/templates/_form_language_tabs.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2117.yml

This PR adds the bot icon for languages that are in the "Other languages" dropdown
- Add changelog entry
- Add if statement for machine translations
- Add translation for it
- I didn't find any
Fixes:  #2117

Add bot icon in "other languages" tab in content forms

---

integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/release_notes/current/unreleased/2155.yml

The translation status for machine translations used to still show the bot icon even when the translation wasn't up-to-date anymore. This PR fixes this and only shows the bot icon for machine translations that are up-to-date and shows the warning icon for machine translations that are outdated. 
- Adds distinction between up-to-date and outdated machine translations and decides for the correct translation status and icon
- I restricted the query for machine translations and this could cause some side effects, although I don't have an exact idea how this might show 
Fixes: #2137

Fix translation status for outdated mts

---

example-configs/integreat-cms.ini
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/templates/hix_widget.html
integreat_cms/cms/templates/pages/page_form_sidebar/minor_edit_box.html
integreat_cms/cms/views/events/event_form_view.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/core/settings.py
integreat_cms/core/signals/hix_signals.py
integreat_cms/deepl_api/utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2130.yml
integreat_cms/static/src/js/analytics/hix-widget.ts

Make sure pages are written in sufficiently simple German before being able to translate them with DeepL
- for each `content_object` passed to the DeepL utils, make sure the HIX score is high enough (or not applicable)
- when loading the `page_form_view` or refreshing the HIX score, hide the Automatic Translation checkbox based on the score
- none that I could find
Fixes: #2130

Only allow machine translation if the HIX value is high enough

---

integreat_cms/cms/forms/translations/machine_translation_form.py
integreat_cms/release_notes/current/unreleased/2160.yml

Fix `AttributeError` when form is saved with no options for machine translations
- Set queryset to `LanguageTreeNode.objects.none()` instead of literally `None`
- Account for case when `automatic_translation` checkbox is not in cleaned data
Fixes: #2160

Fix `AttributeError` when form is saved with no options for MTs

---

integreat_cms/cms/templates/hix_widget.html
integreat_cms/release_notes/current/unreleased/2141.yml

Fix loading animation for HIX widget
The diff looks a bit strange, but all I did was wrapping the `collapsible_box_content` block in a separate `<div class="relative">` to make sure the `absolute` class of the loading spinner only applies to the widget itself.
Fixes: #2141

Fix loading animation for HIX widget

---

.github/ISSUE_TEMPLATE/feature-request.md

This PR adds two new subsections to our feature request template in GitHub.
- Add User Story subsection to the Design Requirements. I added the pattern that the user story should follow to the comments. One could argue that we could also put the pattern outside of the comments into the body, because everyone filling out a feature report should be using the pattern. I guess I depends on how which way you prefer
- Add Link To Figma subsection to the Design Requirements. I also added this section for the UI/UX team to fill this out. Again, there is some room for discussions here, since we could already provide the permanent Figma link to the CMS project. Since the UI/UX team labels the subprojects with the issue ids the project is referring to, this would make sure that there is already a …

Add user story section to feature request template

---

integreat_cms/cms/templates/push_notifications/push_notification_form.html
integreat_cms/release_notes/current/unreleased/2166.yml
integreat_cms/static/src/js/push-notifications.ts

This PR fixes the text direction for RTL languages in the push notification form
- Add text-direction attribute to the HTML element
- Add check in Javascript, and if necessary adjust the text direction from LTR to RTL
- The Typescript code doesn't look create once again, but I didn't know how to improve it. I thought I could do it in one line, but since getElementsByTagName didn't allow me to pass two elements and I needed the conversion to HTML Element it ended up being four lines. Suggestions for improvement are welcome!
Fixes: #2166

Fix text-direction for RTL push notifications

---

integreat_cms/api/v3/locations.py
integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/migrations/0066_update_poi_translation_status.py
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2097.yml

When a region creates a location which is a draft in the default language, but public in other languages, the location API returns an internal server error
- Disable "Publish" button in POI form for non-default languages, when default translation is not public
- Exclude POIs without public translation in the default language from the locations API response
- Add test data to cover the case
Fixes: #2097

Fix locations endpoint error when default translation is not public

---

docs/src/management-commands.rst
integreat_cms/core/management/commands/reset_deepl_budget.py
tests/core/management/commands/test_reset_deepl_budget.py

This PR adds a management command that resets the DeepL budget to 0 if a region's renewal month is the current month.
- Query regions whose renewal month is the current month, reset their `deepl_budget_used` to 0, set `deepl_midyear_start_month` to the current month.
- Add a test for the command (and some test data for it too).
- It seems `datetime.now()` returns the current time of GMT. If the cronjob starts between 00:00 and 02:00 of the first day of the month, the returned value must be adjusted.
Fixes: #1999 

Add management command to reset DeepL budget

---

docs/src/management-commands.rst
integreat_cms/core/management/commands/hix_bulk.py

This pr adds a hix_bulk command which saves the hix store for all pages for which the score is missing.
- Add hix_bulk management command
/
Fixes: #2101 

Add hix_bulk command

---

integreat_cms/cms/templates/events/_poi_form_widget.html
integreat_cms/cms/templates/events/_poi_query_result.html
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/events/event_form_sidebar/venue_box.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/pois/__init__.py
integreat_cms/cms/views/pois/poi_form_ajax_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/1171.yml
integreat_cms/static/src/js/events/event-query-pois.ts
integreat_cms/static/src/js/pois/opening-hours/index.tsx

With this PR a feature should be introduced, where POIs can be created from within the event form. ~However there are still a few important things to do~: 
We decided to reduce the scope of this PR significantly as the solution of a pop-up overlay does bring various design decisions that are questionable (in terms of system design as well as UX design). The solution now is a minimal POI form that is shown inside the event venue box.
- Add a POI form ~overlay~ widget to the ~event form~ event venue box
- Create and save POI form via AJAX
- ~Add new widgets for opening hours and maps to the AJAX POI form~
- ~I think there might be clashes between namings from the input fields of the POI and the event form (due to Django's render_field). Therefore JavaScript Searches through the DOM might …

Dynamically create POIs from within event form 

---

tests/core/management/commands/test_hix_bulk.py

This pr adds some basic tests for the hix_bulk management command
- Test for error if the api is disabled
- Test for error if an unknown region is passed as an argument
/
Fixes: #2192 

Add tests for the hix_bulk management command

---

.prettierignore

`prettier --check .` keeps complaining about `webpack-stats.json`, and `prettier --write .` always "fixes" it (unnecessarily, since the file gets regenerated constantly)
- add the file to `.prettierignore`
- 
- none 
Fixes: # n/a

Make prettier ignore webpack-stats.json

---

integreat_cms/cms/views/utils/hix.py
integreat_cms/release_notes/current/unreleased/2200.yml
integreat_cms/textlab_api/apps.py
integreat_cms/textlab_api/textlab_api_client.py

Basic networking errors are not being caught with the URLError class. These are derived from the OSError class. If the textlab server is for some reason not reachable, we should catch these errors as well.
Catch the OSError class in the textlab API client.
Problems with auto translation? But I think we need to do this anyways.
Fixes: #2200 

Catch network errors for textlab API, fix #2200

---

integreat_cms/cms/views/events/event_form_view.py
integreat_cms/release_notes/current/unreleased/2197.yml

I have to admit that I neither understand why the bug is happening, nor why exactly this line is fixing it (I also tried `invalidate_obj(region)`, `invalidate_obj(event)`, `invalidate_obj(event_translation)`, `invalidate_model(Region)`, `invalidate_model(Event)`, neither of which worked), but the important thing is that it seems to fix the issue :see_no_evil: 
- Invalidate event translation cache after events have been updated
- The cache in all regions is invalidated when an event in one region is updated
Fixes: #2197

Invalidate cache after events have been updated

---

integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/templates/pages/page_pdf.html
integreat_cms/cms/templatetags/pdf_filters.py
integreat_cms/release_notes/current/unreleased/1904.yml
tests/api/expected-outputs/api_augsburg_de_children_depth_2.json
tests/api/expected-outputs/augsburg_de_children.json
tests/api/expected-outputs/augsburg_de_pages.json
tests/pdf/files/92ff67bd01/Integreat - Deutsch - Augsburg.pdf

This PR should provide a temporary solution for long links in PDFs. Instead of overflowing, long links are now limited to 50 chars. Longer links will be truncated. 
- Add a filter that truncates long links 
- Apply filter on pages in the PDF template
- This might be a naive solution. I'm not 100% confident, that there won't be edge cases, where this might affect links in an unexpected way. 
Fixes: #1904

Truncate long links in pdf exports to a maximum of 50 chars

---

integreat_cms/cms/templates/hix_widget.html
integreat_cms/core/signals/hix_signals.py
integreat_cms/static/src/js/analytics/hix-widget.ts
integreat_cms/static/src/js/conditional-fields.ts

If as HIX score is already stored in the DB, we can use it in the page form view instead of making an (unnecessary) request to the Textlab API.
- if the current language is in `TEXTLAB_API_LANGUAGES` and the HIX score is set on the page_translation model, use it as the `initialHixValue` instead of calling to the API
- if the content was unchanged, keep the score from the previous version in the pre-save signal
- none that I could find
Fixes: #2144

Use cached HIX score on page load

---

integreat_cms/cms/templates/analytics/_page_hix_row.html
integreat_cms/cms/templates/analytics/_page_hix_widget.html
integreat_cms/cms/templates/dashboard/dashboard.html
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2088.yml

This PR adds a list of pages sorted ascendingly by HIX-value.
- Add a new widget in region dashbord and show it when HIX is enabled in the region
- Sort and show non archived pages with HIX enabled by HIX-Value with link to form
- Mark pages with low HIX-value with red background
- Show percentage of pages ready for automatic translation between all non archived pages
Following poits are probably to discuss.
- Pages with good HIX-value or hix_ignore=true are counted as "ready for automatic translation" 
- For HIX-value check the latest draft or public translation is considered.
- The list widget is shown to all users independently from their role and whether they are expert user.
Fixes: #2088  …

Add list of worst pages based on HIX to dashboard

---

integreat_cms/cms/forms/machine_translation_form.py

The problem was that the form instance is always an object (so evaluating to `True`), even when it's not yet saved to the database.
- Checking whether the object is saved to the database before accessing the foreign object
Fixes: #2227

Fix `RelatedObjectDoesNotExist` when creating a new page

---

integreat_cms/cms/templates/analytics/_page_hix_widget.html
integreat_cms/cms/templates/dashboard/dashboard.html
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2088.yml
integreat_cms/static/src/css/style.scss
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/analytics/hix-list.ts

Add toggle option to expand the list of pages by HIX score on dashboard.
- Add new release note
- Add toggle trigger to show all pages (starting from the eleventh)
- Refactor a little bit: a. show yellow warning alert if there is no HIX value and b. only show this message and hide table head (different than it was before) / see screenshot below
- Fix minor spelling error in German translation file
- The double tbody and the double message on top of the list aren't great, but it was the only solution I could come up with to fix it. For the double tbody I read on SO that it's better to have two tbody than for example just to wrap the second one inside a div or another HTML tag. For the double message, it's not possible to add a HTML tag inside Django's blocktranslate, therefore I had to …

Add option to expand HIX list on dashboard

---

integreat_cms/cms/forms/machine_translation_form.py
integreat_cms/cms/templates/events/event_form_sidebar/minor_edit_box.html
integreat_cms/cms/templates/pages/page_form_sidebar/minor_edit_box.html
integreat_cms/cms/templates/pois/poi_form_sidebar/minor_edit_box.html

The "HIX score too low for MT" error message was shown whenever the HIX score was too low, even when MT had not been attempted by the user.
- if automatic MT was unchecked, all translation target languages were removed from the forms `cleaned_data`, however to check if MT was possible, the querysets assigned to the fields themselves were checked for emptiness -> fixed
- none 
Fixes: #2230

Fix wrongfully shown 'HIX too low' error message

---

example-configs/integreat-cms.ini
integreat_cms/core/settings.py

Allow adding local translations in `/etc/integreat/locale`.
- Add an additional source path for locales.
- We can use individual strings everywhere ;-)
Fixes: #2206

Allow localized translations

---

.circleci/config.yml

Appparently, the change from `small` to `medium` in c650f5b49b30591696f3625db53c057c8c5c32db (#2213) was not enough:
Further increase `resource_class` for CircleCI tests from `medium` to `large`
- Increased credit usage
Fixes: #2203

Further increase `resource_class` for CircleCI tests

---

integreat_cms/cms/templates/hix_widget.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2222.yml
integreat_cms/static/src/js/analytics/hix-list.ts
integreat_cms/static/src/js/analytics/hix-widget.ts
integreat_cms/static/src/js/forms/tinymce-init.ts

Show "HIX widget is loading..."  instead of "There is no page content." while the HIX widget is loading.
The issue was that the 1000ms timeout used to ensure tinyMCE was fully initialized before attempting to call `getContent()` was insufficient. Instead of increasing the timeout, I did the following:
- remove the timeout completely
- tinyMCE dispatches a new `tinyMCEInitialized` signal after completing initialization
- `initHixValue` is no longer called on page load, but only after that signal has been emitted
- some more refactoring and simplification of the `initHixValue` function
- unrelated: fixed an `uncaught TypeError` (it was such a small fix I did not think a separate issue was necessary)
- none that I could find. AFAIK the behaviour of the widget is as it was before, minus the …

Show less confusing message while HIX widget is loading

---

integreat_cms/release_notes/current/unreleased/2252.yml
integreat_cms/static/src/css/style.scss

This PR fixes the issue with the not editable URL parameter field by adding contenteditable to the parent element.
- ~~Add contenteditable to parent element~~
- Change the CSS selector from &:read-only to &[readonly] as suggested [here](https://stackoverflow.com/questions/69174538/css-read-only-is-applied-to-elements-that-are-not-readonly).
- ~~I'm not sure if this is the best solution. I guess the best solution would be to let the input field know it's writeable. However every trick I tried didn't work, and therefore this is the next best solution. Let me know, what you think.~~
- I checked the places I know the read-only field is needed, but I'm not sure I know all the places. Can you please check all the places you know where a readonly field is needed to see if this doesn't mess …

Change URL parameter field to make it editable

---

integreat_cms/cms/linklists.py
integreat_cms/release_notes/current/unreleased/2053.yml

This PR excludes past events from link check.
- add a new filter in `EventTranslationLinklist`
- This alone does not remove links in past events directly and immediately. When the link check is triggerd, for example by the command `findlinks` or other stimli, they dissapear from the link list. Is there already a scheduled job for link screening?
Fixes: #2053 

Do not check links in past events

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/cms/templates/regions/region_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2245.yml

This PR enables team user to keep the status of the pages of a cloned region.
- Add boolean field to region_form
- Skip the status reset if the field is set
- If the initial cloning mechanism works as expected no issues should arise from this :man_shrugging: 
Fixes: #2245 

Add option to duplicate regions with initial page status

---

integreat_cms/cms/templates/imprint/imprint_sbs.html
integreat_cms/cms/templates/pages/page_form_sidebar/settings_box.html
integreat_cms/cms/templates/pages/page_sbs.html
integreat_cms/static/src/css/style.scss
integreat_cms/static/src/js/media-management/library.tsx

While reviewing, I noticed that I had missed out on the "Back to Form" button in the side-by-side view while I was working on  #2253. This PR fixes this.
- Changes "Back to form" button in side-by-side view from a grayed button (looks like it was disabled) to outline-button (introduced by PR  #2253)
- Remove unused / not rendered class btn-gray from "Order"-Section inside the collapsible box "Settings"
- I think none
- If you find the time, please double-check if you can find any grayed buttons that are not disabled. While going through the views and the code-base I didn't find any anymore, but maybe my keywords weren't great and I don't know all of the views
- I double-checked with UI/UX and they told me to use outline-buttons and not ghost-buttons for "Go back to..." buttons
Fixes: …

Fix remaining grayed button to outline button

---

integreat_cms/sitemap/sitemaps.py

This improves the performance of the sitemap. This is quite relevant as some search engine crawlers frequently crash our server by inducing too much load.
Reference: https://integreat-test.tuerantuer.org/augsburg/de/sitemap.xml
- w/o patch: 24,4MB/2,03min
- w/ patch: 1kB/23ms
- Remove duplicate entries
- N/A
Fixes: #1750

Remove duplicate sitemap entries

---

integreat_cms/cms/templates/events/event_form_sidebar/minor_edit_box.html
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/templates/imprint/imprint_sbs.html
integreat_cms/cms/templates/pages/page_form_sidebar/minor_edit_box.html
integreat_cms/cms/templates/pages/page_form_sidebar/translator_view_box.html
integreat_cms/cms/templates/pages/page_sbs.html
integreat_cms/cms/templates/pois/poi_form_sidebar/minor_edit_box.html
integreat_cms/release_notes/current/unreleased/1632.yml
integreat_cms/release_notes/current/unreleased/2013.yml
integreat_cms/static/src/js/forms/tinymce-init.ts
integreat_cms/static/src/js/unsaved-warning.ts

This PR should prevent a browser alert for unsaved content caused by form elements that don't actually change the content. This was the case for:
- The selection input on page and imprint form view in the "Translator View" box
- The tinyMCE comparison window (right side) in the side-by-side view
- The minor edit checkbox on page form, POI form and event form
- I don't think, that there are side effects
Fixes: #1632, (#2013)
*As a side node:* Neither me nor the service team could reproduce the chrome related bug as described in #2013, however I found that the warning e.g. showed up after toggling the button which shows differences to a previous version. I think this might be the issue that occurred there, but I'd be glad, if any reviewers will also test this with chrome. …

Suppress unsaved warnings for form elements that don't affect content

---

.circleci/config.yml
pyproject.toml

Let the version be parsed by an external tool instead of bash.
(`looseversion` is already installed as dependency of `bumpver`, so no need to update the pinned versions)
- Do the comparison in Python instead of Bash
Fixes: #2288

Fix version parsing on CircleCI

---

integreat_cms/cms/views/utils/hix.py
integreat_cms/release_notes/current/unreleased/2224.yml

This PR tries to keep the HIX value identical between pre save signal and tinymce.
- replace `\n` with `\r\n` before checking HIX value.
- replace entity reference with numeric reference (example: `&auml;` -> `&#228;`) before checking HIX value.
- Sadly I couldn't find a way to convert entity reference to numeric reference directly and needed some converting steps.
- It seems, so far observed in the test data, reference art of special letters does not cause difference in HIX value, but the style of new line does.
-  If "\n" appears in the text by chance, for example when an user writes "Please use \n as line break" in the editor, simple replacement might replace it too, even though it is not intended as a line break. I testet it and "\n" tipped in the editor was not replaced, but I cannot …

Fix HIX value difference

---

example-configs/integreat-cms.ini
integreat_cms/core/management/commands/hix_bulk.py
integreat_cms/core/settings.py
integreat_cms/release_notes/current/unreleased/2303.yml
integreat_cms/release_notes/current/unreleased/2304.yml

Two bugfixes for the HIX bulk action
- Prevent HIX analysis from finding links in archived pages
- Reduce server load when querying the TextLab API
- Longer execution time
Fixes: #2303
Fixes: #2304

Fix HIX bulk action

---

integreat_cms/cms/templates/_machine_translation_overlay.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/pages/__init__.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2102.yml
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/machine-translation-overlay.ts
integreat_cms/textlab_api/utils.py

This PR adds the option to translate pages via MT through a bulk action inside the page tree view. Please note, this PR is not yet ready for review, since I still want to take the time to attempt refactoring it myself. This PR is supposed to fulfill the following use case: I, as CMS user, want to get an overview about my MT budget, the pages that will be able to be translated and those that can't be translated (due to too low HIX score), before translating them.
- Add a option for MT to the bulk action dropdown
- Add a popup to get a report about the attempted MT
- Show from which to which language this translation is going to be
- Show the pages that can be translated
- Show the pages that can't be translated
- Show the budget and calculate, if there is enough budget …

Add popup to DeepL bulk action of page tree view

---

integreat_cms/cms/forms/linkcheck/edit_url_form.py
integreat_cms/cms/templates/linkcheck/link_list_row.html
integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2307.yml

Disabled link text field in the link replacement form caused several issues:
- The existence of the field led to confusion
- The replacement form required scrolling on smaller screens
- It was no longer possible to replace the src attributes of img tags
Revert the previous link replacement form (without the disabled link text field)
No?
However I am not quite sure what was meant by _It was no longer possible to replace the src attributes of img tags_ because I think I can replace src value for images on develop.
Fixes: #2307

Remove link text field from link replacement form

---

integreat_cms/deepl_api/deepl_api_client.py
integreat_cms/release_notes/current/unreleased/2318.yml
integreat_cms/summ_ai_api/utils.py

This PR fixes the translation status change of `currently in translation` pages after they are machine translated.
- Count machine translation as cancellation of translation (XLIFF) process.
- Set "currently in translation" to false in the form.
- Revert the value of `currently in translation` in all the versions to false after machine translation (see #2214).
- I'm very afraid that this change affects other constraints/rules of translation status and its calculation, though so far it looks good to me 🙈 
This needs to be done before the release of #2221.
Fixes: #2318 

Fix translation status of currently in translation pages after MT

---

integreat_cms/cms/forms/feedback/region_feedback_filter_form.py
integreat_cms/release_notes/current/unreleased/2273.yml

This PR fixes `NotSupportedError` which occurs in the feedback filter.
- Make an unrestricted query set after `.union()` so `select_related` can be operated on the query set (like in `get_pages` method of region).
- None (I hope), since no change on the filter query calcuration.
Fixes: #2273 

Fix feedback filter error

---

integreat_cms/cms/templates/analytics/_page_hix_widget.html
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2296.yml
integreat_cms/release_notes/current/unreleased/2317.yml

The value of "ready for MT" in the dashboard calculates the percentage of all pages with HIX above the threshold in relation to all translations.
This is incorrect since e.g. empty pages without a HIX score are allowed for MT
Add the number of empty translations to the ready_for_mt_count value
No?
Fixes: #2317
Fixes: #2296
Fixes: #2310 (self-resolved as a side effect)

Count empty translations as ready for MT in the dashboard

---

integreat_cms/cms/templates/pages/page_form_sidebar/actions_box.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/views/bulk_action_views.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2171.yml

This PR solves the inconsistent state of mirrored pages by prevanting archiving of mirrored pages.
- Deactivate the archiving icon of mirrored pages in the tree 
- Hide the archiving button in the form if the page is mirrored
- Check if there are mirorring pages before archiving a page (both in single request and bulk action)
- Adjust error/success messages of the bulk action and titles of the icon
- None?
- I have chosen the first one among the two suggested solutions (expected behaviour) because it seems to be more in accordance with the existing behaviour of page deletion and probably causes less confusion than the second option.
Fixes: #2171 
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-re …

Do not archive mirrored pages

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/release_notes/current/unreleased/2281.yml
tests/cms/test_duplicate_regions.py

As a temporary solution this PR removes link replacement from region cloning process.
- Remove link replacement from region cloning
- Adjust test
- Now region cloning should function without time out, but link replacement should be done manually with the newly introduced link replacement GUI in the broken link section.
- Background link replacement should follow (#2343)
Fixes: #2281 

Deactivate link replacement in region cloning

---

integreat_cms/cms/utils/email_utils.py
integreat_cms/cms/utils/welcome_mail_utils.py
integreat_cms/cms/views/authentication/password_reset_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2046.yml

Display a graceful error message instead of Internal Server Error when failing to send mail.
- Catch multiple types of exceptions
- *BadHeaderError (was already there, now giving slightly more context)*
- SMTPAuthenticationError (special SMTPException)
- SMTPException
- ConnectionRefusedError
- Every exception gets the same base message that already existed, with a brief hint on what the actual problem is. This might make them more content (they get a feeling of knowing what's wrong, not only that something is wrong) and possibly speed up the investigation process when they report it.
- Only a few hours ago I claimed I would be focusing on Reviews and not submit any new PRs for now. With this I kinda loose credibility, don't I? :sweat_smile: 
- Code should be fine
Fixes: #2046 …

Add graceful error messages when sending mail

---

README.md
docs/src/installation.rst
tools/install.sh

Installing integreat with node 12 causes this error on initial startup:
```
[webpack] [webpack-cli] Failed to load '/home/user/dev/integreat-cms/webpack.config.js' config
[webpack] [webpack-cli] /home/user/dev/integreat-cms/node_modules/jest-worker/build/index.js:126
[webpack]       enableWorkerThreads: this._options.enableWorkerThreads ?? false,
[webpack]                                                               ^
```
Support for the nullish coalescing operator was added in node 14, which seems to be the minimal required version now (Though it is outdated).
- Replace version 12 with 18
/ 
Fixes: /

Raise minimum required nodejs version to 18

---

integreat_cms/cms/templates/organizations/organization_list.html
integreat_cms/release_notes/current/unreleased/2368.yml

This PR fixes the missing page numbers on the organization list.
- Change `chunk=organizations` to `chunk=page_obj`
- None?
Fixes: #2368 

Fix page numbers on organization list

---

integreat_cms/api/v3/locations.py
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po

Explain why we show the name of a POI in the main language in the app.
Fixes: https://chat.tuerantuer.org/digitalfabrik/threads/c3c5i34jwjg7pn46ixyifbb87h

Add info about POI titles

---

integreat_cms/cms/models/pages/page_translation.py
integreat_cms/release_notes/current/unreleased/2172.yml

This PR fixes the bug that not only non-empty translations but also empty translasions are suggested as fallback of the embedded content.
- Filter empty translations out of the fallback list
- Return an empty string as in the case where the page has no mirrored content, if  there is no non-empty translations which can be a fallback. (Otherwise no language will be shown after the message _Part of the page does not exist in the selected language. It is however available in these languages:_ and it is confusing.)
- I may have misunderstood some part of the functionalitry and/or the wished status 🙈 
Fixes: #2172 

Do not show empty mirrored content as fallback

---

integreat_cms/cms/views/language_tree/language_tree_actions.py

This PR cleans up a forgotten `.filter(push_notification__region=region)` in `language_tree_actions.py`
- remove the statement for deleting PushNotificationTranslations, now they might be used in other regions the PushNotification is assigned to
- PushNotificationTranslations might be left in the database that are not in use by any region
- Clean up thoroughly by:
- querying the  Language Tree of all regions the PushNotification is also assigned to
- determining which PushNotificationTranslations are now "orphaned" (rather: no longer in use)
- deleting those

Fix deleting Language Tree Node

---

docs/src/api-docs.rst

This pr fixes a bug in the api documentation
- Don't mark the region bounding box field as potentially null, the cms always returns at least the `settings.DEFAULT_BOUNDING_BOX`
/
https://chat.tuerantuer.org/digitalfabrik/pl/1o1rgw9fi3ny8qtqa1q7by571y

Mark bounding box field as not null in api

---

integreat_cms/cms/templates/_machine_translation_overlay.html
integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/events/event_list_view.py
integreat_cms/cms/views/pages/__init__.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/cms/views/pois/poi_list_view.py
integreat_cms/cms/views/utils/__init__.py
integreat_cms/cms/views/utils/machine_translations.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2314.yml
integreat_cms/static/src/js/machine-translation-overlay.ts

This PR extends the pre-existing machine translation popup from pages only also to POI and events. Since POI and events don't need a check for HIX, in these cases the HIX check is skipped.
- Add release note 
- Extend the machine translation popup to POI and events
- Store code for creating AJAX call in a new general function
- Refactor the TS file a little by shortening some of the variable names and by using content type neutral variable names
- None of that I'm aware of at the moment
Fixes: #2314 

Extend machine translation popup to events and pois

---

integreat_cms/cms/views/bulk_action_views.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2404.yml
integreat_cms/release_notes/current/unreleased/2405.yml
integreat_cms/static/src/js/forms/tinymce-init.ts

The error occurs when trying to archive pages without translation in the backend language, because this action uses a title in the backend language to print a success message
- use default language to print a success message
I also included a change for another tiny task: move "Clear formatting" button to the center in the editor to make it more visible
- no ?
Fixes: #2405
Fixes: #2404

Fix error when archiving a page

---

integreat_cms/cms/views/feedback/admin_feedback_actions.py
integreat_cms/cms/views/feedback/region_feedback_actions.py
integreat_cms/release_notes/current/unreleased/2399.yml

This pr fixes a bug that feedback archiving does not work when caching is enabled.
- Invalidate cache when archiving and restoring feedback
- General slower performance for feedback queries after archiving or restoring since the invalidation used in this pr is very coarse
Fixes: #2399 

Invalidate cache when archiving feedback

---

tools/_functions.sh
tools/test.sh

This PR adds comfort feature for development in making it easier to run one or a set of specific tests without running other modules or even undesired tests within the same module.
It is essentially an extension of the existing specify-a-single-tests-module feature, adding support for the pytest `::` syntax and passing through markers and keyword expressions. (https://docs.pytest.org/en/latest/how-to/usage.html#specifying-which-tests-to-run)
*Example: Selecting the one test that still fails for a specific role, to quickly test the difference of small changes without waiting for the other integration tests in the same test module:*
`tools/test.sh -vv tests/summ_ai_api/summ_ai_test.py::test_summ_ai_error_handling[OBSERVER-pyloop]`
- instead of saving arguments not matching any specific …

test.sh: Allow specific and multiple tests

---

integreat_cms/static/src/js/machine-translation-overlay.ts

Fix the error
```
Uncaught TypeError: document.getElementById(...) is null
```
In the JS console when the machine translation overlay is not available

Fix JS error in machine translation overlay

---

integreat_cms/core/signals/__init__.py
integreat_cms/core/signals/organization_signals.py
integreat_cms/release_notes/2021/unreleased/2363.yml

Another caching related bugfix, where the automatic invalidation system did not invalidate PageTranslations when an organization changed.
- Invalidate all PageTranslations when an organization gets saved
- Also unrelated PageTranslations will not be cached after an organization gets saved
Fixes: #2363 

Invalidate cache when organization was saved

---

integreat_cms/core/management/commands/repair_tree.py

Repair tree works if it encounters an orphan w/o a parent.
- Skip print parent information if parent is not available. 
- N/a
Fixes: #2432 

Repair tree cmd for orphans w/o parent, fix #2432

---

integreat_cms/cms/utils/pdf_utils.py

We get a lot of logging entries like this:
```
Oct 08 02:01:20 WARNING integreat_cms.cms.utils.pdf_utils - The file 'https://www.vhs-bodenseekreis.de/f/cmx512f766acfdb9/cmx_4bbc75f45e264/cmx51e7ea767a9de/FS51e7eccb691ce.png' is not inside the static directories '/static/' and '/media/'.
```
but I think this "warning" is irrelevant - external images work just fine in pdfs.
Thus I suggest to only log the error when it's really a relative URL and not an external one.

Reduce logging verbosity in `link_callback()`

---

integreat_cms/cms/views/utils/hix.py
integreat_cms/core/signals/hix_signals.py
integreat_cms/release_notes/current/unreleased/2224.yml

There are still cases where we got different HIX values for the same content.
For example:
1. Create new page with the following content:
```
<p>Eine sehr schwierige Zeile</p>
<p>Eine weitere sehr schwierige Zeile</p>
```
2. Save or Publish it --> HIX is **19.17**
3. Press "Publish" again with no changes --> HIX is **19.86**
The behavior will be the same if step 3 is "Press Ctrl+A and reload the HIX value".
-  Rework text normalization before sending request to Textlab API
- Hope none, but careful testing is welcomed
Fixes: #2224

Fix different HIX value calculation

---

integreat_cms/cms/models/regions/region.py
integreat_cms/cms/templates/regions/region_list_row.html
integreat_cms/release_notes/current/unreleased/1836.yml

Change 'last updated' field in region list to each region's content instead of the region object itself.
- add `last_content_update` cached property to region model
- use it instead of `last_updated` in the region list
- none I could find, keeping the `last_updated` field unmodified should prevent any backwards compatibility issues
Fixes: #1836 

Change 'last updated' field in region list to refer to their content

---

integreat_cms/cms/templates/pages/page_tree_archived_node.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/core/formats/__init__.py
integreat_cms/core/formats/de/__init__.py
integreat_cms/core/formats/de/formats.py
integreat_cms/core/settings.py
integreat_cms/release_notes/current/unreleased/2446.yml

Improve the date display of the German locale.
See docs: https://docs.djangoproject.com/en/3.2/ref/settings/#format-module-path
- Instead of `09. Oktober 2023 22:15` write `09. Oktober 2023 um 22:15 Uhr`

Improve the date display of the German locale

---

integreat_cms/cms/views/regions/region_actions.py
integreat_cms/release_notes/current/unreleased/2452.yml

Fix error when deleting regions with organization logos
- Delete region's organizations before the region itself (including the region's media library)
- If an error occurs during `region.delete()`, the organization objects can not be recovered
Fixes: #2452

Fix error when deleting regions with organization logos

---

.pre-commit-config.yaml

This fixes the `Cannot read properties of undefined (reading 'getTokens') Occurred while linting [...].tsx:[...] Rule: "@typescript-eslint/no-empty-function"` error during the eslint pre-commit hook.
- as the title says
- none
Fixes: n/a

Align eslint pre-commit version with eslintrc version

---

integreat_cms/cms/views/pages/page_actions.py
integreat_cms/core/settings.py
integreat_cms/deepl_api/deepl_api_client.py
integreat_cms/release_notes/current/unreleased/2318.yml
integreat_cms/summ_ai_api/utils.py
integreat_cms/xliff/base_serializer.py
integreat_cms/xliff/utils.py

This PR fixes the problem that translation status icons sometimes do not transit correctly and quickly.
The problem can be observed when Redis is activated and especially in/after transit to/from `currently_in_translation`. Therefore I assume that cache of the field `currently_in_translation`, which suppresses other translation statuses, is the cause.
- Invalidate cache if Redis is activated.
- As I could not reproduce the exact cases reported in the issues, this solution may not cover all the cases.
Fixes: #2318
Fixes: #2319 

Fix transit of translation status icons

---

integreat_cms/api/v3/locations.py
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2417.yml
tests/api/expected-outputs/augsburg_en_locations.json
tests/api/expected-outputs/nurnberg_en_locations.json

RTL languages can be displayed on the map in the app now.
So we can deliver the POI title in different languages, not only in the default language.
- use poi_translation.title instead of poi.default_public_translation.title
- remove info message from the poi form
No?
Fixes: #2417

Deliver POI title in different languages

---

docs/src/api-docs.rst
integreat_cms/api/v3/events.py
integreat_cms/release_notes/current/unreleased/2294.yml
tests/api/expected-outputs/augsburg_ar_events.json
tests/api/expected-outputs/augsburg_de_events.json
tests/api/expected-outputs/augsburg_de_events_combine_recurring.json
tests/api/expected-outputs/augsburg_en_events.json
tests/api/expected-outputs/nurnberg_de_events.json
tests/api/expected-outputs/nurnberg_en_events.json

This adds the `location_url` to the event endpoint. I decided against adding the url in the `transform_poi` function, as it is also used in the poi endpoint and there this information would be duplicated.
- add attribute `location_url` to event endpoint
Fixes: #2294 

Add `location_url` to event endpoint response

---

integreat_cms/cms/templates/events/_poi_form_widget.html
integreat_cms/release_notes/current/unreleased/2471.yml

This PR fixes an error which occurs when users create a new POI in the event form.
- Add a field for POI category
- I hope there is none.
Fixes: #2471 

Fix POI widget in event form

---

integreat_cms/cms/views/utils/content_edit_lock.py
integreat_cms/static/src/js/content-edit-lock.ts

This pr tries to fix the log spam caused by many content-edit-lock-release requests being aborted.
An error will still be logged if a request gets aborted, but I hope that this should only happen very rarely after this pr.
Unfortunately I cannot reproduce the actual issue locally, does someone know how to do that?
- Use the `navigator.sendBeacon` api which does not cancel requests
- use the `pagehide` event instead of `unload` (https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes)
- Ideally none
Fixes: #2283

Keep content edit lock release request alive

---

.circleci/config.yml

Fix quotes in GitHub release description
- Replace double quotes with single quotes in the release notes of GitHub releases

Fix quotes in GitHub release description

---

integreat_cms/cms/forms/custom_content_model_form.py
integreat_cms/cms/utils/internal_link_utils.py
integreat_cms/release_notes/current/unreleased/2485.yml

Fix error when translating links with HTML tags in the link text
- Only replace link text if `link.text` is not `None`
Fixes: #2485

Fix error when translating links with HTML tags in the link text

---

integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/generic_auto_save_note.html
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/templates/imprint/imprint_sbs.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pages/page_sbs.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2002.yml
integreat_cms/static/src/js/forms/autosave.ts

This PR adds a message incl. a timestamp to the page form when either the status is automatically saved or when the page form has been automatically saved. 
- Add remark that automatically saved to page/event and poi form
- Show remark if last save was auto save
- Show remark if page/event/poi has been auto saved
- I was struggling to test because my server crashed whenever I tried to reload. But given the fact that I also have this issue on the develop branch I assumed I could ignore it for this PR. To me it seemed like it had more to do [with issue 2128](https://github.com/digitalfabrik/integreat-cms/issues/2128)
- In mobile views this doesn't look great
Fixes: #2002  …

Add success message when page/event/poi has been auto saved

---

integreat_cms/cms/templates/pages/page_form_sidebar/settings_box.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2482.yml

This PR fixes the issue that authors and observers can't be assigned during the page creation.
- Hide the permission section during the time that there is not a page id yet (for example page creation)
- Add help text for page creation to inform about this behavior
I think none
Fixes: #2482 

Hide permission section in page form during page creation

---

integreat_cms/api/v3/pdf_export.py
integreat_cms/cms/models/pages/page.py
integreat_cms/cms/models/regions/region.py
integreat_cms/cms/templates/analytics/translation_coverage.html
integreat_cms/cms/templates/dashboard/_todo_dashboard_row.html
integreat_cms/cms/templates/dashboard/_todo_dashboard_widget.html
integreat_cms/cms/templates/dashboard/dashboard.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_automatically_saved_pages_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_broken_links_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_low_hix_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_outdated_pages_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_unread_feedback_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_unreviewed_pages_row.html
integreat_cms/cms/views/analytics/translation_coverage_view.py
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/regions/region_update_view.py
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2107.yml
integreat_cms/sitemap/sitemaps.py
tests/cms/views/view_config.py
tests/sitemap/sitemap_config.py

This PR adds the new todo dashboard to the dashboard. It takes the place of the HIX analysis box. The HIX analysis box is instead moved to the translation coverage section.
- Add new todo dashboard box
- Add template for todos
- Add six todos for the first version of the todo dashboard
- Move the HIX analysis to translation coverage
I think none
Fixes: #2107

Add new todo dashboard

---

integreat_cms/cms/views/regions/region_actions.py
integreat_cms/release_notes/current/unreleased/2462.yml

Fix `IntegrityError` when deleting region with multiple feedback.
1. Submit at least *2 feedback forms of differing types*, for example:
```
curl --location --request POST 'http://localhost:8000/api/augsburg/de/feedback/imprint-page' --form 'comment="test"'
curl --location --request POST 'http://localhost:8000/api/augsburg/de/feedback/map' --form 'comment="test"'
```
2. It does not matter whether these are read or remain unread, but they **cannot** be for the same endpoint (e.g. two feedback submissions for the map)
3. Attempt to delete the region "Stadt Augsburg" and receive the following error:
```
django.db.utils.IntegrityError: update or delete on table "cms_feedback" violates foreign key constraint "
cms_imprintpagefeedb_feedback_ptr_id_8eb10618_fk_cms_feedb" on table …
```

Fix `IntegrityError` when deleting region with multiple feedback

---

integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_low_hix_row.html
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR fixes the display of hix value in ToDo dashboard
- Adjust `blocktranslate trimmed`
- None?
Fixes: #2498 

Fix display of hix value in ToDo Dashboard

---

integreat_cms/release_notes/current/unreleased/2300.yml
integreat_cms/static/src/js/analytics/hix-widget.ts

Any action within the tinymce editor modifies the content, and should thus set the content to be *dirty*. At least, this is the assumption of tinymce. But there are actions that do not modify the content, like making a selection, or end up at a previous state, like adding a character back after accidentally removing it.
This PR fixes this problem by simply monkeypatching tinymce's `isDirty()` and `setDirty()` methods, always comparing it to a previous value and saving that on successful autosaves.
Evaluating the HIX score also sets such a value to use as basis for determining whether an earlier score is actually outdated or not.
- Monkeypatch tinymce `isDirty()` and `setDirty()` to actually represent the content being different from the last saved state
- tinymce provides this nice …

Fix "HIX score outdated"

---

integreat_cms/release_notes/current/unreleased/2517.yml
integreat_cms/static/src/js/analytics/hix-widget.ts

When MT are disabled, checking the "Ignore HIX value" checkbox does not cause the HIX block to expand, because of TS errors:
```
caught (in promise) TypeError: Cannot read properties of null (reading 'classList')
at _callee4$ (hix-widget.ts:212:20)
at tryCatch (.*\.svg$:51:1)
at Generator.<anonymous> (.*\.svg$:51:1)
at Generator.next (.*\.svg$:51:1)
at .*\.svg$:51:1
at new Promise (<anonymous>)
at __webpack_modules__../integreat_cms/static/src/js/analytics/hix-widget.ts.__awaiter (.*\.svg$:51:1)
at HTMLInputElement.toggleHixIgnore (hix-widget.ts:205:40)
_
```
- Use TS optional chaining to access MT-form element
No?

Fix HIX block display when toggling a checkbox

---

integreat_cms/cms/forms/events/event_filter_form.py
integreat_cms/release_notes/current/unreleased/2519.yml

This PR fixes event filtering by time, which is causing internal server error.
- Change `start_time` and  `end_time` to `start__time` and `end__time`
- None (I hope)
Fixes: #2519 

Fix event filtering by time

---

integreat_cms/nominatim_api/nominatim_api_client.py
integreat_cms/release_notes/current/unreleased/2495.yml

This PR fixes `TypeError: expected string or bytes-like object`, which occurs in an edge case where only spaces are given as address and house number.
- Check whether the input for "addess and house number" contains any valid letter
- There may be other edge cases 🤔 
Fixes: #2495 

Fix error in location coordinates retrieving

---

integreat_cms/cms/templates/dashboard/_todo_dashboard_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_automatically_saved_pages_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_broken_links_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_low_hix_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_outdated_pages_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_unread_feedback_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_unreviewed_pages_row.html
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR aims to fix the line break in dashboard sections. It's caused due to the width of the checkmark icon.
- Add basis class to the rows
- I wasn't able to test this on a screen larger than 14". If changes are needed to be made, someone else would need to take over from me :/
- There are some sizes (for example 1280px where the buttons don't look great. But I'm not sure how to improve it with flex. Maybe it would be better to switch to grid?
Fixes: #2522 

Fix line break in dashboard sections

---

integreat_cms/cms/templates/dashboard/dashboard.html
integreat_cms/cms/views/dashboard/dashboard_view.py

Fixes a bug when the newly introduced dashboard (#2348) would cause a regression before a new region could be set up, because it assumed regions always have a default language. When trying to access its slug, it crashed, ironically preventing anyone from setting up the language tree through the CMS.
- Add checks to detect when there is no default language and don't display the items in that case
I couldn't think of any yet
Fixes: #2518

Fix crashing dashboard when region has no default language

---

integreat_cms/cms/templates/dashboard/_todo_dashboard_row.html

FIx underlined space in To-Do dashboard
- wrap the `todo_dashboard_title` in `spaceless` and turn off linitng for the `a` tag to prevent surrounding spaces 
- none
Fixes: #2521 
This is a really unsatisfying solution to the problem, but the only one I could find.

Fix underlined space in To-Do dashboard

---

integreat_cms/cms/templates/dashboard/_todo_dashboard_row.html
integreat_cms/cms/templates/dashboard/_todo_dashboard_widget.html
integreat_cms/cms/views/dashboard/dashboard_view.py

I'd vote for hiding the linkcheck row until the performance problems are resolved.
- Temporarily disable linkcheck widget for performance reasons
- Adapt button label width to new feedback label (#2528)
Fixes: #2536

Fix dashboard performance

---

integreat_cms/cms/views/users/region_user_actions.py
integreat_cms/cms/views/users/user_actions.py
integreat_cms/release_notes/current/unreleased/2408.yml

This PR fixes the following case:
1. the user was assigned to more than one region (z.B. A and B)
2. the user read a feedback in the region A
3. the user was removed from the region A (but remained in the region B)
Then, if we try to remove the user from region B (or in general, in "Network management"), IntegrityError will occur.
```
django.db.utils.IntegrityError: update or delete on table "cms_user" violates foreign key constraint "cms_feedback_read_by_id_fbaaab26_fk_cms_user_id" on table "cms_feedback"
DETAIL:  Key (id)=(668) is still referenced from table "cms_feedback".
```
- Mark feedback read by the user as unread before deleting the user
- No?
Fixes: #2408 …

Fix IntegrityError when deleting user

---

pyproject.toml

#2459 decreased code coverage pretty significantly, which is not a real problem since the imports are checked during the mypy run.
- Ignore the `repr()` functions
- Ignore type checking imports
- Ignore `NotImplementedError` lines
Part of #2492

Ignore unreachable code for test coverage

---

integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/models/push_notifications/push_notification_translation.py
integreat_cms/cms/views/utils/search_content_ajax.py
integreat_cms/release_notes/current/unreleased/2542.yml
tests/cms/views/view_config.py

This PR improves the test coverage.
Add tests for the following views:
- integreat_cms/cms/views/utils/translation_status.py (34%->91%)
- integreat_cms/cms/views/utils/search_content_ajax.py (22%->88%)
- integreat_cms/cms/views/regions/region_actions.py (37%->90%)
- integreat_cms/cms/views/utils/slugify_ajax.py (33%->89%)
Some lines are left unchecked. Is the coverage of 100% a must?:
- `PermissionDenied` at events and POIs in `search_content_ajax`: these lines won't be called because all the roles can veiw events and POIs in the current implementation.
- `AttributeError` in `search_content_ajax`: when this is called (even in a correct context), the test fails and won't complete.
- Error by mirorred pages in region deletion: the (intended) error message "Region could not be deleted, …

Improve test coverage of search, publishing multiple objects and region deletion

---

integreat_cms/cms/models/pages/page_translation.py
integreat_cms/release_notes/current/unreleased/1175.yml

This PR adds an empty tag to empty pages whose subpages are all archived.
- Add to the condition for the empty tag the case where all the subpages are archived 
- Adjust `get_non_archived_children` to choose whether the parent page should be included or not.
- I hope none
- but I may have misunderstood the desired behaviour 🙈 
Fixes: #1175 

Add empty tag to empty pages with only archived subpages

---

integreat_cms/cms/views/regions/region_actions.py
integreat_cms/release_notes/current/unreleased/2336.yml

This pr suppresses most linkcheck deletion listeners when deleting regions, which hopefully improves performance enough that deleting big regions will be possible again.
Currently the `Link` post_delete handlers from linkcheck will still run, which is unnecessary. However this is hopefully not a big problem, since those only run per link and not per page translation. 
- Delete regions with the `disable_listeners` context manager
- The db may be in an inconsistent state after deleting a region. However, this should only result in internal links to content of the deleted region not being flagged as broken. Also the db will be fixed after the next run of the `findlinks` management command.
fixes: #2336 …

Improve performance when deleting regions

---

integreat_cms/static/src/js/user/organization.ts

Fixes an JS error in the News creation page that was caused by an unrelated-to-the-news piece of JS being triggered by the presence of HTML elements with matchinf IDs
- check if other relevant fields are present (and the JS code should run), don't run the offending function otherwise.
- 
- I assume none (😅)
- 
Fixes: #2561

Fix JS error in Region selection for News

---

integreat_cms/cms/templates/_collapsible_box.html
integreat_cms/cms/templates/analytics/translation_coverage.html
integreat_cms/release_notes/current/unreleased/2523.yml

This PR changes the width of the "text understandibilty" box from one to two columns and adds an additional parameter for the collapsible boxes template to allow boxes to also span two columns. 
- Change width of "text understandibilty" box from one to two columns
- Add parameter to enable boxes to also span two columns
I hope none
Fixes: #2523

Widen hix box

---

integreat_cms/cms/utils/slug_utils.py
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/1792.yml
tests/cms/utils/test_slug_utils.py

Currently regions can be created with slugs that are already in use in the webapp. The same goes for page patterns that should be reserved.
Some changes in this PR are required for #2391.
- Validate against reserved region patterns
- Validate against page patterns
Fixes: #1792 

Validate slugs against reserved patterns

---

integreat_cms/cms/forms/custom_content_model_form.py
integreat_cms/cms/templates/_tinymce_config.html
integreat_cms/cms/templatetags/settings_tags.py
integreat_cms/release_notes/current/unreleased/2453.yml
integreat_cms/static/src/js/tinymce-plugins/custom_link_input/plugin.js

This pr moves the code that marks external links as external from autolink plugin to python in order to ensure that all external links get correctly marked as such.
This pr does not automatically fix all links from content translations that already exist. I have opened a separate issue for that: #2491
- Add additional step to `clean_content`
- Remove functionality related to `link-external` from the frontend
/
Fixes: #2453

Auto add `link external` in backend

---

.circleci/config.yml
.github/workflows/codeql-analysis.yml
.pre-commit-config.yaml
README.md
integreat_cms/cms/utils/slug_utils.py
integreat_cms/matomo_api/matomo_api_client.py
integreat_cms/release_notes/2022/2022.2.0-beta/1017.yml
integreat_cms/release_notes/current/unreleased/2448.yml
pyproject.toml
tests/cms/views/view_config.py
tests/xliff/utils.py
tools/install.sh

Update supported Python version to 3.11
- Require Python 3.11
- Update the Python version running on CircleCI
- Dev environments running on Python 3.9 / 3.10 need to upgrade their Python version
Fixes: #2448

Update supported Python version to 3.11

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/release_notes/current/unreleased/2598.yml

Fixes the budget year start not being shown in case it was set to january
- explicitly check if the month is `None`, rather than truthy, because January is saved as `0`
- none 
Fixes: #2598 
(Sorry for taking a `good first issue`, just saw that its prio had been upped to high this morning)

Fix DeepL budget year start not being shown in the case of January

---

integreat_cms/cms/views/pages/page_actions.py
integreat_cms/release_notes/current/unreleased/2511.yml

This PR modifies the function `refresh_date` so outdated translations of the page will not be refreshed
- Filter outdated translations out before refreshing the translation time stamp.
- One additional loop: I think this is safer (avoiding that translations are counted accidentally as outdated due to the order of date refreshing) than checking the status by `is_outdated` or `is_up_to_date` here:
https://github.com/digitalfabrik/integreat-cms/blob/21d735c41312a475c7a16e2f3acc6f792283590d/integreat_cms/cms/views/pages/page_actions.py#L823-L825
Fixes: #2511 

Do not refresh outdated translations

---

integreat_cms/release_notes/current/unreleased/2595.yml
integreat_cms/static/src/js/machine-translation-overlay.ts

This PR fixes the pop-up of MT bulkaction so it again shows the warning text correctly.
- Fix a small typo 
- None? 
Fixes: #2595 

Fix pop-up of MT bulkaction

---

integreat_cms/cms/models/media/media_file.py
integreat_cms/cms/views/media/media_actions.py
integreat_cms/cms/views/media/media_context_mixin.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2585.yml
integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx
integreat_cms/static/src/js/media-management/index.tsx

This PR disables the delete button if the media file is in use and improve as back up the error message which is shown when users try to delete an used media file,
- Disable the delete button for used media files
- Improve the error message in case a media file in use is about to be deleted.
- The delete button is disabled in another way than I suggested in the issue. In my opinion it's better to disable it in the same way as it is disabled for non-empty directories.
Fixes: #2585 

Disable delete button for used media files and improve error message

---

integreat_cms/cms/views/utils/hix.py
integreat_cms/release_notes/current/unreleased/2577.yml
tests/textlab_api/textlab_api_test.py
tests/textlab_api/textlab_config.py

Currently HIX value can be manipulated by adding empty lines in a page, because if we send text with empty paragraphs to the TextLab API, it returns a better HIX value.
1. Enhance normalize_text function: 
- remove empty paragraphs
- add a div tag as root, if it's not there (it covers the case when the text has one non-empty paragraph + one or more empty paragraphs)
2. Add unit tests for normalize_text function
No?
Fixes: #2577

Fix HIX value diff when adding empty lines

---

integreat_cms/cms/forms/feedback/region_feedback_filter_form.py
integreat_cms/cms/templates/feedback/admin_feedback_list.html
integreat_cms/cms/templates/feedback/admin_feedback_list_archived.html
integreat_cms/cms/templates/feedback/region_feedback_list_archived.html
integreat_cms/cms/views/feedback/admin_feedback_list_view.py
integreat_cms/cms/views/feedback/region_feedback_list_view.py
integreat_cms/cms/views/utils/search_content_ajax.py
integreat_cms/release_notes/current/unreleased/2587.yml

Fix a few small bugs in feedback filtering
1. Fix the defect described in #2587
2. Fix the more-less buttons in archived feedback forms
3. Fix the following issue:
When a query search is applied, it ignores the "archived" attribute.
For example, this is a form for active feedback.
But if I try to search for a feedback by comment, it also adds archived feedback to the output (the first one is actually archived).
No?
Fixes: #2587

Fix feedback filtering errors

---

integreat_cms/release_notes/current/unreleased/2604.yml
integreat_cms/static/src/css/style.scss

In Chromium-based browsers, a duplicate 'x' for clearing search fields was inserted by the browser itself. This PR adds styling to hide this element.
- apply `display: none` to the duplicate 'x'
- none 
Fixes: #2604 

Remove duplicate 'x' in search fields

---

docs/src/management-commands.rst
integreat_cms/core/apps.py
integreat_cms/core/circleci_settings.py
integreat_cms/core/management/commands/duplicate_pages.py
integreat_cms/core/management/commands/find_large_files.py
integreat_cms/core/management/commands/find_missing_versions.py
integreat_cms/core/management/commands/fix_internal_links.py
integreat_cms/core/management/commands/hix_bulk.py
integreat_cms/core/management/commands/repair_tree.py
integreat_cms/core/management/commands/replace_links.py
integreat_cms/core/management/commands/reset_deepl_budget.py
integreat_cms/core/management/commands/send_push_notifications.py
integreat_cms/core/management/commands/summ_ai_bulk.py
integreat_cms/core/management/debug_command.py
integreat_cms/core/management/log_command.py
integreat_cms/core/settings.py
integreat_cms/core/storages.py
tests/core/management/commands/test_duplicate_pages.py
tests/core/management/commands/test_find_missing_versions.py
tests/core/management/commands/test_replace_links.py
tests/core/management/commands/test_reset_deepl_budget.py

In January, the cronjob for resetting the DeepL budget apparently did not work.
I noticed that its output is only written to stdout and not to the logfile, so I thought it would make sense to change this behavior, and while I'm at it for the other management commands as well.
- Use colored logging in CircleCI
- Write all management command output to logs
- It's not possible anymore to print something in white and/or bold in the output of management commands.

Write all management command output to logs

---

integreat_cms/cms/views/language_tree/language_tree_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/test_language.py

This PR adds tests for [the language node actions](https://codeclimate.com/github/digitalfabrik/integreat-cms/integreat_cms/cms/views/language_tree/language_tree_actions.py/source)
- Test `move_language_tree_node` and `delete_language_tree_node`
- Add `try` and `except ProtectedError` for the deleting action for better user experience (in case the delete button is somehow not deactivated)
- Creating and updating are not included in [the action file](https://codeclimate.com/github/digitalfabrik/integreat-cms/integreat_cms/cms/views/language_tree/language_tree_actions.py/source) and covered by `view_config` but created/updated objects are not checked. So tests for them are added as small aditionals 😸 
- None?
Fixes: #2582 
[Pull Request …

Add test for language tree node

---

integreat_cms/release_notes/current/unreleased/1589.yml
integreat_cms/static/src/js/filter-form.ts

This PR fixes the reset function for filter. 
- Set `value` of `select` Objects to "" (default).
- I decided against `HTMLFormElement.reset()` because this sets the choices back to the latest chosen values not the default.
- None?
Fixes: #1589 

Fix filter reset function

---

integreat_cms/static/src/js/analytics/hix-widget.ts

This PR fixes an error in our Javascript console that I became aware of while reviewing #2630 
- Make hixScoreWarning optional
- Make mtForm optional
- I think none?
Fixes: -

Fix Javascript error in hix widget

---

integreat_cms/core/management/commands/repair_tree.py

I just noticed the output of the repair tree command looks a bit weird in the log file:
```
Feb 01 15:26:39 INFO    integreat_cms.core.management.commands.repair_tree - Page 34339:
Feb 01 15:26:39 ERROR   integreat_cms.core.management.commands.repair_tree -    parent_id: None
Feb 01 15:26:39 INFO    integreat_cms.core.management.commands.repair_tree -    depth 4
lft: 1
rgt: 2
```
Maybe it would be better if all messages were aligned?
```
Feb 01 15:26:39 INFO    integreat_cms.core.management.commands.repair_tree - Page 34339:
Feb 01 15:26:39 ERROR   integreat_cms.core.management.commands.repair_tree -    parent_id: None
Feb 01 15:26:39 INFO    integreat_cms.core.management.commands.repair_tree -    depth 4
Feb 01 15:26:39 INFO    integreat_cms.core.management.commands.repair_tree -    lft: …
```

Fix output alignment in repair tree command

---

integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/release_notes/current/unreleased/2466.yml

This PR adds an apropriate message when a link from old versions is about to be replaced
- Chekck whether all the queried tranlations are the latest of each translation
- Show the new detailed message
- I know the loop `for translation in translations` is doubled in the function. This is to prevent  it that replacement is successfull in some of the translations but not in the others, so either the link will be replaced in all of the related translations or not at all.
- I left the utility function `replace_links` unchanged, for this works only on the latest versions.
Fixes: #2466 

Hide links from old versions in link checker

---

integreat_cms/cms/views/pages/page_actions.py
integreat_cms/release_notes/current/unreleased/2627.yml

Fix page order not being editable after changing the page's parent in the page form sidebar
- this was caused by the `can_edit_page` variable being set in the parent template, which isn't utilized in the ajax call. Now the permission check is handled in the ajax call and the passed along from there.
- none I am aware of
Fixes: #2627

Fix page order not being editable after changing the page parent

---

integreat_cms/cms/forms/custom_content_model_form.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2605.yml

Instead of showing the message meant for saving drafts, submitting pages for review now has its own success message.
- check if the to-be-saved content object is a Page and the user has permission to edit the page; if not, show the new success message
- tbh I am not super happy with the way checking the content type is done (against a hardcoded string), if someone has a better idea, I am all ears
- none afaik 
Fixes: #2605 

Fix review submission notification

---

integreat_cms/cms/forms/linkcheck/edit_url_form.py
integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
integreat_cms/release_notes/current/unreleased/2646.yml

Allow the central link replacement of URLs with UTF-8 characters in the domain name
- Apply the new `fix_content_link_encoding()` function not only in the forms, but also in the link checker
Fixes: #2646

Allow the central link replacement of URLs with UTF-8 characters

---

integreat_cms/cms/forms/linkcheck/edit_url_form.py
integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
integreat_cms/release_notes/current/unreleased/2646.yml

- [ [#2646](https://github.com/digitalfabrik/integreat-cms/issues/2646) ] Allow the central link replacement of URLs with UTF-8 characters in the domain name

Release `2024.2.1`

---

integreat_cms/cms/views/utils/hix.py
integreat_cms/release_notes/current/unreleased/2621.yml
integreat_cms/release_notes/current/unreleased/2652.yml
integreat_cms/static/src/js/forms/tinymce-init.ts
tests/textlab_api/textlab_config.py

Using root.iter() was not a good choice to iterate over the paragraphs, because it goes "one-way" deep into the nested elements.
For example, if a page has the following structure:
`<div><p>Some image</p><p><a href="some.image"><img src="some.image" alt=""></a></p><p>&nbsp;</p></div>`
The iteration will proceed as follows:
```
<div>
<p>
<p>
<a>
<img>
--> end of iteration
```
And the last p-node will not be processed.
Use list(root) instead of root.iter()
No?
Another follow-up to #2577
**UPD**: added another small HIX-related fix
Fixes: #2621

Fix HIX value diff when page content has nested tags

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/core/circleci_settings.py
integreat_cms/core/settings.py
integreat_cms/release_notes/current/unreleased/2343.yml
tests/cms/test_duplicate_regions.py
tools/test.sh

Reverts #2344.
- ~add a global task queue (implemetation almost identical to [django-linkcheck task queue](https://github.com/DjangoAdminHackers/django-linkcheck/blob/3d6188e5053469a36fedd307b75ecb02b15d0087/linkcheck/listeners.py#L19))~ Instead just create a thread where the links are replaced
- replace links when cloning content
- readd checks in the tests
- Technically there should be no multithread issue here, as django-linkcheck creates a lock when doing sth. like this, but I also did not explicitly test for side effects.
Fixes: #2343 

Perform link replacement as background task

---

integreat_cms/cms/models/regions/region.py
integreat_cms/release_notes/current/unreleased/2674.yml

Fix error when creating regions with the administrative division being included in the name
- Prevent `ValueError` when accessing language tree of unsaved regions
Fixes: #2674

Prevent `ValueError` when accessing language tree of unsaved regions

---

integreat_cms/cms/templates/feedback/region_feedback_list.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/feedback/region_feedback_actions.py
tests/cms/views/feedback/test_region_feedback_actions.py

Allow export to other formats supported by tablib / django-import-export
We were troubleshooting what looked like an encoding problem with feedback exported as CSV, and by the time we found that EXCEL was at fault and our CSVs were flawless, this was already half done. I figured I might as well clean it up and submit it as a low prio PR.
- Extend feedback export URL endpoint by `format` parameter
- Check if requested format is available through the dependency library
- Automatically determine mime type
- We just throw a ValueError if the format is not available. This is likely not the most elegant solution, but at the moment we hard-code which format can be requested through the UI anyway.
none …

Dynamic export formats

---

integreat_cms/cms/templates/push_notifications/push_notification_form.html
integreat_cms/release_notes/current/unreleased/2694.yml

Fix the bug where checkboxes became disabled because of the overflow-scroll property in Chromium and Firefox on Windows.

Fix region selection in push news form

---

integreat_cms/cms/forms/custom_content_model_form.py
integreat_cms/release_notes/current/unreleased/2691.yml
integreat_cms/static/src/js/forms/autosave.ts

This PR fixes 2 issues:
1. Since we kept the state of automatic translation checkbox, some automatic translations were made accidentally (details in #2691)
2. When the automatic translation checkbox was checked, autosave did not work. It caused an error "The options "automatic translation" and "minor edit" are mutually exclusive"
- Set the automatic translation to unchecked by default unless manually enabled (the same behavior as for minor edit)
- Delete automatic translation attributes from the form data on autosave
No?
Fixes: #2691

Set the automatic translation to unchecked by default

---

integreat_cms/cms/utils/stringify_list.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2692.yml

This pr limits the maximum number of items displayed in feedback messages in order to avoid visual clutter.
Add a parameter to `iter_to_str` to stop after a given number of objects (default 5).
If there are more objects to be displayed, the message will only note that there are more objects. 
Fixes: #2692 

Limit the maximum number of items displayed in feedback messages

---

integreat_cms/cms/forms/poi_categories/poi_category_translation_form.py
integreat_cms/release_notes/current/unreleased/2708.yml

This PR fixes `ValueError` triggered when an user tries to create a new POI category.
- Check whether the POICategory object already exists before filterling out languages
- None? 🙈 
Fixes: #2708 

Fix error when creating a new POI category

---

.circleci/config.yml
integreat_cms/core/circleci_settings.py
integreat_cms/core/settings.py

Sometimes we encounter test failures in CI that are not reproduced locally.
We can see some pieces of the log in the test output, but sometimes it's not enough to localize the problem.
To make the analysis a bit easier, I suggest attaching full integreat-cms.log as a job artifact.
It will only be available when there are test failures:
- add step "Copy CMS log" to the test job in CI
No?
I think it would also be useful to set the logging level to DEBUG, but I couldn't find how to do that :(
I thought this was supposed to be managed by
```
#: Use debug logging on CircleCI
LOG_LEVEL = "DEBUG"
```
in circleci_settings.py, but no. 
The actual log level in CI is currently INFO.
[log example](https://circleci-tasks-prod.s3.us-east-1.amazonaws.com/storage/artifacts/ffe45036-8130-48f0-859b-fdbbd736 …

Store integreat-cms.log as an artifact after test run in CI

---

docs/src/index.rst
integreat_cms/core/settings.py
integreat_cms/textlab_api/textlab_api_client.py

Adjust the benchmark ("Textsorte") ID to ask of the Textlab API, improve documentation
- Make the ID a parameter rather than hardcoded
- Previously we used an ID of `5` (whatever that might have been). Since Textlab implemented proper checks and we are only able to use `420` through `424`, and all of those provide the HIX value and we discard the rest anyway, just use `420` as the default
- Maybe the default should be in the settings instead?
- Or furthermore, in theory, robust business logic should query all available benchmarks containing the HIX value from the `/benchmark` endpoint of the API (with a query string) and select the one with the fewest / least costly other metrics. But this is likely overkill.
- Improve the documentation a bit
- Update the Project Architecture (in the …

Adjust Textlab benchmark ID

---

example-configs/integreat-cms.ini
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/summ_ai_api/summ_ai_api_client.py

- Add a new environment variable `SUMM_AI_PLAIN_GERMAN_REGIONS` to list regions that want to use plain German in the bulk MT action.
- Set `output_language_level` to `plain` if the region is listed in `SUMM_AI_PLAIN_GERMAN_REGIONS` **and** the MT translation request is made per bulk action.
- Change the language name in the description of bulk SUMM.AI translation to `German (plain)` if it is the case of `output_language_level = "plain"`.
- None? 🙈 
Fixes: #2670

Add option to translate into Plain German

---

integreat_cms/cms/constants/duplicate_pbo_behaviors.py
integreat_cms/cms/forms/regions/region_form.py
integreat_cms/cms/templates/regions/region_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2665.yml
tests/cms/test_duplicate_regions.py

Currently, cloning a region which has embedded offfers into pages can lead to unexpected errors when the newly-created region does not have the same offers enabled.
- allow users to choose from two behaviors when cloning a region: either force-activate all required offers\* or discard embeddings for missing offers when cloning pages.
- \* small caveat: if no Zammad URL is provided for the new region, Zammad embeddings are discarded even when force-activation is selected
- none that I could find. As far as I can tell, results are correct in all cases (no cloning, cloning with force-activation or discarding, with/without Zammad URL) 
Fixes: #2665 
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-rev …

Fix behavior when cloning region with page based offers

---

integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/poi_categories/__init__.py
integreat_cms/cms/views/poi_categories/poi_category_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Deleting a POICategory still in use by POIs is discouraged by disabling the delete button in the list view. If a request reaches the delete endpoint anyways, an internal server error is displayed. This PR catches the exception and displays a helpful message instead.
- Implement a custom `POICategoryDeleteView` which subclasses `CustomDeleteView` and acts as a simple wrapper around its `post()` logic:
- If a `ProtectedError` is raised, a helpful message is added to the request context and the browser is redirected back to the list view.
- If in the future there are other reasons how a `ProtectedError` could arise, the current message might be misleading.
Fixes: #2733 …

Display helpful message when deleting POICategory fails

---

docs/src/tools.rst
tools/prune_pdf_cache.sh
tools/test.sh

This PR adds a helpful tool to prune the pdf file cache so you don't have to remember the which directory to delete whenever PDF tests fail but probably not because of you.
- adds `tools/prune_pdf_cache.sh` which essentially just runs `rm -rfv "integreat_cms/pdf"`
- list the tool in the documentation
- prune pdf cache before running tests
- pruning the PDF cache deletes the whole cache, not only the files specific to the tests

Add tools/prune_pdf_cache.sh

---

integreat_cms/cms/views/feedback/region_feedback_actions.py

Fixes #2650
* #2650
https://tablib.readthedocs.io/en/stable/api.html suggests that:
> You can also set rows and headers upon instantiation.
- Instantiate the `Dataset` with all data up front instead of repeatedly calling `Dataset.append()`
- Also, use [`Dataset.export("csv")`](https://tablib.readthedocs.io/en/stable/api.html#tablib.Dataset.export) which is documented instead of `Dataset.csv` which is not.
- I do not know how to test or benchmark this beyond the current pytests.
- 
Fixes: #2650

Speed up CSV export by instantiating dataset with data and headers

---

.circleci/config.yml
.pre-commit-config.yaml
integreat_cms/cms/decorators.py
integreat_cms/cms/models/events/recurrence_rule.py
integreat_cms/cms/templatetags/page_filters.py
integreat_cms/core/circleci_settings.py
integreat_cms/core/signals/auth_signals.py
integreat_cms/matomo_api/matomo_api_client.py
integreat_cms/sitemap/sitemaps.py
integreat_cms/summ_ai_api/summ_ai_api_client.py
pyproject.toml
tests/cms/test_language.py
tests/cms/test_media_library.py
tests/cms/views/feedback/test_admin_feedback_actions.py
tests/cms/views/feedback/test_region_feedback_actions.py

Lint Python code with [`ruff`](https://docs.astral.sh/ruff) which is a superset of `black`, `isort`, `mccabe`, `pylint`, `pylint-django`, and numerous other Python linting tools.  It is written in Rust to be able to consistently lint and format the repo in well under one second.
- Lint Python code with ruff.
- Make minor fixes to enable several linters.
- Put `ruff format` in place but disable it until a follow-on pull request.
Fixes: #2442

Lint Python code with ruff

---

integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/models/push_notifications/push_notification.py
integreat_cms/release_notes/current/unreleased/2726.yml
tests/cms/models/push_notifications/test_push_notification.py

This pr fixes a problem that the `best_translation` method of push notifications prefers translations without title over translations with title.
- Only return the backend translation if it has a title
- 
- 
Fixes: #2726

Fix push notification bug

---

integreat_cms/cms/templates/pages/page_form.html
integreat_cms/release_notes/current/unreleased/2689.yml

Change the order of the HIX and the translation blocks. Bring the translation block above the HIX block so that the municipalities   do not oversee it.
- Change their order by bringing the translation block on top of the HIX block
- none
Fixes: #2689 

Change order of the HIX block and the translation block

---

integreat_cms/cms/templates/hix_widget.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2750.yml
integreat_cms/static/src/css/style.scss
integreat_cms/static/src/js/analytics/hix-widget.ts

Update the HIX widget according to the [new design](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?type=design&node-id=1013%3A646&mode=design&t=CoWs1wUEUXzZiKM4-1)
(feedback on the HIX value is not included)
Our current behavior with the "HIX ignore" flag was preserved (as discussed in https://github.com/digitalfabrik/integreat-cms/issues/2358)
I also kept our old update button and old state icons because I think they are nice 🥺
But feel free to object.
- no?
Fixes: #2688

Make HIX widget more compact

---

integreat_cms/cms/models/push_notifications/push_notification.py
integreat_cms/cms/views/push_notifications/push_notification_form_view.py
integreat_cms/firebase_api/firebase_api_client.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2722.yml

This pr makes the title field in the push notification form required for every language that is a default language in one of the push notifications regions. This fixes two issues:
- Previously, only the title field of the first language of the query was required, even if it differed from the primary regions language.
- With the first problem fixed, it was still undefined what happened if a push notification was assigned to two regions with different default languages. The title was arbitrarily required for the language of either region, but not both.
- Require the title field for all region default languages in push notification form
- Do a small refactor on the push notification form view post handler, to make it easier to add this functionality
It is still arbitrary what will be used as …

Require the title field for all region default languages in push notification form

---

tests/conftest.py
tests/deepl_api/deepl_api_test.py
tests/mock.py

Add mock_server fixture that can be re-used in tests.
This is a wrapper for pytest_httpserver, which can be extended with useful features.
For example, currently it allows to count incoming requests (to be re-used in https://github.com/digitalfabrik/integreat-cms/pull/2669)
- add mock_server fixture
- use mock_server fixture in deepl_api_test.py
- no?
Fixes: #

Add mock_server fixture for tests

---

package.json
tools/_functions.sh
tools/test.sh

This pull request introduces a precondition to the `test.sh` tool, ensuring that the webpack output is available. This precaution is necessary because otherwise, the tests would fail when someone runs `./tools/test.sh` in an environment where the application hasn't been initialized.

Ensure that webpack bundle exists before running tests

---

.circleci/config.yml
docs/src/packaging.rst

I hope this fixes our publishing of the dev packages to TestPyPI which is failing since last week.
I assume the build fails are due to this change in setuptools:
- Support [PEP 625](https://peps.python.org/pep-0625/) by canonicalizing package name and version in filenames. ([#3593](https://github.com/pypa/setuptools/issues/3593))
https://setuptools.pypa.io/en/latest/history.html#v69-3-0
So my hope is that by adapting the new package name to the canonical form, everything should be fine. I guess the actual package name on PyPI probably remains the same.

Adapt package dist naming to PEP-625

---

integreat_cms/cms/models/media/media_file.py
integreat_cms/cms/views/media/media_actions.py
tests/cms/models/media/test_media_file.py

This pull request changes the `deletable` flag of the [media_file.py](https://github.com/digitalfabrik/integreat-cms/blob/7f9085f9b8eb13d6639aaafd1efaad1625868c77/integreat_cms/cms/models/media/media_file.py#L2) in a such a way that it is true when only used by events in the past.
- [Media items used in past event should be deletable](https://github.com/digitalfabrik/integreat-cms/issues/2634)
Fixes:  #2634

Deletable media files that are attached to past events only

---

integreat_cms/cms/templates/feedback/admin_feedback_list_row.html
integreat_cms/cms/templates/feedback/region_feedback_list_row.html
integreat_cms/cms/templates/generic_auto_save_note.html
integreat_cms/cms/templates/languages/language_list_row.html
integreat_cms/cms/templates/offertemplates/offertemplate_list_row.html
integreat_cms/cms/templates/pages/page_tree_archived_node.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/templates/regions/region_list_row.html
integreat_cms/cms/templates/settings/user_settings.html
integreat_cms/core/formats/en/__init__.py
integreat_cms/core/formats/en/formats.py
integreat_cms/release_notes/current/unreleased/2706.yml

Change current timestamp format for last update ( I realized that we also need to change all timestamps as well like `created` `last login`, `last usage`, and `date added`) to make a quick overview easier and not so cluttered with long date string. It might be better to remove time for not so relevant components like pages, languages, regions, feedback and include time to chat, user last login, events, and content versions. 
- Change timestamp format for short and remove time for not relevant components
- Change timestamp format for short and add time for relevant components, like chat, content versions, events and user's last login
None?
Fixes: #2706 
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-requ …

Use a consistent format for date and time

---

integreat_cms/cms/forms/media/replace_media_file_form.py
integreat_cms/cms/models/media/media_file.py
integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/cms/views/media/media_actions.py

Update media file paths when uploading a new file in order to avoid caching problems.
Instead of making sure that a path gets reused when a media file is replaced, always create a new path for the new file, so that no caching problems occur.
This is done by prepending the epoch time to the filename.
Then replace all internal links to the old path with links to the new
path.
- Hopfully none, old file paths should still work
Fixes: #1168

Update media file paths

---

integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/templates/analytics/_page_hix_row.html
integreat_cms/cms/templates/content_versions.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_low_hix_row.html
integreat_cms/cms/templates/hix_widget.html
integreat_cms/cms/utils/round_hix_score.py
integreat_cms/cms/views/utils/hix.py
integreat_cms/release_notes/current/unreleased/2756.yml
integreat_cms/static/src/js/analytics/hix-widget.ts

This PR adjusts the hix widget and hix score check to align with the score shown in the hix widget.
- Use up-rounded value when
1. toggling the color of HIX bar
2. toggling the check box for machine translation
3. checking HIX score for machine translation
- <s>There are three ways of rounding up HIX value: `|floatformat:2` (existing) in template, `Math.round(hixValue * 100) / 100` (existing) in Typescript and `round(self.hix_score * 100) / 100` in python (new). There might be cases where they do not align each another 🙈 </s>
Fixes: #2756 

Use uprounded HIX value

---

.circleci/config.yml
pyproject.toml

Apparently, f23a3eae4c4be1b393c087e921f2fef3c421eea5 and c7c84d979dfb5f310e68f784a9fbf48f99919020 were not enough to fix the problem.
- Use `bumpversion.version.parse_version` instead of `looseversion.LooseVersion`
Fixes: #2190

Fix version parsing in CircleCI

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.gitignore
.vscode/tasks.json
README.md
tools/install.sh

This Pull Request adds a devcontainer definition to make the project setup easier and streamline the onboarding process of new devs.
I encountered some difficulties during onboarding and initial setup of the project, which I aim to automate with this addition. Through discussions in the chat, I learned that most people here develop with VSCode, so I thought that a devcontainer would be the appropriate solution.
- Initially, I installed a too-new patch of Python 3.11, which caused some issues and required downgrading.
- The translate.sh script expects the GNU variant of sed, which needs to be installed separately on macOS. Additionally, it needs to be either changed in the script to gsed instead of sed or overridden with an alias. The base image of the devcontainer includes the correct sed …

Add devcontainer definition

---

integreat_cms/cms/models/languages/language_tree_node.py

This modifies the docstring to reference django-treebeard instead of django-mptt. Earlier today, I read the documentation and was puzzled by why the passing classes import from treebeard. Subsequently, I discovered this [release note](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/release_notes/2022/2022.2.0-beta/1088.yml).

 Replace the reference to django-mptt with a reference to django-treebeard in the docstring

---

integreat_cms/cms/forms/linkcheck/link_replace_form.py
integreat_cms/release_notes/current/unreleased/2714.yml

This PR fixes the probelem that the central link replacement showed the success message but the replacement was not done as expected.
The cause of reported problem is the length of fields for old and new links: the replacement was conducted successfully but the link was changed only in the first letters.
- Make the input fields accept longer links
- None? 😅 
Fixes: #2714

Make input fields of link replacement longer

---

integreat_cms/cms/views/analytics/translation_coverage_view.py
integreat_cms/cms/views/dashboard/dashboard_view.py
tests/cms/utils/test_rounded_hix_value.py

This is a follow up PR for #2760, in which still raw HIX score is used in the dashboard/analytics view.
How to reproduce:
1. Enable HIX in Augsburg and fill its pages with HIX value by `hix_bulk`.
2. Go to Augsburg, find 9 in "Pages with low hix score" in ToDo list and "Overview of the text understandability of the pages".
3. Add the two pages listed in the Issue #2756 
4. See 10 instead of 9 in "Pages with low hix score" and "Overview of the text understandability of the pages", while both the pages shuold be good enough in the HIX score check.
- Use rounded HIX score
- Tell me please if you find other points that are to be adjusted too 👀 
Fixes: #
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request …

Use rounded HIX score for dashboard

---

docs/src/prod-server.rst
example-configs/integreat-cms.ini
integreat_cms/core/circleci_settings.py
integreat_cms/core/settings.py
tools/_functions.sh

In #2759 I forgot to update references to `FCM_KEY` which got renamed in that pr. 
- Rename all occurences of `FCM_KEY` to `FCM_CREDENTIALS`, which is the new name

Fix outdated references to FCM_KEY

---

integreat_cms/gvz_api/utils.py

If a region name is available but no AGS, the AGS should be determined with the GVZ API.
- Search for AGS if region name is available but AGS is not
- Only set region name from API if it does not override an existing name (most likely entered manually)
- N/A
Fixes: https://chat.tuerantuer.org/digitalfabrik/threads/tczb6bt38pg9xy8i3f5z7sfrka

GVZ: search region by name

---

integreat_cms/firebase_api/firebase_api_client.py
integreat_cms/release_notes/current/unreleased/2025.yml

This PR add an error handling for invalid FCM URL.
**update**
This takes care of timeout exception too. I've totally forgotten that those two issues are related each other.
- Catch errors and show an error message to users 
- The error message is left universal (not specific to any error type) because many types are possible. 
- The rendering after failing of a push notification is partially broken. 
- A question regarding this rendering: don't we want to redirect not no the create view but to the edit view becuase the push notification is saved in this case?
- I'll suggest to fix the rendering in a separate PR/issue.
Fixes: #2025 , #2790 
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-gu …

Catch and handle errors of FCM

---

integreat_cms/release_notes/current/unreleased/908.yml
integreat_cms/static/src/js/tinymce-plugins/autolink_tel/plugin.js

Automatically transform phone numbers to international standard.
- prepend phone number link targets with `+<country code>`
- prettyprint the internationalized phone numbers for better readability
- none
Fixes: #908 

Automatically transform phone numbers to international standard

---

tools/_functions.sh

This pull request updates the `wait_for_docker_container` function in our shell script to fix the waiting mechanism on macOS, which currently hangs forever, as demonstrated in the attached video.
- Removed the docker run flags, as the waiting mechanism works without them.
- Added echo statements to provide feedback during the waiting period.
The script was tested on macOS to ensure it does not hang and correctly waits for the Docker container to be ready. It'd be nice if someone can test the script on a Linux environment to verify that it maintains compatibility.

Start docker container without -t flag on macOS

---

tools/update_dependencies.sh

I noticed a small bug in the depencency script which causes an error `error: externally-managed-environment` on systems which comply to [PEP 668](https://peps.python.org/pep-0668/).
- Activate venv before installing upgraded versions

Fix missing venv activation in update script

---

.circleci/config.yml
.eslintrc.js
.pre-commit-config.yaml
integreat_cms/static/src/js/__tests__/utils/mfa-utils.test.ts
package-lock.json
package.json
tools/vitest.sh
vitest.config.ts

This pull request configures vitest and adds a simple test as suggested in my review of [deps/upgrade_webauthn_2_0](https://github.com/digitalfabrik/integreat-cms/pull/2716).
- Added a test task to `package.json`
- Included required vitest dependency
- Implemented a simple test for URL and base64 encoding
- Configure vitest to ignore python dependencies
- Configure import/resolver to resolve imports correctly
- Add job to circleci workflow

Add vitest for frontend testing

---

docs/src/api-docs.rst
integreat_cms/api/v3/push_notifications.py

Currently it is not possible to switch languages of the news. Available languages property should be added to push_notifications endpoint.
- Add `available languages` to push notifications endpoint
- Make proper changes in push_notification and push_notification_translation models
-None?
Fixes: #2707 

Add available_languages to news endpoint

---

.pre-commit-config.yaml

https://github.com/pre-commit/mirrors-prettier
* prettier/prettier#16229
One of the other options could be used:
* https://github.com/prettier/prettier/blob/main/docs/precommit.md
```diff
- repo: https://github.com/pre-commit/mirrors-prettier
rev: v4.0.0-alpha.8
hooks:
- id: prettier
additional_dependencies:
- prettier@3.2.5
```
- - -
Unrelated CodeQL warnings: https://github.blog/changelog/2024-01-23-codeql-2-16-python-dependency-installation-disabled-new-queries-and-bug-fixes/
- 
- 
- 
- 
Fixes: #

pre-commit: Remove prettier because the repo is now archived

---

integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/release_notes/current/unreleased/2067.yml
tests/cms/views/pages/test_page_translations.py

Delete all old autos-saves and renumber all affected versions to be continuous.
- we implemented a static method `cleanup_auto_save()`. This method clears all auto-save except the last three (per default). 
- Then we used the `bulk_update()` method to update the version of the pages.  
- Adds a test for this functionality
- when we renumbering auto-save `bulk_update()` we previously got `IntegrityErrors` , probably because postgresql enforced unique constraints before the update statement was finished. We implemented the workaround using individual Data base statement in a `For-`loop, but revisiting this now we cannot reproduces this. We reverted to `bulk_update()` but please test this thoroughly to sure  this doesn't  break. 
Fixes: First part of #2067 …

Clean-up translation version history

---

tools/_functions.sh
tools/vitest.sh

This pull request addresses the issue where the Vitest tools fail if the node_modules directory is missing.
- If node_modules is not found, npm install is executed silently (with output redirected to /dev/null).

Ensure node_modules are in place before running vitest

---

integreat_cms/cms/views/media/media_context_mixin.py
integreat_cms/release_notes/current/unreleased/2623.yml
integreat_cms/static/src/js/media-management/component/upload-file.tsx
integreat_cms/static/src/js/media-management/index.tsx
integreat_cms/static/src/js/media-management/library.tsx
integreat_cms/static/src/js/media-management/select-media.tsx

Currently the upload form on icon set on the editor form of pages does not correctly validate the accepted uploaded files. If the unaccepted file is uploaded, it is removed after 5 seconds. The expected behaviour is that it shouldn't be removed from the upload input and should show type error on mouse over.
- Create an object called mediaTypes with a key "allowedMediaTypes" and set the type "any" to it (it was undefined when it was set to string and seems like directly assigning it in a component resulted in an undefined property value)
- Fix importing of mediaTypes in other files and components
- File types filter on file select can be left as it is because based on the browser it behaves differently (Firefox shows now filters with accepted types, Chrome only shows filters like …

Fix upload file behavior on set icon form

---

integreat_cms/cms/forms/machine_translation_form.py
integreat_cms/cms/templates/pages/page_form_sidebar/minor_edit_box.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2838.yml
integreat_cms/static/src/js/pages/xliff-export-overlay.ts

This PR adds the option to "select all languages" when creating a new page / creating new translations.
- Add option to select multiple languages in the page form at once
- In order to reuse the existing code I now had to twist my way around it. Maybe this is too much spaghetti already. If you have any suggestions on how to make this cleaner, I'm very interested to know! :)
- It might be necessary to add more language nodes to the default language first, as our unchanged test data provides only one child language for our default language
- It's a bit easier to test this when creating a new page than when updating a new page 
Fixes: #2838
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guid …

Add a select-all button to language selection in page form

---

integreat_cms/cms/models/users/user.py
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/views/pages/page_tree_view.py
integreat_cms/cms/views/utils/slugify_ajax.py
integreat_cms/static/src/js/forms/prevent-premature-submission.ts
integreat_cms/static/src/js/forms/update-permalink.ts
tests/cms/views/view_config.py

I had a bit of trouble reproducing the issue. The only way I could trigger it was by entering Firefox's Responsive Design Mode and enabling Touch Simulation (though I suspect this might also happen on real touch devices).
I don't think this is worth an entry in the change log, this really is an edge case.
- if the content form is submitted while we're still waiting on a response for `slugify`, prevent the submission, then trigger it again once the previous call completed.
- hopefully not
Fixes: #2624

Update page link before submitting page form

---

tests/textlab_api/textlab_api_test.py

This PR for testing HIX score representation on page create
Tests for:
- HIX score is requested and saved when the page translation is created and published
- HIX score is not requested when when the page translation without content is created and published
Relates to: https://github.com/digitalfabrik/integreat-cms/issues/2582

Create page tests for HIX signals

---

integreat_cms/release_notes/current/unreleased/2877.yml
integreat_cms/static/src/js/analytics/hix-widget.ts

This PR fixes HIX feedback display in the page form.
- For bug A: check whether the HIX feedback is empty so `feedbackCount` does not go up
- For bug B: accept the old format and recast `feedbackResult` in the case.
Fixes: #2877 

Fix feedback display

---

integreat_cms/cms/models/push_notifications/push_notification.py
integreat_cms/cms/templates/push_notifications/push_notification_list_row.html
integreat_cms/core/management/commands/send_push_notifications.py
integreat_cms/core/settings.py
integreat_cms/firebase_api/firebase_api_client.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/core/management/commands/test_send_push_notifications.py

This pull request introduces a new setting to control the retention time for notifications. Notifications that exceed the specified retention time will no longer be sent and will be marked accordingly in the user interface.
- Add `NOTIFICATION_RETAIN_TIME_IN_HOURS` that can also be set through environment variables as recommended in [The Twelve-Factor App](https://12factor.net/config)
- Implement `is_overdue` function in the PushNotification class to be used by the HTML template
- Add new case to the [push_notification_list_row.html](https://github.com/digitalfabrik/integreat-cms/pull/2861/files#diff-83cf1391d28d5cc93fd2655748cb3664e7ac4fcffe32b7fc71aa0542ec13c402)
- Add retention time filter to [send_push_notifications.py](https://github.com/digitalfabrik/integreat-cms/pull/2861/files#dif …

Don't send news when they're overdue

---

integreat_cms/cms/models/events/event_translation.py
integreat_cms/cms/models/pois/poi_translation.py
integreat_cms/cms/views/utils/search_content_ajax.py
integreat_cms/release_notes/current/unreleased/1639.yml

This pr modifies the search of pois and events to include fallback translations.
- Additionally search for objects in the default language and include them in the result if they don't have a translation in the requested language
- In search_ajax, check if the translation matches the expected language, and if not, use its fallback translation
- The generated SQL query looks a bit scary :eyes:
- This implementation does not make use of the `fallback_translation_enabled` property and thus adds a bit of overhead if we decide to change for which objects fallback translations are enabled
- Since the `search` method is used in other places too, these will now receive results that are potentially not in the request language. AFAIK this only affects the search functionality of the filter form and …

Return fallback translations in search

---

integreat_cms/release_notes/current/unreleased/2854.yml
integreat_cms/static/src/css/tinymce_custom.css
integreat_cms/static/src/js/tinymce-plugins/autolink_tel/plugin.js

Add LTR marker to `notranslate` texts and do not translate phone numbers
- add `dir="ltr"` to the existing `toggleNoTranslate` function
- add the wrapping `span` to phone numbers
- add class to overwrite the red background. IMO it's confusing when applied to phone numbers, esp. since it's applied automatically and might lead users to assume that something is wrong with the phone number they just entered.
- none
Fixes: #2854

Add LTR marker to `notranslate` texts and do not translate phone numbers

---

integreat_cms/cms/models/users/user.py
integreat_cms/cms/templates/users/region_user_list.html
integreat_cms/cms/templates/users/region_user_list_row.html
integreat_cms/cms/templates/users/user_list.html
integreat_cms/cms/templates/users/user_list_row.html
integreat_cms/cms/views/users/user_list_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/1915.yml

This pull request introduces information about users' multi-factor authentication mechanisms. The user list now includes a new 'Security' column, displaying a green checkmark if at least a second factor is configured, or a red x otherwise.
- Annotate the query with has_fido_keys
- Add has_totp property to the user model
- Introduce a new column in both user_list and region_user_list
- Include the used translations in the .po file
Fixes: #1915

Add information about mfa to user list

---

integreat_cms/release_notes/current/unreleased/2893.yml
integreat_cms/textlab_api/textlab_api_client.py

This PR wants to solve the problem that HIX feature is currently not working in Integreat (and in Malte too?).
So far as I googled, the value which will be set as `User-Agent` to requests without `User-Agent` setting in the header, is causing TextLab to reject our requests
- Set `User-Agent` into the header
- None?
- Suggestion for a better value setting for `User-Agent` will be welcomed :)
Fixes: #2893 

Fix blocked HIX request

---

integreat_cms/cms/templates/hix_widget.html
integreat_cms/release_notes/current/unreleased/2853.yml

This PR fixes the problem that HIX score in the hix widget was shown with decimals cut off if German is chosen in the settings (form example, 14 instead of 14, 99). 
- No change in the calculation logic
- Replace `,` to `.` so `parseFloat` works well.
- HIX score is shown with `.` even in German (Currenlty in German 14,99 with comma, but now 14.99 with point). If this is too bad I'll do something for that 😅 
Fixes: #2853 

Fix HIX value display in the HIX widget

---

integreat_cms/cms/forms/custom_content_model_form.py
integreat_cms/cms/utils/content_utils.py
tests/cms/utils/test_content_utils.py

This PR attempts to clean up the code of `clean_content` a little bit. As this is my very first attempt at refactoring empathic and honest feedback is much appreciated. In general I tried to follow instructions and ideas from "Clean Code" by Robert C. Martin, but I'm not 100% sure if I was successful.
- Split up `clean_content` into multiple sub-methods
- Remove pylint ignores
- Write a test for the method and it's sub-methods
- None that I'm aware of. Thorough double-checking is much appreciated.
Fixes: #2849

Refactor `clean_content`

---

example-configs/integreat-cms.ini
integreat_cms/cms/models/languages/language.py
integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/core/settings.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2890.yml

This PR deactivates PDF ecport for languages that are specified in the newly introuced variable `PDF_DEACTIVATED_LANGUAGES`.
I know there is an ongoing discussion about the in-browser PDF function as alternative, but opened this PR because the implementation for deactivating was already done before it started 😅 We can of course discard this if we decide for the in-browser PDF function and it can be implemented quickly, or use this as temporary bridge until it comes into the production.
- Add a new variable in which slugs of languages can be listed for which the PDF function should be deactivated
- Gray out the PDF bulk action if it is disabled for the current language and show an warning as tooltip
- None?
Fixes: #2890 
[Pull Request …

Deactivate PDF export for some languages

---

integreat_cms/cms/fixtures/test_data.json

This pr fixes a bug where it was impossible to modify groups in migrations, because they were always overwritten by their values from the test data. It was an oversight from #2781 that the new test data file contains auth values.
The updated command I used to generate the test data is `./tools/integreat-cms-cli dumpdata --natural-primary --natural-foreign --exclude auth --exclude contenttypes --o test_data.json`
- Exclude `auth` models and `contenttypes` models from the test data (Unfortunately this caused some shuffling around in the test data)
- Test data now also contain some values that were forgotten to add in previous pull requests
/
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-gu …

Remove 'auth' and 'contenttypes' objects from testdata

---

docs/src/documentation.rst

Building docs suddenly failed with `WARNING: undefined label: 'sphinx:python-roles'` apparently caused by a restructuring (no pun intended) of the docs about sphinx itself. This was also indicated by the label `sphinx:usage/restructuredtext/domains` rendering as a link named *[MOVED: Domains](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html)* (which was clearly not intended with the text flow), which pointed to a stub with redirections to the new location of moved content.
- update both labels to point to the content likely originally intended by the author of the docs
none
Fixes failing pipeline for #2904

docs: fix `WARNING: undefined label: 'sphinx:python-roles'`

---

integreat_cms/cms/templates/pois/poi_form_sidebar/action_box.html
integreat_cms/cms/templates/pois/poi_list_row.html
integreat_cms/cms/views/bulk_action_views.py
integreat_cms/cms/views/pois/poi_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2906.yml
tests/cms/views/poi/test_poi_form.py

This PR deactivates archiving for POIs that are used in events.
- Use the same logic with deactivating deletion for POIs in use
- Almost same information is shown in the action box in the form both for archiving and deleting when those are deactivated with only slight wording difference "delete" vs "archive". Unifying both section came into consideration but the design has been kept and the warning is shown twice, because in my opinion users are used to seeing two different sections for each deleting and archiving.
Fixes: #2906 

Prevent POIs in use from being archived

---

integreat_cms/matomo_api/matomo_api_client.py
integreat_cms/release_notes/current/unreleased/2905.yml

Change the line color in statistics on the dashboard from the grey color to the black for the total accesses.
- Add border-color to total-accesses
none
Fixes: #2905 

Change line color in statistics on the dashboard

---

docs/src/api-docs.rst
integreat_cms/api/v3/push_notifications.py

Currently the id of the news has a string type. The id should be a numeric type like in other endpoints.
- Remove stringify from id
Fixes: #2927 

Fix stringified id of the news

---

integreat_cms/cms/templates/dashboard/_todo_dashboard_row.html
integreat_cms/cms/templates/dashboard/_todo_dashboard_widget.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_broken_links_row.html
integreat_cms/cms/templatetags/tagifnotempty.py
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/2024/2024.7.0/2824.yml
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/dashboard/broken-links.ts
tests/cms/views/dashboard/test_dashboard.py

This PR adds an AJAX call for the link checker row on our To-Do-Board in order to hopefully increase the loading times so we can enable the row on our system.
- Add an AJAX call for the broken link context
- Add additional optional properties to the HTML template
- The loading times were normal for 1200+ pages in one region (but only 7 regions and not a lot of pages in the other regions). Is there a way to test this more reliably before merging it and testing it on the test system? 
Fixes: #2824

Add link checker to the `to-do-board`

---

integreat_cms/firebase_api/firebase_api_client.py

To implement ticket #589 and display the number of users who will be reached by a notification (news), I've added the region as an analytics label to all Firebase Cloud Messaging (FCM) calls. The original plan was to call an API that returns the count of subscribed devices per Firebase topic. Unfortunately, Firebase does not offer such an API.
By adding the analytics label, we can leverage the [Firebase Cloud Messaging Data API](https://firebase.google.com/docs/reference/fcmdata/rest) to get an approximate number of delivered messages per topic. It will take some time for users on the live system to send push notifications, and for the API to deliver real data grouped by the analytics label.
Therefore, I propose merging this pull request first so that I can work on the analytics aspect in …

Attach region as analytics label to fcm call

---

integreat_cms/cms/models/abstract_tree_node.py
tests/core/management/commands/test_send_push_notifications.py

suggest to use Node.add_root(), node.add_child() and node.add_sibling() instead
Tests not depending on test data fixtures but creating DB objects prior to assertions are self contained and thus very easy to understand. While values like the primary key are suitibly selected by the django ORM without problems of collision and values for foreign keys are determined by passing the desired model object to the ORM function, relationships like [the expectation that any combination of `lft` and `tree_id` values must be unique for models inheriting from `AbstractTreeNode`](https://github.com/digitalfabrik/integreat-cms/pull/2596/commits/38812657c30bf342b7b40ed2807c7867dc2cac51#diff-49c75de4c1fa67b8c725a15cd51b0b9467f659d07c1f2a552550cdf9b67dd26c) are not ensured by django. Treebeard supplies …

Add stdout message discouraging `AbstractTreeNode.objects.create()`

---

integreat_cms/cms/templates/content_versions.html
integreat_cms/release_notes/current/unreleased/2912.yml
integreat_cms/static/src/css/style.scss
integreat_cms/static/src/js/revisions.ts

This pull request re-implements the revision timeline feature. Originally targeting the issue described in #830, the project scope expanded to include a comprehensive refactor. The new implementation improves code readability and functionality by utilizing `flex-layout` and replacing `datalist` and `option` elements with click listeners for item selection.
In response to feedback from @osmers and @JoeyStk, the timeline has been made scrollable. Users can now navigate through the timeline using the previous and next buttons, the left and right arrow keys, or horizontal scrolling.
You can find a screencast that demonstrates the new behaviuor here: https://github.com/user-attachments/assets/418389df-3168-431f-a2c9-894acbdbb0b8.
- Enhanced accessibility by increasing contrast for revision …

Page revision timeline rework

---

integreat_cms/cms/views/dashboard/dashboard_view.py

This PR changes the hook from the "Go to link" button in that it removes `replace-url`. 
Before the link set us somewhere in the middle of the page and not nicely. This is again important for the release
Before:
After:
- Change hook
- None I'm aware of
Fixes: -

Change hook in button link

---

integreat_cms/release_notes/current/unreleased/2943.yml
integreat_cms/static/src/css/tinymce_custom.css

Specify whitespace handling for `translate="no"` elements
- Add `white-space: pre-wrap;` to the `[translate="no"]` rule
- Spaces are *not* collapsed when at the beginning or end of a line if the element with `white-space: pre-wrap;` is starting/ending there
- I don't see a better solution without implementing custom text layouting/rendering in the browser, which is likely a very bad idea
- The impact of this is negligible, especially as it only concerns our editor in the backend
Fixes: #2943 

Fix disappearing spaces next to Do Not Translate markers

---

integreat_cms/release_notes/current/unreleased/2943.yml
integreat_cms/static/src/css/tinymce_custom.css

- [ [#2943](https://github.com/digitalfabrik/integreat-cms/issues/2943) ] Fix disappearing spaces next to Do Not Translate markers

Release `2024.7.3`

---

integreat_cms/cms/forms/pages/page_form.py
integreat_cms/cms/forms/pois/poi_form.py
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/release_notes/current/unreleased/2928.yml

This PR fixes the bug that ALL organizations were shown as choice in the POI form.
- Apply the same procedure with the page form and view
- None? I hope 🙈 
Fixes: #2928 

Show only organization of the region in POI form

---

integreat_cms/cms/templates/_form_language_tabs.html
integreat_cms/release_notes/current/unreleased/2918.yml
integreat_cms/static/src/css/style.scss
integreat_cms/static/src/js/language-tabs.ts

This PR attempts to fix the bug that the "Other languages" dropdown doesn't open up when too long languages are one of the dropdown options.
- Decouple the list of "Other languages" from the button
- Graphical less pleasing 
Fixes: #2918

Fix jumping language tabs

---

integreat_cms/cms/views/analytics/translation_coverage_view.py
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/cms/views/utils/hix.py
integreat_cms/release_notes/current/unreleased/2903.yml
tests/cms/utils/test_disable_hix_post_save_signal.py
tests/cms/views/utils/test_hix.py
tests/utils.py

Move calculation of pages ready / not ready for mt from multiple places to singular location
- Move implementation from region dashboard and translation coverage analytics to view utils
- `get_translations_relevant_to_hix()`
- `get_translation_under_hix_threshold()`
- `get_translation_over_hix_threshold()`
- Calculate effects of rounding / threshold on raw hix value to more efficiently determine set of PageTranslations directly on the database
- Add test validating implementation of `round_hix_value()` based on this new method of calculation
- Add tests validating util functions
- Add decorator to disable the hix calculation post save hook
- Add tests validating functionality of said decorator
- There are still two ways with distinct implementations of the same functionality: Our new …

Unifiy calculation of pages (not) ready for mt

---

integreat_cms/cms/views/pois/poi_form_ajax_view.py
integreat_cms/release_notes/current/unreleased/2973.yml
tests/cms/utils/test_disable_hix_post_save_signal.py

This PR fixes Error 500 which occurs during location creation on the event form. The cause is the queryset introduced by #2932 
- Pass the current region as `additional_instance_attributes` so organizations of the region can be found without problem
- I hope I'm not bringing any bug this time 🙈 
Fixes: #2973 

Fix error at creating POI in event form

---

integreat_cms/cms/views/utils/hix.py
integreat_cms/core/signals/hix_signals.py
integreat_cms/release_notes/current/unreleased/2917.yml
integreat_cms/static/src/js/analytics/hix-widget.ts
integreat_cms/textlab_api/textlab_api_client.py
tests/cms/views/utils/test_hix.py

This pr fixes hix calculation for pages without text.
- Treat `None` as an indicator that the page has no relevant content
- If the page has no text content, don't even send a request to textlab, since we already know the result
Ideally none other
Fixes: #2917
Fixes: #2916 

Fix hix for pages without text

---

integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/release_notes/current/unreleased/2982.yml

This PR adds `ImprintPageTranslation` into the target models of `replace_links` so links in imprints can be replaced too by the "Search&Replace" on the uppr right corner of the broken link list.
- Add `ImprintPageTranslation` into the list `models` in the function `replace_links`
- Should we probaly think of centralised check for such process of adding/removing a model to/from our link features? Somthing like, listing models in one single list (as an environment variable, for exmaple) and we add a check whether all models of the list are included at the points where you need to add changes while removing/adding a model to the link check feature.
Fixes: #2982
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pul …

Include links of imprints into link replacement

---

integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/release_notes/current/unreleased/2807.yml

When marking pages as up-to-date, their machine-translated translations where changed to be out-of-date. This PR fixes this.
- in `AbstractContentTranslation`, change the definition of "up to date" to include machine translations
- surprisingly, this breaks 0 tests 🤔 
- none, but I think we might need a discussion about outdated/up-to-date definitions. Right now, there are multiple `translation_status` states which are neither up-to-date nor outdated, which is a bit weird.
Fixes: #2807

Fix machine translations being considered as not up-to-date

---

integreat_cms/cms/utils/content_utils.py
integreat_cms/release_notes/current/unreleased/2801.yml

Our CI is haunted.
- Do nothing and see if it still fails. ~~If so, something already merged on develop is the culprit~~ ***all tests passed***
- Use a commit known to produce this error on the tip of develop. ~~If the error is reproduced, proceed with something like a bisect *(but using that commit on top various commits from `develop`s history)*~~ ***all tests passed***
- Use a commit known to produce this error on top of their original parent commit. ***all tests still passed***
- Use the exact commit known to produce this error *(same hash)* ***all tests passed, despite failing on a different branch, for a different PR***
*Note that the pipeline d2103e7 now appears to have failed. Following the link reveals that the pipeline was run for the branch of #2901, not for this branch. CI …

Haunted CI

---

integreat_cms/api/v3/chat/zammad_api.py

Do not return internal Zammad messages as chat responses to app users.
Filter messages by internal attribute.
- None
Fixes: #2843

Keep internal chat messages internal

---

integreat_cms/cms/templates/_tinymce_config.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3001.yml
integreat_cms/static/src/js/tinymce-plugins/custom_link_input/plugin.js

Fix link auto update checkbox always checked
- When the dialog is opened without an existing anchor being selected, determine whether the checkbox should be checked by checking if the selection is empty
- Disable the text field when the checkbox is checked
- Always set the text field to the targets title, and set text and URL to nothing whenever there is no auto completion when the checkbox is checked
- Reword the checkbox description
- Omit the `data-integreat-auto-update` attribute on links if `autoupdate` is `false` in order to not unnecessarily clutter the source code for normal links
- When the checkbox should be checked when the dialog is first opened, the text field is not yet disabled *(only once the update function is run)* – tell me if you know how to initially disable a field
- …

fix link auto update checkbox always checked

---

integreat_cms/cms/templates/pages/page_tree_archived.html
integreat_cms/locale/de/LC_MESSAGES/django.po

While reviewing #3018 I noticed, that I had messed up the translation for "Back to pages". It was "Back to page tree" before but should have been changed to "Back to pages" to fit the pattern of "Back to [model_name_plural]"
- Change translation of button
- Does this need a release note? To me this change is too small and unnoticeable, but I can add one if wished for
Fixes: -

Fix translation for back-to-pages-button

---

integreat_cms/cms/templates/_poi_query_result.html
integreat_cms/cms/templates/ajax_poi_form/_poi_form_widget.html
integreat_cms/cms/templates/ajax_poi_form/poi_box.html
integreat_cms/cms/templates/events/_event_filter_form.html
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/views/events/event_actions.py
integreat_cms/cms/views/pois/poi_form_ajax_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3015.yml
integreat_cms/static/src/js/events/event-query-pois.ts

This PR extends the ajax poi form in the event form with three new fields and renames some files and variables universal
- Add fields E-mail, phone number and website to the ajax POI form.
- Show those informations together with the address if a POI is selected.
- Rename "venue_box.html" to "poi_box.html"
- Move "venue_box.html" and "_poi_form_widget.html" to a new folder "ajax_poi_form"
- Mov "_poi_query_result.html" to the folder "templates"
- Rename "event_form" to "form" in "venue_box.html" and make the box title configuarable.
- None? 🙏 
- 
Fixes: #3015 

[7.11.24] Extend ajax poi form

---

.pre-commit-config.yaml
tools/_functions.sh
tools/black.sh
tools/djlint.sh
tools/eslint.sh
tools/mypy.sh
tools/prettier.sh
tools/pylint.sh
tools/ruff.sh

This is a followup to the discussion in #2804. This PR swaps out the existing pre-commit hooks for calls to our existing devtools. @cclauss I cannot request you as a reviewer, but you're more than welcome to also take a look!!
- a new helper function `run_as_precommit` is called at the start of each relevant devtool
- if the tool was called with the `--as-precommit` flag, the tool is only run against staged files
- `.pre-commit-config` uses the local tools and sets the `--as-precommit` flag
- this *should* be a drop-in replacement for the current pre-commit hooks
- additionally, `pylint` can now be run as a pre-commit hook 🎉 
- possibly the behavior doesn't match 100%? It's a bit hard to tell, honestly.
- no more mismatches between pre-commit / installed tool versions!
Fixes: n/a …

Define pre-commit hooks in devtool scripts

---

integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/utils/content_translation_utils.py
integreat_cms/cms/utils/content_utils.py
integreat_cms/cms/utils/link_utils.py
integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
integreat_cms/core/management/commands/fix_internal_links.py

This PR refactors the function `replace_links` by using `get_region_links`
- Use `get_region_links` to collect link objects of the current region
- The function looks cleaner
- It doesn't have to go through all the translations of latest version anymore, now only checking translations related to links whose URL contains "search" string and is in the selected types.
Fixes: #2993 

Refactor `replace_links` by using `get_region_links`

---

integreat_cms/static/src/js/events/conditional-fields.ts

This PR fixes `Uncaught TypeError` which occurs when the event list is visited. 
- Remove the code lines which contains the cause of the error `node.closest("li")`.
- I didn't find the case when `node.closest("li")` is **not** `null`. If thre is any case it is not `null`, this code breaks the current behaviour 😅 
Fixes: #3031 

Fix Uncaught TypeError in the event list

---

.devcontainer/.env
.devcontainer/docker-compose.yml
README.md

This PR adds the configuration file `integreat-cms.ini` to the development container so it can be used.
- Pass path of the configuration file via the environmental variable `INTEGREAT_CMS_CONFIG`, this ensures the devcontainer to work even when the variable isn't set (in that case it's passed as blank)
- Add Information about using configuration file to README
Fixes: #2939 

Add cms configuration file to devcontainer

---

integreat_cms/cms/forms/language_tree/language_tree_node_form.py
integreat_cms/cms/views/language_tree/language_tree_actions.py
integreat_cms/release_notes/current/unreleased/2625.yml

After deleting a language tree node, the language was still visible in the imprint form. A similar behavior showed when adding or moving nodes.
- Invalidate the imprint cache after deleting nodes
- Invalidate the imprint cache after adding nodes
- None
Fixes: #2625

Invalidate imprint cache after deleting or adding language tree node

---

integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/templates/pois/poi_list_archived.html

Before #2895, we had [a css rule](https://github.com/digitalfabrik/integreat-cms/pull/2895/files#diff-d0f24712a2bf2e307d18ff548e8aa7747ef3be932bb9456c0262b32c87285e65L337) that set every table listing table's width to `inherit`. This caused `table-fixed` to have no effect, because using `table-fixed` without a specific size is an error in css and causes css to fallback to `table-auto`, which is the default value.
Now, that every table has `w-full` though, this rule is valid and causes the table to get too large. Fortunately, simply removing this rule fixes the table layout.
Additional context: https://github.com/digitalfabrik/integreat-cms/pull/2895#discussion_r1744433126
- Remove the `table-fixed` class
Fixes: #3041 …

Fix poi table layout

---

.github/dependabot.yml
docs/src/documentation.rst

This pull request extends the existing dependabot configuration by adding support for `devcontainers`, `pip`, and `npm`. Dependabot is a tool that continuously monitors our repository for available updates across various ecosystems. It automatically creates weekly pull requests to update dependencies, organized by their respective ecosystems.
Fixes: #2812 #2347

Configure dependabot for devcontainer, pip and npm

---

integreat_cms/api/v3/chat/zammad_api.py

Allow Zammad users to answer to chat messages / tickets and remove default mention.
- Set the Zammad ticket type to "web" instead of "chat".
- Remove default handler mention as this overrides the users personal notification settings.
None. This should only affect Zammad.
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/20

Change Zammad ticket type

---

.github/dependabot.yml

Dependabot does not work with our `pyproject.toml` format: #3047
- Disable dependabot for pip
Links to: #2812

Remove dependabot for pip

---

integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/linklists.py
integreat_cms/cms/models/users/organization.py
integreat_cms/cms/templatetags/content_filters.py
integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
integreat_cms/release_notes/current/unreleased/2369.yml

This PR adds URLs of organizations to our link check/replace feature.
The issue is planned not for Q3 but Q4, but in my opinion it's better to implement this before we start refactoring of link check/replace feature for performance and the centralised link management system.
- Add the model `Organization` to the link checker
- Add a new function `replace_urls` to the model `Organization` to be compatible with the refactoring from #3003 
- <s>Adjust functions for link replacement (because organization objects do not have any translations)</s>
- <s>I hope it functions at least. We definately need some refactoring (but suggest to do it in another PR)</s> It's merged now :)
Fixes: #2369  …

Add organization URLs to link check

---

integreat_cms/cms/templates/_base.html
integreat_cms/cms/templates/linkcheck/link_list_row.html
integreat_cms/cms/templates/linkcheck/links_by_filter.html
integreat_cms/cms/templatetags/linkcheck_filters.py
integreat_cms/cms/templatetags/url_tags.py
integreat_cms/cms/urls/protected.py
integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/cms/views/linkcheck/link_replace_view.py
integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/1443.yml

This is an updated version of #2898 with improvement sugeestion by @david-venhoff (Thank you 🙏)
- Reuse the template and view of region link list
- Do not prefetch links in the centalized link list
- Use the util function `replace_links` if users replace an URL per ✏️ in a row of the centalized link list (because we are not prefetching)*1
- *1 is sadly slow (but this is actually what you get when you use "Search&Replace" on the upper right corner). We can alternatively deactivate link replacement in "option" column until further performance improvement
-  
Fixes: #1443 

Add centralised link list in the network management

---

.gitignore

I am using pyenv to use a local python version for integreat-cms. However, this creates a `.python-version` file in the directory, which should not be tracked with git.
- Add the file to `.gitignore`
None
Fixes: /

Add `.python-version` to .gitignore

---

integreat_cms/api/v3/chat/chat_bot.py
integreat_cms/api/v3/chat/user_chat.py

Ignore empty automatic answer messages. This enables the chat bot to decide which messages actually need an answer.
- Only send responses to Zammad that are not an empty string
- Update the actions list
- None
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/45

Chat: treat empty answer as no response

---

integreat_cms/api/v3/chat/chat_bot.py
integreat_cms/api/v3/chat/user_chat.py

Use self hosted LLM translations to enable GDPR compliant chat message translations.
- Use chat bot translation endpoint for chat message translations.
- The quality of translations is probably not as good as Google translate but totally sufficient for simple messages. 
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/37

Chat: use self hosted translation model

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/release_notes/current/unreleased/3098.yml

Fix handling empty Zammad URL in region form. We allowed Null/None values for the zammad_url field in #3051 but forgot to consider this in the form sanitization.
- Check if the zammad_url field in the form is empty before doing string operations. If empty, return None (Null for database).
- I cannot think of any.
Fixes: #3098

Fix empty Zammad field in region form

---

integreat_cms/cms/models/regions/region.py
integreat_cms/cms/templates/_base.html
integreat_cms/cms/templates/region_condition/region_condition.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/cms/views/region_condition/__init__.py
integreat_cms/cms/views/region_condition/region_condition_actions.py
integreat_cms/cms/views/region_condition/region_condition_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Adds a new admin page with a button to download a region condition export.
The page itself is very minimal and will be improved with #3012.
Speed is not great, unfortunately. An export using production data takes about 6 minutes.
- Add a new view
- Add a new endpoint to create a data export
- Move some methods from the dashboard to the region, so that they can be shared by the dashboard and the region condition export
None
Fixes: #3053

Implement region condition data export

---

integreat_cms/cms/templates/events/external_calendar_form.html
integreat_cms/cms/templates/organizations/organization_form.html

Hitting `Enter` in our organization or external calendar form opens the "Do you really want to delete this?" popup. This is not the desired behavior. Instead the form should be saved when hitting `Enter`. This issue was because the delete button is the first one on our page and therefore by default the button that's going to be executed when hitting `Enter` (at least this was the result of my research).
- Adjust button type in organization and external calendar form. The "Submit"-Button will be executed when hitting `Enter`, which fixes the issue at hand
- I went through the other content types (at least POI, event and pages). There we don't have this issue.
- I'm not aware of any possible side effects by this change
Fixes: #3112
[Pull …

[2024-11-07] Fix enter saves form

---

integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/events/event_list_row.html

Allow all users to see external calendar column in event list view
- Change permission
- Add icon in case there is no external calendar
None I'm aware of
Fixes: #3104 

[2024-11-07] Extend user permissions for external calendar column in event list

---

integreat_cms/cms/templates/contacts/contact_list.html
integreat_cms/locale/de/LC_MESSAGES/django.po

When opening the list of archived contacts and the list is still empty the wrong text is shown. This PR fixes the translation.
- Fix translation
None
Fixes: #3152

Fix translation for empty archived contact list

---

integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/cms/views/linkcheck/linkcheck_list_view.py

I noticed that postgres could not optimize our query which loads links for a specific region very well. A dramatic speedup is possible by making a multiple smaller queries and `union`ing them together, instead of making a big query with a more complex condition.
- use `union all` to speed up the `get_region_links` query by up to 90% (Augsburg)
- Add a new parameter to `get_urls` and `filter_urls` to prevent the prefetch. The prefetch typically takes more time than the query. Thus, it can save more than 50% when the prefetch is not needed.
- #3079 on the production data now takes one minute, instead of six minutes :tada: (Though there is still a lot of optimization potential)
- faster region linkcheck view loading 
For testing, I added an index on the link model and got another 30-40% …

Improve the performance of `get_region_links`

---

integreat_cms/cms/utils/external_calendar_utils.py

- simply subtract a day from the imported date if the event is all-day
Even though it is probably not likely to occur "in the wild", we previously had the possibility of *only* either the start or end date being a `datetime.date` instead of a `datetime.datetime`.
This could lead to either all-day events with and end time, or non-all-day events with no end time.
I opted to change the logic slightly, and now events are all-day as soon as either the start or end has no time.
Fixes: #3109

Fix end date of all-day events in iCal imports

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/cms/templates/regions/region_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/test_duplicate_regions.py

- add chekcbox to "new region" form
- if a region is duplicated, and the checkbox is unchecked, only copy the root nodes of the language tree
- also only copy the translations of the languages that were copied, i.e. only of the root language tree nodes
- probably slightly worse runtime when duplicating a region WITH all translations/languages
Fixes: #2991

Add option to skip copying language tree and translations when duplicating a region

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

We renamed labels back from e.g. ***:bug: bug*** to *https://github.com/digitalfabrik/integreat-cms/labels/bug* and now issue templates don't automatically add labels anymore.
- Fix the names of the labels in the issue temlates

Fix issue template labels

---

integreat_cms/cms/views/region_condition/region_condition_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

The current region condition csv doesn't contain the number of pages per region. This renders some of the information as useless, since they are relative to the number of pages. This PR attempts to fix this
- Add column for total number of pages per region to csv export
- None?
Fixes: #3174

Add total number of pages to region condition

---

integreat_cms/cms/fixtures/test_data.json
tests/cms/models/contacts/test_contacts.py
tests/cms/views/contacts/test_contact_actions.py
tests/cms/views/contacts/test_contact_form.py

This PR adds tests for the features introduced by #3034 
Test following cases
- A contact is successfully created
- An existing contact is successfully updated
- A contact cannot be created if no POI is selected
- A contact cannot be created with all the fields empty
- A contact cannot be created without title and name if a primary contact already exists for the selected POI
Comment if you come up with other cases that need to be tested 😸 
- Reduced risk of bugs in future.
Fixes: #3013 

Add tests for contact form

---

integreat_cms/cms/templates/statistics/_statistics_legend.html
integreat_cms/cms/templates/statistics/_statistics_legend_item.html
integreat_cms/cms/templates/statistics/statistics_overview.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/matomo_api/matomo_api_client.py
integreat_cms/release_notes/current/unreleased/3133.yml
integreat_cms/static/src/js/analytics/statistics-charts.ts

Remove the legend at the top of the chart, replacing it with a box in the right-hand column, as shown in the [design proposal](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=1179-830) in preparation of #1097.
- remove old legend
- generate new legend server-side, using jinja
- wire them together using the method recommended in the [docs for chart.js](https://www.chartjs.org/docs/master/samples/legend/html.html)
- none
Fixes: #3133

Add separate legend for statistics charts

---

integreat_cms/cms/migrations/0109_custom_truncating_char_field.py
integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/cms/models/contact/contact.py
integreat_cms/cms/models/fields/truncating_char_field.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR attempts to fix the `DataError` which occurs when copying a long contact name. This is because appending the suffix exceeds the maximum length of the field.
- Try & catch
- In case the `DataError` would occur truncate the pre-existing name and then append the suffix.
- ~~I don't have a finally block so there might be some?~~
Fixes: #3145
Fixes: #3146

Fix data error when copying long contact

---

integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
integreat_cms/release_notes/current/unreleased/3183.yml

This PR fixes the bug which occurs when URLs are ignored or unignored by bulk action.
- Add `prefetch_region_links=True`
Alternatively we could probably set `prefetch_region_links` as default `True`
- Tests will come in #3096 
Fixes: #3183 

Fix error at bulk link ignore/unignore

---

integreat_cms/cms/forms/regions/region_form.py

When creating a new region which copies contents from another region and only the root languages should be included, the `lft` and `rgt` values of the new language node must be set to `1` and `2`, respectively. Otherwise, it would behave as if it still contained child nodes.
- Set the correct `lft` and `rgt` values
Fixes: #3200

Fix copying of language tree nodes in the region form

---

integreat_cms/core/settings.py
integreat_cms/deepl_api/apps.py
integreat_cms/deepl_api/deepl_api_client.py

This pr adds basic support for deepl glossaries.
If enabled, every glossary defined at deepl will be used (undefined behavior if multiple glossaries for the same source to target language pair exist)
For now, the feature is disabled by default.
Note to self: Enable the setting on the test server when merged
- Set `DEEPL_GLOSSARIES_ENABLED` to `True` in the settings
- Configure deepl by setting the integreat deepl password to the free deepl api password from passbolt.
- Translate a page that contains glossary words from german to english 
- Check that the english translation uses the corresponding glossary entry
You can print out all available glossary entries with `print(self.translator.get_glossary_entries(glossary))`
~~Note that at the time where I am writing this the de-en dictionary …

Add support for deepl glossaries

---

integreat_cms/cms/templates/statistics/statistics_chart.html
integreat_cms/cms/templates/statistics/statistics_overview.html
integreat_cms/cms/templates/statistics/statistics_sidebar.html
integreat_cms/locale/de/LC_MESSAGES/django.po

Make the number of online accesses collapsible as a part of the #1097 as shown in [design proposal v3](https://www.figma.com/design/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=1179-830&node-type=frame&t=vaCXaXccgqveytL3-0)
- Make use of the template for collapsible box
- Create a new file called statistics to hold all the upcoming collapsible separate boxes in statistics and the sidebar
- Change the path to the template in statistics view
- should be none?
Fixes: #3131 

[2024-12-18] Make the number of online accesses in statistics collapsible

---

integreat_cms/cms/templates/linkcheck/links_by_filter.html
integreat_cms/release_notes/current/unreleased/3118.yml

This PR fixes the error which occurs when a bulk action is executed while pagination is active.
This issue is not planned for the current mile stone, but it would be nice to include check for this bug in #3096 
- Purge the evil space
- should be none 🙈 
Fixes: #3118 

Fix error at bulk action in broken link list

---

integreat_cms/cms/templates/events/event_list_archived_row.html
integreat_cms/release_notes/current/unreleased/3190.yml

This PR fixes the bug that the start and end date/time of archived events are not displayed.
- Use `start_local` and `end_local` as in the non-archived event list
- None 
Fixes: #3190 

Fix display of start and end of archived events

---

integreat_cms/cms/templates/statistics/statistics_overview.html
integreat_cms/cms/templates/statistics/statistics_sidebar.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3131.yml

This PR revives the export option box of the statistics that was accidentally removed.
- Embed the deleted codes into the current structure.
- Add a release note for #3131 afterwards
- should be none.
Fixes: #3214 

Revive export box of statistics

---

integreat_cms/release_notes/current/unreleased/3213.yml
integreat_cms/static/src/js/analytics/statistics-charts.ts

This PR fixes the error messsage in the dashboard statistics that is shown despite the statistics is working correctly.
The cause is `TypeError` (propaties of null) . It triggers `catch (error)`.
- Avoid `TypeError`
- The change is held minimal to avoid side effects.
Fixes: #3213 

 Fix false positiv error message in statistics in dashboard

---

integreat_cms/cms/views/organizations/organization_form_view.py

Currently redirection after the creation of a new organization does not work as intended, instead of redirecting to edit page, it is creating new organizations.
- Add redirect to edit page after creating a new organization
- none
Fixes: #3239 

Redirect to edit after creating a new organization

---

integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/views/organizations/organization_actions.py
integreat_cms/cms/views/organizations/organization_bulk_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/views/organizations/test_organization_actions.py
tests/cms/views/organizations/test_organization_form.py

This PR adds tests for actions users can take with organization objects.
Following actions are tested:
- Archive, delete, restore an organization
- Archive, delete, restore organizations by bulk action
- Creating and editing an organization
<s>`test_create_new_organization` is disabled, as we are waiting for #3239 </s>
Some minor changes are done on the existing code:
- Change the type of message "Organization couldn't be deleted as..." to `error`
- Fix typo in the English messages (resulting in some translations removed)
Fixes: #3216 

Add tests for organization actions

---

integreat_cms/cms/models/contact/contact.py
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templates/pois/poi_form_sidebar/action_box.html
integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/views/poi/test_poi_form.py

This PR implements a box into the POI form which shows contacts referring the POI.
- Add a new collapsible side box like "Organization", "Barrier free" or "Actions"
- List up related contacts with a link to contact form respectively
- Add tests for this box
- This brings more duplicate than mentioned in #3147 but it is consistent with other models (Organization, for example) to show the list of related objects. I'll leave the duplicate problem to #3147.
Fixes: #3087 

[2024-11-07] Show related contacts in the POI form

---

integreat_cms/cms/templates/_machine_translation_overlay.html
integreat_cms/cms/templates/generic_confirmation_dialog.html
integreat_cms/cms/templates/linkcheck/link_list_row.html
integreat_cms/cms/templates/pois/poi_form_sidebar/position_box.html

Right now cancel button in machine translation overlay has a red button instead of having ghost button. Additionally fix all other occurrences of cancel button not having the ghost button style.
- Change the button style to ghost button
- none
Fixes: #2966 

Fix cancel button color to have ghost button style

---

integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/events/event_list_row.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/templates/pois/poi_list_row.html
integreat_cms/release_notes/current/unreleased/3014.yml

Checkboxes on list views for location and events are being shown for observer who has no edit permission. 
- Add permission check conditions on these list views
- none
Fixes: #3014 

Remove checkbox appearence for roles who do not have edit permission in events and locations

---

integreat_cms/cms/templates/content_versions.html
integreat_cms/cms/views/content_version_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR removes the buttons from the version history for imported events from an external calendar.
- Remove buttons
- I'm not 100% sure if this is the best way to do it, or if maybe some explanatory text would be helpful. What do you think?
Fixes: #3107 

Disallow publishing imported events through version history

---

integreat_cms/core/wsgi.py

Since yesterday, `ruff` has been complaining about the following:
```
integreat_cms/core/wsgi.py:43:5: PLC0206 Extracting value from dictionary without calling `.items()`
|
42 |       # Read config from environment
43 |       for key in environ:
|  _____^
44 | |         if key.startswith("INTEGREAT_CMS_"):
45 | |             os.environ[key] = environ[key]
| |__________________________________________^ PLC0206
46 |   
47 |       _application = get_wsgi_application()
|
```
That code was last touched 3 years ago, so not sure why the sudden complaint, but it *is* a valid complaint.
- use `items()` instead of implicitly iterating over / accessing by key
- oof I hope none
- alternative would be to just ignore the ruff error
Fixes: n/a
[Pull …

Fix sudden ruff complaint

---

integreat_cms/cms/templates/ajax_poi_form/_poi_address_container.html
integreat_cms/release_notes/current/unreleased/3223.yml
tests/cms/views/events/test_event_form.py
tests/cms/views/view_config.py
tests/mt_api/mt_api_test.py

This PR fixes the problem that events cannot be created without POI even if "Event does not have a physical location" is checked.
- <s>Clean the POI id before passing the user input values into the form.: the cause was "-1", which is passed as POI id if no POI is selected but causes validation error, resulting in the form is judged as invalid (before reaching `clean` method). </s>
- Apply the suggestion from @david-venhoff (see the comment below)
- Add a test for this case
- I hope none :see_no_evil: 
- 
Fixes: #3223 

Fix event creation without physical location

---

tests/cms/models/contacts/test_contacts.py
tests/cms/views/contacts/test_contact_actions.py

This PR adds test for archiving, deleting and restoring of contact objects.
- Test archiving, deleting and restoring one contact object
- Test bulk archiving, deleting and restoring
- The existing tests of the model functions are moved to another file, as they are rather test for "the model" than the user view/action
- Protection of used contacts is not (yet) tested in this PR. We can either merge this PR first and adjust the relevant parts in #3282 or we wait for #3282 and do adjustment here.
Fixes: #3245 

Add tests for contact actions

---

integreat_cms/cms/models/contact/contact.py
integreat_cms/cms/models/pois/poi.py
integreat_cms/cms/models/pois/poi_translation.py
integreat_cms/cms/templates/_related_contents_table.html
integreat_cms/cms/templates/_tinymce_config.html
integreat_cms/cms/templates/ajax_poi_form/_poi_address_container.html
integreat_cms/cms/templates/contacts/contact_card.html
integreat_cms/cms/templates/organizations/organization_form.html
integreat_cms/cms/templatetags/svg_tags.py
integreat_cms/cms/urls/protected.py
integreat_cms/cms/utils/content_utils.py
integreat_cms/cms/utils/internal_link_checker.py
integreat_cms/cms/views/contacts/contact_form_view.py
integreat_cms/cms/views/utils/__init__.py
integreat_cms/cms/views/utils/contact_utils.py
integreat_cms/core/signals/__init__.py
integreat_cms/core/signals/contact_signals.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/css/contact_card.css
integreat_cms/static/src/css/style.scss
integreat_cms/static/src/css/tinymce_custom.css
integreat_cms/static/src/css/tomselect.scss
integreat_cms/static/src/editor_content.ts
integreat_cms/static/src/js/forms/tinymce-init.ts
integreat_cms/static/src/js/tinymce-plugins/custom_contact_input/plugin.js
integreat_cms/static/src/js/tinymce-plugins/custom_link_input/plugin.js
package-lock.json
package.json

We want to embed contacts on pages and in other content. This PR is an alternative to #3124.
Contact cards contain a hidden link, allowing us to track where a contact is used with the linkchecker.
- Add a URL to each contact, making it trackable by linkcheck
- Add a **custom TinyMCE plugin** to embed contacts via a button and dialog, similar to our custom link plugin
- In the contact form, **show where contacts are being embedded**
- saving changes to a contact will update all translation objects referencing the contact
- `linkcheck` will check the contact links and find that no resource is being served at those URIs. THey are shown as valid, but we could also hide them.
- The URI contains the region slug, but it is never relevant in the code for now
Adding a contact to a page/poi/event …

[2024-11-07] TinyMCE: Insert contact, but track using linkcheck

---

integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/templates/pois/poi_list_archived.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3263.yml

Currently the strings `X Locations selected` and `X Events selected`are being displayed regardless of user role. The observer role can not see checkboxes and therefore can not manupulate anything thus the strings `X Locations/Events selected` should be hidden.
- Hide the strings from non permitted roles
- Add `X Locations selected` in archived locations (currently it does not exist) and add check condition whether the user role allowed to see it or not
- none
Fixes: #3263 

Remove `x Locations/Events selected` string for observer role

---

integreat_cms/cms/templates/events/event_form_sidebar/date_and_time_box.html

This Pr disables the select button in the event form for events that have been imported from external calendars.
- Disable dropdown when it's from an external calendar
This has been worked on in collaboration with @KateGithub12 
Fixes: #3204

Disable select for events from external calendars

---

integreat_cms/api/v3/chat/utils/chat_bot.py

Improve Integreat Chat performance by asynchronously processing the Zammad webhook request.
- Parallelize the message translation and answer generation with aiohttp
- Remove formatting function, moved to RagResponse response class in chat back end in https://github.com/digitalfabrik/integreat-chat/pull/108 
- More load on the Chat back end.
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/113

Async processing of Chat Zammad webhook

---

integreat_cms/cms/templates/pois/poi_list_archived.html
integreat_cms/cms/templates/pois/poi_list_archived_row.html

This is the follow up implementation of the #3014 During the implementation I forgot to remove checkboxes for archived locations as well.
- Remove checkboxes for observer role in archived locations
- none
Fixes: #3262

Hide checkboxes in archived locations for observer role

---

integreat_cms/cms/forms/machine_translation_form.py
integreat_cms/cms/templates/imprint/imprint_form.html
integreat_cms/cms/views/events/event_form_view.py
integreat_cms/cms/views/imprint/imprint_form_view.py
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/release_notes/current/unreleased/3290.yml

This PR fixes text direction of the title and content field.
- Pass `right_to_left` in the event, POI and imprint view too, which is already used in the page form to set the text direction of TinyMCE.
- Add `text_direction` in the event, POI, imprint and page view to set the text direction of title input field in the template.
- `right_to_left` and `text_direction` have almost the same function but I let both exist, because `right_to_left` is already being used in several places and it does not look cool (in my opinion) to write `text_direction == "rtl"` or something repeatedly 😅 (solved for page, POI and event)
- If I remember correctly, there was once a discusion about fixing the text direction of title field but it was rejected/postponed due to some technical problem or complexity or …

Fix text direction in form

---

tools/code_style.sh

Some of the code style tools "fail" with exit code 1 when they performed an action (e.g.: djlint exits with code 1 after changing any file's formatting).
This exits the entire `tools/code_style.sh` script, and you need to invoke it again.
- continue with the next tool, even if the previous one "failed"
- none I think
- I will stop feeling annoyed by this 😂 😂 😂 
Fixes: n/a

Fix: prevent early exit of tools/code_style.sh after exit code 1

---

integreat_cms/cms/models/regions/region.py
integreat_cms/release_notes/current/unreleased/3309.yml
tests/cms/views/regions/test_region_mt_management.py

This PR fixes MT budget calculation of add-on package with mid-year start in January.
- Check explicitly for `None` to avoid January (= 0) is avaluated as if `None`
- None? 🙏 
Fixes: #3309 

Fix MT budget calculation for add-on package booked with mid-year start in January

---

integreat_cms/cms/utils/external_calendar_utils.py
integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR changes the error message for importing external calendars to be more speaking
- Add new integer field to the model to keep track how many errors there are
- Adjust the error message itself
This PR was worked on with @KateGithub12.
- We don't feel one hundred percent sure about adding the new field to the model, but couldn't think of anything else. Please let us know, if you can see an alternative :)
Fixes: #3219

Change error message for external calendars

---

integreat_cms/cms/templates/contacts/contact_form.html
integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/events/external_calendar_form.html
integreat_cms/cms/templates/languagetreenodes/languagetreenode_form.html
integreat_cms/cms/templates/organizations/organization_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templates/push_notifications/push_notification_form.html
integreat_cms/cms/templates/users/region_user_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2930.yml

Add cancel button to create and update form where user can just go back to the list overview instead of going back through side menu navigation
- Add anchor tag with ghost-button style which returns to the list overview of the related forms
Fixes: #2930 

Add cancel button to creation and edit forms

---

integreat_cms/release_notes/current/unreleased/3279.yml
integreat_cms/static/src/js/analytics/statistics-charts.ts

This PR fixes the CSV export of statistics so it does not contain de-selected data (language, access type) anymore.
- Check whether the data is set to "visible" at the moment of export
- None?
Fixes: #3279 

Show only selected data in CSV export

---

integreat_cms/cms/models/contact/contact.py
integreat_cms/cms/templates/contacts/contact_card.html
integreat_cms/cms/views/utils/contact_utils.py
integreat_cms/static/src/js/forms/tinymce-init.ts

On the testserver we have multiple possible backend urls, and the contacts were previously loaded using their complete server url. For example, if a user was on `https://cms-test.integreat-app.de` the contact was still loaded using `https://integreat-test.tuerantuer.org`. Then the login form would be returned, because the user had of course no valid session for the other url.
So instead of using full urls, we can just use relative urls, like we do for all other links.
It's a bit hard to test this pr, because everything worked anyways on localhost, but I hope the explanation helps :)
I also considered adding `redirect: "error",` to the fetch call. This would at least have prevented that the full login form gets pasted. But maybe that is something we should add to all our fetch calls?
- …

Fix contact insertion

---

integreat_cms/cms/templates/ajax_poi_form/poi_box.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/poi-box.ts

This PR fixes the prblem that the middle and right grid are closing when a POI is removed while editing an existing contact.
- Remove code lines that close the grids whenever location is unseleted
- Change the trash icon to pencil icon
- Add a message indicating location is mandatory.
- Please check for side effects in event form too
Fixes: #3151 

Stop hiding the grids when POI is removed

---

integreat_cms/release_notes/current/unreleased/3266.yml
integreat_cms/static/src/js/analytics/statistics-charts.ts

After moving the language labels to the sidebar, the language legends disappeared on png export. Language legends should be there on exported png file.
- Set legend display to true on image export and make necessary adjustments to render legends
- Make the legends border radius circle
Fixes: #3266 

Fix missing legend on png export in statistics

---

integreat_cms/cms/views/pages/page_permission_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po

Show a more sensible error message when attempting to add inactive users to pages
- grant_permission method checks if user is active before checking the permissions
None
Fixes: #3078 

Error message when attempting to add inactive users to pages

---

integreat_cms/cms/templates/contacts/contact_list.html

Hide create button in archived contacts list
- add additional check in HTML form to hide 'Create contact' button in archived contacts
None 
Fixes: #3326

Hide create button in archived contacts list

---

integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/views/linkcheck/link_replace_view.py
tests/cms/views/link_replace/test_link_actions.py

This PR adds tests for actions users can take in the broken link list.
- Do each action and check whether the target URLs/links are changed as expected.
- Check whether actions taken in the netowork management are affecting all the targets system-wide, while actions within a region changing on the objects that belong to the region.
- Two assersions are disabled, as they are failling somehow (new url/link objects are not created after action). So far as I observed, both search&replace and URL replace are working fine. Probably a special care is needed for the link check listener?
Fixes: #3062 

Add tests for broken link actions

---

.eslintrc.js
integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx

In #3329 I noticed that neither eslint (nor prettier, which apprently was the original idea) complain about uses of `console.log`.
- let eslint throw errors on `console.log`
- `console.debug`, `console.warn`, `console.error` remain usable.
(TBH I am more than open to also forbidding `console.warn`, but did not want to deicde this unilaterally. Forbidding `console.log` is more important anyways, since those are our accidentally missed debug statements)
- none
Fixes: n/a

Make `eslint` catch `console.log` statements

---

integreat_cms/cms/constants/calendar.py
integreat_cms/cms/forms/events/event_filter_form.py
integreat_cms/cms/templates/events/_event_filter_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR adds a filter for external calendars to the event list view. It only makes sense to merge this PR once we decide to "go live" with the external calendar feature. 
- Add two checkboxes to filter for imported events or for not imported events
None?
Fixes: #3102 

Add filter for external calendar

---

integreat_cms/release_notes/current/unreleased/100.yml

This PR adds the release note for the external calendars. This PR is one of the blocker for the next release. However we should wait for the final testing of @juliankehne until we merge this PR.
- Add release note.  
- I used the initial issue #100 as the issue id. Do you think another issue would be better suited?
Fixes: #100 

Add release note for external calendars

---

integreat_cms/cms/templates/dashboard/_todo_dashboard_widget.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_missing_translations_row.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/number_of_missing_or_outdated_translations_row.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/analytics/translation_coverage_view.py
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/cms/views/utils/__init__.py
integreat_cms/cms/views/utils/translation_coverage.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/dashboard/translation-coverage.ts

This PR adds the translation coverage row to the dashboard. This branch is already quite old and needs a bit of an update, however I finally wanted to open up this PR to get some feedback in advance
- Calculate the number of outdated translations
- Load the row via AJAX to increase loading time
- ~Uff... the calculation doesn't seem great. Is someone aware of a better way to do it?~
Fixes: #4 

Add translation coverage row to dashboard

---

integreat_cms/cms/models/contact/contact.py
integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/contacts/__init__.py
integreat_cms/cms/views/contacts/contact_form_ajax_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/index.ts
integreat_cms/static/src/js/ajax-contact-form.ts

This PR adds the creation of contacts with a collapsible box in the POI form.
- Add collapsibele box with a contact form in POI form
- Add view for the box
- Trigger creation of a contact with clicking at publish and setting the location automatically to the POI that is created parallel
- None
Fixes: #3088 

Add contact creation in POI form

---

integreat_cms/cms/templates/_poi_query_result.html
integreat_cms/cms/views/pois/poi_form_ajax_view.py
integreat_cms/release_notes/current/unreleased/3212.yml
integreat_cms/static/src/js/poi-box.ts

This PR fixes the bug that none of the suggested locations can be selected in the event form.
- Putting the ID of selected POI to the input field to hand over to the filter
- Fix `TypeError: Cannot set properties of null` at `.outerHTML`
-  I hope none 🙈 Please check there is no side effect on ajax POI creation in the event and contact form too.
Fixes: #3212 

Fix location selection in the event filter

---

integreat_cms/cms/models/contact/contact.py
integreat_cms/cms/templates/contacts/contact_card.html
integreat_cms/cms/utils/content_utils.py
integreat_cms/cms/views/utils/contact_utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/tinymce-plugins/custom_contact_input/plugin.js

This PR allows users to choose which contact details are shown when they insert a contact into TinyMCE, as well as when updating the contact later on.
- use a GET parameter to encode which contact details should be shown on a per-contact-card basis
- show appropriate checkboxes after selecting a contact through Tomselect
- styling the checkboxes was... a challenge, since I frustratingly was not able to target them through the `tinymce.css` file - if someone knows why/how to fix this, I am all ears!
- suboptimal from a UX perspective: if a user selects a contact, deselects some details, then chooses a different contact, the details selection is reset. Not sure if this is worth the effort to change, though, since the shown checkboxes are necessarily contact-specific
Fixes: #3258 …

Allow users to select shown contact details

---

integreat_cms/cms/templates/dashboard/_todo_dashboard_widget.html
integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_missing_translations_row.html
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR is a short follow-up to adding the translation coverage to the dashboard. It changes the provided description (correcting it) and moving the translation coverage up - just under the feedback row. This decisions were made during a conversation with @osmers 
- Change text to "Your pages currently have x outdated or missing translations. In order for the users to benefit from your content you should translate them." or in German "Ihre Seiten haben momentan x veraltete oder fehlendende Übersetzungen. Damit die Nutzer:innen von Ihren Inhalten profitieren können, sollten Sie diese übersetzen (lassen)."
- Move it up in the dashboard view
None? 
This PR blocks the next release, but should be a fairly quick fix :)
Fixes: -
[Pull Request …

Move translation coverage and change text

---

flake.nix
integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/models/contact/contact.py
integreat_cms/cms/utils/internal_link_checker.py
tests/api/expected-outputs/augsburg_de_children.json
tests/api/expected-outputs/augsburg_de_children_depth_2.json
tests/api/expected-outputs/augsburg_de_pages.json

This PR fixes bugs with contact link tracking which were introduced in #3320.
- update test data fixtures so the "Testkontakt" URL is correct (i.e. contains details information)
- adjusts the DB query for gathering referring objects to check if Link objects *start* with the same URL as the contact. This is what has been preventing contacts from being tracked correctly for the last week. 
- Similarly, adjust internal link checker to be able to handle contact URLs with details information
- none, but please note that this does not really solve #3280, it just fixes the regressions which #3320 caused. Once this PR is merged, contact tracking should start working locally again, and we can go back to observing if it also works on the test server 🙈 
Fixes: n/a …

Fix contact link tracking

---

integreat_cms/cms/models/regions/region.py
integreat_cms/cms/templates/region_condition/region_condition.html
integreat_cms/cms/templates/region_condition/region_condition_row.html
integreat_cms/cms/views/region_condition/region_condition_actions.py
integreat_cms/cms/views/region_condition/region_condition_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR adds the first batch of columns to the region condition - namely number of pages, number of outdated pages, number of languages and whether the mt add on was booked.
- Add table to region condition
- Add columns: number of pages, number of outdated pages, number of languages and booked_mt_addon
- I tried to take the calculations from `region_condition_actions`, not from dashboard
- As we expect a high loading time, please test this with the database dump, if you can :)
Fixes: Parts of #3012

Add basic table to region condition

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Add Redis Server to Development Container similar to #3256 did for nix
- Since the introduction of Cellery, Redis Server is now required to run the cms
- Adds installation of Redis Server while building the container
- Adds startup of Redis Server after building the container
Since as far as I know I'm the only one using the dev container, it should be enough to check if there is no unwanted side effect on your own setup
- None
Fixes: n.a.

Startup redis server in devcontainer

---

integreat_cms/cms/models/abstract_tree_node.py
integreat_cms/cms/utils/repair_tree.py
integreat_cms/cms/utils/tree_mutex.py
integreat_cms/cms/views/bulk_action_views.py
integreat_cms/cms/views/language_tree/language_tree_actions.py
integreat_cms/cms/views/language_tree/language_tree_bulk_actions.py
integreat_cms/cms/views/language_tree/language_tree_node_form_view.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/core/management/commands/repair_tree.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/cms/utils/test_tree_mutex.py

Force treebeard to use transactions. This should remove any race conditions caused by the library. The tests seem promising.
- Add `@tree_mutex()` decorator to replace `@django.db.transactions.atomic` (still uses it inside in addition to the mutex implementation)
- Monkeypatch treebeards Node class to use djangos database cursor for its raw SQL queries so that changes get rolled back on failure
- Add tests for `@tree_mutex()`
- The system might respond slower when many page move operations are attempted simultaneously, because treebeard now waits with each operation until any previous operations are finished
Fixes: #1518, possibly #1716
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide …

Add @tree_mutex() decorator and trick treebeard into using transactions

---

integreat_cms/firebase_api/firebase_api_client.py

This is a follow up PR which solves the Issue #2927 which was already merged by me. I oversaw last time that I also needed to include changes in `firebase_api_client` to fully fix this issue.
- Remove `str()` function from news_id
- should be none? 
Fixes: #

Fix news_id to be number type

---

integreat_cms/cms/templates/pages/_page_preview_overlay.html
integreat_cms/release_notes/current/unreleased/3072.yml
integreat_cms/static/src/css/page_preview.css
integreat_cms/static/src/css/style.scss

This PR fixes the styling of page preview.
- Add a new css for page preview
- 
- None?
Fixes: #3072 

Fix styling of page preview

---

integreat_cms/cms/models/push_notifications/push_notification.py
integreat_cms/cms/models/push_notifications/push_notification_translation.py
integreat_cms/core/management/commands/send_push_notifications.py
integreat_cms/firebase_api/firebase_api_client.py

<details><summary>Our `send_push_notifications` management command is giving confusing output.</summary>
```
INFO    integreat_cms.firebase_api.firebase_api_client - <PushNotificationTranslation (id: …, push_notification_id: …, title: …)> sent, FCM id: …
SUCCESS integreat_cms.core.management.commands.send_push_notifications - Successfully sent 0/3 <PushNotification (id: …, channel: …, regions: <QuerySet […]>)>
INFO    integreat_cms.firebase_api.firebase_api_client - <PushNotificationTranslation (id: …, push_notification_id: …, title: …)> sent, FCM id: …
INFO    integreat_cms.firebase_api.firebase_api_client - <PushNotificationTranslation (id: …, push_notification_id: …, title: …)> sent, FCM id: …
SUCCESS integreat_cms.core.management.commands.send_push_notifications - Successfully sent …
```

send_push_notifications: 1–based counting, improve messages

---

integreat_cms/cms/templates/_tinymce_config.html
integreat_cms/cms/utils/content_utils.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/tinymce-plugins/custom_contact_input/plugin.js

Currently, you can just de-select all details and insert a completely empty contact card.
This PR prevents that.
- If no detail is selected, disable the insert/submit button.
- if a user still manages to sneak an empty card in, filter it out server-side.
- none 
Fixes: #3400

Do not allow users to insert empty contact cards

---

integreat_cms/api/v3/chat/utils/zammad_api.py

It seems that a change introduced in #3333 made the `_raise_or_return_json()` incompatible with the method it was supposed to replace.
- Add the self parameter
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/212

Fix patching Zammad API function

---

integreat_cms/cms/views/events/event_form_view.py

This PR fixes the initialization of recurrence end date.
- Set explicitly to the end date of the recurrence rule if exists, to `None` if not
- As the bug cannot be reproduced in the local environment, I'm not sure whether this fix really works. It won't hurt, however, to give it a try as long as there is no negative side effect.
Fixes: #3414 

Fix recurrence end date

---

integreat_cms/api/decorators.py

Check if the X-INTEGREAT-DEVELOPMENT header is set before forwarding the request to matomo.
- Check if the HTTP header "X-Integreat-Development" is set for requests to matomo.

Check if Integreat Development Header is set for requests

---

integreat_cms/cms/utils/external_calendar_utils.py
tests/core/management/commands/test_import_events.py

This PR changes the event import functionality so no event with daily recurrence can be imported.
- Check the frequency and raise error if it is daily
- None?
Fixes: #3431 

Reject all daily events in import

---

integreat_cms/cms/templates/contacts/contact_list_row.html
integreat_cms/cms/templates/feedback/admin_feedback_list_row.html
integreat_cms/cms/templates/feedback/region_feedback_list_row.html
integreat_cms/cms/templates/linkcheck/link_list_row.html
integreat_cms/cms/templates/offertemplates/offertemplate_list_row.html
integreat_cms/cms/templates/push_notifications/push_notification_list_row.html
integreat_cms/cms/templates/users/user_list_row.html
integreat_cms/release_notes/current/unreleased/3397.yml

This PR adds the minus icon to the contact list for information that hasn't been filled out.
- Add dashes / minus icon to empty fields
- Adjust some paddings
- Add fallback link for website (fallback is to direct to contact form as for all other fields too)
- This PR still might be expanded to other content types (or this might be done in another PR)
Fixes: #3397

Fix missing dashes for all list views

---

integreat_cms/cms/utils/linkcheck_utils.py
tests/cms/test_duplicate_regions.py

As a temp solution, we will be hiding the contact cards as well as the links contained within them from the linkchecker (see the linked issue).
- remove all URLs from the set shown to the user which are used in a contact (of the same region)
- remove all contact-card URLs from the set
- this is not exactly great for performance.
Fixes: #3434

Hide contact links and contact cards from the linkchecker

---

integreat_cms/cms/migrations/0115_update_contact_permission.py

This PR adds a migration that updates the permission settings of contact objects
- Do the same with #1988 where a similar permission change was introduced
Fixes: # /

Update permission setting for contact

---

integreat_cms/cms/templates/pages/page_form_sidebar/actions_box.html
integreat_cms/cms/templates/pages/page_tree_node.html
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/release_notes/current/unreleased/3374.yml
tests/cms/views/view_config.py

Only users with publishing rights should be able to archive pages
- change necessary permissions for archiving from "cms.change_page_object" to "cms.publish_page_object"
- don't show archive button to users without publishing rights
- some users without publishing rights might be used to archiving pages and could be confused
Fixes: #3374 

only users with publishing rights can archive pages

---

integreat_cms/cms/templates/events/event_form_sidebar/date_and_time_box.html

This PR fixes the spacing in the start and end date in events as they are currently being cut off. The first idea to change the width of the sidebars wasn't as easy as thought as it came with a bunch of side effects. Therefore I stuck to the second idea and put the two input fields below each other. If you have other ideas for this fix, please let me know :)
- Put start and end date beneath each other instead of next to each other
- There might be, but I don't know about them at the moment
Fixes: #3424

Fix spacing of start and end date in event

---

integreat_cms/cms/forms/pages/mirrored_page_field_widget.py
integreat_cms/cms/forms/pages/page_form.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/release_notes/current/unreleased/3426.yml

This PR fixes rendering of live content in the page preview
- Fix the region slug of the mirrored pages
- The page preview functionality is available both on the page tree (👁️ icon) and on the page form. Please check both are working fine and in the same way
- Please check also, that the styling is fine (see #3396 )
- Please check also (sorry for such many "please"s), that the rendering is working fine after changing the embedded content before and after saving the form.
Fixes: #3426 

Fix live content in page preview

---

integreat_cms/cms/constants/recurrence.py
integreat_cms/cms/fixtures/test_data.json
integreat_cms/cms/forms/events/event_filter_form.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3379.yml
tests/cms/views/events/test_event_filter.py

This PR refactors the event filters, adjusts the filters for long term events and adds a test.
- Refactor event list
- Adjust filters
- Add test
- Please check if I didn't break anything with the refactoring
- I deleted all comments as I think the code is more speaking now - but this might be "author blindness", so please let me know if you want to restore any comments
Fixes: #3379

Adjust filters for long term events

---

integreat_cms/api/v3/chat/user_chat.py
integreat_cms/api/v3/chat/utils/chat_bot.py
integreat_cms/api/v3/chat/utils/zammad_api.py

Instead of sending the last user message, the chat bot should have the full history of the conversation available. This PR fetches the full history for a given message and transmits it as the `messages` attribute to the chat back end. The API is already compatible for that.
- Fetch full chat history for user generated messages
- Send the full message history to the chat back end
- Requests become larger and we add a bit of latency for generating answers.
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/235

Chat: send full message history to back end

---

tools/test.sh

While working on #2297 I made a mistake that left using markers dysfunctional.
- Actually pass the specified marker to pytest, not the keyword arguments
- ~~If you relied on the functionality to completely ignore a marker when no keyword was specified or to ignore the given marker string and replace it with whatever you specified as keyword, then this will be a breaking change for you~~

Pytest: Enable using markers

---

integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
integreat_cms/cms/templates/contacts/contact_form.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3473.yml

This PR fixes the german translation of an warning and removes reference to "fax" number in the release note
- Fix them, fix!
- 
- 
- 
Fixes: #3504 

Fix the german translation for phone number warning and remove "fax" from the release note

---

integreat_cms/cms/templates/events/event_form.html
integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/release_notes/current/unreleased/3327.yml

Since adding the "Cancel" button on content forms, the info message that the page/event/poi has been automatically saved is in between two buttons, which doesn't look great. This PR moves the note so that it shows to the far left again.
- Move automatically saved note
- I'm not sure for which permission to check in the event form. If you have any suggestion, please let me know :)
Fixes: #3327 

Move automatically saved note

---

integreat_cms/cms/templates/pages/_page_preview_overlay.html
integreat_cms/release_notes/current/unreleased/496.yml
integreat_cms/static/src/css/page_preview.css

It was wished that the width of the preview mirrors the width of the content in the Integreat Webapp. This PR fixes this.
- Limit the  width of the preview to max 680px
- This PR also fixes the styling of headlines 2 and 3 and the ordered list for previews
Should be none
- @MizukiTemma I think it might make sense to fix the last issues for the preview which I noticed during testing are fixed in this PR. If you have already started working on them, I think it's fine to leave it as it is. If you haven't I can work on them here :)
- Does it make sense to add a release note for this?
Fixes: #496

Fixes for preview

---

integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
integreat_cms/cms/templates/pois/poi_form.html
integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3322.yml
integreat_cms/static/src/js/ajax-contact-form.ts

This PR makes it possible to create a contact while a new POI is being created (before the initial save)
- Render contact form as static form (not ajax)
- Add the newly created POI to the contact form and save
- Currenlty only one contact can be created at the same time with a new POI. I guess it's but enough, as this feature is primarily needed for the primary contact.
Fixes: #3322 

Add possibility to create a contact while a new POI being created

---

integreat_cms/cms/templates/events/event_form.html
integreat_cms/release_notes/current/unreleased/3519.yml

This PR fixes the bug that the message "Automatically saved on: ..." is not shown in the event form.
- `event_form` -> `event_translation_form`
- I'd go without a release note if this is merged before the next release.
Fixes: #3517 

Fix: Missing "Automatically saved on: ..." message in event form

---

integreat_cms/release_notes/current/unreleased/3285.yml
integreat_cms/static/src/js/tinymce-plugins/autolink_tel/plugin.js

Phone numbers are currently not being formatted upon pressing space/enter.
- change the TinyMCE parameter name `default_link_target` to `link_default_target` -> this variable no longer evaluates to false -> formatting happens
- I have no idea WHY this change is necessary. The line in question has not been touched in over two years. My best guess is that TinyMCE changed its name sometime in the past couple of months, but I cannot find any mention of this in their changelogs.
- None, I think
Fixes: #3285

Fix: phone numbers not being formatted any more

---

integreat_cms/cms/models/contact/contact.py
integreat_cms/release_notes/current/unreleased/3464.yml
tests/cms/views/contacts/test_contact_utils.py

Currently a contact doesn't show up when searching for the address linked to the contact. As the address is part of the contact card it has been confusing to users why the contact card doesn't show when searching for the address. This PR attempts to fix this.
- Include the full address to the string representation of a contact
- Unsure, there might be some
Fixes: #3464

Fix contact doesn't show up in search when searching for address

---

integreat_cms/cms/forms/contacts/contact_form.py
integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3523.yml

This PR hides the button for ajax contact creation if the POI is archived
- Check whether the POI is archived
- 
- None?
- 
Fixes: #3523 

Hide the button for ajax contact creation when POI is archived

---

integreat_cms/cms/utils/content_utils.py

Circumventing the client-side protection for not inserting empty or non-existent contacts, then saving the content object with the empty card, leads to an error because the HTML element representing the contact card is being "unpacked" to prevent deep nesting of contact cards (see: #3440). This PR fixes this.
- instead of returning an empty `p` in these error cases, return a `p` wrapped in a `div`; this can then be unwrapped, just like normal contact cards.
- I have not added a release note, because this should only affect naughty, naughty users who tried to circumvent client-side protections, and those do not deserve release notes! 😆
- none
Fixes: #3461
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-re …

Fix: error thrown when an empty contact card is rendered

---

pyproject.toml

According to https://packaging.python.org/en/latest/guides/writing-pyproject-toml/ the license name should be an SPDX expression. The Apache2 SPDX expression according to https://spdx.org/licenses/ is `Apache-2.0`
Fixes: https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/14816/workflows/0034cc25-8c8f-40dc-a8da-93d85ccb4915/jobs/197178?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary

Fix license name

---

tests/cms/views/events/test_event_form.py

This PR introduces tests for events (create, update) to cover the changes by #3355 
- Test an event is created successfully with correct end date when user input is given as expected
- Test no event with daily recurrence is allowed
- Test the recurrence rule is deleted when a recurring event is changed to one-time or long-term.
- Test the end date is correctly set when a long-term event is changed to one-time or recurring.
- Better test coverage
Fixes: #3361 

Extend test for event

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/release_notes/current/unreleased/3244.yml

This PR improves the speed of page duplication, which is a part of region cloning.
- ~Disable the pre_save signal, to skip HIX score API call~
- Set `hix_enabled` of the newly created region to `False` while pages are duplicated to avoid hitting HIX API
- I hope None
Fixes: #3244 

Improve speed of page duplication in region cloning

---

integreat_cms/cms/templates/pages/page_tree.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/pages/__init__.py
integreat_cms/cms/views/pages/page_bulk_actions.py
integreat_cms/release_notes/current/unreleased/3486.yml
tests/cms/views/view_config.py

Users without publishing rights should not be able to use the bulk archive method
- hide archive option in views for users without publishing rights
- check permissions when using the bulk action form for archiving pages
- Users without publishing rights can no longer archive pages, but can still see and restore archived pages
Fixes: #3486 

restrict bulk archive for pages to users with publishing rights

---

integreat_cms/api/v3/chat/utils/chat_bot.py

The chatanswers endpoint of the chat back end may return an error status. We can catch this error message, skip updating the Zammad ticket, and log the message.
- Log Integreat chat error messages
- Shorter stack traces in Celery
Fixes: N/A

Catch Integreat Chat error messages

---

integreat_cms/cms/utils/zammad.py

* Reduce the cache time for messages to 60s as Zammad users can write messages as well.
* Set the cache for automatic answers and evaluation consent attributes
* N/A
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/299

Change chat cache TTL & fix attributes cache

---

integreat_cms/cms/forms/events/event_form.py
integreat_cms/cms/forms/pages/page_form.py
integreat_cms/cms/forms/pois/poi_form.py
integreat_cms/cms/migrations/0122_add_do_not_translate_title_field.py
integreat_cms/cms/models/abstract_content_model.py
integreat_cms/cms/templates/events/event_form_sidebar/minor_edit_box.html
integreat_cms/cms/templates/pages/page_form_sidebar/minor_edit_box.html
integreat_cms/cms/templates/pois/poi_form_sidebar/minor_edit_box.html
integreat_cms/deepl_api/deepl_api_client.py
integreat_cms/google_translate_api/google_translate_api_client.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2311.yml
tests/mt_api/mt_api_test.py

This PR adds an option to not translate the title of page/event/poi.
- Add a new field `do_not_translate_title` into `AbstractContentModel`
- Add a new check box to the side bar in the form.
- Skip Deepl/Googl API call if `do_not_translate_title = True`
- Add a test
- Should be none 🙈 
- I decided for adding `do_not_translate_title` to the content model, not the translation model or the translation form, considering this is rather a characteistic set per content: I don't think it is usually the case that users want to translate a title into some languages but not into others. Another reason is to save the effort on user side: deciding for each language whether or not translate the title or clicking at least one more checkbox to check/uncheck all the languages would be too much work (many …

Add option to not translate title of content

---

integreat_cms/api/v3/chat/utils/chat_bot.py
integreat_cms/cms/models/chat/user_chat.py
integreat_cms/cms/utils/zammad.py

This PR introduces a `chatbot_typing` attribute to the chat API endpoint. While the chat bot is generating an answer, a cache item is set and unset when the bot is finished. While the cache item is set to true, the API returns a `"chatbot_typing": true`, otherwise the value will be `false`
- None, I hope
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/316

Chatbot typing indicator

---

integreat_cms/core/utils/machine_translation_api_client.py
integreat_cms/core/utils/word_count.py
integreat_cms/deepl_api/deepl_api_client.py
integreat_cms/google_translate_api/google_translate_api_client.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/summ_ai_api/summ_ai_api_client.py

Refactors the DeepL and Google Translate API client `translate_queryset` functions. Since they were largely identical, a lot of things have not only been broken off into smaller methods, but also moved to the parent class.
@juliankehne testing only really involves checking that all machine translation invocations work like they did beforehand
- refactor `translate_queryset`
- a couple more iterations over the `content_objects`-to-be-translated. No nested loops though, still O(n) iterations for length n of the content_objects; but now it's about 7n instead of 1n. Should not really matter though, just a heads up that I did take it into consideration, I just could not come up with a fewer-iterations way to split everything up into nice, small methods. 
- *failed* translations (as in, an …

Refactor translation api clients

---

integreat_cms/api/decorators.py
integreat_cms/core/settings.py
tests/api/test_api_chat.py

@charludo was right all along. We should play it safe an assume that admins do not configure the CMS correctly.
- Do not trust the `X-Forwarded-For` header by default.
- Do not manually serialize list of timestamps into string as the cache can directly work with lists.
- Admins have to configure the trusted source IP header explicitly in the CMS and web server. 
Fixes: https://github.com/digitalfabrik/integreat-chat/issues/320

Explicitely configure trusted source IP header

---

integreat_cms/cms/constants/machine_translatable_attributes.py
integreat_cms/cms/templates/_machine_translation_overlay.html
integreat_cms/cms/views/utils/machine_translations.py
integreat_cms/core/utils/machine_translation_api_client.py
integreat_cms/core/utils/word_count.py
integreat_cms/locale/de/LC_MESSAGES/django.po
tests/mt_api/utils.py

Just noticed that content object attributes which get excluded from translation (currently, mostly titles, but maybe more in the future?) were still being counted towards the translation budget, because the `word_count` function used a hardcoded attribute list. 
- pass content object specific list of "wanted" attributes to that function
- 
- none, I think
- 
Fixes: n/a

Do not count excluded content attributes towards translation budget

---

integreat_cms/cms/forms/pages/page_translation_form.py
integreat_cms/cms/views/pages/page_context_mixin.py
integreat_cms/release_notes/current/unreleased/2961.yml
tests/mt_api/test_mt_button_visibility.py

Show MT-button for pages only to users with publishing rights
- add additional check user_has_publish_rights in PageTranslationForm and return an empty queryset if they don't
- requires changes in some tests, because the AUTHOR role can now only use machine translations for specific pages
Fixes: #2961

only show MT-button if user has publish rights for a page

---

integreat_cms/cms/views/pois/poi_form_ajax_view.py

As a code enhancement, we do not filte for poi_instance anymore inside the ajax form, since it is always none.
- no more filtering for poi_instance (and poi_translation_instance respectively) since it is always None
- none
Fixes: #3359 

Set poi instance to none

---

integreat_cms/cms/templates/pages/pages_page_tree_node.html

This PR fixes the bugs with the edit icon in the page tree.
- Delete the pen-square icon, as we had the pencil icon
- Hide the survived one if it is the archived page tree (partially solves #3597 )
- Should be none 
- 
Fixes: #3598 

Fix edit icon in the page tree

---

integreat_cms/cms/utils/internal_link_utils.py

When translating links of other regions, not all languages are supported by the other region. This can result in an `KeyError: 'ar'`, see https://chat.tuerantuer.org/digitalfabrik/threads/c9iytpszs7dz3mdtdrhq47raro
This seems to happen for location objects only right now, pages do not seem to be a problem. Nonetheless it probably does not hurt to introduce some general error handling that keeps the original URL if it cannot be updated.
- Catch error and keep original URL
- URLs in translations will keep the original link target.

Catch error when translating links into unsupprted languages

---

integreat_cms/cms/views/pois/poi_form_view.py
integreat_cms/release_notes/current/unreleased/3574.yml

This PR fixes the bug that contact cards are not updated and still show the old address when the related POI is updated with a new address.
- Send post save signal to trigger the contact card update function, if a POI is changed with a new address and there are cotnacts referring this POI.
- 
Fixes: #3574 

Update contact cards when the related POI is updated with a new address

---

integreat_cms/cms/templates/statistics/_statistics_widget.html

Fix weird sizing behavior of the statistics graph in the `My Dashboard` view.
- Put the graph in it's own container and fixate the height
Fixes: #3599 

Fix statistics graph sizing

---

integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3591.yml

First of all, sorry for this back and forth on my side. This PR re-adds the warning shown to users of the CMS that the mobile phone number is not yet shown in the app. Why? I removed the warning because I thought that with the changes in the API the mobile phone number would of course magically show up the second after in the apps. Well yes, no, actual people need to work on this. So therefore let's add this warning until this feature is done in the app-team. I will get notified by them in a channel and will remove the warning then. 
- Add release note for correcting the typo in the mobile phone number warning
- Re-adding the warning to develop
None?
Fixes: - …

Re-add warning for mobile phone

---

integreat_cms/cms/templates/languages/language_list.html

This PR fixes the pagination of language list
- `chunk=page_obj` to `chunk=languages`
- 
- 
Fixes: #3615 

Fix pagination in language list

---

integreat_cms/api/decorators.py

Test servers should never track any API hits in Matomo.
- Check if `settings.TEST` flag is set and quit the tracking decorator function.
- N/A
Fixes: #

Disable Matomo tracking for test servers

---

docs/src/api-docs.rst
integreat_cms/api/v3/push_notifications.py

News items are sent out as push notifications to subscribed devices as well as served via our API. Push notifications are saved as separate objects in our database in order to retain the information for which news items we already sent notifications and to keep that separate from the concept of the content of the news item itself.
News items have a property `last_updated`, which describes when the content was last edited. Push Notification objects have a `sent_date`, which describes when the notification for this news item in that channel and this language was sent out. In the API, we only expose `last_updated`, which is the value also being displayed in the app. This can cause confusion whenever the date the news item was last edited is far before the date when it was actually sent.
- …

Sort news/push notifications

---

integreat_cms/cms/templates/statistics/statistics_viewed_pages.html
integreat_cms/static/src/js/collapsible-boxes.ts

This PR adds the option to suppress a box to collapse for elements with the class "do-not-collapse" 
- Add option for collapsible boxes to not collapse if certain elements have been clicked 
- It's still a bit flaky, especially if the element is small and can easily be mis-clicked
Fixes: #3623

Add an attribute for elements to not collapse

---

integreat_cms/cms/constants/roles.py
integreat_cms/cms/fixtures/test_roles.json
integreat_cms/cms/migrations/0127_hide_page_based_statistics.py
integreat_cms/cms/models/users/user.py
integreat_cms/cms/templates/statistics/statistics_overview.html

After merging #3325 and introducing a first iteration of page based statistics, we discovered problems with loading data from matomo which can lead to crashing the server. To avoid this from accidentally happening this PR hides the page based statistics for the service team until the problems are fixed.
- Introduce `view_page_based_statistics` permission and hide the page based statistics box behind it
- We as CMS Team will still be able access the page based statistics on production after the upcoming release. It's probably a good idea for us as CMS Team to avoid the statistics section on production as much as possible.
Fixes: n.a. …

Hide page based statistics

---

integreat_cms/cms/templates/linkcheck/link_list_row.html
integreat_cms/cms/templates/linkcheck/links_by_filter.html
integreat_cms/cms/utils/linkcheck_utils.py
integreat_cms/cms/views/contacts/contact_from_existing_data.py
integreat_cms/cms/views/dashboard/dashboard_view.py
integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
integreat_cms/core/management/commands/fix_internal_links.py
integreat_cms/release_notes/current/unreleased/3458.yml

This PR refactors `linkcheck_utils.py`, mainly the `get_urls` method
- Reduce the things `get_urls` does and externalize some functionality to new methods
- Same for `filter_urls`
- Rename and extend the functionality of `get_region_links` to be able to handle multiple regions
- Exclude archived regions when multiple regions are requested
- This PR will also resolve #3458 since there was only one line of code that would have been changed after refactoring
- Otherwise everything revolving the linkchecker should work as always
Fixes: #3488 
Fixes: #3458

Refactor linkcheck utils

---

integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/contacts/contact_from_existing_data.py
integreat_cms/core/management/commands/fix_internal_links.py
tests/cms/views/contacts/test_contact_from_existing_data.py

This PR fixes the `Internal Server Error` on the page `potential-contacts` and in the management command to replace internal links. This bug was caused by #3541. The refactored `get_link_query` tries to access the first item within a Queryset of regions, if only a region is given this causes a `TypeError` which was represented by the `Internal Server Error`.
- But two occurrences of region in a list
- This probably needs a test, right?
Fixes: #3649

Fix internal server error in suggest contacts

---

integreat_cms/cms/fixtures/test_data.json
tests/api/expected-outputs/augsburg_de_children.json
tests/api/expected-outputs/augsburg_de_children_depth_2.json
tests/api/expected-outputs/augsburg_de_pages.json
tests/cms/test_duplicate_regions.py
tests/cms/views/link_replace/test_link_actions.py

There is a broken link to an SVG in one page. This image does not exist in the known links for Augsburg. Depending on how tests are split, sometimes this link is discovered before the region clone test is being executed. In that case the clone region test fails because one additional failing URL is found. The total number of expected links in the source region does not include this "unknown" link.
This link is obviously discovered when all pages in the cloned region are being saved. Therefore we need to decrease the known failing and total links there by one.
Okay, the issue is this: `filter_urls("augsburg", "unchecked")` requires a few other conditions to be met to have the URL sorted into "unchecked". Most importantly, the `status` attribute has to be `None`. If for any reason the other …

Fix linkcheck tests for CI pipeline

---

integreat_cms/cms/utils/linkcheck_utils.py

This fixes the shown source url and usages count in the general linkchecker view when a link is used in more regions from which one is archived
- Filter out the source PageTranslation objects from archived regions when in the general linkchecker view
Fixes: #3653 

Fix source link and count in linkchecker

---

integreat_cms/cms/constants/roles.py
integreat_cms/cms/forms/push_notifications/push_notification_form.py
integreat_cms/cms/migrations/0132_archive_pushnotification.py
integreat_cms/cms/models/push_notifications/push_notification.py
integreat_cms/cms/templates/push_notifications/push_notification_form.html
integreat_cms/cms/templates/push_notifications/push_notification_list.html
integreat_cms/cms/templates/push_notifications/push_notification_list_row.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/contacts/contact_context_mixin.py
integreat_cms/cms/views/push_notifications/__init__.py
integreat_cms/cms/views/push_notifications/push_notification_actions.py
integreat_cms/cms/views/push_notifications/push_notification_bulk_actions.py
integreat_cms/cms/views/push_notifications/push_notification_form_view.py
integreat_cms/cms/views/push_notifications/push_notification_list_view.py
integreat_cms/core/management/commands/send_push_notifications.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3588.yml

This PR adds the option to archive and restore push notification
- This PR adds the option to archive and restore a single push notifications
- This PR adds the option to archive and restore many push notifications at once
I see two possible problems:
- I introduced a new permission "archive_pushnotifications", but I'm not sure if it's working already or if I need another migration file for it. I haven't figured this part out yet. Maybe a case for @MizukiTemma 
- The goal is not send archived push notifications. This is where my lack of knowledge on push notifications comes in. Do I need to exclude it from more than just the management command? This might be a case for @PeterNerlich 
Fixes: #3588 …

Add option to archive push notifications

---

tests/core/management/commands/test_find_missing_versions.py

It seems that some other previously running test manipulates the slug of version 1 of the augsburg/de/willkommen page. In order for this test to successfully complete, we need to ensure that the slug is correct.
- Set the slug of version 1 to `willkommen` before the test starts.
- Some other COULD depend on the slug being `welcome`? But I doubt that currently.
:100: :joy: 
Fixes: #3669 

Fix test_find_missing_versions_failure

---

integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR is an attempt to fix the `NoneType` error that occurs sometimes when renaming a page. Some more testing on our side show that this issue is indeed flaky and seems to be caused because `other_translation` is `None`.  
- Catch case when `other_translation` is still `None` and show an error message instead. 
- This is not ideal for user experience. An alternative could be to wait for a while to make sure there is enough time for `other_translation` to be set.
- Please note that this really is only a draft and I'm shooting out ideas hoping that it sparks some more ideas from your side :sparkles: 
Fixes: Parts of #3319

Attempt to fix issue with none existant other translation

---

docs/src/management-commands.rst
integreat_cms/core/management/commands/update_link_text.py
tests/core/management/commands/test_update_link_text.py

This PR introduces a management command which updates the link texts of ALL link object with the given URL. 
The motivation is to fulfill [this need](https://chat.tuerantuer.org/digitalfabrik/pl/5otdpsbjmiy53fd1cwzqr6mqfr). This PR can be a step of #2226 
- Find contents which contain the specified URL, check all links in each content and replace the link text if the link matches the given URL
- Add a documentation
- **note**: There is no way to specify which links should get the new link text (by regin, content). Change will be applied to ALL links with the URL. ALL link objects with the URL get the SAME link text.
- 
Fixes: 

Add management command to update link text

---

docs/src/installation.rst

I ran into this problem with python 3.12 during development environment setup on my Ubuntu laptop. These additions to the documentation might be helpful for the next person
- install.sh needs python 3.9 to 3.11 (3.12 fails)
- so best way is to install python3.11 alongside, but keep python3 pointing at 3.12
- end then run install.sh by setting the python parameter to python 3.11
none
Fixes: #

Add to documentation handling pyhon3.12 during installation

---

integreat_cms/cms/migrations/0133_add_page_accesses.py
integreat_cms/cms/models/__init__.py
integreat_cms/cms/models/regions/region.py
integreat_cms/cms/models/statistics/__init__.py
integreat_cms/cms/models/statistics/page_accesses.py
integreat_cms/locale/de/LC_MESSAGES/django.po

This PR adds a model for page based statistics.
- Adds PageAccesses model
- Adds method to region to get page accesses for requested languages
- 
Innitial Idea was to add page accesses to the page model, but page accesses also contains information about the language that was accessed. So it needs to have it's own table. This partially solves #3673
Fixes: 

Add page accesses model

---

docs/src/dev-server.rst

- a little addition that explains how to add create-database permissions in PostrgreSQL
- I ran into this problem when running automated tests for the first time (see here: https://chat.tuerantuer.org/digitalfabrik/pl/hfekidjn63yamkmf3o8fcy9x7o): -> The tests were not able to create a database.
- and setting the permissions in the way described in the documentation solved this for me
Fixes: #

Add dev server documentation about setting permissions for PostgreSQL

---

integreat_cms/cms/forms/media/upload_media_file_form.py
integreat_cms/cms/models/media/media_file.py
integreat_cms/cms/utils/media_utils.py

Ensure SVGs are indeed saved as such on the server.
Mimetypes of files handed out by the server seem to be determined by the file extension only, so we need to manually set the extension for thumbnails of SVGs to PNG.
- Don't generate an optimized image for SVGs
- Use the normal thumbnail generation *(which we always need)* to determine if the file is corrupted instead of the generation of an optimized image
- Change the file extension for thumbnails to `.png` if the original files are `.svg`
And as a bonus:
- Allow scaling up SVGs for thumbnail generation even if the stored dimensions of the file are smaller, since SVGs do not blur anyway *(unless someone embedded a raster image and defeated the whole purpose)*
Fixes: #3687 …

Fix svg upload and thumbnails

---

integreat_cms/core/settings.py
integreat_cms/gvz_api/apps.py
integreat_cms/release_notes/current/unreleased/3655.yml

This PR fixes the aliases for GVZ
- Load api_available via cache
api_available was always False and therefore the code wasn't executed. We think this issue was because `api_available` wasn't stored anywhere. Our idea was to store it in the cache to have it saved somewhere. 
Fixes: #3655 

Fix GVZ API aliases

---

tools/ruff.sh
tools/ruff_check.sh
tools/ruff_format.sh

With #3333 just merged, ruff became our main linting tool. However if you're like me and have a lot of messy files and experiments lying around your working directory, you might want to restrict ruff to only look at a few subtrees in your project. While the performance improvement barely matters because ruff is already so fast, you will appreciate having irrelevant files untouched and ruff only printing messages about files you care about.
- Split `ruff.sh` into `ruff_check.sh` and `ruff_format.sh`, where arguments are handed over to ruff verbatim!
- `ruff.sh` now just calls those two scripts, and hands paths over to both if you specified them:
- Parse arguments to `tools/ruff.sh` and save them to `PATHS`
- Set `PATHS` to `BASE_DIR` if none are supplied
- Run both `ruff_check.sh` and …

tools/ruff.sh: Allow restricting checking to specific subtrees

---

integreat_cms/cms/forms/__init__.py
integreat_cms/cms/forms/users/user_name_form.py
integreat_cms/cms/templates/settings/user_settings.html
integreat_cms/cms/views/settings/user_settings_view.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/2025/2025.6.3/1124.yml

Adds a form to allow users to update their first and last name from the user settings page.
- Created a `UserNameForm` extending `CustomModelForm`
- Added `user_name_form` to the `UserSettingsView`
- Updated `user_settings_view.py` to handle name form submission with validation and success messaging
- Integrated the form into the `user_settings.html` template with proper styling and localization
- Touches user form rendering logic in the settings template
- Extends view context and POST handling logic, which could affect other forms on that page
Closes #1124

Add UserNameForm to user settings

---

integreat_cms/release_notes/2025/2025.6.3/3693.yml
integreat_cms/release_notes/2025/2025.6.3/3713.yml
integreat_cms/static/src/js/tinymce-plugins/autolink_tel/plugin.js

Fix phone-number autolinking in TinyMCE: creates the `<a href>` on space-press and stops the `do-not-translate` span from leaking to later text.
---
- Move space-key handler from `keyup` to `keydown`  
- Guard: skip formatter when caret is after the newly created link (keeps user’s space)  
- Call `parseCurrentLine(editor, -1, '')` so the full number is wrapped  
- Collapse selection outside the span after link creation
---
- Touches only the custom `autolink_tel` plugin → could affect other automatic-link cases inside TinyMCE  
- Tested with Enter/Space, multiple numbers, mixed content – no regressions found
---
No intentional deviations.
---
Fixes: #3693, #3713

Fix phone number autolink on space key

---

integreat_cms/api/v3/regions.py
tests/api/expected-outputs/regions.json
tests/api/expected-outputs/regions_berlin.json
tests/api/expected-outputs/regions_nurnberg.json

As requested by the app, let the zammad_privacy_policy return null if no policy is set.
- Convert empty zammad_privacy_policy string to None / null
- None, this attribute is not yet in use.
N/A
https://chat.tuerantuer.org/digitalfabrik/pl/57n4hipbuty8dx85sntajof6no

Change Zammad privacy policy attr in region endpoint

---

integreat_cms/cms/utils/content_translation_utils.py
integreat_cms/release_notes/current/unreleased/3781.yml

This is the bugfix PR to fix the issue that occurred on production the past week. While a similar patch is already applied in production, this is the PR to bring a fix to our code base as well.
- Further limit any URLs to be considered to end in the slug instead of just containing it
- Require the slug to be delimited with slashes
- Eliminate the extra call to `url.internal` by directly requiring any URL to start with the `WEBAPP_URL` configured in the settings
- Even further limit any URLs to contain the fitting region and language slug
- If there are multiple possible domains, this implementation will no longer suffice and using linkchecks `url.internal` would be more complete. However, our `settings.py` clearly only intends one domain and so skipping the extra roundtrip through python …

Bugfix update_links_to()

---

integreat_cms/release_notes/current/unreleased/3315.yml
integreat_cms/static/src/js/media-management/library.tsx

This PR fixes the transparent background of search suggestion in the media library
- Fix the typo 😁 
- 
- 
Fixes: #3315 

Fix background color of search suggestion in media library

---

integreat_cms/release_notes/current/unreleased/3709.yml
integreat_cms/static/src/css/tinymce_custom.css

This PR fixes the bug that spacing is different in contact cards in Arabic.
- Apply the same font and font size to the contact cards regardless of the language
- 
- Font setting per language ("Lateef" for Arabic and Farsi, "Open Sans" for most european languages) is ignored whithing the contact cards. Contact cards will look the same (as in the german translations) in all languages. @laravoelk @hauf-toni is this okay? I personally like it as the contact cards (which are "do not translate") look consistently.
This is how it will look in Arabic translations after this PR
Fixes: #3709 
[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review- …

Fix spacing in contact card in RTL languages

---

integreat_cms/release_notes/current/unreleased/3197.yml
integreat_cms/static/src/js/analytics/statistics-charts.ts

This PR fixes the bug that details of each node in the statistics graph won't be shown after once exporting as PNG
- Set `globalCompositeOperation` to the original value after export
- 
- 
Fixes: #3197 

Fix hover on not showing details after PNG export

---

integreat_cms/cms/models/events/event.py
integreat_cms/cms/models/languages/language_tree_node.py
integreat_cms/cms/models/pages/page.py
integreat_cms/cms/models/pois/poi.py
integreat_cms/cms/templates/events/event_list.html
integreat_cms/cms/templates/languagetreenodes/languagetreenode_list.html
integreat_cms/cms/templates/pages/pages_page_tree.html
integreat_cms/cms/templates/pois/poi_list.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/bulk_action_views.py
integreat_cms/cms/views/events/event_actions.py
integreat_cms/cms/views/language_tree/language_tree_actions.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pois/poi_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/3122.yml
integreat_cms/static/src/js/bulk-actions.ts
tests/cms/views/bulk_actions.py
tests/cms/views/events/test_event_form.py
tests/cms/views/language_nodes/test_language_tree_node_actions.py
tests/cms/views/pages/test_page_actions.py
tests/cms/views/poi/test_poi_form.py

This adds a bulk delete option to events, pages, pois and language tree nodes
- On the list form template for pois, events, pages and language tree nodes you can now select to delete multiple entries
- After chosing to execute a confirmation dialogue will show that asks you to confirm the action
- the functionality is bundled in a general bulk_action_delete function that is used in the view of the entries
- I have added to the models of the entries (where necessary) a helper method "canBeDeleted" and adjusted the delete methods, so that the general bulk_action_delete can reuse those
- for the tests I have aimed for more self-containment as such that the entries (pois, pages, ...) are dynamically generated and not inserted into test_data.json
- there have been some changes to the models of …

Add bulk delete to entries

---

.circleci/config.yml

Since the 18th of July the API for CodeClimates test coverage has been discontinued. All PRs are failing on the CircleCI `upload-test-coverage` job
- follow Code Climates guide for migrating from the Code Climate Quality to using their Qlty Cloud ( https://docs.qlty.sh/migration/coverage ) using their (uncertified) qlty CircleCI orb 
- delete all jobs referrring to old API in config.yml
- set up coverage reporting with qlty in config.yml
- register qlty as an app for our repo (has to be undone manually if PR rejected)
- allow uncertified orbs in our circle ci setup
- might be potentially risky using the qlty orb (even if recommended by codeclimate) as it is not certified by CircleCI
- please also refer to this thread: https://chat.tuerantuer.org/digitalfabrik/pl/cabg6tt8p3yd5xqqbjztqm5jzw …

Fix the test coverage reporting failure

---

integreat_cms/cms/forms/regions/region_form.py
integreat_cms/release_notes/current/unreleased/3829.yml

This PR fixes the bug that a region cannot be created/updated when the public chat is enabled.
- Add "zammad_url", "zammad_access_token" and "zammad_webhook_token" into `relevant_fields`
- 
Fixes: #3829 

Release `2025.8.1`

---

integreat_cms/cms/models/abstract_content_translation.py
integreat_cms/core/signals/hix_signals.py
integreat_cms/release_notes/current/unreleased/3819.yml

During `cleanup_autosaves()`, a number of content translation objects get their `.version` modified. During the save, the `pre_save` hook is executed that re-evaluates the HIX score, even though the content has not changed, taking a lot of time per object changed. 
- Add `disable_listeners()` and `enable_listeners()` context managers *(inspired by how `linkcheck` does it)*
- Disable HIX listeners along with linkcheck ones during `cleanup_autosaves()`
- 
Fixes: #3819 

Disable hix signals during cleanup_autosaves()

---

integreat_cms/cms/templates/pages/page_form.html
integreat_cms/cms/templates/pages/page_form_sidebar/actions_box.html
integreat_cms/cms/templates/pages/pages_page_tree.html
integreat_cms/cms/templates/pages/pages_page_tree_node.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/pages/__init__.py
integreat_cms/cms/views/pages/page_actions.py
integreat_cms/cms/views/pages/page_bulk_actions.py
integreat_cms/cms/views/pages/page_form_view.py
integreat_cms/release_notes/current/unreleased/3512.yml
tests/cms/views/view_config.py

Users without publish rights are not able to archive pages, but thus far have been able to restore pages. To adhere to the principle of coherent responsibility, users that can't archive pages should not be able to restore pages.
- check publish page permissions when restoring pages
- hide restore page icon in forms and tree views
- Due to an error in the page_tree_node, users with publish rights to specific pages (author role) were not able to archive these pages, even though they had the appropriate permissions, because the icon was always hidden. With this PR, icons for archiving and restoring are shown as expected
Fixes: #3512 …

restrict restoring pages to users that have publishing permissions

---

integreat_cms/cms/templates/pages/page_form.html

This PR fixes the bug that users cannot publish a page even if they have permission for "publish"
- Revive `{% has_perm 'cms.publish_page_object' request.user page as can_publish_page %}` which was deleted accidentally.
- 
- Release not blocked anymore 
Fixes: #3838 

Fix page submit button

---

integreat_cms/api/v3/locations.py
integreat_cms/release_notes/current/unreleased/3776.yml

This PR fixes the bug on the events endpoint of our API leading to an internal server error when handling an event referencing a location that is set to draft, meaning that the user sees no events at all.
- Expose the name of a location as `null` if it does not have a `best_public_translation`
- This might not be the correct strategy. Maybe we don't want to show locations set as draft and anything connected to it at all
- We need to check with the app team whether this is a change that makes sense in their context
Fixes: #3776 

API events: Fix internal server error

---

integreat_cms/cms/templates/feedback/region_feedback_list.html
integreat_cms/cms/urls/protected.py
integreat_cms/cms/views/feedback/__init__.py
integreat_cms/cms/views/feedback/region_feedback_actions.py
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/release_notes/current/unreleased/2925.yml

This PR adds a new bulk action to forward region feedback items to the feedback list in the network management (technical feedback).
- Add a new bulk action
- Show it only in the list of not-archived region feedback
- 
It was not specified in the issue, but all the forwarded feedback items are turned into "unread", to avoid Service Team overlook them.
Fixes: #2925 

Add bulk action to forward feedback to Integreat Staff

---

docs/src/management-commands.rst
integreat_cms/cms/views/statistics/statistics_actions.py
integreat_cms/core/management/commands/fetch_page_accesses.py
integreat_cms/integreat_celery/celery.py
integreat_cms/matomo_api/matomo_api_client.py
integreat_cms/matomo_api/utils.py

This PR adds fetching and saving page accesses with celery and a daily celery job to fetch the latest accesses
- Fetch page accesses from Matomo with celery
- Add management command to start fetching page accesses
- Add a daily celery job to start fetching latest page accesses 
- There is a small possibility that the daily job interferes with the daily import of calendars, during local testing it seemed fine since the calendar import seemed to be a really fast job
- Probably the easiest way to test this is by activating statistics for a region e.g. Stadt Augsburg. You can find the needed token in the test system. Then run the here introduced management command. With only a couple of pages it doesn't take that long.
- The daily job is probably best tested on the test server. While testing …

Fetch page accesses with celery

---

integreat_cms/cms/models/pages/page_translation.py
integreat_cms/release_notes/current/unreleased/2712.yml

This PR fixes the bug that empty entries appear in the list of alternative languages for the mirrored content.
- Check which languages are available for the mirrored content
- Check which languages are available for the mirroring content
- List only the languages that are available in both of the above sets
- Happier user experience?
- 
Fixes: #2712 

Fix empty entry in the languages in which mirrored content is available

---

integreat_cms/cms/views/pois/poi_form_view.py

This PR fixes the bug that contacts that are created during a new POI being created automatically receive the opening hours of the POI.
- Flush `opening_hours` from the data, when creating a contact following the POI
- None?
Fixes: #3729

Fix opening hours of contact created together with a new POI

---

integreat_cms/cms/templates/statistics/statistics_viewed_pages.html
integreat_cms/cms/templates/statistics/statistics_viewed_pages_node.html
integreat_cms/locale/de/LC_MESSAGES/django.po
integreat_cms/static/src/js/analytics/statistics-page-accesses.ts

This PR changes the loading indication for the page access statistics to a single indication instead of indications for every page in the page list 
- Moves the loader Icon from the page nodes to the top of the list
- The toggleLoader method isn't needed anymore since we don't need to iterate over multiple icons anymore
To test this you need statistics activated. 
- Go to the region settings of e.g. Augsburg on the test system and copy the matomo auth token
- Run the cms locally and go to the region settings of Augsburg
- Check the statistics Checkbox and paste the matomo auth token
- Run the fetch page accesses management command: `integreat-cms-cli fetch_page_accesses --start-date START_DATE --end-date END_DATE --region-slug …

Change page access statistics loading indication to single indication

---

integreat_cms/cms/models/contact/contact.py
integreat_cms/cms/models/events/event_translation.py
integreat_cms/cms/models/feedback/feedback.py
integreat_cms/cms/models/media/media_file.py
integreat_cms/cms/models/pages/page.py
integreat_cms/cms/models/pois/poi_translation.py
integreat_cms/cms/models/push_notifications/push_notification_translation.py
integreat_cms/cms/models/regions/region.py
integreat_cms/cms/views/utils/search_content_ajax.py
integreat_cms/static/src/js/tinymce-plugins/custom_link_input/plugin.js

This PR fixes the bug that search keywords can appear multiple times in the suggestion list when user uses search window.
This bug has existed since a long time, but will be really a problem if #3727 is merged as is (it makes all primary contacts named after the related POI)
- Use `.distinct()` or check whether a search keyword is already in the suggestion list
- 
- 
There is no fix implemented for languages, as it is unlikely that we have more than one language with the same name and implementation is not so trivial due to translation of language names into the system languages user is using
Fixes: #3839  …

Remove duplicates from the search suggestion list
